/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef QEMU_MODULE_BLOCK_H
#define QEMU_MODULE_BLOCK_H

static const struct {
    const char *format_name;
    const char *protocol_name;
    const char *library_name;
} block_driver_modules[] = {
    /* empty: no loadable block modules on Android build */
};

#endif