/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_ACCEL_HVF_H
#define TRACE_TRACE_ACCEL_HVF_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_HVF_VM_MAP 0
#define TRACE_HVF_VM_MAP_ENABLED 0
#define TRACE_HVF_VM_MAP_BACKEND_DSTATE() (0)
static inline void trace_hvf_vm_map(uint64_t paddr, uint64_t size, void *vaddr, uint8_t flags, const char r, const char w, const char e) {
    (void)paddr;
    (void)size;
    (void)vaddr;
    (void)flags;
    (void)r;
    (void)w;
    (void)e;
}
#define TRACE_HVF_VM_UNMAP 0
#define TRACE_HVF_VM_UNMAP_ENABLED 0
#define TRACE_HVF_VM_UNMAP_BACKEND_DSTATE() (0)
static inline void trace_hvf_vm_unmap(uint64_t paddr, uint64_t size) {
    (void)paddr;
    (void)size;
}

#endif