/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_VIRTIO_H
#define TRACE_TRACE_HW_VIRTIO_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_VHOST_COMMIT 0
#define TRACE_VHOST_COMMIT_ENABLED 0
#define TRACE_VHOST_COMMIT_BACKEND_DSTATE() (0)
static inline void trace_vhost_commit(bool started, bool changed) {
    (void)started;
    (void)changed;
}
#define TRACE_VHOST_DEV_CLEANUP 0
#define TRACE_VHOST_DEV_CLEANUP_ENABLED 0
#define TRACE_VHOST_DEV_CLEANUP_BACKEND_DSTATE() (0)
static inline void trace_vhost_dev_cleanup(void *dev) {
    (void)dev;
}
#define TRACE_VHOST_DEV_START 0
#define TRACE_VHOST_DEV_START_ENABLED 0
#define TRACE_VHOST_DEV_START_BACKEND_DSTATE() (0)
static inline void trace_vhost_dev_start(void *dev, const char *name, bool vrings) {
    (void)dev;
    (void)name;
    (void)vrings;
}
#define TRACE_VHOST_DEV_STOP 0
#define TRACE_VHOST_DEV_STOP_ENABLED 0
#define TRACE_VHOST_DEV_STOP_BACKEND_DSTATE() (0)
static inline void trace_vhost_dev_stop(void *dev, const char *name, bool vrings) {
    (void)dev;
    (void)name;
    (void)vrings;
}
#define TRACE_VHOST_IOTLB_MISS 0
#define TRACE_VHOST_IOTLB_MISS_ENABLED 0
#define TRACE_VHOST_IOTLB_MISS_BACKEND_DSTATE() (0)
static inline void trace_vhost_iotlb_miss(void *dev, int step) {
    (void)dev;
    (void)step;
}
#define TRACE_VHOST_REGION_ADD_SECTION 0
#define TRACE_VHOST_REGION_ADD_SECTION_ENABLED 0
#define TRACE_VHOST_REGION_ADD_SECTION_BACKEND_DSTATE() (0)
static inline void trace_vhost_region_add_section(const char *name, uint64_t gpa, uint64_t size, uint64_t host) {
    (void)name;
    (void)gpa;
    (void)size;
    (void)host;
}
#define TRACE_VHOST_REGION_ADD_SECTION_ALIGNED 0
#define TRACE_VHOST_REGION_ADD_SECTION_ALIGNED_ENABLED 0
#define TRACE_VHOST_REGION_ADD_SECTION_ALIGNED_BACKEND_DSTATE() (0)
static inline void trace_vhost_region_add_section_aligned(const char *name, uint64_t gpa, uint64_t size, uint64_t host) {
    (void)name;
    (void)gpa;
    (void)size;
    (void)host;
}
#define TRACE_VHOST_REGION_ADD_SECTION_MERGE 0
#define TRACE_VHOST_REGION_ADD_SECTION_MERGE_ENABLED 0
#define TRACE_VHOST_REGION_ADD_SECTION_MERGE_BACKEND_DSTATE() (0)
static inline void trace_vhost_region_add_section_merge(const char *name, uint64_t new_size, uint64_t gpa, uint64_t owr) {
    (void)name;
    (void)new_size;
    (void)gpa;
    (void)owr;
}
#define TRACE_VHOST_REJECT_SECTION 0
#define TRACE_VHOST_REJECT_SECTION_ENABLED 0
#define TRACE_VHOST_REJECT_SECTION_BACKEND_DSTATE() (0)
static inline void trace_vhost_reject_section(const char *name, int d) {
    (void)name;
    (void)d;
}
#define TRACE_VHOST_SECTION 0
#define TRACE_VHOST_SECTION_ENABLED 0
#define TRACE_VHOST_SECTION_BACKEND_DSTATE() (0)
static inline void trace_vhost_section(const char *name) {
    (void)name;
}
#define TRACE_VHOST_USER_CREATE_NOTIFIER 0
#define TRACE_VHOST_USER_CREATE_NOTIFIER_ENABLED 0
#define TRACE_VHOST_USER_CREATE_NOTIFIER_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_create_notifier(int idx, void *n) {
    (void)idx;
    (void)n;
}
#define TRACE_VHOST_USER_POSTCOPY_END_ENTRY 0
#define TRACE_VHOST_USER_POSTCOPY_END_ENTRY_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_END_ENTRY_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_end_entry(void) {
}
#define TRACE_VHOST_USER_POSTCOPY_END_EXIT 0
#define TRACE_VHOST_USER_POSTCOPY_END_EXIT_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_END_EXIT_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_end_exit(void) {
}
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER 0
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_fault_handler(const char *name, uint64_t fault_address, int nregions) {
    (void)name;
    (void)fault_address;
    (void)nregions;
}
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER_FOUND 0
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER_FOUND_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER_FOUND_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_fault_handler_found(int i, uint64_t region_offset, uint64_t rb_offset) {
    (void)i;
    (void)region_offset;
    (void)rb_offset;
}
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER_LOOP 0
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER_LOOP_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_FAULT_HANDLER_LOOP_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_fault_handler_loop(int i, uint64_t client_base, uint64_t size) {
    (void)i;
    (void)client_base;
    (void)size;
}
#define TRACE_VHOST_USER_POSTCOPY_LISTEN 0
#define TRACE_VHOST_USER_POSTCOPY_LISTEN_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_LISTEN_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_listen(void) {
}
#define TRACE_VHOST_USER_POSTCOPY_WAKER 0
#define TRACE_VHOST_USER_POSTCOPY_WAKER_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_WAKER_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_waker(const char *rb, uint64_t rb_offset) {
    (void)rb;
    (void)rb_offset;
}
#define TRACE_VHOST_USER_POSTCOPY_WAKER_FOUND 0
#define TRACE_VHOST_USER_POSTCOPY_WAKER_FOUND_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_WAKER_FOUND_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_waker_found(uint64_t client_addr) {
    (void)client_addr;
}
#define TRACE_VHOST_USER_POSTCOPY_WAKER_NOMATCH 0
#define TRACE_VHOST_USER_POSTCOPY_WAKER_NOMATCH_ENABLED 0
#define TRACE_VHOST_USER_POSTCOPY_WAKER_NOMATCH_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_postcopy_waker_nomatch(const char *rb, uint64_t rb_offset) {
    (void)rb;
    (void)rb_offset;
}
#define TRACE_VHOST_USER_READ 0
#define TRACE_VHOST_USER_READ_ENABLED 0
#define TRACE_VHOST_USER_READ_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_read(uint32_t req, uint32_t flags) {
    (void)req;
    (void)flags;
}
#define TRACE_VHOST_USER_SET_MEM_TABLE_POSTCOPY 0
#define TRACE_VHOST_USER_SET_MEM_TABLE_POSTCOPY_ENABLED 0
#define TRACE_VHOST_USER_SET_MEM_TABLE_POSTCOPY_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_set_mem_table_postcopy(uint64_t client_addr, uint64_t qhva, int reply_i, int region_i) {
    (void)client_addr;
    (void)qhva;
    (void)reply_i;
    (void)region_i;
}
#define TRACE_VHOST_USER_SET_MEM_TABLE_WITHFD 0
#define TRACE_VHOST_USER_SET_MEM_TABLE_WITHFD_ENABLED 0
#define TRACE_VHOST_USER_SET_MEM_TABLE_WITHFD_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_set_mem_table_withfd(int index, const char *name, uint64_t memory_size, uint64_t guest_phys_addr, uint64_t userspace_addr, uint64_t offset) {
    (void)index;
    (void)name;
    (void)memory_size;
    (void)guest_phys_addr;
    (void)userspace_addr;
    (void)offset;
}
#define TRACE_VHOST_USER_WRITE 0
#define TRACE_VHOST_USER_WRITE_ENABLED 0
#define TRACE_VHOST_USER_WRITE_BACKEND_DSTATE() (0)
static inline void trace_vhost_user_write(uint32_t req, uint32_t flags) {
    (void)req;
    (void)flags;
}
#define TRACE_VHOST_VDPA_ADD_STATUS 0
#define TRACE_VHOST_VDPA_ADD_STATUS_ENABLED 0
#define TRACE_VHOST_VDPA_ADD_STATUS_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_add_status(void *dev, uint8_t status) {
    (void)dev;
    (void)status;
}
#define TRACE_VHOST_VDPA_CLEANUP 0
#define TRACE_VHOST_VDPA_CLEANUP_ENABLED 0
#define TRACE_VHOST_VDPA_CLEANUP_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_cleanup(void *dev, void *vdpa) {
    (void)dev;
    (void)vdpa;
}
#define TRACE_VHOST_VDPA_DEV_START 0
#define TRACE_VHOST_VDPA_DEV_START_ENABLED 0
#define TRACE_VHOST_VDPA_DEV_START_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_dev_start(void *dev, bool started) {
    (void)dev;
    (void)started;
}
#define TRACE_VHOST_VDPA_DMA_MAP 0
#define TRACE_VHOST_VDPA_DMA_MAP_ENABLED 0
#define TRACE_VHOST_VDPA_DMA_MAP_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_dma_map(void *vdpa, int fd, uint32_t msg_type, uint32_t asid, uint64_t iova, uint64_t size, uint64_t uaddr, uint8_t perm, uint8_t type) {
    (void)vdpa;
    (void)fd;
    (void)msg_type;
    (void)asid;
    (void)iova;
    (void)size;
    (void)uaddr;
    (void)perm;
    (void)type;
}
#define TRACE_VHOST_VDPA_DMA_UNMAP 0
#define TRACE_VHOST_VDPA_DMA_UNMAP_ENABLED 0
#define TRACE_VHOST_VDPA_DMA_UNMAP_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_dma_unmap(void *vdpa, int fd, uint32_t msg_type, uint32_t asid, uint64_t iova, uint64_t size, uint8_t type) {
    (void)vdpa;
    (void)fd;
    (void)msg_type;
    (void)asid;
    (void)iova;
    (void)size;
    (void)type;
}
#define TRACE_VHOST_VDPA_DUMP_CONFIG 0
#define TRACE_VHOST_VDPA_DUMP_CONFIG_ENABLED 0
#define TRACE_VHOST_VDPA_DUMP_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_dump_config(void *dev, unsigned ofs, const char *line) {
    (void)dev;
    (void)ofs;
    (void)line;
}
#define TRACE_VHOST_VDPA_DUMP_REGIONS 0
#define TRACE_VHOST_VDPA_DUMP_REGIONS_ENABLED 0
#define TRACE_VHOST_VDPA_DUMP_REGIONS_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_dump_regions(void *dev, int i, uint64_t guest_phys_addr, uint64_t memory_size, uint64_t userspace_addr, uint64_t flags_padding) {
    (void)dev;
    (void)i;
    (void)guest_phys_addr;
    (void)memory_size;
    (void)userspace_addr;
    (void)flags_padding;
}
#define TRACE_VHOST_VDPA_GET_CONFIG 0
#define TRACE_VHOST_VDPA_GET_CONFIG_ENABLED 0
#define TRACE_VHOST_VDPA_GET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_get_config(void *dev, void *config, uint32_t config_len) {
    (void)dev;
    (void)config;
    (void)config_len;
}
#define TRACE_VHOST_VDPA_GET_DEVICE_ID 0
#define TRACE_VHOST_VDPA_GET_DEVICE_ID_ENABLED 0
#define TRACE_VHOST_VDPA_GET_DEVICE_ID_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_get_device_id(void *dev, uint32_t device_id) {
    (void)dev;
    (void)device_id;
}
#define TRACE_VHOST_VDPA_GET_FEATURES 0
#define TRACE_VHOST_VDPA_GET_FEATURES_ENABLED 0
#define TRACE_VHOST_VDPA_GET_FEATURES_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_get_features(void *dev, uint64_t features) {
    (void)dev;
    (void)features;
}
#define TRACE_VHOST_VDPA_GET_IOVA_RANGE 0
#define TRACE_VHOST_VDPA_GET_IOVA_RANGE_ENABLED 0
#define TRACE_VHOST_VDPA_GET_IOVA_RANGE_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_get_iova_range(void *dev, uint64_t first, uint64_t last) {
    (void)dev;
    (void)first;
    (void)last;
}
#define TRACE_VHOST_VDPA_GET_VQ_INDEX 0
#define TRACE_VHOST_VDPA_GET_VQ_INDEX_ENABLED 0
#define TRACE_VHOST_VDPA_GET_VQ_INDEX_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_get_vq_index(void *dev, int idx, int vq_idx) {
    (void)dev;
    (void)idx;
    (void)vq_idx;
}
#define TRACE_VHOST_VDPA_GET_VRING_BASE 0
#define TRACE_VHOST_VDPA_GET_VRING_BASE_ENABLED 0
#define TRACE_VHOST_VDPA_GET_VRING_BASE_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_get_vring_base(void *dev, unsigned int index, unsigned int num, bool svq) {
    (void)dev;
    (void)index;
    (void)num;
    (void)svq;
}
#define TRACE_VHOST_VDPA_INIT 0
#define TRACE_VHOST_VDPA_INIT_ENABLED 0
#define TRACE_VHOST_VDPA_INIT_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_init(void *dev, void *s, void *vdpa) {
    (void)dev;
    (void)s;
    (void)vdpa;
}
#define TRACE_VHOST_VDPA_LISTENER_BEGIN_BATCH 0
#define TRACE_VHOST_VDPA_LISTENER_BEGIN_BATCH_ENABLED 0
#define TRACE_VHOST_VDPA_LISTENER_BEGIN_BATCH_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_listener_begin_batch(void *v, int fd, uint32_t msg_type, uint8_t type) {
    (void)v;
    (void)fd;
    (void)msg_type;
    (void)type;
}
#define TRACE_VHOST_VDPA_LISTENER_COMMIT 0
#define TRACE_VHOST_VDPA_LISTENER_COMMIT_ENABLED 0
#define TRACE_VHOST_VDPA_LISTENER_COMMIT_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_listener_commit(void *v, int fd, uint32_t msg_type, uint8_t type) {
    (void)v;
    (void)fd;
    (void)msg_type;
    (void)type;
}
#define TRACE_VHOST_VDPA_LISTENER_REGION_ADD 0
#define TRACE_VHOST_VDPA_LISTENER_REGION_ADD_ENABLED 0
#define TRACE_VHOST_VDPA_LISTENER_REGION_ADD_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_listener_region_add(void *vdpa, uint64_t iova, uint64_t llend, void *vaddr, bool readonly) {
    (void)vdpa;
    (void)iova;
    (void)llend;
    (void)vaddr;
    (void)readonly;
}
#define TRACE_VHOST_VDPA_LISTENER_REGION_ADD_UNALIGNED 0
#define TRACE_VHOST_VDPA_LISTENER_REGION_ADD_UNALIGNED_ENABLED 0
#define TRACE_VHOST_VDPA_LISTENER_REGION_ADD_UNALIGNED_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_listener_region_add_unaligned(void *v, const char *name, uint64_t offset_as, uint64_t offset_page) {
    (void)v;
    (void)name;
    (void)offset_as;
    (void)offset_page;
}
#define TRACE_VHOST_VDPA_LISTENER_REGION_DEL 0
#define TRACE_VHOST_VDPA_LISTENER_REGION_DEL_ENABLED 0
#define TRACE_VHOST_VDPA_LISTENER_REGION_DEL_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_listener_region_del(void *vdpa, uint64_t iova, uint64_t llend) {
    (void)vdpa;
    (void)iova;
    (void)llend;
}
#define TRACE_VHOST_VDPA_LISTENER_REGION_DEL_UNALIGNED 0
#define TRACE_VHOST_VDPA_LISTENER_REGION_DEL_UNALIGNED_ENABLED 0
#define TRACE_VHOST_VDPA_LISTENER_REGION_DEL_UNALIGNED_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_listener_region_del_unaligned(void *v, const char *name, uint64_t offset_as, uint64_t offset_page) {
    (void)v;
    (void)name;
    (void)offset_as;
    (void)offset_page;
}
#define TRACE_VHOST_VDPA_MEMSLOTS_LIMIT 0
#define TRACE_VHOST_VDPA_MEMSLOTS_LIMIT_ENABLED 0
#define TRACE_VHOST_VDPA_MEMSLOTS_LIMIT_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_memslots_limit(void *dev, int ret) {
    (void)dev;
    (void)ret;
}
#define TRACE_VHOST_VDPA_RESET_DEVICE 0
#define TRACE_VHOST_VDPA_RESET_DEVICE_ENABLED 0
#define TRACE_VHOST_VDPA_RESET_DEVICE_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_reset_device(void *dev) {
    (void)dev;
}
#define TRACE_VHOST_VDPA_SET_CONFIG 0
#define TRACE_VHOST_VDPA_SET_CONFIG_ENABLED 0
#define TRACE_VHOST_VDPA_SET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_config(void *dev, uint32_t offset, uint32_t size, uint32_t flags) {
    (void)dev;
    (void)offset;
    (void)size;
    (void)flags;
}
#define TRACE_VHOST_VDPA_SET_CONFIG_CALL 0
#define TRACE_VHOST_VDPA_SET_CONFIG_CALL_ENABLED 0
#define TRACE_VHOST_VDPA_SET_CONFIG_CALL_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_config_call(void *dev, int fd) {
    (void)dev;
    (void)fd;
}
#define TRACE_VHOST_VDPA_SET_DEV_VRING_BASE 0
#define TRACE_VHOST_VDPA_SET_DEV_VRING_BASE_ENABLED 0
#define TRACE_VHOST_VDPA_SET_DEV_VRING_BASE_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_dev_vring_base(void *dev, unsigned int index, unsigned int num, bool svq) {
    (void)dev;
    (void)index;
    (void)num;
    (void)svq;
}
#define TRACE_VHOST_VDPA_SET_FEATURES 0
#define TRACE_VHOST_VDPA_SET_FEATURES_ENABLED 0
#define TRACE_VHOST_VDPA_SET_FEATURES_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_features(void *dev, uint64_t features) {
    (void)dev;
    (void)features;
}
#define TRACE_VHOST_VDPA_SET_LOG_BASE 0
#define TRACE_VHOST_VDPA_SET_LOG_BASE_ENABLED 0
#define TRACE_VHOST_VDPA_SET_LOG_BASE_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_log_base(void *dev, uint64_t base, unsigned long long size, int refcnt, int fd, void *log) {
    (void)dev;
    (void)base;
    (void)size;
    (void)refcnt;
    (void)fd;
    (void)log;
}
#define TRACE_VHOST_VDPA_SET_MEM_TABLE 0
#define TRACE_VHOST_VDPA_SET_MEM_TABLE_ENABLED 0
#define TRACE_VHOST_VDPA_SET_MEM_TABLE_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_mem_table(void *dev, uint32_t nregions, uint32_t padding) {
    (void)dev;
    (void)nregions;
    (void)padding;
}
#define TRACE_VHOST_VDPA_SET_OWNER 0
#define TRACE_VHOST_VDPA_SET_OWNER_ENABLED 0
#define TRACE_VHOST_VDPA_SET_OWNER_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_owner(void *dev) {
    (void)dev;
}
#define TRACE_VHOST_VDPA_SET_VRING_ADDR 0
#define TRACE_VHOST_VDPA_SET_VRING_ADDR_ENABLED 0
#define TRACE_VHOST_VDPA_SET_VRING_ADDR_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_vring_addr(void *dev, unsigned int index, unsigned int flags, uint64_t desc_user_addr, uint64_t used_user_addr, uint64_t avail_user_addr, uint64_t log_guest_addr) {
    (void)dev;
    (void)index;
    (void)flags;
    (void)desc_user_addr;
    (void)used_user_addr;
    (void)avail_user_addr;
    (void)log_guest_addr;
}
#define TRACE_VHOST_VDPA_SET_VRING_CALL 0
#define TRACE_VHOST_VDPA_SET_VRING_CALL_ENABLED 0
#define TRACE_VHOST_VDPA_SET_VRING_CALL_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_vring_call(void *dev, unsigned int index, int fd) {
    (void)dev;
    (void)index;
    (void)fd;
}
#define TRACE_VHOST_VDPA_SET_VRING_ENABLE_ONE 0
#define TRACE_VHOST_VDPA_SET_VRING_ENABLE_ONE_ENABLED 0
#define TRACE_VHOST_VDPA_SET_VRING_ENABLE_ONE_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_vring_enable_one(void *dev, unsigned i, int enable, int r) {
    (void)dev;
    (void)i;
    (void)enable;
    (void)r;
}
#define TRACE_VHOST_VDPA_SET_VRING_KICK 0
#define TRACE_VHOST_VDPA_SET_VRING_KICK_ENABLED 0
#define TRACE_VHOST_VDPA_SET_VRING_KICK_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_vring_kick(void *dev, unsigned int index, int fd) {
    (void)dev;
    (void)index;
    (void)fd;
}
#define TRACE_VHOST_VDPA_SET_VRING_NUM 0
#define TRACE_VHOST_VDPA_SET_VRING_NUM_ENABLED 0
#define TRACE_VHOST_VDPA_SET_VRING_NUM_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_set_vring_num(void *dev, unsigned int index, unsigned int num) {
    (void)dev;
    (void)index;
    (void)num;
}
#define TRACE_VHOST_VDPA_SKIPPED_MEMORY_SECTION 0
#define TRACE_VHOST_VDPA_SKIPPED_MEMORY_SECTION_ENABLED 0
#define TRACE_VHOST_VDPA_SKIPPED_MEMORY_SECTION_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_skipped_memory_section(int is_ram, int is_iommu, int is_protected, int is_ram_device, uint64_t first, uint64_t last, int page_mask) {
    (void)is_ram;
    (void)is_iommu;
    (void)is_protected;
    (void)is_ram_device;
    (void)first;
    (void)last;
    (void)page_mask;
}
#define TRACE_VHOST_VDPA_SUSPEND 0
#define TRACE_VHOST_VDPA_SUSPEND_ENABLED 0
#define TRACE_VHOST_VDPA_SUSPEND_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_suspend(void *dev) {
    (void)dev;
}
#define TRACE_VHOST_VDPA_VQ_GET_ADDR 0
#define TRACE_VHOST_VDPA_VQ_GET_ADDR_ENABLED 0
#define TRACE_VHOST_VDPA_VQ_GET_ADDR_BACKEND_DSTATE() (0)
static inline void trace_vhost_vdpa_vq_get_addr(void *dev, void *vq, uint64_t desc_user_addr, uint64_t avail_user_addr, uint64_t used_user_addr) {
    (void)dev;
    (void)vq;
    (void)desc_user_addr;
    (void)avail_user_addr;
    (void)used_user_addr;
}
#define TRACE_VIRTIO_BALLOON_BAD_ADDR 0
#define TRACE_VIRTIO_BALLOON_BAD_ADDR_ENABLED 0
#define TRACE_VIRTIO_BALLOON_BAD_ADDR_BACKEND_DSTATE() (0)
static inline void trace_virtio_balloon_bad_addr(uint64_t gpa) {
    (void)gpa;
}
#define TRACE_VIRTIO_BALLOON_GET_CONFIG 0
#define TRACE_VIRTIO_BALLOON_GET_CONFIG_ENABLED 0
#define TRACE_VIRTIO_BALLOON_GET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_virtio_balloon_get_config(uint32_t num_pages, uint32_t actual) {
    (void)num_pages;
    (void)actual;
}
#define TRACE_VIRTIO_BALLOON_HANDLE_OUTPUT 0
#define TRACE_VIRTIO_BALLOON_HANDLE_OUTPUT_ENABLED 0
#define TRACE_VIRTIO_BALLOON_HANDLE_OUTPUT_BACKEND_DSTATE() (0)
static inline void trace_virtio_balloon_handle_output(const char *name, uint64_t gpa) {
    (void)name;
    (void)gpa;
}
#define TRACE_VIRTIO_BALLOON_SET_CONFIG 0
#define TRACE_VIRTIO_BALLOON_SET_CONFIG_ENABLED 0
#define TRACE_VIRTIO_BALLOON_SET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_virtio_balloon_set_config(uint32_t actual, uint32_t oldactual) {
    (void)actual;
    (void)oldactual;
}
#define TRACE_VIRTIO_BALLOON_TO_TARGET 0
#define TRACE_VIRTIO_BALLOON_TO_TARGET_ENABLED 0
#define TRACE_VIRTIO_BALLOON_TO_TARGET_BACKEND_DSTATE() (0)
static inline void trace_virtio_balloon_to_target(uint64_t target, uint32_t num_pages) {
    (void)target;
    (void)num_pages;
}
#define TRACE_VIRTIO_GPIO_SET_STATUS 0
#define TRACE_VIRTIO_GPIO_SET_STATUS_ENABLED 0
#define TRACE_VIRTIO_GPIO_SET_STATUS_BACKEND_DSTATE() (0)
static inline void trace_virtio_gpio_set_status(uint8_t status) {
    (void)status;
}
#define TRACE_VIRTIO_GPIO_START 0
#define TRACE_VIRTIO_GPIO_START_ENABLED 0
#define TRACE_VIRTIO_GPIO_START_BACKEND_DSTATE() (0)
static inline void trace_virtio_gpio_start(void) {
}
#define TRACE_VIRTIO_GPIO_STOP 0
#define TRACE_VIRTIO_GPIO_STOP_ENABLED 0
#define TRACE_VIRTIO_GPIO_STOP_BACKEND_DSTATE() (0)
static inline void trace_virtio_gpio_stop(void) {
}
#define TRACE_VIRTIO_IOMMU_ATTACH 0
#define TRACE_VIRTIO_IOMMU_ATTACH_ENABLED 0
#define TRACE_VIRTIO_IOMMU_ATTACH_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_attach(uint32_t domain_id, uint32_t ep_id) {
    (void)domain_id;
    (void)ep_id;
}
#define TRACE_VIRTIO_IOMMU_DETACH 0
#define TRACE_VIRTIO_IOMMU_DETACH_ENABLED 0
#define TRACE_VIRTIO_IOMMU_DETACH_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_detach(uint32_t domain_id, uint32_t ep_id) {
    (void)domain_id;
    (void)ep_id;
}
#define TRACE_VIRTIO_IOMMU_DETACH_ENDPOINT_FROM_DOMAIN 0
#define TRACE_VIRTIO_IOMMU_DETACH_ENDPOINT_FROM_DOMAIN_ENABLED 0
#define TRACE_VIRTIO_IOMMU_DETACH_ENDPOINT_FROM_DOMAIN_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_detach_endpoint_from_domain(uint32_t domain_id, uint32_t ep_id) {
    (void)domain_id;
    (void)ep_id;
}
#define TRACE_VIRTIO_IOMMU_DEVICE_RESET_EXIT 0
#define TRACE_VIRTIO_IOMMU_DEVICE_RESET_EXIT_ENABLED 0
#define TRACE_VIRTIO_IOMMU_DEVICE_RESET_EXIT_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_device_reset_exit(void) {
}
#define TRACE_VIRTIO_IOMMU_DEVICE_STATUS 0
#define TRACE_VIRTIO_IOMMU_DEVICE_STATUS_ENABLED 0
#define TRACE_VIRTIO_IOMMU_DEVICE_STATUS_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_device_status(uint8_t status) {
    (void)status;
}
#define TRACE_VIRTIO_IOMMU_FILL_RESV_PROPERTY 0
#define TRACE_VIRTIO_IOMMU_FILL_RESV_PROPERTY_ENABLED 0
#define TRACE_VIRTIO_IOMMU_FILL_RESV_PROPERTY_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_fill_resv_property(uint32_t devid, uint8_t subtype, uint64_t start, uint64_t end) {
    (void)devid;
    (void)subtype;
    (void)start;
    (void)end;
}
#define TRACE_VIRTIO_IOMMU_FREEZE_GRANULE 0
#define TRACE_VIRTIO_IOMMU_FREEZE_GRANULE_ENABLED 0
#define TRACE_VIRTIO_IOMMU_FREEZE_GRANULE_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_freeze_granule(uint64_t page_size_mask) {
    (void)page_size_mask;
}
#define TRACE_VIRTIO_IOMMU_GET_CONFIG 0
#define TRACE_VIRTIO_IOMMU_GET_CONFIG_ENABLED 0
#define TRACE_VIRTIO_IOMMU_GET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_get_config(uint64_t page_size_mask, uint64_t start, uint64_t end, uint32_t domain_start, uint32_t domain_end, uint32_t probe_size, uint8_t bypass) {
    (void)page_size_mask;
    (void)start;
    (void)end;
    (void)domain_start;
    (void)domain_end;
    (void)probe_size;
    (void)bypass;
}
#define TRACE_VIRTIO_IOMMU_GET_DOMAIN 0
#define TRACE_VIRTIO_IOMMU_GET_DOMAIN_ENABLED 0
#define TRACE_VIRTIO_IOMMU_GET_DOMAIN_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_get_domain(uint32_t domain_id) {
    (void)domain_id;
}
#define TRACE_VIRTIO_IOMMU_GET_ENDPOINT 0
#define TRACE_VIRTIO_IOMMU_GET_ENDPOINT_ENABLED 0
#define TRACE_VIRTIO_IOMMU_GET_ENDPOINT_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_get_endpoint(uint32_t ep_id) {
    (void)ep_id;
}
#define TRACE_VIRTIO_IOMMU_GET_FEATURES 0
#define TRACE_VIRTIO_IOMMU_GET_FEATURES_ENABLED 0
#define TRACE_VIRTIO_IOMMU_GET_FEATURES_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_get_features(uint64_t features) {
    (void)features;
}
#define TRACE_VIRTIO_IOMMU_HOST_RESV_REGIONS 0
#define TRACE_VIRTIO_IOMMU_HOST_RESV_REGIONS_ENABLED 0
#define TRACE_VIRTIO_IOMMU_HOST_RESV_REGIONS_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_host_resv_regions(const char *name, uint32_t index, uint64_t lob, uint64_t upb) {
    (void)name;
    (void)index;
    (void)lob;
    (void)upb;
}
#define TRACE_VIRTIO_IOMMU_INIT_IOMMU_MR 0
#define TRACE_VIRTIO_IOMMU_INIT_IOMMU_MR_ENABLED 0
#define TRACE_VIRTIO_IOMMU_INIT_IOMMU_MR_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_init_iommu_mr(char *iommu_mr) {
    (void)iommu_mr;
}
#define TRACE_VIRTIO_IOMMU_MAP 0
#define TRACE_VIRTIO_IOMMU_MAP_ENABLED 0
#define TRACE_VIRTIO_IOMMU_MAP_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_map(uint32_t domain_id, uint64_t virt_start, uint64_t virt_end, uint64_t phys_start, uint32_t flags) {
    (void)domain_id;
    (void)virt_start;
    (void)virt_end;
    (void)phys_start;
    (void)flags;
}
#define TRACE_VIRTIO_IOMMU_NOTIFY_FLAG_ADD 0
#define TRACE_VIRTIO_IOMMU_NOTIFY_FLAG_ADD_ENABLED 0
#define TRACE_VIRTIO_IOMMU_NOTIFY_FLAG_ADD_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_notify_flag_add(const char *name) {
    (void)name;
}
#define TRACE_VIRTIO_IOMMU_NOTIFY_FLAG_DEL 0
#define TRACE_VIRTIO_IOMMU_NOTIFY_FLAG_DEL_ENABLED 0
#define TRACE_VIRTIO_IOMMU_NOTIFY_FLAG_DEL_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_notify_flag_del(const char *name) {
    (void)name;
}
#define TRACE_VIRTIO_IOMMU_NOTIFY_MAP 0
#define TRACE_VIRTIO_IOMMU_NOTIFY_MAP_ENABLED 0
#define TRACE_VIRTIO_IOMMU_NOTIFY_MAP_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_notify_map(const char *name, uint64_t virt_start, uint64_t virt_end, uint64_t phys_start, uint32_t flags) {
    (void)name;
    (void)virt_start;
    (void)virt_end;
    (void)phys_start;
    (void)flags;
}
#define TRACE_VIRTIO_IOMMU_NOTIFY_UNMAP 0
#define TRACE_VIRTIO_IOMMU_NOTIFY_UNMAP_ENABLED 0
#define TRACE_VIRTIO_IOMMU_NOTIFY_UNMAP_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_notify_unmap(const char *name, uint64_t virt_start, uint64_t virt_end) {
    (void)name;
    (void)virt_start;
    (void)virt_end;
}
#define TRACE_VIRTIO_IOMMU_PUT_DOMAIN 0
#define TRACE_VIRTIO_IOMMU_PUT_DOMAIN_ENABLED 0
#define TRACE_VIRTIO_IOMMU_PUT_DOMAIN_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_put_domain(uint32_t domain_id) {
    (void)domain_id;
}
#define TRACE_VIRTIO_IOMMU_PUT_ENDPOINT 0
#define TRACE_VIRTIO_IOMMU_PUT_ENDPOINT_ENABLED 0
#define TRACE_VIRTIO_IOMMU_PUT_ENDPOINT_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_put_endpoint(uint32_t ep_id) {
    (void)ep_id;
}
#define TRACE_VIRTIO_IOMMU_REMAP 0
#define TRACE_VIRTIO_IOMMU_REMAP_ENABLED 0
#define TRACE_VIRTIO_IOMMU_REMAP_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_remap(const char *name, uint64_t virt_start, uint64_t virt_end, uint64_t phys_start) {
    (void)name;
    (void)virt_start;
    (void)virt_end;
    (void)phys_start;
}
#define TRACE_VIRTIO_IOMMU_REPORT_FAULT 0
#define TRACE_VIRTIO_IOMMU_REPORT_FAULT_ENABLED 0
#define TRACE_VIRTIO_IOMMU_REPORT_FAULT_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_report_fault(uint8_t reason, uint32_t flags, uint32_t endpoint, uint64_t addr) {
    (void)reason;
    (void)flags;
    (void)endpoint;
    (void)addr;
}
#define TRACE_VIRTIO_IOMMU_SET_CONFIG 0
#define TRACE_VIRTIO_IOMMU_SET_CONFIG_ENABLED 0
#define TRACE_VIRTIO_IOMMU_SET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_set_config(uint8_t bypass) {
    (void)bypass;
}
#define TRACE_VIRTIO_IOMMU_SWITCH_ADDRESS_SPACE 0
#define TRACE_VIRTIO_IOMMU_SWITCH_ADDRESS_SPACE_ENABLED 0
#define TRACE_VIRTIO_IOMMU_SWITCH_ADDRESS_SPACE_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_switch_address_space(uint8_t bus, uint8_t slot, uint8_t fn, bool on) {
    (void)bus;
    (void)slot;
    (void)fn;
    (void)on;
}
#define TRACE_VIRTIO_IOMMU_SYSTEM_RESET 0
#define TRACE_VIRTIO_IOMMU_SYSTEM_RESET_ENABLED 0
#define TRACE_VIRTIO_IOMMU_SYSTEM_RESET_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_system_reset(void) {
}
#define TRACE_VIRTIO_IOMMU_TRANSLATE 0
#define TRACE_VIRTIO_IOMMU_TRANSLATE_ENABLED 0
#define TRACE_VIRTIO_IOMMU_TRANSLATE_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_translate(const char *name, uint32_t rid, uint64_t iova, int flag) {
    (void)name;
    (void)rid;
    (void)iova;
    (void)flag;
}
#define TRACE_VIRTIO_IOMMU_TRANSLATE_OUT 0
#define TRACE_VIRTIO_IOMMU_TRANSLATE_OUT_ENABLED 0
#define TRACE_VIRTIO_IOMMU_TRANSLATE_OUT_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_translate_out(uint64_t virt_addr, uint64_t phys_addr, uint32_t sid) {
    (void)virt_addr;
    (void)phys_addr;
    (void)sid;
}
#define TRACE_VIRTIO_IOMMU_UNMAP 0
#define TRACE_VIRTIO_IOMMU_UNMAP_ENABLED 0
#define TRACE_VIRTIO_IOMMU_UNMAP_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_unmap(uint32_t domain_id, uint64_t virt_start, uint64_t virt_end) {
    (void)domain_id;
    (void)virt_start;
    (void)virt_end;
}
#define TRACE_VIRTIO_IOMMU_UNMAP_DONE 0
#define TRACE_VIRTIO_IOMMU_UNMAP_DONE_ENABLED 0
#define TRACE_VIRTIO_IOMMU_UNMAP_DONE_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_unmap_done(uint32_t domain_id, uint64_t virt_start, uint64_t virt_end) {
    (void)domain_id;
    (void)virt_start;
    (void)virt_end;
}
#define TRACE_VIRTIO_IOMMU_UPDATE_PAGE_SIZE_MASK 0
#define TRACE_VIRTIO_IOMMU_UPDATE_PAGE_SIZE_MASK_ENABLED 0
#define TRACE_VIRTIO_IOMMU_UPDATE_PAGE_SIZE_MASK_BACKEND_DSTATE() (0)
static inline void trace_virtio_iommu_update_page_size_mask(const char *name, uint64_t old, uint64_t new) {
    (void)name;
    (void)old;
    (void)new;
}
#define TRACE_VIRTIO_MEM_PLUG_REQUEST 0
#define TRACE_VIRTIO_MEM_PLUG_REQUEST_ENABLED 0
#define TRACE_VIRTIO_MEM_PLUG_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_virtio_mem_plug_request(uint64_t addr, uint16_t nb_blocks) {
    (void)addr;
    (void)nb_blocks;
}
#define TRACE_VIRTIO_MEM_RESIZED_USABLE_REGION 0
#define TRACE_VIRTIO_MEM_RESIZED_USABLE_REGION_ENABLED 0
#define TRACE_VIRTIO_MEM_RESIZED_USABLE_REGION_BACKEND_DSTATE() (0)
static inline void trace_virtio_mem_resized_usable_region(uint64_t old_size, uint64_t new_size) {
    (void)old_size;
    (void)new_size;
}
#define TRACE_VIRTIO_MEM_SEND_RESPONSE 0
#define TRACE_VIRTIO_MEM_SEND_RESPONSE_ENABLED 0
#define TRACE_VIRTIO_MEM_SEND_RESPONSE_BACKEND_DSTATE() (0)
static inline void trace_virtio_mem_send_response(uint16_t type) {
    (void)type;
}
#define TRACE_VIRTIO_MEM_STATE_REQUEST 0
#define TRACE_VIRTIO_MEM_STATE_REQUEST_ENABLED 0
#define TRACE_VIRTIO_MEM_STATE_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_virtio_mem_state_request(uint64_t addr, uint16_t nb_blocks) {
    (void)addr;
    (void)nb_blocks;
}
#define TRACE_VIRTIO_MEM_STATE_RESPONSE 0
#define TRACE_VIRTIO_MEM_STATE_RESPONSE_ENABLED 0
#define TRACE_VIRTIO_MEM_STATE_RESPONSE_BACKEND_DSTATE() (0)
static inline void trace_virtio_mem_state_response(uint16_t state) {
    (void)state;
}
#define TRACE_VIRTIO_MEM_UNPLUG_ALL_REQUEST 0
#define TRACE_VIRTIO_MEM_UNPLUG_ALL_REQUEST_ENABLED 0
#define TRACE_VIRTIO_MEM_UNPLUG_ALL_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_virtio_mem_unplug_all_request(void) {
}
#define TRACE_VIRTIO_MEM_UNPLUG_REQUEST 0
#define TRACE_VIRTIO_MEM_UNPLUG_REQUEST_ENABLED 0
#define TRACE_VIRTIO_MEM_UNPLUG_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_virtio_mem_unplug_request(uint64_t addr, uint16_t nb_blocks) {
    (void)addr;
    (void)nb_blocks;
}
#define TRACE_VIRTIO_MEM_UNPLUGGED_ALL 0
#define TRACE_VIRTIO_MEM_UNPLUGGED_ALL_ENABLED 0
#define TRACE_VIRTIO_MEM_UNPLUGGED_ALL_BACKEND_DSTATE() (0)
static inline void trace_virtio_mem_unplugged_all(void) {
}
#define TRACE_VIRTIO_MMIO_GUEST_PAGE 0
#define TRACE_VIRTIO_MMIO_GUEST_PAGE_ENABLED 0
#define TRACE_VIRTIO_MMIO_GUEST_PAGE_BACKEND_DSTATE() (0)
static inline void trace_virtio_mmio_guest_page(uint64_t size, int shift) {
    (void)size;
    (void)shift;
}
#define TRACE_VIRTIO_MMIO_QUEUE_WRITE 0
#define TRACE_VIRTIO_MMIO_QUEUE_WRITE_ENABLED 0
#define TRACE_VIRTIO_MMIO_QUEUE_WRITE_BACKEND_DSTATE() (0)
static inline void trace_virtio_mmio_queue_write(uint64_t value, int max_size) {
    (void)value;
    (void)max_size;
}
#define TRACE_VIRTIO_MMIO_READ 0
#define TRACE_VIRTIO_MMIO_READ_ENABLED 0
#define TRACE_VIRTIO_MMIO_READ_BACKEND_DSTATE() (0)
static inline void trace_virtio_mmio_read(uint64_t offset) {
    (void)offset;
}
#define TRACE_VIRTIO_MMIO_SETTING_IRQ 0
#define TRACE_VIRTIO_MMIO_SETTING_IRQ_ENABLED 0
#define TRACE_VIRTIO_MMIO_SETTING_IRQ_BACKEND_DSTATE() (0)
static inline void trace_virtio_mmio_setting_irq(int level) {
    (void)level;
}
#define TRACE_VIRTIO_MMIO_WRITE_OFFSET 0
#define TRACE_VIRTIO_MMIO_WRITE_OFFSET_ENABLED 0
#define TRACE_VIRTIO_MMIO_WRITE_OFFSET_BACKEND_DSTATE() (0)
static inline void trace_virtio_mmio_write_offset(uint64_t offset, uint64_t value) {
    (void)offset;
    (void)value;
}
#define TRACE_VIRTIO_NOTIFY 0
#define TRACE_VIRTIO_NOTIFY_ENABLED 0
#define TRACE_VIRTIO_NOTIFY_BACKEND_DSTATE() (0)
static inline void trace_virtio_notify(void *vdev, void *vq) {
    (void)vdev;
    (void)vq;
}
#define TRACE_VIRTIO_NOTIFY_IRQFD_DEFERRED_FN 0
#define TRACE_VIRTIO_NOTIFY_IRQFD_DEFERRED_FN_ENABLED 0
#define TRACE_VIRTIO_NOTIFY_IRQFD_DEFERRED_FN_BACKEND_DSTATE() (0)
static inline void trace_virtio_notify_irqfd_deferred_fn(void *vdev, void *vq) {
    (void)vdev;
    (void)vq;
}
#define TRACE_VIRTIO_PCI_NOTIFY 0
#define TRACE_VIRTIO_PCI_NOTIFY_ENABLED 0
#define TRACE_VIRTIO_PCI_NOTIFY_BACKEND_DSTATE() (0)
static inline void trace_virtio_pci_notify(uint16_t vector) {
    (void)vector;
}
#define TRACE_VIRTIO_PCI_NOTIFY_WRITE 0
#define TRACE_VIRTIO_PCI_NOTIFY_WRITE_ENABLED 0
#define TRACE_VIRTIO_PCI_NOTIFY_WRITE_BACKEND_DSTATE() (0)
static inline void trace_virtio_pci_notify_write(uint64_t addr, uint64_t val, unsigned int size) {
    (void)addr;
    (void)val;
    (void)size;
}
#define TRACE_VIRTIO_PCI_NOTIFY_WRITE_PIO 0
#define TRACE_VIRTIO_PCI_NOTIFY_WRITE_PIO_ENABLED 0
#define TRACE_VIRTIO_PCI_NOTIFY_WRITE_PIO_BACKEND_DSTATE() (0)
static inline void trace_virtio_pci_notify_write_pio(uint64_t addr, uint64_t val, unsigned int size) {
    (void)addr;
    (void)val;
    (void)size;
}
#define TRACE_VIRTIO_PMEM_FLUSH_DONE 0
#define TRACE_VIRTIO_PMEM_FLUSH_DONE_ENABLED 0
#define TRACE_VIRTIO_PMEM_FLUSH_DONE_BACKEND_DSTATE() (0)
static inline void trace_virtio_pmem_flush_done(int type) {
    (void)type;
}
#define TRACE_VIRTIO_PMEM_FLUSH_REQUEST 0
#define TRACE_VIRTIO_PMEM_FLUSH_REQUEST_ENABLED 0
#define TRACE_VIRTIO_PMEM_FLUSH_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_virtio_pmem_flush_request(void) {
}
#define TRACE_VIRTIO_PMEM_RESPONSE 0
#define TRACE_VIRTIO_PMEM_RESPONSE_ENABLED 0
#define TRACE_VIRTIO_PMEM_RESPONSE_BACKEND_DSTATE() (0)
static inline void trace_virtio_pmem_response(void) {
}
#define TRACE_VIRTIO_QUEUE_NOTIFY 0
#define TRACE_VIRTIO_QUEUE_NOTIFY_ENABLED 0
#define TRACE_VIRTIO_QUEUE_NOTIFY_BACKEND_DSTATE() (0)
static inline void trace_virtio_queue_notify(void *vdev, int n, void *vq) {
    (void)vdev;
    (void)n;
    (void)vq;
}
#define TRACE_VIRTIO_RNG_CPU_IS_STOPPED 0
#define TRACE_VIRTIO_RNG_CPU_IS_STOPPED_ENABLED 0
#define TRACE_VIRTIO_RNG_CPU_IS_STOPPED_BACKEND_DSTATE() (0)
static inline void trace_virtio_rng_cpu_is_stopped(void *rng, int size) {
    (void)rng;
    (void)size;
}
#define TRACE_VIRTIO_RNG_GUEST_NOT_READY 0
#define TRACE_VIRTIO_RNG_GUEST_NOT_READY_ENABLED 0
#define TRACE_VIRTIO_RNG_GUEST_NOT_READY_BACKEND_DSTATE() (0)
static inline void trace_virtio_rng_guest_not_ready(void *rng) {
    (void)rng;
}
#define TRACE_VIRTIO_RNG_POPPED 0
#define TRACE_VIRTIO_RNG_POPPED_ENABLED 0
#define TRACE_VIRTIO_RNG_POPPED_BACKEND_DSTATE() (0)
static inline void trace_virtio_rng_popped(void *rng) {
    (void)rng;
}
#define TRACE_VIRTIO_RNG_PUSHED 0
#define TRACE_VIRTIO_RNG_PUSHED_ENABLED 0
#define TRACE_VIRTIO_RNG_PUSHED_BACKEND_DSTATE() (0)
static inline void trace_virtio_rng_pushed(void *rng, size_t len) {
    (void)rng;
    (void)len;
}
#define TRACE_VIRTIO_RNG_REQUEST 0
#define TRACE_VIRTIO_RNG_REQUEST_ENABLED 0
#define TRACE_VIRTIO_RNG_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_virtio_rng_request(void *rng, size_t size, unsigned quota) {
    (void)rng;
    (void)size;
    (void)quota;
}
#define TRACE_VIRTIO_RNG_VM_STATE_CHANGE 0
#define TRACE_VIRTIO_RNG_VM_STATE_CHANGE_ENABLED 0
#define TRACE_VIRTIO_RNG_VM_STATE_CHANGE_BACKEND_DSTATE() (0)
static inline void trace_virtio_rng_vm_state_change(void *rng, int running, int state) {
    (void)rng;
    (void)running;
    (void)state;
}
#define TRACE_VIRTIO_SET_STATUS 0
#define TRACE_VIRTIO_SET_STATUS_ENABLED 0
#define TRACE_VIRTIO_SET_STATUS_BACKEND_DSTATE() (0)
static inline void trace_virtio_set_status(void *vdev, uint8_t val) {
    (void)vdev;
    (void)val;
}
#define TRACE_VIRTQUEUE_ALLOC_ELEMENT 0
#define TRACE_VIRTQUEUE_ALLOC_ELEMENT_ENABLED 0
#define TRACE_VIRTQUEUE_ALLOC_ELEMENT_BACKEND_DSTATE() (0)
static inline void trace_virtqueue_alloc_element(void *elem, size_t sz, unsigned in_num, unsigned out_num) {
    (void)elem;
    (void)sz;
    (void)in_num;
    (void)out_num;
}
#define TRACE_VIRTQUEUE_FILL 0
#define TRACE_VIRTQUEUE_FILL_ENABLED 0
#define TRACE_VIRTQUEUE_FILL_BACKEND_DSTATE() (0)
static inline void trace_virtqueue_fill(void *vq, const void *elem, unsigned int len, unsigned int idx) {
    (void)vq;
    (void)elem;
    (void)len;
    (void)idx;
}
#define TRACE_VIRTQUEUE_FLUSH 0
#define TRACE_VIRTQUEUE_FLUSH_ENABLED 0
#define TRACE_VIRTQUEUE_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_virtqueue_flush(void *vq, unsigned int count) {
    (void)vq;
    (void)count;
}
#define TRACE_VIRTQUEUE_POP 0
#define TRACE_VIRTQUEUE_POP_ENABLED 0
#define TRACE_VIRTQUEUE_POP_BACKEND_DSTATE() (0)
static inline void trace_virtqueue_pop(void *vq, void *elem, unsigned int in_num, unsigned int out_num) {
    (void)vq;
    (void)elem;
    (void)in_num;
    (void)out_num;
}

#endif