/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_ALPHA_H
#define TRACE_TRACE_HW_ALPHA_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_ALPHA_PCI_IACK_WRITE 0
#define TRACE_ALPHA_PCI_IACK_WRITE_ENABLED 0
#define TRACE_ALPHA_PCI_IACK_WRITE_BACKEND_DSTATE() (0)
static inline void trace_alpha_pci_iack_write(void) {
}

#endif