/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_EBPF_H
#define TRACE_TRACE_EBPF_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_EBPF_RSS_LOAD 0
#define TRACE_EBPF_RSS_LOAD_ENABLED 0
#define TRACE_EBPF_RSS_LOAD_BACKEND_DSTATE() (0)
static inline void trace_ebpf_rss_load(void *ctx, int progfd, int cfgfd, int toepfd, int indirfd) {
    (void)ctx;
    (void)progfd;
    (void)cfgfd;
    (void)toepfd;
    (void)indirfd;
}
#define TRACE_EBPF_RSS_LOAD_ERROR 0
#define TRACE_EBPF_RSS_LOAD_ERROR_ENABLED 0
#define TRACE_EBPF_RSS_LOAD_ERROR_BACKEND_DSTATE() (0)
static inline void trace_ebpf_rss_load_error(void *ctx) {
    (void)ctx;
}
#define TRACE_EBPF_RSS_MMAP 0
#define TRACE_EBPF_RSS_MMAP_ENABLED 0
#define TRACE_EBPF_RSS_MMAP_BACKEND_DSTATE() (0)
static inline void trace_ebpf_rss_mmap(void *ctx, void *cfgptr, void *toepptr, void *indirptr) {
    (void)ctx;
    (void)cfgptr;
    (void)toepptr;
    (void)indirptr;
}
#define TRACE_EBPF_RSS_MMAP_ERROR 0
#define TRACE_EBPF_RSS_MMAP_ERROR_ENABLED 0
#define TRACE_EBPF_RSS_MMAP_ERROR_BACKEND_DSTATE() (0)
static inline void trace_ebpf_rss_mmap_error(void *ctx, const char *object) {
    (void)ctx;
    (void)object;
}
#define TRACE_EBPF_RSS_OPEN_ERROR 0
#define TRACE_EBPF_RSS_OPEN_ERROR_ENABLED 0
#define TRACE_EBPF_RSS_OPEN_ERROR_BACKEND_DSTATE() (0)
static inline void trace_ebpf_rss_open_error(void *ctx) {
    (void)ctx;
}
#define TRACE_EBPF_RSS_SET_DATA 0
#define TRACE_EBPF_RSS_SET_DATA_ENABLED 0
#define TRACE_EBPF_RSS_SET_DATA_BACKEND_DSTATE() (0)
static inline void trace_ebpf_rss_set_data(void *ctx, void *cfgptr, void *toepptr, void *indirptr) {
    (void)ctx;
    (void)cfgptr;
    (void)toepptr;
    (void)indirptr;
}
#define TRACE_EBPF_RSS_UNLOAD 0
#define TRACE_EBPF_RSS_UNLOAD_ENABLED 0
#define TRACE_EBPF_RSS_UNLOAD_BACKEND_DSTATE() (0)
static inline void trace_ebpf_rss_unload(void *ctx) {
    (void)ctx;
}

#endif