/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_NET_CAN_H
#define TRACE_TRACE_HW_NET_CAN_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_XLNX_CAN_FILTER_ID_PRE_WRITE 0
#define TRACE_XLNX_CAN_FILTER_ID_PRE_WRITE_ENABLED 0
#define TRACE_XLNX_CAN_FILTER_ID_PRE_WRITE_BACKEND_DSTATE() (0)
static inline void trace_xlnx_can_filter_id_pre_write(uint8_t filter_num, uint32_t value) {
    (void)filter_num;
    (void)value;
}
#define TRACE_XLNX_CAN_FILTER_MASK_PRE_WRITE 0
#define TRACE_XLNX_CAN_FILTER_MASK_PRE_WRITE_ENABLED 0
#define TRACE_XLNX_CAN_FILTER_MASK_PRE_WRITE_BACKEND_DSTATE() (0)
static inline void trace_xlnx_can_filter_mask_pre_write(uint8_t filter_num, uint32_t value) {
    (void)filter_num;
    (void)value;
}
#define TRACE_XLNX_CAN_RESET 0
#define TRACE_XLNX_CAN_RESET_ENABLED 0
#define TRACE_XLNX_CAN_RESET_BACKEND_DSTATE() (0)
static inline void trace_xlnx_can_reset(uint32_t val) {
    (void)val;
}
#define TRACE_XLNX_CAN_RX_DATA 0
#define TRACE_XLNX_CAN_RX_DATA_ENABLED 0
#define TRACE_XLNX_CAN_RX_DATA_BACKEND_DSTATE() (0)
static inline void trace_xlnx_can_rx_data(uint32_t id, uint32_t dlc, uint8_t db0, uint8_t db1, uint8_t db2, uint8_t db3, uint8_t db4, uint8_t db5, uint8_t db6, uint8_t db7) {
    (void)id;
    (void)dlc;
    (void)db0;
    (void)db1;
    (void)db2;
    (void)db3;
    (void)db4;
    (void)db5;
    (void)db6;
    (void)db7;
}
#define TRACE_XLNX_CAN_RX_DISCARD 0
#define TRACE_XLNX_CAN_RX_DISCARD_ENABLED 0
#define TRACE_XLNX_CAN_RX_DISCARD_BACKEND_DSTATE() (0)
static inline void trace_xlnx_can_rx_discard(uint32_t status) {
    (void)status;
}
#define TRACE_XLNX_CAN_RX_FIFO_FILTER_REJECT 0
#define TRACE_XLNX_CAN_RX_FIFO_FILTER_REJECT_ENABLED 0
#define TRACE_XLNX_CAN_RX_FIFO_FILTER_REJECT_BACKEND_DSTATE() (0)
static inline void trace_xlnx_can_rx_fifo_filter_reject(uint32_t id, uint8_t dlc) {
    (void)id;
    (void)dlc;
}
#define TRACE_XLNX_CAN_TX_DATA 0
#define TRACE_XLNX_CAN_TX_DATA_ENABLED 0
#define TRACE_XLNX_CAN_TX_DATA_BACKEND_DSTATE() (0)
static inline void trace_xlnx_can_tx_data(uint32_t id, uint8_t dlc, uint8_t db0, uint8_t db1, uint8_t db2, uint8_t db3, uint8_t db4, uint8_t db5, uint8_t db6, uint8_t db7) {
    (void)id;
    (void)dlc;
    (void)db0;
    (void)db1;
    (void)db2;
    (void)db3;
    (void)db4;
    (void)db5;
    (void)db6;
    (void)db7;
}
#define TRACE_XLNX_CAN_UPDATE_IRQ 0
#define TRACE_XLNX_CAN_UPDATE_IRQ_ENABLED 0
#define TRACE_XLNX_CAN_UPDATE_IRQ_BACKEND_DSTATE() (0)
static inline void trace_xlnx_can_update_irq(uint32_t isr, uint32_t ier, uint32_t irq) {
    (void)isr;
    (void)ier;
    (void)irq;
}
#define TRACE_XLNX_CANFD_RESET 0
#define TRACE_XLNX_CANFD_RESET_ENABLED 0
#define TRACE_XLNX_CANFD_RESET_BACKEND_DSTATE() (0)
static inline void trace_xlnx_canfd_reset(char *path, uint32_t val) {
    (void)path;
    (void)val;
}
#define TRACE_XLNX_CANFD_RX_DATA 0
#define TRACE_XLNX_CANFD_RX_DATA_ENABLED 0
#define TRACE_XLNX_CANFD_RX_DATA_BACKEND_DSTATE() (0)
static inline void trace_xlnx_canfd_rx_data(char *path, uint32_t id, uint8_t dlc, uint8_t flags) {
    (void)path;
    (void)id;
    (void)dlc;
    (void)flags;
}
#define TRACE_XLNX_CANFD_RX_FIFO_FILTER_REJECT 0
#define TRACE_XLNX_CANFD_RX_FIFO_FILTER_REJECT_ENABLED 0
#define TRACE_XLNX_CANFD_RX_FIFO_FILTER_REJECT_BACKEND_DSTATE() (0)
static inline void trace_xlnx_canfd_rx_fifo_filter_reject(char *path, uint32_t id, uint8_t dlc) {
    (void)path;
    (void)id;
    (void)dlc;
}
#define TRACE_XLNX_CANFD_TX_DATA 0
#define TRACE_XLNX_CANFD_TX_DATA_ENABLED 0
#define TRACE_XLNX_CANFD_TX_DATA_BACKEND_DSTATE() (0)
static inline void trace_xlnx_canfd_tx_data(char *path, uint32_t id, uint8_t dlc, uint8_t flgas) {
    (void)path;
    (void)id;
    (void)dlc;
    (void)flgas;
}
#define TRACE_XLNX_CANFD_UPDATE_IRQ 0
#define TRACE_XLNX_CANFD_UPDATE_IRQ_ENABLED 0
#define TRACE_XLNX_CANFD_UPDATE_IRQ_BACKEND_DSTATE() (0)
static inline void trace_xlnx_canfd_update_irq(char *path, uint32_t isr, uint32_t ier, uint32_t irq) {
    (void)path;
    (void)isr;
    (void)ier;
    (void)irq;
}

#endif