/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_CHARDEV_H
#define TRACE_TRACE_CHARDEV_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_CHR_SOCKET_DISCONNECT 0
#define TRACE_CHR_SOCKET_DISCONNECT_ENABLED 0
#define TRACE_CHR_SOCKET_DISCONNECT_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_disconnect(void *chrdev, const char *label) {
    (void)chrdev;
    (void)label;
}
#define TRACE_CHR_SOCKET_HANGUP 0
#define TRACE_CHR_SOCKET_HANGUP_ENABLED 0
#define TRACE_CHR_SOCKET_HANGUP_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_hangup(void *chrdev, const char *label) {
    (void)chrdev;
    (void)label;
}
#define TRACE_CHR_SOCKET_POLL_ERR 0
#define TRACE_CHR_SOCKET_POLL_ERR_ENABLED 0
#define TRACE_CHR_SOCKET_POLL_ERR_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_poll_err(void *chrdev, const char *label) {
    (void)chrdev;
    (void)label;
}
#define TRACE_CHR_SOCKET_RECV_EOF 0
#define TRACE_CHR_SOCKET_RECV_EOF_ENABLED 0
#define TRACE_CHR_SOCKET_RECV_EOF_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_recv_eof(void *chrdev, const char *label) {
    (void)chrdev;
    (void)label;
}
#define TRACE_CHR_SOCKET_RECV_ERR 0
#define TRACE_CHR_SOCKET_RECV_ERR_ENABLED 0
#define TRACE_CHR_SOCKET_RECV_ERR_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_recv_err(void *chrdev, const char *label, const char *err) {
    (void)chrdev;
    (void)label;
    (void)err;
}
#define TRACE_CHR_SOCKET_TLS_HANDSHAKE_ERR 0
#define TRACE_CHR_SOCKET_TLS_HANDSHAKE_ERR_ENABLED 0
#define TRACE_CHR_SOCKET_TLS_HANDSHAKE_ERR_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_tls_handshake_err(void *chrdev, const char *label, const char *err) {
    (void)chrdev;
    (void)label;
    (void)err;
}
#define TRACE_CHR_SOCKET_TLS_INIT_ERR 0
#define TRACE_CHR_SOCKET_TLS_INIT_ERR_ENABLED 0
#define TRACE_CHR_SOCKET_TLS_INIT_ERR_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_tls_init_err(void *chrdev, const char *label, const char *err) {
    (void)chrdev;
    (void)label;
    (void)err;
}
#define TRACE_CHR_SOCKET_WRITE_ERR 0
#define TRACE_CHR_SOCKET_WRITE_ERR_ENABLED 0
#define TRACE_CHR_SOCKET_WRITE_ERR_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_write_err(void *chrdev, const char *label, const char *err) {
    (void)chrdev;
    (void)label;
    (void)err;
}
#define TRACE_CHR_SOCKET_WS_HANDSHAKE_ERR 0
#define TRACE_CHR_SOCKET_WS_HANDSHAKE_ERR_ENABLED 0
#define TRACE_CHR_SOCKET_WS_HANDSHAKE_ERR_BACKEND_DSTATE() (0)
static inline void trace_chr_socket_ws_handshake_err(void *chrdev, const char *label, const char *err) {
    (void)chrdev;
    (void)label;
    (void)err;
}
#define TRACE_SPICE_CHR_DISCARD_WRITE 0
#define TRACE_SPICE_CHR_DISCARD_WRITE_ENABLED 0
#define TRACE_SPICE_CHR_DISCARD_WRITE_BACKEND_DSTATE() (0)
static inline void trace_spice_chr_discard_write(int len) {
    (void)len;
}
#define TRACE_SPICE_VMC_EVENT 0
#define TRACE_SPICE_VMC_EVENT_ENABLED 0
#define TRACE_SPICE_VMC_EVENT_BACKEND_DSTATE() (0)
static inline void trace_spice_vmc_event(int event) {
    (void)event;
}
#define TRACE_SPICE_VMC_READ 0
#define TRACE_SPICE_VMC_READ_ENABLED 0
#define TRACE_SPICE_VMC_READ_BACKEND_DSTATE() (0)
static inline void trace_spice_vmc_read(int bytes, int len) {
    (void)bytes;
    (void)len;
}
#define TRACE_SPICE_VMC_REGISTER_INTERFACE 0
#define TRACE_SPICE_VMC_REGISTER_INTERFACE_ENABLED 0
#define TRACE_SPICE_VMC_REGISTER_INTERFACE_BACKEND_DSTATE() (0)
static inline void trace_spice_vmc_register_interface(void *scd) {
    (void)scd;
}
#define TRACE_SPICE_VMC_UNREGISTER_INTERFACE 0
#define TRACE_SPICE_VMC_UNREGISTER_INTERFACE_ENABLED 0
#define TRACE_SPICE_VMC_UNREGISTER_INTERFACE_BACKEND_DSTATE() (0)
static inline void trace_spice_vmc_unregister_interface(void *scd) {
    (void)scd;
}
#define TRACE_SPICE_VMC_WRITE 0
#define TRACE_SPICE_VMC_WRITE_ENABLED 0
#define TRACE_SPICE_VMC_WRITE_BACKEND_DSTATE() (0)
static inline void trace_spice_vmc_write(ssize_t out, int len) {
    (void)out;
    (void)len;
}
#define TRACE_WCT_CMD_OTHER 0
#define TRACE_WCT_CMD_OTHER_ENABLED 0
#define TRACE_WCT_CMD_OTHER_BACKEND_DSTATE() (0)
static inline void trace_wct_cmd_other(const char *cmd) {
    (void)cmd;
}
#define TRACE_WCT_CMD_RE 0
#define TRACE_WCT_CMD_RE_ENABLED 0
#define TRACE_WCT_CMD_RE_BACKEND_DSTATE() (0)
static inline void trace_wct_cmd_re(void) {
}
#define TRACE_WCT_CMD_SP 0
#define TRACE_WCT_CMD_SP_ENABLED 0
#define TRACE_WCT_CMD_SP_BACKEND_DSTATE() (0)
static inline void trace_wct_cmd_sp(void) {
}
#define TRACE_WCT_CMD_ST 0
#define TRACE_WCT_CMD_ST_ENABLED 0
#define TRACE_WCT_CMD_ST_BACKEND_DSTATE() (0)
static inline void trace_wct_cmd_st(void) {
}
#define TRACE_WCT_CMD_TS 0
#define TRACE_WCT_CMD_TS_ENABLED 0
#define TRACE_WCT_CMD_TS_BACKEND_DSTATE() (0)
static inline void trace_wct_cmd_ts(int input) {
    (void)input;
}
#define TRACE_WCT_INIT 0
#define TRACE_WCT_INIT_ENABLED 0
#define TRACE_WCT_INIT_BACKEND_DSTATE() (0)
static inline void trace_wct_init(void) {
}
#define TRACE_WCT_SPEED 0
#define TRACE_WCT_SPEED_ENABLED 0
#define TRACE_WCT_SPEED_BACKEND_DSTATE() (0)
static inline void trace_wct_speed(int speed) {
    (void)speed;
}

#endif