/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_SCSI_H
#define TRACE_TRACE_HW_SCSI_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_ESP_COMMAND_COMPLETE 0
#define TRACE_ESP_COMMAND_COMPLETE_ENABLED 0
#define TRACE_ESP_COMMAND_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_esp_command_complete(void) {
}
#define TRACE_ESP_COMMAND_COMPLETE_DEFERRED 0
#define TRACE_ESP_COMMAND_COMPLETE_DEFERRED_ENABLED 0
#define TRACE_ESP_COMMAND_COMPLETE_DEFERRED_BACKEND_DSTATE() (0)
static inline void trace_esp_command_complete_deferred(void) {
}
#define TRACE_ESP_COMMAND_COMPLETE_FAIL 0
#define TRACE_ESP_COMMAND_COMPLETE_FAIL_ENABLED 0
#define TRACE_ESP_COMMAND_COMPLETE_FAIL_BACKEND_DSTATE() (0)
static inline void trace_esp_command_complete_fail(void) {
}
#define TRACE_ESP_COMMAND_COMPLETE_UNEXPECTED 0
#define TRACE_ESP_COMMAND_COMPLETE_UNEXPECTED_ENABLED 0
#define TRACE_ESP_COMMAND_COMPLETE_UNEXPECTED_BACKEND_DSTATE() (0)
static inline void trace_esp_command_complete_unexpected(void) {
}
#define TRACE_ESP_DMA_DISABLE 0
#define TRACE_ESP_DMA_DISABLE_ENABLED 0
#define TRACE_ESP_DMA_DISABLE_BACKEND_DSTATE() (0)
static inline void trace_esp_dma_disable(void) {
}
#define TRACE_ESP_DMA_ENABLE 0
#define TRACE_ESP_DMA_ENABLE_ENABLED 0
#define TRACE_ESP_DMA_ENABLE_BACKEND_DSTATE() (0)
static inline void trace_esp_dma_enable(void) {
}
#define TRACE_ESP_DO_COMMAND_PHASE 0
#define TRACE_ESP_DO_COMMAND_PHASE_ENABLED 0
#define TRACE_ESP_DO_COMMAND_PHASE_BACKEND_DSTATE() (0)
static inline void trace_esp_do_command_phase(uint8_t busid) {
    (void)busid;
}
#define TRACE_ESP_DO_DMA 0
#define TRACE_ESP_DO_DMA_ENABLED 0
#define TRACE_ESP_DO_DMA_BACKEND_DSTATE() (0)
static inline void trace_esp_do_dma(uint32_t cmdlen, uint32_t len) {
    (void)cmdlen;
    (void)len;
}
#define TRACE_ESP_DO_IDENTIFY 0
#define TRACE_ESP_DO_IDENTIFY_ENABLED 0
#define TRACE_ESP_DO_IDENTIFY_BACKEND_DSTATE() (0)
static inline void trace_esp_do_identify(uint8_t byte) {
    (void)byte;
}
#define TRACE_ESP_ERROR_FIFO_OVERRUN 0
#define TRACE_ESP_ERROR_FIFO_OVERRUN_ENABLED 0
#define TRACE_ESP_ERROR_FIFO_OVERRUN_BACKEND_DSTATE() (0)
static inline void trace_esp_error_fifo_overrun(void) {
}
#define TRACE_ESP_ERROR_INVALID_WRITE 0
#define TRACE_ESP_ERROR_INVALID_WRITE_ENABLED 0
#define TRACE_ESP_ERROR_INVALID_WRITE_BACKEND_DSTATE() (0)
static inline void trace_esp_error_invalid_write(uint32_t val, uint32_t addr) {
    (void)val;
    (void)addr;
}
#define TRACE_ESP_ERROR_UNHANDLED_COMMAND 0
#define TRACE_ESP_ERROR_UNHANDLED_COMMAND_ENABLED 0
#define TRACE_ESP_ERROR_UNHANDLED_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_esp_error_unhandled_command(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_GET_CMD 0
#define TRACE_ESP_GET_CMD_ENABLED 0
#define TRACE_ESP_GET_CMD_BACKEND_DSTATE() (0)
static inline void trace_esp_get_cmd(uint32_t dmalen, int target) {
    (void)dmalen;
    (void)target;
}
#define TRACE_ESP_HANDLE_SATN_STOP 0
#define TRACE_ESP_HANDLE_SATN_STOP_ENABLED 0
#define TRACE_ESP_HANDLE_SATN_STOP_BACKEND_DSTATE() (0)
static inline void trace_esp_handle_satn_stop(uint32_t cmdlen) {
    (void)cmdlen;
}
#define TRACE_ESP_HANDLE_TI 0
#define TRACE_ESP_HANDLE_TI_ENABLED 0
#define TRACE_ESP_HANDLE_TI_BACKEND_DSTATE() (0)
static inline void trace_esp_handle_ti(uint32_t minlen) {
    (void)minlen;
}
#define TRACE_ESP_HANDLE_TI_CMD 0
#define TRACE_ESP_HANDLE_TI_CMD_ENABLED 0
#define TRACE_ESP_HANDLE_TI_CMD_BACKEND_DSTATE() (0)
static inline void trace_esp_handle_ti_cmd(uint32_t cmdlen) {
    (void)cmdlen;
}
#define TRACE_ESP_INVALID_CMD 0
#define TRACE_ESP_INVALID_CMD_ENABLED 0
#define TRACE_ESP_INVALID_CMD_BACKEND_DSTATE() (0)
static inline void trace_esp_invalid_cmd(uint8_t cmd, uint8_t asc_mode) {
    (void)cmd;
    (void)asc_mode;
}
#define TRACE_ESP_LOWER_DRQ 0
#define TRACE_ESP_LOWER_DRQ_ENABLED 0
#define TRACE_ESP_LOWER_DRQ_BACKEND_DSTATE() (0)
static inline void trace_esp_lower_drq(void) {
}
#define TRACE_ESP_LOWER_IRQ 0
#define TRACE_ESP_LOWER_IRQ_ENABLED 0
#define TRACE_ESP_LOWER_IRQ_BACKEND_DSTATE() (0)
static inline void trace_esp_lower_irq(void) {
}
#define TRACE_ESP_MEM_READB 0
#define TRACE_ESP_MEM_READB_ENABLED 0
#define TRACE_ESP_MEM_READB_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_readb(uint32_t saddr, uint8_t reg) {
    (void)saddr;
    (void)reg;
}
#define TRACE_ESP_MEM_WRITEB 0
#define TRACE_ESP_MEM_WRITEB_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb(uint32_t saddr, uint8_t reg, uint32_t val) {
    (void)saddr;
    (void)reg;
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_BUS_RESET 0
#define TRACE_ESP_MEM_WRITEB_CMD_BUS_RESET_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_BUS_RESET_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_bus_reset(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_DISSEL 0
#define TRACE_ESP_MEM_WRITEB_CMD_DISSEL_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_DISSEL_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_dissel(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_ENSEL 0
#define TRACE_ESP_MEM_WRITEB_CMD_ENSEL_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_ENSEL_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_ensel(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_FLUSH 0
#define TRACE_ESP_MEM_WRITEB_CMD_FLUSH_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_flush(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_ICCS 0
#define TRACE_ESP_MEM_WRITEB_CMD_ICCS_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_ICCS_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_iccs(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_MSGACC 0
#define TRACE_ESP_MEM_WRITEB_CMD_MSGACC_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_MSGACC_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_msgacc(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_NOP 0
#define TRACE_ESP_MEM_WRITEB_CMD_NOP_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_NOP_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_nop(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_PAD 0
#define TRACE_ESP_MEM_WRITEB_CMD_PAD_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_PAD_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_pad(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_RESET 0
#define TRACE_ESP_MEM_WRITEB_CMD_RESET_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_RESET_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_reset(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_RSTATN 0
#define TRACE_ESP_MEM_WRITEB_CMD_RSTATN_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_RSTATN_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_rstatn(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_SATN 0
#define TRACE_ESP_MEM_WRITEB_CMD_SATN_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_SATN_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_satn(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_SEL 0
#define TRACE_ESP_MEM_WRITEB_CMD_SEL_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_SEL_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_sel(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_SELATN 0
#define TRACE_ESP_MEM_WRITEB_CMD_SELATN_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_SELATN_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_selatn(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_SELATNS 0
#define TRACE_ESP_MEM_WRITEB_CMD_SELATNS_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_SELATNS_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_selatns(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_MEM_WRITEB_CMD_TI 0
#define TRACE_ESP_MEM_WRITEB_CMD_TI_ENABLED 0
#define TRACE_ESP_MEM_WRITEB_CMD_TI_BACKEND_DSTATE() (0)
static inline void trace_esp_mem_writeb_cmd_ti(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_PCI_DMA_ABORT 0
#define TRACE_ESP_PCI_DMA_ABORT_ENABLED 0
#define TRACE_ESP_PCI_DMA_ABORT_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_dma_abort(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_PCI_DMA_BLAST 0
#define TRACE_ESP_PCI_DMA_BLAST_ENABLED 0
#define TRACE_ESP_PCI_DMA_BLAST_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_dma_blast(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_PCI_DMA_IDLE 0
#define TRACE_ESP_PCI_DMA_IDLE_ENABLED 0
#define TRACE_ESP_PCI_DMA_IDLE_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_dma_idle(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_PCI_DMA_READ 0
#define TRACE_ESP_PCI_DMA_READ_ENABLED 0
#define TRACE_ESP_PCI_DMA_READ_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_dma_read(uint32_t saddr, uint32_t reg) {
    (void)saddr;
    (void)reg;
}
#define TRACE_ESP_PCI_DMA_START 0
#define TRACE_ESP_PCI_DMA_START_ENABLED 0
#define TRACE_ESP_PCI_DMA_START_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_dma_start(uint32_t val) {
    (void)val;
}
#define TRACE_ESP_PCI_DMA_WRITE 0
#define TRACE_ESP_PCI_DMA_WRITE_ENABLED 0
#define TRACE_ESP_PCI_DMA_WRITE_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_dma_write(uint32_t saddr, uint32_t reg, uint32_t val) {
    (void)saddr;
    (void)reg;
    (void)val;
}
#define TRACE_ESP_PCI_ERROR_INVALID_DMA_DIRECTION 0
#define TRACE_ESP_PCI_ERROR_INVALID_DMA_DIRECTION_ENABLED 0
#define TRACE_ESP_PCI_ERROR_INVALID_DMA_DIRECTION_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_error_invalid_dma_direction(void) {
}
#define TRACE_ESP_PCI_ERROR_INVALID_READ 0
#define TRACE_ESP_PCI_ERROR_INVALID_READ_ENABLED 0
#define TRACE_ESP_PCI_ERROR_INVALID_READ_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_error_invalid_read(uint32_t reg) {
    (void)reg;
}
#define TRACE_ESP_PCI_ERROR_INVALID_WRITE 0
#define TRACE_ESP_PCI_ERROR_INVALID_WRITE_ENABLED 0
#define TRACE_ESP_PCI_ERROR_INVALID_WRITE_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_error_invalid_write(uint32_t reg) {
    (void)reg;
}
#define TRACE_ESP_PCI_ERROR_INVALID_WRITE_DMA 0
#define TRACE_ESP_PCI_ERROR_INVALID_WRITE_DMA_ENABLED 0
#define TRACE_ESP_PCI_ERROR_INVALID_WRITE_DMA_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_error_invalid_write_dma(uint32_t val, uint32_t addr) {
    (void)val;
    (void)addr;
}
#define TRACE_ESP_PCI_SBAC_READ 0
#define TRACE_ESP_PCI_SBAC_READ_ENABLED 0
#define TRACE_ESP_PCI_SBAC_READ_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_sbac_read(uint32_t reg) {
    (void)reg;
}
#define TRACE_ESP_PCI_SBAC_WRITE 0
#define TRACE_ESP_PCI_SBAC_WRITE_ENABLED 0
#define TRACE_ESP_PCI_SBAC_WRITE_BACKEND_DSTATE() (0)
static inline void trace_esp_pci_sbac_write(uint32_t reg, uint32_t val) {
    (void)reg;
    (void)val;
}
#define TRACE_ESP_PDMA_READ 0
#define TRACE_ESP_PDMA_READ_ENABLED 0
#define TRACE_ESP_PDMA_READ_BACKEND_DSTATE() (0)
static inline void trace_esp_pdma_read(int size) {
    (void)size;
}
#define TRACE_ESP_PDMA_WRITE 0
#define TRACE_ESP_PDMA_WRITE_ENABLED 0
#define TRACE_ESP_PDMA_WRITE_BACKEND_DSTATE() (0)
static inline void trace_esp_pdma_write(int size) {
    (void)size;
}
#define TRACE_ESP_RAISE_DRQ 0
#define TRACE_ESP_RAISE_DRQ_ENABLED 0
#define TRACE_ESP_RAISE_DRQ_BACKEND_DSTATE() (0)
static inline void trace_esp_raise_drq(void) {
}
#define TRACE_ESP_RAISE_IRQ 0
#define TRACE_ESP_RAISE_IRQ_ENABLED 0
#define TRACE_ESP_RAISE_IRQ_BACKEND_DSTATE() (0)
static inline void trace_esp_raise_irq(void) {
}
#define TRACE_ESP_SET_PHASE 0
#define TRACE_ESP_SET_PHASE_ENABLED 0
#define TRACE_ESP_SET_PHASE_BACKEND_DSTATE() (0)
static inline void trace_esp_set_phase(const char *phase) {
    (void)phase;
}
#define TRACE_ESP_TRANSFER_DATA 0
#define TRACE_ESP_TRANSFER_DATA_ENABLED 0
#define TRACE_ESP_TRANSFER_DATA_BACKEND_DSTATE() (0)
static inline void trace_esp_transfer_data(uint32_t dma_left, int32_t ti_size) {
    (void)dma_left;
    (void)ti_size;
}
#define TRACE_ESP_WRITE_RESPONSE 0
#define TRACE_ESP_WRITE_RESPONSE_ENABLED 0
#define TRACE_ESP_WRITE_RESPONSE_BACKEND_DSTATE() (0)
static inline void trace_esp_write_response(uint32_t status) {
    (void)status;
}
#define TRACE_LASI_NCR710_COMMAND_COMPLETE 0
#define TRACE_LASI_NCR710_COMMAND_COMPLETE_ENABLED 0
#define TRACE_LASI_NCR710_COMMAND_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_command_complete(uint32_t status, size_t resid) {
    (void)status;
    (void)resid;
}
#define TRACE_LASI_NCR710_DEVICE_REALIZE 0
#define TRACE_LASI_NCR710_DEVICE_REALIZE_ENABLED 0
#define TRACE_LASI_NCR710_DEVICE_REALIZE_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_device_realize(void) {
}
#define TRACE_LASI_NCR710_DEVICE_RESET 0
#define TRACE_LASI_NCR710_DEVICE_RESET_ENABLED 0
#define TRACE_LASI_NCR710_DEVICE_RESET_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_device_reset(void) {
}
#define TRACE_LASI_NCR710_HANDLE_LEGACY_CMDLINE 0
#define TRACE_LASI_NCR710_HANDLE_LEGACY_CMDLINE_ENABLED 0
#define TRACE_LASI_NCR710_HANDLE_LEGACY_CMDLINE_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_handle_legacy_cmdline(int busnr, int found_drives) {
    (void)busnr;
    (void)found_drives;
}
#define TRACE_LASI_NCR710_LEGACY_DRIVE_FOUND 0
#define TRACE_LASI_NCR710_LEGACY_DRIVE_FOUND_ENABLED 0
#define TRACE_LASI_NCR710_LEGACY_DRIVE_FOUND_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_legacy_drive_found(int busnr, int unit) {
    (void)busnr;
    (void)unit;
}
#define TRACE_LASI_NCR710_REG_FORWARD_READ 0
#define TRACE_LASI_NCR710_REG_FORWARD_READ_ENABLED 0
#define TRACE_LASI_NCR710_REG_FORWARD_READ_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_reg_forward_read(uint32_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_LASI_NCR710_REG_FORWARD_WRITE 0
#define TRACE_LASI_NCR710_REG_FORWARD_WRITE_ENABLED 0
#define TRACE_LASI_NCR710_REG_FORWARD_WRITE_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_reg_forward_write(uint32_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_LASI_NCR710_REG_READ 0
#define TRACE_LASI_NCR710_REG_READ_ENABLED 0
#define TRACE_LASI_NCR710_REG_READ_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_reg_read(uint32_t addr, uint32_t val, unsigned size) {
    (void)addr;
    (void)val;
    (void)size;
}
#define TRACE_LASI_NCR710_REG_READ_HVERSION 0
#define TRACE_LASI_NCR710_REG_READ_HVERSION_ENABLED 0
#define TRACE_LASI_NCR710_REG_READ_HVERSION_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_reg_read_hversion(uint32_t hversion) {
    (void)hversion;
}
#define TRACE_LASI_NCR710_REG_READ_ID 0
#define TRACE_LASI_NCR710_REG_READ_ID_ENABLED 0
#define TRACE_LASI_NCR710_REG_READ_ID_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_reg_read_id(uint32_t hw_type, uint32_t sversion, uint32_t val) {
    (void)hw_type;
    (void)sversion;
    (void)val;
}
#define TRACE_LASI_NCR710_REG_WRITE 0
#define TRACE_LASI_NCR710_REG_WRITE_ENABLED 0
#define TRACE_LASI_NCR710_REG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_reg_write(uint32_t addr, uint32_t val, unsigned size) {
    (void)addr;
    (void)val;
    (void)size;
}
#define TRACE_LASI_NCR710_REQUEST_CANCELLED 0
#define TRACE_LASI_NCR710_REQUEST_CANCELLED_ENABLED 0
#define TRACE_LASI_NCR710_REQUEST_CANCELLED_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_request_cancelled(void *req) {
    (void)req;
}
#define TRACE_LASI_NCR710_SCSI_DEVICE_CREATED 0
#define TRACE_LASI_NCR710_SCSI_DEVICE_CREATED_ENABLED 0
#define TRACE_LASI_NCR710_SCSI_DEVICE_CREATED_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_scsi_device_created(const char *type) {
    (void)type;
}
#define TRACE_LASI_NCR710_TIMERS_INITIALIZED 0
#define TRACE_LASI_NCR710_TIMERS_INITIALIZED_ENABLED 0
#define TRACE_LASI_NCR710_TIMERS_INITIALIZED_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_timers_initialized(uint64_t reselection) {
    (void)reselection;
}
#define TRACE_LASI_NCR710_TRANSFER_DATA 0
#define TRACE_LASI_NCR710_TRANSFER_DATA_ENABLED 0
#define TRACE_LASI_NCR710_TRANSFER_DATA_BACKEND_DSTATE() (0)
static inline void trace_lasi_ncr710_transfer_data(uint32_t len) {
    (void)len;
}
#define TRACE_LSI_ADD_MSG_BYTE 0
#define TRACE_LSI_ADD_MSG_BYTE_ENABLED 0
#define TRACE_LSI_ADD_MSG_BYTE_BACKEND_DSTATE() (0)
static inline void trace_lsi_add_msg_byte(uint8_t data) {
    (void)data;
}
#define TRACE_LSI_ADD_MSG_BYTE_ERROR 0
#define TRACE_LSI_ADD_MSG_BYTE_ERROR_ENABLED 0
#define TRACE_LSI_ADD_MSG_BYTE_ERROR_BACKEND_DSTATE() (0)
static inline void trace_lsi_add_msg_byte_error(void) {
}
#define TRACE_LSI_AWOKEN 0
#define TRACE_LSI_AWOKEN_ENABLED 0
#define TRACE_LSI_AWOKEN_BACKEND_DSTATE() (0)
static inline void trace_lsi_awoken(void) {
}
#define TRACE_LSI_BAD_PHASE_INTERRUPT 0
#define TRACE_LSI_BAD_PHASE_INTERRUPT_ENABLED 0
#define TRACE_LSI_BAD_PHASE_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_lsi_bad_phase_interrupt(void) {
}
#define TRACE_LSI_BAD_PHASE_JUMP 0
#define TRACE_LSI_BAD_PHASE_JUMP_ENABLED 0
#define TRACE_LSI_BAD_PHASE_JUMP_BACKEND_DSTATE() (0)
static inline void trace_lsi_bad_phase_jump(uint32_t dsp) {
    (void)dsp;
}
#define TRACE_LSI_BAD_SELECTION 0
#define TRACE_LSI_BAD_SELECTION_ENABLED 0
#define TRACE_LSI_BAD_SELECTION_BACKEND_DSTATE() (0)
static inline void trace_lsi_bad_selection(uint32_t id) {
    (void)id;
}
#define TRACE_LSI_COMMAND_COMPLETE 0
#define TRACE_LSI_COMMAND_COMPLETE_ENABLED 0
#define TRACE_LSI_COMMAND_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_lsi_command_complete(uint32_t status) {
    (void)status;
}
#define TRACE_LSI_DO_COMMAND 0
#define TRACE_LSI_DO_COMMAND_ENABLED 0
#define TRACE_LSI_DO_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_command(uint32_t dbc) {
    (void)dbc;
}
#define TRACE_LSI_DO_DMA 0
#define TRACE_LSI_DO_DMA_ENABLED 0
#define TRACE_LSI_DO_DMA_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_dma(uint64_t addr, int len) {
    (void)addr;
    (void)len;
}
#define TRACE_LSI_DO_DMA_UNAVAILABLE 0
#define TRACE_LSI_DO_DMA_UNAVAILABLE_ENABLED 0
#define TRACE_LSI_DO_DMA_UNAVAILABLE_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_dma_unavailable(void) {
}
#define TRACE_LSI_DO_MSGIN 0
#define TRACE_LSI_DO_MSGIN_ENABLED 0
#define TRACE_LSI_DO_MSGIN_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgin(uint32_t dbc, int len) {
    (void)dbc;
    (void)len;
}
#define TRACE_LSI_DO_MSGOUT 0
#define TRACE_LSI_DO_MSGOUT_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout(uint32_t dbc) {
    (void)dbc;
}
#define TRACE_LSI_DO_MSGOUT_ABORT 0
#define TRACE_LSI_DO_MSGOUT_ABORT_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_ABORT_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_abort(uint32_t tag) {
    (void)tag;
}
#define TRACE_LSI_DO_MSGOUT_BUSDEVICERESET 0
#define TRACE_LSI_DO_MSGOUT_BUSDEVICERESET_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_BUSDEVICERESET_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_busdevicereset(uint32_t tag) {
    (void)tag;
}
#define TRACE_LSI_DO_MSGOUT_CLEARQUEUE 0
#define TRACE_LSI_DO_MSGOUT_CLEARQUEUE_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_CLEARQUEUE_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_clearqueue(uint32_t tag) {
    (void)tag;
}
#define TRACE_LSI_DO_MSGOUT_DISCONNECT 0
#define TRACE_LSI_DO_MSGOUT_DISCONNECT_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_DISCONNECT_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_disconnect(void) {
}
#define TRACE_LSI_DO_MSGOUT_EXTENDED 0
#define TRACE_LSI_DO_MSGOUT_EXTENDED_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_EXTENDED_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_extended(uint8_t msg, uint8_t len) {
    (void)msg;
    (void)len;
}
#define TRACE_LSI_DO_MSGOUT_IGNORED 0
#define TRACE_LSI_DO_MSGOUT_IGNORED_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_IGNORED_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_ignored(const char *msg) {
    (void)msg;
}
#define TRACE_LSI_DO_MSGOUT_NOOP 0
#define TRACE_LSI_DO_MSGOUT_NOOP_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_NOOP_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_noop(void) {
}
#define TRACE_LSI_DO_MSGOUT_SELECT 0
#define TRACE_LSI_DO_MSGOUT_SELECT_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_SELECT_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_select(int id) {
    (void)id;
}
#define TRACE_LSI_DO_MSGOUT_SIMPLEQUEUE 0
#define TRACE_LSI_DO_MSGOUT_SIMPLEQUEUE_ENABLED 0
#define TRACE_LSI_DO_MSGOUT_SIMPLEQUEUE_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_msgout_simplequeue(uint8_t select_tag) {
    (void)select_tag;
}
#define TRACE_LSI_DO_STATUS 0
#define TRACE_LSI_DO_STATUS_ENABLED 0
#define TRACE_LSI_DO_STATUS_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_status(uint32_t dbc, uint8_t status) {
    (void)dbc;
    (void)status;
}
#define TRACE_LSI_DO_STATUS_ERROR 0
#define TRACE_LSI_DO_STATUS_ERROR_ENABLED 0
#define TRACE_LSI_DO_STATUS_ERROR_BACKEND_DSTATE() (0)
static inline void trace_lsi_do_status_error(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT 0
#define TRACE_LSI_EXECUTE_SCRIPT_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script(uint32_t dsp, uint32_t insn, uint32_t addr) {
    (void)dsp;
    (void)insn;
    (void)addr;
}
#define TRACE_LSI_EXECUTE_SCRIPT_BLOCKMOVE_BADPHASE 0
#define TRACE_LSI_EXECUTE_SCRIPT_BLOCKMOVE_BADPHASE_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_BLOCKMOVE_BADPHASE_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_blockmove_badphase(const char *phase, const char *expected) {
    (void)phase;
    (void)expected;
}
#define TRACE_LSI_EXECUTE_SCRIPT_BLOCKMOVE_DELAYED 0
#define TRACE_LSI_EXECUTE_SCRIPT_BLOCKMOVE_DELAYED_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_BLOCKMOVE_DELAYED_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_blockmove_delayed(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT_IO_ALREADYRESELECTED 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_ALREADYRESELECTED_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_ALREADYRESELECTED_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_io_alreadyreselected(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT_IO_CLEAR 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_CLEAR_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_CLEAR_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_io_clear(const char *atn, const char *ack, const char *tm, const char *cc) {
    (void)atn;
    (void)ack;
    (void)tm;
    (void)cc;
}
#define TRACE_LSI_EXECUTE_SCRIPT_IO_DISCONNECT 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_DISCONNECT_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_DISCONNECT_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_io_disconnect(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT_IO_OPCODE 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_OPCODE_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_OPCODE_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_io_opcode(const char *opcode, int reg, const char *opname, uint8_t data8, uint32_t sfbr, const char *ssfbr) {
    (void)opcode;
    (void)reg;
    (void)opname;
    (void)data8;
    (void)sfbr;
    (void)ssfbr;
}
#define TRACE_LSI_EXECUTE_SCRIPT_IO_SELECTED 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_SELECTED_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_SELECTED_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_io_selected(uint8_t id, const char *atn) {
    (void)id;
    (void)atn;
}
#define TRACE_LSI_EXECUTE_SCRIPT_IO_SET 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_SET_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_IO_SET_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_io_set(const char *atn, const char *ack, const char *tm, const char *cc) {
    (void)atn;
    (void)ack;
    (void)tm;
    (void)cc;
}
#define TRACE_LSI_EXECUTE_SCRIPT_MM_LOAD 0
#define TRACE_LSI_EXECUTE_SCRIPT_MM_LOAD_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_MM_LOAD_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_mm_load(int reg, int n, uint32_t addr, int data) {
    (void)reg;
    (void)n;
    (void)addr;
    (void)data;
}
#define TRACE_LSI_EXECUTE_SCRIPT_MM_STORE 0
#define TRACE_LSI_EXECUTE_SCRIPT_MM_STORE_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_MM_STORE_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_mm_store(int reg, int n, uint32_t addr) {
    (void)reg;
    (void)n;
    (void)addr;
}
#define TRACE_LSI_EXECUTE_SCRIPT_STOP 0
#define TRACE_LSI_EXECUTE_SCRIPT_STOP_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_STOP_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_stop(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_CALL 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_CALL_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_CALL_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_call(uint32_t addr) {
    (void)addr;
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_CC_FAILED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_CC_FAILED_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_CC_FAILED_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_cc_failed(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPC 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPC_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPC_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_compc(int result) {
    (void)result;
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPD 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPD_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPD_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_compd(uint32_t sfbr, uint8_t mask, char op, int result) {
    (void)sfbr;
    (void)mask;
    (void)op;
    (void)result;
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPP 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPP_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_COMPP_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_compp(const char *phase, char op, const char *insn_phase) {
    (void)phase;
    (void)op;
    (void)insn_phase;
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_DELAYEDSELECT_TIMEOUT 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_DELAYEDSELECT_TIMEOUT_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_DELAYEDSELECT_TIMEOUT_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_delayedselect_timeout(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_ILLEGAL 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_ILLEGAL_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_ILLEGAL_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_illegal(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_INTERRUPT 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_INTERRUPT_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_interrupt(uint32_t addr) {
    (void)addr;
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_JUMP 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_JUMP_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_JUMP_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_jump(uint32_t addr) {
    (void)addr;
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_NOP 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_NOP_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_NOP_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_nop(void) {
}
#define TRACE_LSI_EXECUTE_SCRIPT_TC_RETURN 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_RETURN_ENABLED 0
#define TRACE_LSI_EXECUTE_SCRIPT_TC_RETURN_BACKEND_DSTATE() (0)
static inline void trace_lsi_execute_script_tc_return(uint32_t addr) {
    (void)addr;
}
#define TRACE_LSI_MEMCPY 0
#define TRACE_LSI_MEMCPY_ENABLED 0
#define TRACE_LSI_MEMCPY_BACKEND_DSTATE() (0)
static inline void trace_lsi_memcpy(uint32_t dest, uint32_t src, int count) {
    (void)dest;
    (void)src;
    (void)count;
}
#define TRACE_LSI_QUEUE_COMMAND 0
#define TRACE_LSI_QUEUE_COMMAND_ENABLED 0
#define TRACE_LSI_QUEUE_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_lsi_queue_command(uint32_t tag) {
    (void)tag;
}
#define TRACE_LSI_QUEUE_REQ 0
#define TRACE_LSI_QUEUE_REQ_ENABLED 0
#define TRACE_LSI_QUEUE_REQ_BACKEND_DSTATE() (0)
static inline void trace_lsi_queue_req(uint32_t tag) {
    (void)tag;
}
#define TRACE_LSI_QUEUE_REQ_ERROR 0
#define TRACE_LSI_QUEUE_REQ_ERROR_ENABLED 0
#define TRACE_LSI_QUEUE_REQ_ERROR_BACKEND_DSTATE() (0)
static inline void trace_lsi_queue_req_error(void *p) {
    (void)p;
}
#define TRACE_LSI_REG_READ 0
#define TRACE_LSI_REG_READ_ENABLED 0
#define TRACE_LSI_REG_READ_BACKEND_DSTATE() (0)
static inline void trace_lsi_reg_read(const char *name, int offset, uint8_t ret) {
    (void)name;
    (void)offset;
    (void)ret;
}
#define TRACE_LSI_REG_WRITE 0
#define TRACE_LSI_REG_WRITE_ENABLED 0
#define TRACE_LSI_REG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_lsi_reg_write(const char *name, int offset, uint8_t val) {
    (void)name;
    (void)offset;
    (void)val;
}
#define TRACE_LSI_RESELECT 0
#define TRACE_LSI_RESELECT_ENABLED 0
#define TRACE_LSI_RESELECT_BACKEND_DSTATE() (0)
static inline void trace_lsi_reselect(int id) {
    (void)id;
}
#define TRACE_LSI_RESET 0
#define TRACE_LSI_RESET_ENABLED 0
#define TRACE_LSI_RESET_BACKEND_DSTATE() (0)
static inline void trace_lsi_reset(void) {
}
#define TRACE_LSI_SCRIPT_DMA_INTERRUPT 0
#define TRACE_LSI_SCRIPT_DMA_INTERRUPT_ENABLED 0
#define TRACE_LSI_SCRIPT_DMA_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_lsi_script_dma_interrupt(uint8_t stat, uint8_t dstat) {
    (void)stat;
    (void)dstat;
}
#define TRACE_LSI_SCRIPT_SCSI_INTERRUPT 0
#define TRACE_LSI_SCRIPT_SCSI_INTERRUPT_ENABLED 0
#define TRACE_LSI_SCRIPT_SCSI_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_lsi_script_scsi_interrupt(uint8_t stat1, uint8_t stat0, uint8_t sist1, uint8_t sist0) {
    (void)stat1;
    (void)stat0;
    (void)sist1;
    (void)sist0;
}
#define TRACE_LSI_SCRIPTS_TIMER_START 0
#define TRACE_LSI_SCRIPTS_TIMER_START_ENABLED 0
#define TRACE_LSI_SCRIPTS_TIMER_START_BACKEND_DSTATE() (0)
static inline void trace_lsi_scripts_timer_start(void) {
}
#define TRACE_LSI_SCRIPTS_TIMER_TRIGGERED 0
#define TRACE_LSI_SCRIPTS_TIMER_TRIGGERED_ENABLED 0
#define TRACE_LSI_SCRIPTS_TIMER_TRIGGERED_BACKEND_DSTATE() (0)
static inline void trace_lsi_scripts_timer_triggered(void) {
}
#define TRACE_LSI_TRANSFER_DATA 0
#define TRACE_LSI_TRANSFER_DATA_ENABLED 0
#define TRACE_LSI_TRANSFER_DATA_BACKEND_DSTATE() (0)
static inline void trace_lsi_transfer_data(uint32_t tag, uint32_t len) {
    (void)tag;
    (void)len;
}
#define TRACE_LSI_UPDATE_IRQ 0
#define TRACE_LSI_UPDATE_IRQ_ENABLED 0
#define TRACE_LSI_UPDATE_IRQ_BACKEND_DSTATE() (0)
static inline void trace_lsi_update_irq(int level, uint8_t dstat, uint8_t sist1, uint8_t sist0) {
    (void)level;
    (void)dstat;
    (void)sist1;
    (void)sist0;
}
#define TRACE_LSI_UPDATE_IRQ_DISCONNECTED 0
#define TRACE_LSI_UPDATE_IRQ_DISCONNECTED_ENABLED 0
#define TRACE_LSI_UPDATE_IRQ_DISCONNECTED_BACKEND_DSTATE() (0)
static inline void trace_lsi_update_irq_disconnected(void) {
}
#define TRACE_LSI_WAIT_RESELECT 0
#define TRACE_LSI_WAIT_RESELECT_ENABLED 0
#define TRACE_LSI_WAIT_RESELECT_BACKEND_DSTATE() (0)
static inline void trace_lsi_wait_reselect(void) {
}
#define TRACE_MEGASAS_ABORT_FRAME 0
#define TRACE_MEGASAS_ABORT_FRAME_ENABLED 0
#define TRACE_MEGASAS_ABORT_FRAME_BACKEND_DSTATE() (0)
static inline void trace_megasas_abort_frame(int cmd, int abort_cmd) {
    (void)cmd;
    (void)abort_cmd;
}
#define TRACE_MEGASAS_ABORT_INVALID_CONTEXT 0
#define TRACE_MEGASAS_ABORT_INVALID_CONTEXT_ENABLED 0
#define TRACE_MEGASAS_ABORT_INVALID_CONTEXT_BACKEND_DSTATE() (0)
static inline void trace_megasas_abort_invalid_context(int cmd, uint64_t context, int abort_cmd) {
    (void)cmd;
    (void)context;
    (void)abort_cmd;
}
#define TRACE_MEGASAS_ABORT_NO_CMD 0
#define TRACE_MEGASAS_ABORT_NO_CMD_ENABLED 0
#define TRACE_MEGASAS_ABORT_NO_CMD_BACKEND_DSTATE() (0)
static inline void trace_megasas_abort_no_cmd(int cmd, uint64_t context) {
    (void)cmd;
    (void)context;
}
#define TRACE_MEGASAS_COMMAND_COMPLETE 0
#define TRACE_MEGASAS_COMMAND_COMPLETE_ENABLED 0
#define TRACE_MEGASAS_COMMAND_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_megasas_command_complete(int cmd, uint32_t status, uint32_t resid) {
    (void)cmd;
    (void)status;
    (void)resid;
}
#define TRACE_MEGASAS_DCMD_DUMMY 0
#define TRACE_MEGASAS_DCMD_DUMMY_ENABLED 0
#define TRACE_MEGASAS_DCMD_DUMMY_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_dummy(int cmd, unsigned long size) {
    (void)cmd;
    (void)size;
}
#define TRACE_MEGASAS_DCMD_ENTER 0
#define TRACE_MEGASAS_DCMD_ENTER_ENABLED 0
#define TRACE_MEGASAS_DCMD_ENTER_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_enter(int cmd, const char *dcmd, int len) {
    (void)cmd;
    (void)dcmd;
    (void)len;
}
#define TRACE_MEGASAS_DCMD_INTERNAL_FINISH 0
#define TRACE_MEGASAS_DCMD_INTERNAL_FINISH_ENABLED 0
#define TRACE_MEGASAS_DCMD_INTERNAL_FINISH_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_internal_finish(int cmd, int opcode, int lun) {
    (void)cmd;
    (void)opcode;
    (void)lun;
}
#define TRACE_MEGASAS_DCMD_INTERNAL_INVALID 0
#define TRACE_MEGASAS_DCMD_INTERNAL_INVALID_ENABLED 0
#define TRACE_MEGASAS_DCMD_INTERNAL_INVALID_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_internal_invalid(int cmd, int opcode) {
    (void)cmd;
    (void)opcode;
}
#define TRACE_MEGASAS_DCMD_INTERNAL_SUBMIT 0
#define TRACE_MEGASAS_DCMD_INTERNAL_SUBMIT_ENABLED 0
#define TRACE_MEGASAS_DCMD_INTERNAL_SUBMIT_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_internal_submit(int cmd, const char *desc, int dev) {
    (void)cmd;
    (void)desc;
    (void)dev;
}
#define TRACE_MEGASAS_DCMD_INVALID_SGE 0
#define TRACE_MEGASAS_DCMD_INVALID_SGE_ENABLED 0
#define TRACE_MEGASAS_DCMD_INVALID_SGE_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_invalid_sge(int cmd, int count) {
    (void)cmd;
    (void)count;
}
#define TRACE_MEGASAS_DCMD_INVALID_XFER_LEN 0
#define TRACE_MEGASAS_DCMD_INVALID_XFER_LEN_ENABLED 0
#define TRACE_MEGASAS_DCMD_INVALID_XFER_LEN_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_invalid_xfer_len(int cmd, unsigned long size, unsigned long max) {
    (void)cmd;
    (void)size;
    (void)max;
}
#define TRACE_MEGASAS_DCMD_LD_GET_INFO 0
#define TRACE_MEGASAS_DCMD_LD_GET_INFO_ENABLED 0
#define TRACE_MEGASAS_DCMD_LD_GET_INFO_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_ld_get_info(int cmd, int ld_id) {
    (void)cmd;
    (void)ld_id;
}
#define TRACE_MEGASAS_DCMD_LD_GET_LIST 0
#define TRACE_MEGASAS_DCMD_LD_GET_LIST_ENABLED 0
#define TRACE_MEGASAS_DCMD_LD_GET_LIST_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_ld_get_list(int cmd, int num, int max) {
    (void)cmd;
    (void)num;
    (void)max;
}
#define TRACE_MEGASAS_DCMD_LD_LIST_QUERY 0
#define TRACE_MEGASAS_DCMD_LD_LIST_QUERY_ENABLED 0
#define TRACE_MEGASAS_DCMD_LD_LIST_QUERY_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_ld_list_query(int cmd, int flags) {
    (void)cmd;
    (void)flags;
}
#define TRACE_MEGASAS_DCMD_PD_GET_INFO 0
#define TRACE_MEGASAS_DCMD_PD_GET_INFO_ENABLED 0
#define TRACE_MEGASAS_DCMD_PD_GET_INFO_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_pd_get_info(int cmd, int pd_id) {
    (void)cmd;
    (void)pd_id;
}
#define TRACE_MEGASAS_DCMD_PD_GET_LIST 0
#define TRACE_MEGASAS_DCMD_PD_GET_LIST_ENABLED 0
#define TRACE_MEGASAS_DCMD_PD_GET_LIST_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_pd_get_list(int cmd, int num, int max, int offset) {
    (void)cmd;
    (void)num;
    (void)max;
    (void)offset;
}
#define TRACE_MEGASAS_DCMD_PD_LIST_QUERY 0
#define TRACE_MEGASAS_DCMD_PD_LIST_QUERY_ENABLED 0
#define TRACE_MEGASAS_DCMD_PD_LIST_QUERY_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_pd_list_query(int cmd, int flags) {
    (void)cmd;
    (void)flags;
}
#define TRACE_MEGASAS_DCMD_REQ_ALLOC_FAILED 0
#define TRACE_MEGASAS_DCMD_REQ_ALLOC_FAILED_ENABLED 0
#define TRACE_MEGASAS_DCMD_REQ_ALLOC_FAILED_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_req_alloc_failed(int cmd, const char *desc) {
    (void)cmd;
    (void)desc;
}
#define TRACE_MEGASAS_DCMD_RESET_LD 0
#define TRACE_MEGASAS_DCMD_RESET_LD_ENABLED 0
#define TRACE_MEGASAS_DCMD_RESET_LD_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_reset_ld(int cmd, int target_id) {
    (void)cmd;
    (void)target_id;
}
#define TRACE_MEGASAS_DCMD_SET_FW_TIME 0
#define TRACE_MEGASAS_DCMD_SET_FW_TIME_ENABLED 0
#define TRACE_MEGASAS_DCMD_SET_FW_TIME_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_set_fw_time(int cmd, unsigned long time) {
    (void)cmd;
    (void)time;
}
#define TRACE_MEGASAS_DCMD_UNHANDLED 0
#define TRACE_MEGASAS_DCMD_UNHANDLED_ENABLED 0
#define TRACE_MEGASAS_DCMD_UNHANDLED_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_unhandled(int cmd, int opcode, int len) {
    (void)cmd;
    (void)opcode;
    (void)len;
}
#define TRACE_MEGASAS_DCMD_UNSUPPORTED 0
#define TRACE_MEGASAS_DCMD_UNSUPPORTED_ENABLED 0
#define TRACE_MEGASAS_DCMD_UNSUPPORTED_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_unsupported(int cmd, unsigned long size) {
    (void)cmd;
    (void)size;
}
#define TRACE_MEGASAS_DCMD_ZERO_SGE 0
#define TRACE_MEGASAS_DCMD_ZERO_SGE_ENABLED 0
#define TRACE_MEGASAS_DCMD_ZERO_SGE_BACKEND_DSTATE() (0)
static inline void trace_megasas_dcmd_zero_sge(int cmd) {
    (void)cmd;
}
#define TRACE_MEGASAS_FINISH_DCMD 0
#define TRACE_MEGASAS_FINISH_DCMD_ENABLED 0
#define TRACE_MEGASAS_FINISH_DCMD_BACKEND_DSTATE() (0)
static inline void trace_megasas_finish_dcmd(int cmd, int size) {
    (void)cmd;
    (void)size;
}
#define TRACE_MEGASAS_FRAME_BUSY 0
#define TRACE_MEGASAS_FRAME_BUSY_ENABLED 0
#define TRACE_MEGASAS_FRAME_BUSY_BACKEND_DSTATE() (0)
static inline void trace_megasas_frame_busy(uint64_t addr) {
    (void)addr;
}
#define TRACE_MEGASAS_HANDLE_DCMD 0
#define TRACE_MEGASAS_HANDLE_DCMD_ENABLED 0
#define TRACE_MEGASAS_HANDLE_DCMD_BACKEND_DSTATE() (0)
static inline void trace_megasas_handle_dcmd(int cmd, int opcode) {
    (void)cmd;
    (void)opcode;
}
#define TRACE_MEGASAS_HANDLE_IO 0
#define TRACE_MEGASAS_HANDLE_IO_ENABLED 0
#define TRACE_MEGASAS_HANDLE_IO_BACKEND_DSTATE() (0)
static inline void trace_megasas_handle_io(int cmd, const char *frame, int dev, int lun, unsigned long lba, unsigned long count) {
    (void)cmd;
    (void)frame;
    (void)dev;
    (void)lun;
    (void)lba;
    (void)count;
}
#define TRACE_MEGASAS_HANDLE_SCSI 0
#define TRACE_MEGASAS_HANDLE_SCSI_ENABLED 0
#define TRACE_MEGASAS_HANDLE_SCSI_BACKEND_DSTATE() (0)
static inline void trace_megasas_handle_scsi(const char *frame, int bus, int dev, int lun, void *sdev, unsigned long size) {
    (void)frame;
    (void)bus;
    (void)dev;
    (void)lun;
    (void)sdev;
    (void)size;
}
#define TRACE_MEGASAS_INIT 0
#define TRACE_MEGASAS_INIT_ENABLED 0
#define TRACE_MEGASAS_INIT_BACKEND_DSTATE() (0)
static inline void trace_megasas_init(int sges, int cmds, const char *mode) {
    (void)sges;
    (void)cmds;
    (void)mode;
}
#define TRACE_MEGASAS_INIT_FIRMWARE 0
#define TRACE_MEGASAS_INIT_FIRMWARE_ENABLED 0
#define TRACE_MEGASAS_INIT_FIRMWARE_BACKEND_DSTATE() (0)
static inline void trace_megasas_init_firmware(uint64_t pa) {
    (void)pa;
}
#define TRACE_MEGASAS_INIT_QUEUE 0
#define TRACE_MEGASAS_INIT_QUEUE_ENABLED 0
#define TRACE_MEGASAS_INIT_QUEUE_BACKEND_DSTATE() (0)
static inline void trace_megasas_init_queue(uint64_t queue_pa, int queue_len, uint32_t head, uint32_t tail, uint32_t flags) {
    (void)queue_pa;
    (void)queue_len;
    (void)head;
    (void)tail;
    (void)flags;
}
#define TRACE_MEGASAS_INITQ_MAP_FAILED 0
#define TRACE_MEGASAS_INITQ_MAP_FAILED_ENABLED 0
#define TRACE_MEGASAS_INITQ_MAP_FAILED_BACKEND_DSTATE() (0)
static inline void trace_megasas_initq_map_failed(int frame) {
    (void)frame;
}
#define TRACE_MEGASAS_INITQ_MAPPED 0
#define TRACE_MEGASAS_INITQ_MAPPED_ENABLED 0
#define TRACE_MEGASAS_INITQ_MAPPED_BACKEND_DSTATE() (0)
static inline void trace_megasas_initq_mapped(uint64_t pa) {
    (void)pa;
}
#define TRACE_MEGASAS_INITQ_MISMATCH 0
#define TRACE_MEGASAS_INITQ_MISMATCH_ENABLED 0
#define TRACE_MEGASAS_INITQ_MISMATCH_BACKEND_DSTATE() (0)
static inline void trace_megasas_initq_mismatch(int queue_len, int fw_cmds) {
    (void)queue_len;
    (void)fw_cmds;
}
#define TRACE_MEGASAS_INTR_DISABLED 0
#define TRACE_MEGASAS_INTR_DISABLED_ENABLED 0
#define TRACE_MEGASAS_INTR_DISABLED_BACKEND_DSTATE() (0)
static inline void trace_megasas_intr_disabled(void) {
}
#define TRACE_MEGASAS_INTR_ENABLED 0
#define TRACE_MEGASAS_INTR_ENABLED_ENABLED 0
#define TRACE_MEGASAS_INTR_ENABLED_BACKEND_DSTATE() (0)
static inline void trace_megasas_intr_enabled(void) {
}
#define TRACE_MEGASAS_IO_COMPLETE 0
#define TRACE_MEGASAS_IO_COMPLETE_ENABLED 0
#define TRACE_MEGASAS_IO_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_megasas_io_complete(int cmd, uint32_t len) {
    (void)cmd;
    (void)len;
}
#define TRACE_MEGASAS_IO_READ_START 0
#define TRACE_MEGASAS_IO_READ_START_ENABLED 0
#define TRACE_MEGASAS_IO_READ_START_BACKEND_DSTATE() (0)
static inline void trace_megasas_io_read_start(int cmd, unsigned long lba, unsigned long count, unsigned long len) {
    (void)cmd;
    (void)lba;
    (void)count;
    (void)len;
}
#define TRACE_MEGASAS_IO_TARGET_NOT_PRESENT 0
#define TRACE_MEGASAS_IO_TARGET_NOT_PRESENT_ENABLED 0
#define TRACE_MEGASAS_IO_TARGET_NOT_PRESENT_BACKEND_DSTATE() (0)
static inline void trace_megasas_io_target_not_present(int cmd, const char *frame, int dev, int lun) {
    (void)cmd;
    (void)frame;
    (void)dev;
    (void)lun;
}
#define TRACE_MEGASAS_IO_WRITE_START 0
#define TRACE_MEGASAS_IO_WRITE_START_ENABLED 0
#define TRACE_MEGASAS_IO_WRITE_START_BACKEND_DSTATE() (0)
static inline void trace_megasas_io_write_start(int cmd, unsigned long lba, unsigned long count, unsigned long len) {
    (void)cmd;
    (void)lba;
    (void)count;
    (void)len;
}
#define TRACE_MEGASAS_IOV_READ_OVERFLOW 0
#define TRACE_MEGASAS_IOV_READ_OVERFLOW_ENABLED 0
#define TRACE_MEGASAS_IOV_READ_OVERFLOW_BACKEND_DSTATE() (0)
static inline void trace_megasas_iov_read_overflow(int cmd, int bytes, int len) {
    (void)cmd;
    (void)bytes;
    (void)len;
}
#define TRACE_MEGASAS_IOV_READ_UNDERFLOW 0
#define TRACE_MEGASAS_IOV_READ_UNDERFLOW_ENABLED 0
#define TRACE_MEGASAS_IOV_READ_UNDERFLOW_BACKEND_DSTATE() (0)
static inline void trace_megasas_iov_read_underflow(int cmd, int bytes, int len) {
    (void)cmd;
    (void)bytes;
    (void)len;
}
#define TRACE_MEGASAS_IOV_WRITE_OVERFLOW 0
#define TRACE_MEGASAS_IOV_WRITE_OVERFLOW_ENABLED 0
#define TRACE_MEGASAS_IOV_WRITE_OVERFLOW_BACKEND_DSTATE() (0)
static inline void trace_megasas_iov_write_overflow(int cmd, int bytes, int len) {
    (void)cmd;
    (void)bytes;
    (void)len;
}
#define TRACE_MEGASAS_IOV_WRITE_UNDERFLOW 0
#define TRACE_MEGASAS_IOV_WRITE_UNDERFLOW_ENABLED 0
#define TRACE_MEGASAS_IOV_WRITE_UNDERFLOW_BACKEND_DSTATE() (0)
static inline void trace_megasas_iov_write_underflow(int cmd, int bytes, int len) {
    (void)cmd;
    (void)bytes;
    (void)len;
}
#define TRACE_MEGASAS_IOVEC_OVERFLOW 0
#define TRACE_MEGASAS_IOVEC_OVERFLOW_ENABLED 0
#define TRACE_MEGASAS_IOVEC_OVERFLOW_BACKEND_DSTATE() (0)
static inline void trace_megasas_iovec_overflow(int cmd, int len, int limit) {
    (void)cmd;
    (void)len;
    (void)limit;
}
#define TRACE_MEGASAS_IOVEC_SGL_INVALID 0
#define TRACE_MEGASAS_IOVEC_SGL_INVALID_ENABLED 0
#define TRACE_MEGASAS_IOVEC_SGL_INVALID_BACKEND_DSTATE() (0)
static inline void trace_megasas_iovec_sgl_invalid(int cmd, int index, uint64_t pa, uint32_t len) {
    (void)cmd;
    (void)index;
    (void)pa;
    (void)len;
}
#define TRACE_MEGASAS_IOVEC_SGL_OVERFLOW 0
#define TRACE_MEGASAS_IOVEC_SGL_OVERFLOW_ENABLED 0
#define TRACE_MEGASAS_IOVEC_SGL_OVERFLOW_BACKEND_DSTATE() (0)
static inline void trace_megasas_iovec_sgl_overflow(int cmd, int index, int limit) {
    (void)cmd;
    (void)index;
    (void)limit;
}
#define TRACE_MEGASAS_IOVEC_SGL_UNDERFLOW 0
#define TRACE_MEGASAS_IOVEC_SGL_UNDERFLOW_ENABLED 0
#define TRACE_MEGASAS_IOVEC_SGL_UNDERFLOW_BACKEND_DSTATE() (0)
static inline void trace_megasas_iovec_sgl_underflow(int cmd, int index) {
    (void)cmd;
    (void)index;
}
#define TRACE_MEGASAS_IOVEC_UNDERFLOW 0
#define TRACE_MEGASAS_IOVEC_UNDERFLOW_ENABLED 0
#define TRACE_MEGASAS_IOVEC_UNDERFLOW_BACKEND_DSTATE() (0)
static inline void trace_megasas_iovec_underflow(int cmd, int len, int limit) {
    (void)cmd;
    (void)len;
    (void)limit;
}
#define TRACE_MEGASAS_IRQ_LOWER 0
#define TRACE_MEGASAS_IRQ_LOWER_ENABLED 0
#define TRACE_MEGASAS_IRQ_LOWER_BACKEND_DSTATE() (0)
static inline void trace_megasas_irq_lower(void) {
}
#define TRACE_MEGASAS_IRQ_RAISE 0
#define TRACE_MEGASAS_IRQ_RAISE_ENABLED 0
#define TRACE_MEGASAS_IRQ_RAISE_BACKEND_DSTATE() (0)
static inline void trace_megasas_irq_raise(void) {
}
#define TRACE_MEGASAS_MMIO_INVALID_READL 0
#define TRACE_MEGASAS_MMIO_INVALID_READL_ENABLED 0
#define TRACE_MEGASAS_MMIO_INVALID_READL_BACKEND_DSTATE() (0)
static inline void trace_megasas_mmio_invalid_readl(unsigned long addr) {
    (void)addr;
}
#define TRACE_MEGASAS_MMIO_INVALID_WRITEL 0
#define TRACE_MEGASAS_MMIO_INVALID_WRITEL_ENABLED 0
#define TRACE_MEGASAS_MMIO_INVALID_WRITEL_BACKEND_DSTATE() (0)
static inline void trace_megasas_mmio_invalid_writel(uint32_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_MEGASAS_MMIO_READL 0
#define TRACE_MEGASAS_MMIO_READL_ENABLED 0
#define TRACE_MEGASAS_MMIO_READL_BACKEND_DSTATE() (0)
static inline void trace_megasas_mmio_readl(const char *reg, uint32_t val) {
    (void)reg;
    (void)val;
}
#define TRACE_MEGASAS_MMIO_WRITEL 0
#define TRACE_MEGASAS_MMIO_WRITEL_ENABLED 0
#define TRACE_MEGASAS_MMIO_WRITEL_BACKEND_DSTATE() (0)
static inline void trace_megasas_mmio_writel(const char *reg, uint32_t val) {
    (void)reg;
    (void)val;
}
#define TRACE_MEGASAS_MSI_ENABLED 0
#define TRACE_MEGASAS_MSI_ENABLED_ENABLED 0
#define TRACE_MEGASAS_MSI_ENABLED_BACKEND_DSTATE() (0)
static inline void trace_megasas_msi_enabled(int vector) {
    (void)vector;
}
#define TRACE_MEGASAS_MSI_RAISE 0
#define TRACE_MEGASAS_MSI_RAISE_ENABLED 0
#define TRACE_MEGASAS_MSI_RAISE_BACKEND_DSTATE() (0)
static inline void trace_megasas_msi_raise(int vector) {
    (void)vector;
}
#define TRACE_MEGASAS_MSIX_ENABLED 0
#define TRACE_MEGASAS_MSIX_ENABLED_ENABLED 0
#define TRACE_MEGASAS_MSIX_ENABLED_BACKEND_DSTATE() (0)
static inline void trace_megasas_msix_enabled(int vector) {
    (void)vector;
}
#define TRACE_MEGASAS_MSIX_RAISE 0
#define TRACE_MEGASAS_MSIX_RAISE_ENABLED 0
#define TRACE_MEGASAS_MSIX_RAISE_BACKEND_DSTATE() (0)
static inline void trace_megasas_msix_raise(int vector) {
    (void)vector;
}
#define TRACE_MEGASAS_QF_BUSY 0
#define TRACE_MEGASAS_QF_BUSY_ENABLED 0
#define TRACE_MEGASAS_QF_BUSY_BACKEND_DSTATE() (0)
static inline void trace_megasas_qf_busy(unsigned long pa) {
    (void)pa;
}
#define TRACE_MEGASAS_QF_COMPLETE 0
#define TRACE_MEGASAS_QF_COMPLETE_ENABLED 0
#define TRACE_MEGASAS_QF_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_megasas_qf_complete(uint64_t context, uint32_t head, uint32_t tail, int busy) {
    (void)context;
    (void)head;
    (void)tail;
    (void)busy;
}
#define TRACE_MEGASAS_QF_COMPLETE_NOIRQ 0
#define TRACE_MEGASAS_QF_COMPLETE_NOIRQ_ENABLED 0
#define TRACE_MEGASAS_QF_COMPLETE_NOIRQ_BACKEND_DSTATE() (0)
static inline void trace_megasas_qf_complete_noirq(uint64_t context) {
    (void)context;
}
#define TRACE_MEGASAS_QF_ENQUEUE 0
#define TRACE_MEGASAS_QF_ENQUEUE_ENABLED 0
#define TRACE_MEGASAS_QF_ENQUEUE_BACKEND_DSTATE() (0)
static inline void trace_megasas_qf_enqueue(unsigned int index, unsigned int count, uint64_t context, uint32_t head, uint32_t tail, unsigned int busy) {
    (void)index;
    (void)count;
    (void)context;
    (void)head;
    (void)tail;
    (void)busy;
}
#define TRACE_MEGASAS_QF_MAP_FAILED 0
#define TRACE_MEGASAS_QF_MAP_FAILED_ENABLED 0
#define TRACE_MEGASAS_QF_MAP_FAILED_BACKEND_DSTATE() (0)
static inline void trace_megasas_qf_map_failed(int cmd, unsigned long frame) {
    (void)cmd;
    (void)frame;
}
#define TRACE_MEGASAS_QF_MAPPED 0
#define TRACE_MEGASAS_QF_MAPPED_ENABLED 0
#define TRACE_MEGASAS_QF_MAPPED_BACKEND_DSTATE() (0)
static inline void trace_megasas_qf_mapped(unsigned int index) {
    (void)index;
}
#define TRACE_MEGASAS_QF_NEW 0
#define TRACE_MEGASAS_QF_NEW_ENABLED 0
#define TRACE_MEGASAS_QF_NEW_BACKEND_DSTATE() (0)
static inline void trace_megasas_qf_new(unsigned int index, uint64_t frame) {
    (void)index;
    (void)frame;
}
#define TRACE_MEGASAS_QF_UPDATE 0
#define TRACE_MEGASAS_QF_UPDATE_ENABLED 0
#define TRACE_MEGASAS_QF_UPDATE_BACKEND_DSTATE() (0)
static inline void trace_megasas_qf_update(uint32_t head, uint32_t tail, unsigned int busy) {
    (void)head;
    (void)tail;
    (void)busy;
}
#define TRACE_MEGASAS_RESET 0
#define TRACE_MEGASAS_RESET_ENABLED 0
#define TRACE_MEGASAS_RESET_BACKEND_DSTATE() (0)
static inline void trace_megasas_reset(int fw_state) {
    (void)fw_state;
}
#define TRACE_MEGASAS_SCSI_COMPLETE 0
#define TRACE_MEGASAS_SCSI_COMPLETE_ENABLED 0
#define TRACE_MEGASAS_SCSI_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_megasas_scsi_complete(int cmd, uint32_t status, int len, int xfer) {
    (void)cmd;
    (void)status;
    (void)len;
    (void)xfer;
}
#define TRACE_MEGASAS_SCSI_INVALID_CDB_LEN 0
#define TRACE_MEGASAS_SCSI_INVALID_CDB_LEN_ENABLED 0
#define TRACE_MEGASAS_SCSI_INVALID_CDB_LEN_BACKEND_DSTATE() (0)
static inline void trace_megasas_scsi_invalid_cdb_len(const char *frame, int bus, int dev, int lun, int len) {
    (void)frame;
    (void)bus;
    (void)dev;
    (void)lun;
    (void)len;
}
#define TRACE_MEGASAS_SCSI_NODATA 0
#define TRACE_MEGASAS_SCSI_NODATA_ENABLED 0
#define TRACE_MEGASAS_SCSI_NODATA_BACKEND_DSTATE() (0)
static inline void trace_megasas_scsi_nodata(int cmd) {
    (void)cmd;
}
#define TRACE_MEGASAS_SCSI_READ_START 0
#define TRACE_MEGASAS_SCSI_READ_START_ENABLED 0
#define TRACE_MEGASAS_SCSI_READ_START_BACKEND_DSTATE() (0)
static inline void trace_megasas_scsi_read_start(int cmd, int len) {
    (void)cmd;
    (void)len;
}
#define TRACE_MEGASAS_SCSI_REQ_ALLOC_FAILED 0
#define TRACE_MEGASAS_SCSI_REQ_ALLOC_FAILED_ENABLED 0
#define TRACE_MEGASAS_SCSI_REQ_ALLOC_FAILED_BACKEND_DSTATE() (0)
static inline void trace_megasas_scsi_req_alloc_failed(const char *frame, int dev, int lun) {
    (void)frame;
    (void)dev;
    (void)lun;
}
#define TRACE_MEGASAS_SCSI_TARGET_NOT_PRESENT 0
#define TRACE_MEGASAS_SCSI_TARGET_NOT_PRESENT_ENABLED 0
#define TRACE_MEGASAS_SCSI_TARGET_NOT_PRESENT_BACKEND_DSTATE() (0)
static inline void trace_megasas_scsi_target_not_present(const char *frame, int bus, int dev, int lun) {
    (void)frame;
    (void)bus;
    (void)dev;
    (void)lun;
}
#define TRACE_MEGASAS_SCSI_WRITE_START 0
#define TRACE_MEGASAS_SCSI_WRITE_START_ENABLED 0
#define TRACE_MEGASAS_SCSI_WRITE_START_BACKEND_DSTATE() (0)
static inline void trace_megasas_scsi_write_start(int cmd, int len) {
    (void)cmd;
    (void)len;
}
#define TRACE_MEGASAS_UNHANDLED_FRAME_CMD 0
#define TRACE_MEGASAS_UNHANDLED_FRAME_CMD_ENABLED 0
#define TRACE_MEGASAS_UNHANDLED_FRAME_CMD_BACKEND_DSTATE() (0)
static inline void trace_megasas_unhandled_frame_cmd(int cmd, uint8_t frame_cmd) {
    (void)cmd;
    (void)frame_cmd;
}
#define TRACE_MPTSAS_COMMAND_COMPLETE 0
#define TRACE_MPTSAS_COMMAND_COMPLETE_ENABLED 0
#define TRACE_MPTSAS_COMMAND_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_mptsas_command_complete(void *dev, uint32_t ctx, uint32_t status, uint32_t resid) {
    (void)dev;
    (void)ctx;
    (void)status;
    (void)resid;
}
#define TRACE_MPTSAS_CONFIG_SAS_DEVICE 0
#define TRACE_MPTSAS_CONFIG_SAS_DEVICE_ENABLED 0
#define TRACE_MPTSAS_CONFIG_SAS_DEVICE_BACKEND_DSTATE() (0)
static inline void trace_mptsas_config_sas_device(void *dev, int address, int port, int phy_handle, int dev_handle, int page) {
    (void)dev;
    (void)address;
    (void)port;
    (void)phy_handle;
    (void)dev_handle;
    (void)page;
}
#define TRACE_MPTSAS_CONFIG_SAS_PHY 0
#define TRACE_MPTSAS_CONFIG_SAS_PHY_ENABLED 0
#define TRACE_MPTSAS_CONFIG_SAS_PHY_BACKEND_DSTATE() (0)
static inline void trace_mptsas_config_sas_phy(void *dev, int address, int port, int phy_handle, int dev_handle, int page) {
    (void)dev;
    (void)address;
    (void)port;
    (void)phy_handle;
    (void)dev_handle;
    (void)page;
}
#define TRACE_MPTSAS_DIAG_READ 0
#define TRACE_MPTSAS_DIAG_READ_ENABLED 0
#define TRACE_MPTSAS_DIAG_READ_BACKEND_DSTATE() (0)
static inline void trace_mptsas_diag_read(void *dev, uint32_t addr, uint32_t val) {
    (void)dev;
    (void)addr;
    (void)val;
}
#define TRACE_MPTSAS_DIAG_WRITE 0
#define TRACE_MPTSAS_DIAG_WRITE_ENABLED 0
#define TRACE_MPTSAS_DIAG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_mptsas_diag_write(void *dev, uint32_t addr, uint32_t val) {
    (void)dev;
    (void)addr;
    (void)val;
}
#define TRACE_MPTSAS_IRQ_INTX 0
#define TRACE_MPTSAS_IRQ_INTX_ENABLED 0
#define TRACE_MPTSAS_IRQ_INTX_BACKEND_DSTATE() (0)
static inline void trace_mptsas_irq_intx(void *dev, int level) {
    (void)dev;
    (void)level;
}
#define TRACE_MPTSAS_IRQ_MSI 0
#define TRACE_MPTSAS_IRQ_MSI_ENABLED 0
#define TRACE_MPTSAS_IRQ_MSI_BACKEND_DSTATE() (0)
static inline void trace_mptsas_irq_msi(void *dev) {
    (void)dev;
}
#define TRACE_MPTSAS_MMIO_READ 0
#define TRACE_MPTSAS_MMIO_READ_ENABLED 0
#define TRACE_MPTSAS_MMIO_READ_BACKEND_DSTATE() (0)
static inline void trace_mptsas_mmio_read(void *dev, uint32_t addr, uint32_t val) {
    (void)dev;
    (void)addr;
    (void)val;
}
#define TRACE_MPTSAS_MMIO_UNHANDLED_READ 0
#define TRACE_MPTSAS_MMIO_UNHANDLED_READ_ENABLED 0
#define TRACE_MPTSAS_MMIO_UNHANDLED_READ_BACKEND_DSTATE() (0)
static inline void trace_mptsas_mmio_unhandled_read(void *dev, uint32_t addr) {
    (void)dev;
    (void)addr;
}
#define TRACE_MPTSAS_MMIO_UNHANDLED_WRITE 0
#define TRACE_MPTSAS_MMIO_UNHANDLED_WRITE_ENABLED 0
#define TRACE_MPTSAS_MMIO_UNHANDLED_WRITE_BACKEND_DSTATE() (0)
static inline void trace_mptsas_mmio_unhandled_write(void *dev, uint32_t addr, uint32_t val) {
    (void)dev;
    (void)addr;
    (void)val;
}
#define TRACE_MPTSAS_MMIO_WRITE 0
#define TRACE_MPTSAS_MMIO_WRITE_ENABLED 0
#define TRACE_MPTSAS_MMIO_WRITE_BACKEND_DSTATE() (0)
static inline void trace_mptsas_mmio_write(void *dev, uint32_t addr, uint32_t val) {
    (void)dev;
    (void)addr;
    (void)val;
}
#define TRACE_MPTSAS_PROCESS_MESSAGE 0
#define TRACE_MPTSAS_PROCESS_MESSAGE_ENABLED 0
#define TRACE_MPTSAS_PROCESS_MESSAGE_BACKEND_DSTATE() (0)
static inline void trace_mptsas_process_message(void *dev, int msg, uint32_t ctx) {
    (void)dev;
    (void)msg;
    (void)ctx;
}
#define TRACE_MPTSAS_PROCESS_SCSI_IO_REQUEST 0
#define TRACE_MPTSAS_PROCESS_SCSI_IO_REQUEST_ENABLED 0
#define TRACE_MPTSAS_PROCESS_SCSI_IO_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_mptsas_process_scsi_io_request(void *dev, int bus, int target, int lun, uint64_t len) {
    (void)dev;
    (void)bus;
    (void)target;
    (void)lun;
    (void)len;
}
#define TRACE_MPTSAS_RESET 0
#define TRACE_MPTSAS_RESET_ENABLED 0
#define TRACE_MPTSAS_RESET_BACKEND_DSTATE() (0)
static inline void trace_mptsas_reset(void *dev) {
    (void)dev;
}
#define TRACE_MPTSAS_SCSI_OVERFLOW 0
#define TRACE_MPTSAS_SCSI_OVERFLOW_ENABLED 0
#define TRACE_MPTSAS_SCSI_OVERFLOW_BACKEND_DSTATE() (0)
static inline void trace_mptsas_scsi_overflow(void *dev, uint32_t ctx, uint64_t req, uint64_t found) {
    (void)dev;
    (void)ctx;
    (void)req;
    (void)found;
}
#define TRACE_MPTSAS_SGL_OVERFLOW 0
#define TRACE_MPTSAS_SGL_OVERFLOW_ENABLED 0
#define TRACE_MPTSAS_SGL_OVERFLOW_BACKEND_DSTATE() (0)
static inline void trace_mptsas_sgl_overflow(void *dev, uint32_t ctx, uint64_t req, uint64_t found) {
    (void)dev;
    (void)ctx;
    (void)req;
    (void)found;
}
#define TRACE_MPTSAS_UNHANDLED_CMD 0
#define TRACE_MPTSAS_UNHANDLED_CMD_ENABLED 0
#define TRACE_MPTSAS_UNHANDLED_CMD_BACKEND_DSTATE() (0)
static inline void trace_mptsas_unhandled_cmd(void *dev, uint32_t ctx, uint8_t msg_cmd) {
    (void)dev;
    (void)ctx;
    (void)msg_cmd;
}
#define TRACE_MPTSAS_UNHANDLED_DOORBELL_CMD 0
#define TRACE_MPTSAS_UNHANDLED_DOORBELL_CMD_ENABLED 0
#define TRACE_MPTSAS_UNHANDLED_DOORBELL_CMD_BACKEND_DSTATE() (0)
static inline void trace_mptsas_unhandled_doorbell_cmd(void *dev, int cmd) {
    (void)dev;
    (void)cmd;
}
#define TRACE_NCR710_BAD_SELECTION 0
#define TRACE_NCR710_BAD_SELECTION_ENABLED 0
#define TRACE_NCR710_BAD_SELECTION_BACKEND_DSTATE() (0)
static inline void trace_ncr710_bad_selection(uint32_t target) {
    (void)target;
}
#define TRACE_NCR710_COMMAND_COMPLETE 0
#define TRACE_NCR710_COMMAND_COMPLETE_ENABLED 0
#define TRACE_NCR710_COMMAND_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_ncr710_command_complete(uint32_t tag, uint8_t status) {
    (void)tag;
    (void)status;
}
#define TRACE_NCR710_DEVICE_REALIZE 0
#define TRACE_NCR710_DEVICE_REALIZE_ENABLED 0
#define TRACE_NCR710_DEVICE_REALIZE_BACKEND_DSTATE() (0)
static inline void trace_ncr710_device_realize(void) {
}
#define TRACE_NCR710_DISCONNECT 0
#define TRACE_NCR710_DISCONNECT_ENABLED 0
#define TRACE_NCR710_DISCONNECT_BACKEND_DSTATE() (0)
static inline void trace_ncr710_disconnect(uint8_t waiting) {
    (void)waiting;
}
#define TRACE_NCR710_PARITY_SENSE_CHANGED 0
#define TRACE_NCR710_PARITY_SENSE_CHANGED_ENABLED 0
#define TRACE_NCR710_PARITY_SENSE_CHANGED_BACKEND_DSTATE() (0)
static inline void trace_ncr710_parity_sense_changed(const char *parity) {
    (void)parity;
}
#define TRACE_NCR710_REG_READ 0
#define TRACE_NCR710_REG_READ_ENABLED 0
#define TRACE_NCR710_REG_READ_BACKEND_DSTATE() (0)
static inline void trace_ncr710_reg_read(const char *name, int offset, uint8_t ret) {
    (void)name;
    (void)offset;
    (void)ret;
}
#define TRACE_NCR710_REG_WRITE 0
#define TRACE_NCR710_REG_WRITE_ENABLED 0
#define TRACE_NCR710_REG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_ncr710_reg_write(const char *name, int offset, uint8_t val) {
    (void)name;
    (void)offset;
    (void)val;
}
#define TRACE_NCR710_RESET 0
#define TRACE_NCR710_RESET_ENABLED 0
#define TRACE_NCR710_RESET_BACKEND_DSTATE() (0)
static inline void trace_ncr710_reset(void) {
}
#define TRACE_NCR710_SCRIPT_DMA_INTERRUPT 0
#define TRACE_NCR710_SCRIPT_DMA_INTERRUPT_ENABLED 0
#define TRACE_NCR710_SCRIPT_DMA_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_ncr710_script_dma_interrupt(uint8_t stat, uint8_t dstat) {
    (void)stat;
    (void)dstat;
}
#define TRACE_NCR710_SCRIPT_SCSI_INTERRUPT 0
#define TRACE_NCR710_SCRIPT_SCSI_INTERRUPT_ENABLED 0
#define TRACE_NCR710_SCRIPT_SCSI_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_ncr710_script_scsi_interrupt(uint8_t stat0, uint8_t sstat0) {
    (void)stat0;
    (void)sstat0;
}
#define TRACE_PVSCSI_CMP_RING_PUT 0
#define TRACE_PVSCSI_CMP_RING_PUT_ENABLED 0
#define TRACE_PVSCSI_CMP_RING_PUT_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_cmp_ring_put(unsigned long addr) {
    (void)addr;
}
#define TRACE_PVSCSI_COMMAND_COMPLETE_DATA_RUN 0
#define TRACE_PVSCSI_COMMAND_COMPLETE_DATA_RUN_ENABLED 0
#define TRACE_PVSCSI_COMMAND_COMPLETE_DATA_RUN_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_command_complete_data_run(void) {
}
#define TRACE_PVSCSI_COMMAND_COMPLETE_NOT_FOUND 0
#define TRACE_PVSCSI_COMMAND_COMPLETE_NOT_FOUND_ENABLED 0
#define TRACE_PVSCSI_COMMAND_COMPLETE_NOT_FOUND_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_command_complete_not_found(uint32_t tag) {
    (void)tag;
}
#define TRACE_PVSCSI_COMMAND_COMPLETE_SENSE_LEN 0
#define TRACE_PVSCSI_COMMAND_COMPLETE_SENSE_LEN_ENABLED 0
#define TRACE_PVSCSI_COMMAND_COMPLETE_SENSE_LEN_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_command_complete_sense_len(int len) {
    (void)len;
}
#define TRACE_PVSCSI_COMPLETE_REQUEST 0
#define TRACE_PVSCSI_COMPLETE_REQUEST_ENABLED 0
#define TRACE_PVSCSI_COMPLETE_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_complete_request(uint64_t context, uint64_t len, uint8_t sense_key) {
    (void)context;
    (void)len;
    (void)sense_key;
}
#define TRACE_PVSCSI_CONVERT_SGLIST 0
#define TRACE_PVSCSI_CONVERT_SGLIST_ENABLED 0
#define TRACE_PVSCSI_CONVERT_SGLIST_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_convert_sglist(uint64_t context, unsigned long addr, uint32_t resid) {
    (void)context;
    (void)addr;
    (void)resid;
}
#define TRACE_PVSCSI_GET_NEXT_SG_ELEM 0
#define TRACE_PVSCSI_GET_NEXT_SG_ELEM_ENABLED 0
#define TRACE_PVSCSI_GET_NEXT_SG_ELEM_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_get_next_sg_elem(uint32_t flags) {
    (void)flags;
}
#define TRACE_PVSCSI_GET_SG_LIST 0
#define TRACE_PVSCSI_GET_SG_LIST_ENABLED 0
#define TRACE_PVSCSI_GET_SG_LIST_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_get_sg_list(int nsg, size_t size) {
    (void)nsg;
    (void)size;
}
#define TRACE_PVSCSI_INIT_MSI_FAIL 0
#define TRACE_PVSCSI_INIT_MSI_FAIL_ENABLED 0
#define TRACE_PVSCSI_INIT_MSI_FAIL_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_init_msi_fail(int res) {
    (void)res;
}
#define TRACE_PVSCSI_IO_READ 0
#define TRACE_PVSCSI_IO_READ_ENABLED 0
#define TRACE_PVSCSI_IO_READ_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_io_read(const char* cmd, uint64_t status) {
    (void)cmd;
    (void)status;
}
#define TRACE_PVSCSI_IO_READ_UNKNOWN 0
#define TRACE_PVSCSI_IO_READ_UNKNOWN_ENABLED 0
#define TRACE_PVSCSI_IO_READ_UNKNOWN_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_io_read_unknown(unsigned long addr, unsigned sz) {
    (void)addr;
    (void)sz;
}
#define TRACE_PVSCSI_IO_WRITE 0
#define TRACE_PVSCSI_IO_WRITE_ENABLED 0
#define TRACE_PVSCSI_IO_WRITE_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_io_write(const char* cmd, uint64_t val) {
    (void)cmd;
    (void)val;
}
#define TRACE_PVSCSI_IO_WRITE_UNKNOWN 0
#define TRACE_PVSCSI_IO_WRITE_UNKNOWN_ENABLED 0
#define TRACE_PVSCSI_IO_WRITE_UNKNOWN_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_io_write_unknown(unsigned long addr, unsigned sz, uint64_t val) {
    (void)addr;
    (void)sz;
    (void)val;
}
#define TRACE_PVSCSI_MSG_RING_PUT 0
#define TRACE_PVSCSI_MSG_RING_PUT_ENABLED 0
#define TRACE_PVSCSI_MSG_RING_PUT_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_msg_ring_put(unsigned long addr) {
    (void)addr;
}
#define TRACE_PVSCSI_ON_CMD_ABORT 0
#define TRACE_PVSCSI_ON_CMD_ABORT_ENABLED 0
#define TRACE_PVSCSI_ON_CMD_ABORT_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_on_cmd_abort(uint64_t ctx, uint32_t tgt) {
    (void)ctx;
    (void)tgt;
}
#define TRACE_PVSCSI_ON_CMD_ARRIVED 0
#define TRACE_PVSCSI_ON_CMD_ARRIVED_ENABLED 0
#define TRACE_PVSCSI_ON_CMD_ARRIVED_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_on_cmd_arrived(const char* cmd) {
    (void)cmd;
}
#define TRACE_PVSCSI_ON_CMD_NOIMPL 0
#define TRACE_PVSCSI_ON_CMD_NOIMPL_ENABLED 0
#define TRACE_PVSCSI_ON_CMD_NOIMPL_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_on_cmd_noimpl(const char* cmd) {
    (void)cmd;
}
#define TRACE_PVSCSI_ON_CMD_RESET_DEV 0
#define TRACE_PVSCSI_ON_CMD_RESET_DEV_ENABLED 0
#define TRACE_PVSCSI_ON_CMD_RESET_DEV_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_on_cmd_reset_dev(uint32_t tgt, int lun, void* dev) {
    (void)tgt;
    (void)lun;
    (void)dev;
}
#define TRACE_PVSCSI_ON_CMD_UNKNOWN 0
#define TRACE_PVSCSI_ON_CMD_UNKNOWN_ENABLED 0
#define TRACE_PVSCSI_ON_CMD_UNKNOWN_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_on_cmd_unknown(uint64_t cmd_id) {
    (void)cmd_id;
}
#define TRACE_PVSCSI_ON_CMD_UNKNOWN_DATA 0
#define TRACE_PVSCSI_ON_CMD_UNKNOWN_DATA_ENABLED 0
#define TRACE_PVSCSI_ON_CMD_UNKNOWN_DATA_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_on_cmd_unknown_data(uint32_t data) {
    (void)data;
}
#define TRACE_PVSCSI_PROCESS_IO 0
#define TRACE_PVSCSI_PROCESS_IO_ENABLED 0
#define TRACE_PVSCSI_PROCESS_IO_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_process_io(unsigned long addr) {
    (void)addr;
}
#define TRACE_PVSCSI_PROCESS_REQ_DESCR 0
#define TRACE_PVSCSI_PROCESS_REQ_DESCR_ENABLED 0
#define TRACE_PVSCSI_PROCESS_REQ_DESCR_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_process_req_descr(uint8_t cmd, uint64_t ctx) {
    (void)cmd;
    (void)ctx;
}
#define TRACE_PVSCSI_PROCESS_REQ_DESCR_INVALID_DIR 0
#define TRACE_PVSCSI_PROCESS_REQ_DESCR_INVALID_DIR_ENABLED 0
#define TRACE_PVSCSI_PROCESS_REQ_DESCR_INVALID_DIR_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_process_req_descr_invalid_dir(void) {
}
#define TRACE_PVSCSI_PROCESS_REQ_DESCR_UNKNOWN_DEVICE 0
#define TRACE_PVSCSI_PROCESS_REQ_DESCR_UNKNOWN_DEVICE_ENABLED 0
#define TRACE_PVSCSI_PROCESS_REQ_DESCR_UNKNOWN_DEVICE_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_process_req_descr_unknown_device(void) {
}
#define TRACE_PVSCSI_RING_FLUSH_CMP 0
#define TRACE_PVSCSI_RING_FLUSH_CMP_ENABLED 0
#define TRACE_PVSCSI_RING_FLUSH_CMP_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_ring_flush_cmp(uint64_t filled_cmp_ptr) {
    (void)filled_cmp_ptr;
}
#define TRACE_PVSCSI_RING_FLUSH_MSG 0
#define TRACE_PVSCSI_RING_FLUSH_MSG_ENABLED 0
#define TRACE_PVSCSI_RING_FLUSH_MSG_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_ring_flush_msg(uint64_t filled_cmp_ptr) {
    (void)filled_cmp_ptr;
}
#define TRACE_PVSCSI_RING_INIT_DATA 0
#define TRACE_PVSCSI_RING_INIT_DATA_ENABLED 0
#define TRACE_PVSCSI_RING_INIT_DATA_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_ring_init_data(uint32_t txr_len_log2, uint32_t rxr_len_log2) {
    (void)txr_len_log2;
    (void)rxr_len_log2;
}
#define TRACE_PVSCSI_RING_INIT_MSG 0
#define TRACE_PVSCSI_RING_INIT_MSG_ENABLED 0
#define TRACE_PVSCSI_RING_INIT_MSG_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_ring_init_msg(uint32_t len_log2) {
    (void)len_log2;
}
#define TRACE_PVSCSI_STATE 0
#define TRACE_PVSCSI_STATE_ENABLED 0
#define TRACE_PVSCSI_STATE_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_state(const char* state) {
    (void)state;
}
#define TRACE_PVSCSI_TX_RINGS_NUM_PAGES 0
#define TRACE_PVSCSI_TX_RINGS_NUM_PAGES_ENABLED 0
#define TRACE_PVSCSI_TX_RINGS_NUM_PAGES_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_tx_rings_num_pages(const char* label, uint32_t num) {
    (void)label;
    (void)num;
}
#define TRACE_PVSCSI_TX_RINGS_PPN 0
#define TRACE_PVSCSI_TX_RINGS_PPN_ENABLED 0
#define TRACE_PVSCSI_TX_RINGS_PPN_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_tx_rings_ppn(const char* label, uint64_t ppn) {
    (void)label;
    (void)ppn;
}
#define TRACE_PVSCSI_UPDATE_IRQ_LEVEL 0
#define TRACE_PVSCSI_UPDATE_IRQ_LEVEL_ENABLED 0
#define TRACE_PVSCSI_UPDATE_IRQ_LEVEL_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_update_irq_level(bool raise, uint64_t mask, uint64_t status) {
    (void)raise;
    (void)mask;
    (void)status;
}
#define TRACE_PVSCSI_UPDATE_IRQ_MSI 0
#define TRACE_PVSCSI_UPDATE_IRQ_MSI_ENABLED 0
#define TRACE_PVSCSI_UPDATE_IRQ_MSI_BACKEND_DSTATE() (0)
static inline void trace_pvscsi_update_irq_msi(void) {
}
#define TRACE_SCSI_BUS_DRAINED_BEGIN 0
#define TRACE_SCSI_BUS_DRAINED_BEGIN_ENABLED 0
#define TRACE_SCSI_BUS_DRAINED_BEGIN_BACKEND_DSTATE() (0)
static inline void trace_scsi_bus_drained_begin(void *bus, void *sdev) {
    (void)bus;
    (void)sdev;
}
#define TRACE_SCSI_BUS_DRAINED_END 0
#define TRACE_SCSI_BUS_DRAINED_END_ENABLED 0
#define TRACE_SCSI_BUS_DRAINED_END_BACKEND_DSTATE() (0)
static inline void trace_scsi_bus_drained_end(void *bus, void *sdev) {
    (void)bus;
    (void)sdev;
}
#define TRACE_SCSI_DEVICE_SET_UA 0
#define TRACE_SCSI_DEVICE_SET_UA_ENABLED 0
#define TRACE_SCSI_DEVICE_SET_UA_BACKEND_DSTATE() (0)
static inline void trace_scsi_device_set_ua(int target, int lun, int key, int asc, int ascq) {
    (void)target;
    (void)lun;
    (void)key;
    (void)asc;
    (void)ascq;
}
#define TRACE_SCSI_DISK_AIO_SGIO_COMMAND 0
#define TRACE_SCSI_DISK_AIO_SGIO_COMMAND_ENABLED 0
#define TRACE_SCSI_DISK_AIO_SGIO_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_aio_sgio_command(uint32_t tag, uint8_t cmd, uint64_t lba, int len, uint32_t timeout) {
    (void)tag;
    (void)cmd;
    (void)lba;
    (void)len;
    (void)timeout;
}
#define TRACE_SCSI_DISK_CHECK_CONDITION 0
#define TRACE_SCSI_DISK_CHECK_CONDITION_ENABLED 0
#define TRACE_SCSI_DISK_CHECK_CONDITION_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_check_condition(uint32_t tag, uint8_t key, uint8_t asc, uint8_t ascq) {
    (void)tag;
    (void)key;
    (void)asc;
    (void)ascq;
}
#define TRACE_SCSI_DISK_DMA_COMMAND_READ 0
#define TRACE_SCSI_DISK_DMA_COMMAND_READ_ENABLED 0
#define TRACE_SCSI_DISK_DMA_COMMAND_READ_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_dma_command_READ(uint64_t lba, uint32_t len) {
    (void)lba;
    (void)len;
}
#define TRACE_SCSI_DISK_DMA_COMMAND_WRITE 0
#define TRACE_SCSI_DISK_DMA_COMMAND_WRITE_ENABLED 0
#define TRACE_SCSI_DISK_DMA_COMMAND_WRITE_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_dma_command_WRITE(const char *cmd, uint64_t lba, int len) {
    (void)cmd;
    (void)lba;
    (void)len;
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_FORMAT_UNIT 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_FORMAT_UNIT_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_FORMAT_UNIT_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_FORMAT_UNIT(size_t xfer) {
    (void)xfer;
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_MODE_SELECT 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_MODE_SELECT_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_MODE_SELECT_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_MODE_SELECT(size_t xfer) {
    (void)xfer;
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_MODE_SELECT_10 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_MODE_SELECT_10_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_MODE_SELECT_10_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_MODE_SELECT_10(size_t xfer) {
    (void)xfer;
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SAI_16 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SAI_16_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SAI_16_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_SAI_16(void) {
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SAI_UNSUPPORTED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SAI_UNSUPPORTED_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SAI_UNSUPPORTED_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_SAI_unsupported(void) {
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SEEK_10 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SEEK_10_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_SEEK_10_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_SEEK_10(uint64_t lba) {
    (void)lba;
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_UNKNOWN 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_UNKNOWN_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_UNKNOWN_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_UNKNOWN(int cmd, const char *name) {
    (void)cmd;
    (void)name;
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_UNMAP 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_UNMAP_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_UNMAP_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_UNMAP(size_t xfer) {
    (void)xfer;
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_VERIFY 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_VERIFY_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_VERIFY_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_VERIFY(int bytchk) {
    (void)bytchk;
}
#define TRACE_SCSI_DISK_EMULATE_COMMAND_WRITE_SAME 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_WRITE_SAME_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_COMMAND_WRITE_SAME_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_command_WRITE_SAME(int cmd, size_t xfer) {
    (void)cmd;
    (void)xfer;
}
#define TRACE_SCSI_DISK_EMULATE_MODE_SENSE 0
#define TRACE_SCSI_DISK_EMULATE_MODE_SENSE_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_MODE_SENSE_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_mode_sense(int cmd, int page, size_t xfer, int control) {
    (void)cmd;
    (void)page;
    (void)xfer;
    (void)control;
}
#define TRACE_SCSI_DISK_EMULATE_READ_DATA 0
#define TRACE_SCSI_DISK_EMULATE_READ_DATA_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_READ_DATA_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_read_data(int buflen) {
    (void)buflen;
}
#define TRACE_SCSI_DISK_EMULATE_READ_TOC 0
#define TRACE_SCSI_DISK_EMULATE_READ_TOC_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_READ_TOC_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_read_toc(int start_track, int format, int msf) {
    (void)start_track;
    (void)format;
    (void)msf;
}
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_00 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_00_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_00_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_vpd_page_00(size_t xfer) {
    (void)xfer;
}
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_80 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_80_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_80_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_vpd_page_80(size_t xfer) {
    (void)xfer;
}
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_80_NOT_SUPPORTED 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_80_NOT_SUPPORTED_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_80_NOT_SUPPORTED_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_vpd_page_80_not_supported(void) {
}
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_83 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_83_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_83_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_vpd_page_83(size_t xfer) {
    (void)xfer;
}
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_B0_NOT_SUPPORTED 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_B0_NOT_SUPPORTED_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_VPD_PAGE_B0_NOT_SUPPORTED_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_vpd_page_b0_not_supported(void) {
}
#define TRACE_SCSI_DISK_EMULATE_WRITE_DATA 0
#define TRACE_SCSI_DISK_EMULATE_WRITE_DATA_ENABLED 0
#define TRACE_SCSI_DISK_EMULATE_WRITE_DATA_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_emulate_write_data(int buflen) {
    (void)buflen;
}
#define TRACE_SCSI_DISK_MODE_SELECT_PAGE_TRUNCATED 0
#define TRACE_SCSI_DISK_MODE_SELECT_PAGE_TRUNCATED_ENABLED 0
#define TRACE_SCSI_DISK_MODE_SELECT_PAGE_TRUNCATED_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_mode_select_page_truncated(int page, int len, int page_len) {
    (void)page;
    (void)len;
    (void)page_len;
}
#define TRACE_SCSI_DISK_MODE_SELECT_SET_BLOCKSIZE 0
#define TRACE_SCSI_DISK_MODE_SELECT_SET_BLOCKSIZE_ENABLED 0
#define TRACE_SCSI_DISK_MODE_SELECT_SET_BLOCKSIZE_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_mode_select_set_blocksize(int blocksize) {
    (void)blocksize;
}
#define TRACE_SCSI_DISK_NEW_REQUEST 0
#define TRACE_SCSI_DISK_NEW_REQUEST_ENABLED 0
#define TRACE_SCSI_DISK_NEW_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_new_request(uint32_t lun, uint32_t tag, const char *line) {
    (void)lun;
    (void)tag;
    (void)line;
}
#define TRACE_SCSI_DISK_READ_COMPLETE 0
#define TRACE_SCSI_DISK_READ_COMPLETE_ENABLED 0
#define TRACE_SCSI_DISK_READ_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_read_complete(uint32_t tag, size_t size) {
    (void)tag;
    (void)size;
}
#define TRACE_SCSI_DISK_READ_DATA_COUNT 0
#define TRACE_SCSI_DISK_READ_DATA_COUNT_ENABLED 0
#define TRACE_SCSI_DISK_READ_DATA_COUNT_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_read_data_count(uint32_t sector_count) {
    (void)sector_count;
}
#define TRACE_SCSI_DISK_READ_DATA_INVALID 0
#define TRACE_SCSI_DISK_READ_DATA_INVALID_ENABLED 0
#define TRACE_SCSI_DISK_READ_DATA_INVALID_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_read_data_invalid(void) {
}
#define TRACE_SCSI_DISK_WRITE_COMPLETE_NOIO 0
#define TRACE_SCSI_DISK_WRITE_COMPLETE_NOIO_ENABLED 0
#define TRACE_SCSI_DISK_WRITE_COMPLETE_NOIO_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_write_complete_noio(uint32_t tag, size_t size) {
    (void)tag;
    (void)size;
}
#define TRACE_SCSI_DISK_WRITE_DATA_INVALID 0
#define TRACE_SCSI_DISK_WRITE_DATA_INVALID_ENABLED 0
#define TRACE_SCSI_DISK_WRITE_DATA_INVALID_BACKEND_DSTATE() (0)
static inline void trace_scsi_disk_write_data_invalid(void) {
}
#define TRACE_SCSI_GENERIC_AIO_SGIO_COMMAND 0
#define TRACE_SCSI_GENERIC_AIO_SGIO_COMMAND_ENABLED 0
#define TRACE_SCSI_GENERIC_AIO_SGIO_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_aio_sgio_command(uint32_t tag, uint8_t cmd, uint32_t timeout) {
    (void)tag;
    (void)cmd;
    (void)timeout;
}
#define TRACE_SCSI_GENERIC_COMMAND_COMPLETE_NOIO 0
#define TRACE_SCSI_GENERIC_COMMAND_COMPLETE_NOIO_ENABLED 0
#define TRACE_SCSI_GENERIC_COMMAND_COMPLETE_NOIO_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_command_complete_noio(void *req, uint32_t tag, int statuc) {
    (void)req;
    (void)tag;
    (void)statuc;
}
#define TRACE_SCSI_GENERIC_IOCTL_SGIO_COMMAND 0
#define TRACE_SCSI_GENERIC_IOCTL_SGIO_COMMAND_ENABLED 0
#define TRACE_SCSI_GENERIC_IOCTL_SGIO_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_ioctl_sgio_command(uint8_t cmd, uint32_t timeout) {
    (void)cmd;
    (void)timeout;
}
#define TRACE_SCSI_GENERIC_IOCTL_SGIO_DONE 0
#define TRACE_SCSI_GENERIC_IOCTL_SGIO_DONE_ENABLED 0
#define TRACE_SCSI_GENERIC_IOCTL_SGIO_DONE_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_ioctl_sgio_done(uint8_t cmd, int ret, uint8_t status, uint8_t host_status) {
    (void)cmd;
    (void)ret;
    (void)status;
    (void)host_status;
}
#define TRACE_SCSI_GENERIC_READ_COMPLETE 0
#define TRACE_SCSI_GENERIC_READ_COMPLETE_ENABLED 0
#define TRACE_SCSI_GENERIC_READ_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_read_complete(uint32_t tag, int len) {
    (void)tag;
    (void)len;
}
#define TRACE_SCSI_GENERIC_READ_DATA 0
#define TRACE_SCSI_GENERIC_READ_DATA_ENABLED 0
#define TRACE_SCSI_GENERIC_READ_DATA_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_read_data(uint32_t tag) {
    (void)tag;
}
#define TRACE_SCSI_GENERIC_REALIZE_BLOCKSIZE 0
#define TRACE_SCSI_GENERIC_REALIZE_BLOCKSIZE_ENABLED 0
#define TRACE_SCSI_GENERIC_REALIZE_BLOCKSIZE_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_realize_blocksize(int blocksize) {
    (void)blocksize;
}
#define TRACE_SCSI_GENERIC_REALIZE_TYPE 0
#define TRACE_SCSI_GENERIC_REALIZE_TYPE_ENABLED 0
#define TRACE_SCSI_GENERIC_REALIZE_TYPE_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_realize_type(int type) {
    (void)type;
}
#define TRACE_SCSI_GENERIC_SEND_COMMAND 0
#define TRACE_SCSI_GENERIC_SEND_COMMAND_ENABLED 0
#define TRACE_SCSI_GENERIC_SEND_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_send_command(const char *line) {
    (void)line;
}
#define TRACE_SCSI_GENERIC_WRITE_COMPLETE 0
#define TRACE_SCSI_GENERIC_WRITE_COMPLETE_ENABLED 0
#define TRACE_SCSI_GENERIC_WRITE_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_write_complete(int ret) {
    (void)ret;
}
#define TRACE_SCSI_GENERIC_WRITE_COMPLETE_BLOCKSIZE 0
#define TRACE_SCSI_GENERIC_WRITE_COMPLETE_BLOCKSIZE_ENABLED 0
#define TRACE_SCSI_GENERIC_WRITE_COMPLETE_BLOCKSIZE_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_write_complete_blocksize(int blocksize) {
    (void)blocksize;
}
#define TRACE_SCSI_GENERIC_WRITE_DATA 0
#define TRACE_SCSI_GENERIC_WRITE_DATA_ENABLED 0
#define TRACE_SCSI_GENERIC_WRITE_DATA_BACKEND_DSTATE() (0)
static inline void trace_scsi_generic_write_data(uint32_t tag) {
    (void)tag;
}
#define TRACE_SCSI_INQUIRY 0
#define TRACE_SCSI_INQUIRY_ENABLED 0
#define TRACE_SCSI_INQUIRY_BACKEND_DSTATE() (0)
static inline void trace_scsi_inquiry(int target, int lun, int tag, int cdb1, int cdb2) {
    (void)target;
    (void)lun;
    (void)tag;
    (void)cdb1;
    (void)cdb2;
}
#define TRACE_SCSI_REPORT_LUNS 0
#define TRACE_SCSI_REPORT_LUNS_ENABLED 0
#define TRACE_SCSI_REPORT_LUNS_BACKEND_DSTATE() (0)
static inline void trace_scsi_report_luns(int target, int lun, int tag) {
    (void)target;
    (void)lun;
    (void)tag;
}
#define TRACE_SCSI_REQ_ALLOC 0
#define TRACE_SCSI_REQ_ALLOC_ENABLED 0
#define TRACE_SCSI_REQ_ALLOC_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_alloc(int target, int lun, int tag) {
    (void)target;
    (void)lun;
    (void)tag;
}
#define TRACE_SCSI_REQ_BUILD_SENSE 0
#define TRACE_SCSI_REQ_BUILD_SENSE_ENABLED 0
#define TRACE_SCSI_REQ_BUILD_SENSE_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_build_sense(int target, int lun, int tag, int key, int asc, int ascq) {
    (void)target;
    (void)lun;
    (void)tag;
    (void)key;
    (void)asc;
    (void)ascq;
}
#define TRACE_SCSI_REQ_CANCEL 0
#define TRACE_SCSI_REQ_CANCEL_ENABLED 0
#define TRACE_SCSI_REQ_CANCEL_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_cancel(int target, int lun, int tag) {
    (void)target;
    (void)lun;
    (void)tag;
}
#define TRACE_SCSI_REQ_CONTINUE 0
#define TRACE_SCSI_REQ_CONTINUE_ENABLED 0
#define TRACE_SCSI_REQ_CONTINUE_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_continue(int target, int lun, int tag) {
    (void)target;
    (void)lun;
    (void)tag;
}
#define TRACE_SCSI_REQ_CONTINUE_CANCELED 0
#define TRACE_SCSI_REQ_CONTINUE_CANCELED_ENABLED 0
#define TRACE_SCSI_REQ_CONTINUE_CANCELED_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_continue_canceled(int target, int lun, int tag) {
    (void)target;
    (void)lun;
    (void)tag;
}
#define TRACE_SCSI_REQ_DATA 0
#define TRACE_SCSI_REQ_DATA_ENABLED 0
#define TRACE_SCSI_REQ_DATA_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_data(int target, int lun, int tag, int len) {
    (void)target;
    (void)lun;
    (void)tag;
    (void)len;
}
#define TRACE_SCSI_REQ_DATA_CANCELED 0
#define TRACE_SCSI_REQ_DATA_CANCELED_ENABLED 0
#define TRACE_SCSI_REQ_DATA_CANCELED_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_data_canceled(int target, int lun, int tag, int len) {
    (void)target;
    (void)lun;
    (void)tag;
    (void)len;
}
#define TRACE_SCSI_REQ_DEQUEUE 0
#define TRACE_SCSI_REQ_DEQUEUE_ENABLED 0
#define TRACE_SCSI_REQ_DEQUEUE_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_dequeue(int target, int lun, int tag) {
    (void)target;
    (void)lun;
    (void)tag;
}
#define TRACE_SCSI_REQ_PARSE_BAD 0
#define TRACE_SCSI_REQ_PARSE_BAD_ENABLED 0
#define TRACE_SCSI_REQ_PARSE_BAD_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_parse_bad(int target, int lun, int tag, int cmd) {
    (void)target;
    (void)lun;
    (void)tag;
    (void)cmd;
}
#define TRACE_SCSI_REQ_PARSED 0
#define TRACE_SCSI_REQ_PARSED_ENABLED 0
#define TRACE_SCSI_REQ_PARSED_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_parsed(int target, int lun, int tag, int cmd, int mode, int xfer) {
    (void)target;
    (void)lun;
    (void)tag;
    (void)cmd;
    (void)mode;
    (void)xfer;
}
#define TRACE_SCSI_REQ_PARSED_LBA 0
#define TRACE_SCSI_REQ_PARSED_LBA_ENABLED 0
#define TRACE_SCSI_REQ_PARSED_LBA_BACKEND_DSTATE() (0)
static inline void trace_scsi_req_parsed_lba(int target, int lun, int tag, int cmd, uint64_t lba) {
    (void)target;
    (void)lun;
    (void)tag;
    (void)cmd;
    (void)lba;
}
#define TRACE_SCSI_REQUEST_SENSE 0
#define TRACE_SCSI_REQUEST_SENSE_ENABLED 0
#define TRACE_SCSI_REQUEST_SENSE_BACKEND_DSTATE() (0)
static inline void trace_scsi_request_sense(int target, int lun, int tag) {
    (void)target;
    (void)lun;
    (void)tag;
}
#define TRACE_SCSI_TEST_UNIT_READY 0
#define TRACE_SCSI_TEST_UNIT_READY_ENABLED 0
#define TRACE_SCSI_TEST_UNIT_READY_BACKEND_DSTATE() (0)
static inline void trace_scsi_test_unit_ready(int target, int lun, int tag) {
    (void)target;
    (void)lun;
    (void)tag;
}
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE 0
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_ENABLED 0
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_command_complete(uint32_t tag, uint32_t status, void *req) {
    (void)tag;
    (void)status;
    (void)req;
}
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_SENSE_DATA1 0
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_SENSE_DATA1_ENABLED 0
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_SENSE_DATA1_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_command_complete_sense_data1(uint32_t len, unsigned s0, unsigned s1, unsigned s2, unsigned s3, unsigned s4, unsigned s5, unsigned s6, unsigned s7) {
    (void)len;
    (void)s0;
    (void)s1;
    (void)s2;
    (void)s3;
    (void)s4;
    (void)s5;
    (void)s6;
    (void)s7;
}
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_SENSE_DATA2 0
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_SENSE_DATA2_ENABLED 0
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_SENSE_DATA2_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_command_complete_sense_data2(unsigned s8, unsigned s9, unsigned s10, unsigned s11, unsigned s12, unsigned s13, unsigned s14, unsigned s15) {
    (void)s8;
    (void)s9;
    (void)s10;
    (void)s11;
    (void)s12;
    (void)s13;
    (void)s14;
    (void)s15;
}
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_STATUS 0
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_STATUS_ENABLED 0
#define TRACE_SPAPR_VSCSI_COMMAND_COMPLETE_STATUS_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_command_complete_status(uint32_t status) {
    (void)status;
}
#define TRACE_SPAPR_VSCSI_DO_CRQ 0
#define TRACE_SPAPR_VSCSI_DO_CRQ_ENABLED 0
#define TRACE_SPAPR_VSCSI_DO_CRQ_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_do_crq(unsigned c0, unsigned c1) {
    (void)c0;
    (void)c1;
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DIRECT 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DIRECT_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DIRECT_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_direct(void) {
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DMA_READ_ERROR 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DMA_READ_ERROR_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DMA_READ_ERROR_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_dma_read_error(int rc) {
    (void)rc;
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DONE 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DONE_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_DONE_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_done(unsigned desc_num, unsigned desc_offset, uint64_t va, uint32_t len) {
    (void)desc_num;
    (void)desc_offset;
    (void)va;
    (void)len;
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_INDIRECT 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_INDIRECT_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_INDIRECT_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_indirect(uint32_t qtag, unsigned desc, unsigned local_desc) {
    (void)qtag;
    (void)desc;
    (void)local_desc;
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_INDIRECT_SEG_EXT 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_INDIRECT_SEG_EXT_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_INDIRECT_SEG_EXT_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_indirect_seg_ext(uint32_t qtag, unsigned n, unsigned desc, uint64_t va, uint32_t len) {
    (void)qtag;
    (void)n;
    (void)desc;
    (void)va;
    (void)len;
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_NO_DATA 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_NO_DATA_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_NO_DATA_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_no_data(void) {
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_DESC 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_DESC_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_DESC_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_out_of_desc(void) {
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_DESC_BOUNDARY 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_DESC_BOUNDARY_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_DESC_BOUNDARY_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_out_of_desc_boundary(unsigned offset, unsigned desc, uint32_t len) {
    (void)offset;
    (void)desc;
    (void)len;
}
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_RANGE 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_RANGE_ENABLED 0
#define TRACE_SPAPR_VSCSI_FETCH_DESC_OUT_OF_RANGE_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_fetch_desc_out_of_range(unsigned desc, unsigned desc_offset) {
    (void)desc;
    (void)desc_offset;
}
#define TRACE_SPAPR_VSCSI_LOAD_REQUEST 0
#define TRACE_SPAPR_VSCSI_LOAD_REQUEST_ENABLED 0
#define TRACE_SPAPR_VSCSI_LOAD_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_load_request(uint32_t qtag, unsigned desc, unsigned offset) {
    (void)qtag;
    (void)desc;
    (void)offset;
}
#define TRACE_SPAPR_VSCSI_PROCESS_LOGIN 0
#define TRACE_SPAPR_VSCSI_PROCESS_LOGIN_ENABLED 0
#define TRACE_SPAPR_VSCSI_PROCESS_LOGIN_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_process_login(void) {
}
#define TRACE_SPAPR_VSCSI_PROCESS_TSK_MGMT 0
#define TRACE_SPAPR_VSCSI_PROCESS_TSK_MGMT_ENABLED 0
#define TRACE_SPAPR_VSCSI_PROCESS_TSK_MGMT_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_process_tsk_mgmt(uint8_t func) {
    (void)func;
}
#define TRACE_SPAPR_VSCSI_QUEUE_CMD 0
#define TRACE_SPAPR_VSCSI_QUEUE_CMD_ENABLED 0
#define TRACE_SPAPR_VSCSI_QUEUE_CMD_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_queue_cmd(uint32_t qtag, unsigned cdb, const char *cmd, int lun, int ret) {
    (void)qtag;
    (void)cdb;
    (void)cmd;
    (void)lun;
    (void)ret;
}
#define TRACE_SPAPR_VSCSI_QUEUE_CMD_NO_DRIVE 0
#define TRACE_SPAPR_VSCSI_QUEUE_CMD_NO_DRIVE_ENABLED 0
#define TRACE_SPAPR_VSCSI_QUEUE_CMD_NO_DRIVE_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_queue_cmd_no_drive(uint64_t lun) {
    (void)lun;
}
#define TRACE_SPAPR_VSCSI_SAVE_REQUEST 0
#define TRACE_SPAPR_VSCSI_SAVE_REQUEST_ENABLED 0
#define TRACE_SPAPR_VSCSI_SAVE_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_save_request(uint32_t qtag, unsigned desc, unsigned offset) {
    (void)qtag;
    (void)desc;
    (void)offset;
}
#define TRACE_SPAPR_VSCSI_SEND_RSP 0
#define TRACE_SPAPR_VSCSI_SEND_RSP_ENABLED 0
#define TRACE_SPAPR_VSCSI_SEND_RSP_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_send_rsp(uint8_t status, int32_t res_in, int32_t res_out) {
    (void)status;
    (void)res_in;
    (void)res_out;
}
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA 0
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA_ENABLED 0
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_srp_indirect_data(uint32_t len) {
    (void)len;
}
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA_BUF 0
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA_BUF_ENABLED 0
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA_BUF_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_srp_indirect_data_buf(unsigned a, unsigned b, unsigned c, unsigned d) {
    (void)a;
    (void)b;
    (void)c;
    (void)d;
}
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA_RW 0
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA_RW_ENABLED 0
#define TRACE_SPAPR_VSCSI_SRP_INDIRECT_DATA_RW_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_srp_indirect_data_rw(int writing, int rc) {
    (void)writing;
    (void)rc;
}
#define TRACE_SPAPR_VSCSI_SRP_TRANSFER_DATA 0
#define TRACE_SPAPR_VSCSI_SRP_TRANSFER_DATA_ENABLED 0
#define TRACE_SPAPR_VSCSI_SRP_TRANSFER_DATA_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_srp_transfer_data(uint32_t len) {
    (void)len;
}
#define TRACE_SPAPR_VSCSI_TRANSFER_DATA 0
#define TRACE_SPAPR_VSCSI_TRANSFER_DATA_ENABLED 0
#define TRACE_SPAPR_VSCSI_TRANSFER_DATA_BACKEND_DSTATE() (0)
static inline void trace_spapr_vscsi_transfer_data(uint32_t tag, uint32_t len, void *req) {
    (void)tag;
    (void)len;
    (void)req;
}
#define TRACE_VIRTIO_SCSI_AN_REQ 0
#define TRACE_VIRTIO_SCSI_AN_REQ_ENABLED 0
#define TRACE_VIRTIO_SCSI_AN_REQ_BACKEND_DSTATE() (0)
static inline void trace_virtio_scsi_an_req(int lun, uint32_t event_requested) {
    (void)lun;
    (void)event_requested;
}
#define TRACE_VIRTIO_SCSI_AN_RESP 0
#define TRACE_VIRTIO_SCSI_AN_RESP_ENABLED 0
#define TRACE_VIRTIO_SCSI_AN_RESP_BACKEND_DSTATE() (0)
static inline void trace_virtio_scsi_an_resp(int lun, int response) {
    (void)lun;
    (void)response;
}
#define TRACE_VIRTIO_SCSI_CMD_REQ 0
#define TRACE_VIRTIO_SCSI_CMD_REQ_ENABLED 0
#define TRACE_VIRTIO_SCSI_CMD_REQ_BACKEND_DSTATE() (0)
static inline void trace_virtio_scsi_cmd_req(int lun, uint32_t tag, uint8_t cmd) {
    (void)lun;
    (void)tag;
    (void)cmd;
}
#define TRACE_VIRTIO_SCSI_CMD_RESP 0
#define TRACE_VIRTIO_SCSI_CMD_RESP_ENABLED 0
#define TRACE_VIRTIO_SCSI_CMD_RESP_BACKEND_DSTATE() (0)
static inline void trace_virtio_scsi_cmd_resp(int lun, uint32_t tag, int response, uint8_t status) {
    (void)lun;
    (void)tag;
    (void)response;
    (void)status;
}
#define TRACE_VIRTIO_SCSI_EVENT 0
#define TRACE_VIRTIO_SCSI_EVENT_ENABLED 0
#define TRACE_VIRTIO_SCSI_EVENT_BACKEND_DSTATE() (0)
static inline void trace_virtio_scsi_event(int lun, int event, int reason) {
    (void)lun;
    (void)event;
    (void)reason;
}
#define TRACE_VIRTIO_SCSI_TMF_REQ 0
#define TRACE_VIRTIO_SCSI_TMF_REQ_ENABLED 0
#define TRACE_VIRTIO_SCSI_TMF_REQ_BACKEND_DSTATE() (0)
static inline void trace_virtio_scsi_tmf_req(int lun, uint32_t tag, int subtype) {
    (void)lun;
    (void)tag;
    (void)subtype;
}
#define TRACE_VIRTIO_SCSI_TMF_RESP 0
#define TRACE_VIRTIO_SCSI_TMF_RESP_ENABLED 0
#define TRACE_VIRTIO_SCSI_TMF_RESP_BACKEND_DSTATE() (0)
static inline void trace_virtio_scsi_tmf_resp(int lun, uint32_t tag, int response) {
    (void)lun;
    (void)tag;
    (void)response;
}

#endif