/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_S390X_H
#define TRACE_TRACE_HW_S390X_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_CSS_ADAPTER_INTERRUPT 0
#define TRACE_CSS_ADAPTER_INTERRUPT_ENABLED 0
#define TRACE_CSS_ADAPTER_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_css_adapter_interrupt(uint8_t isc) {
    (void)isc;
}
#define TRACE_CSS_ASSIGN_SUBCH 0
#define TRACE_CSS_ASSIGN_SUBCH_ENABLED 0
#define TRACE_CSS_ASSIGN_SUBCH_BACKEND_DSTATE() (0)
static inline void trace_css_assign_subch(const char *do_assign, uint8_t cssid, uint8_t ssid, uint16_t schid, uint16_t devno) {
    (void)do_assign;
    (void)cssid;
    (void)ssid;
    (void)schid;
    (void)devno;
}
#define TRACE_CSS_CHPID_ADD 0
#define TRACE_CSS_CHPID_ADD_ENABLED 0
#define TRACE_CSS_CHPID_ADD_BACKEND_DSTATE() (0)
static inline void trace_css_chpid_add(uint8_t cssid, uint8_t chpid, uint8_t type) {
    (void)cssid;
    (void)chpid;
    (void)type;
}
#define TRACE_CSS_CRW 0
#define TRACE_CSS_CRW_ENABLED 0
#define TRACE_CSS_CRW_BACKEND_DSTATE() (0)
static inline void trace_css_crw(uint8_t rsc, uint8_t erc, uint16_t rsid, const char *chained) {
    (void)rsc;
    (void)erc;
    (void)rsid;
    (void)chained;
}
#define TRACE_CSS_DO_SIC 0
#define TRACE_CSS_DO_SIC_ENABLED 0
#define TRACE_CSS_DO_SIC_BACKEND_DSTATE() (0)
static inline void trace_css_do_sic(uint16_t mode, uint8_t isc) {
    (void)mode;
    (void)isc;
}
#define TRACE_CSS_ENABLE_FACILITY 0
#define TRACE_CSS_ENABLE_FACILITY_ENABLED 0
#define TRACE_CSS_ENABLE_FACILITY_BACKEND_DSTATE() (0)
static inline void trace_css_enable_facility(const char *facility) {
    (void)facility;
}
#define TRACE_CSS_IO_INTERRUPT 0
#define TRACE_CSS_IO_INTERRUPT_ENABLED 0
#define TRACE_CSS_IO_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_css_io_interrupt(int cssid, int ssid, int schid, uint32_t intparm, uint8_t isc, const char *conditional) {
    (void)cssid;
    (void)ssid;
    (void)schid;
    (void)intparm;
    (void)isc;
    (void)conditional;
}
#define TRACE_CSS_NEW_IMAGE 0
#define TRACE_CSS_NEW_IMAGE_ENABLED 0
#define TRACE_CSS_NEW_IMAGE_BACKEND_DSTATE() (0)
static inline void trace_css_new_image(uint8_t cssid, const char *default_cssid) {
    (void)cssid;
    (void)default_cssid;
}
#define TRACE_S390_PCI_BAR 0
#define TRACE_S390_PCI_BAR_ENABLED 0
#define TRACE_S390_PCI_BAR_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_bar(uint32_t bar, uint32_t addr, uint64_t size, uint32_t barsize) {
    (void)bar;
    (void)addr;
    (void)size;
    (void)barsize;
}
#define TRACE_S390_PCI_CLP_CAP 0
#define TRACE_S390_PCI_CLP_CAP_ENABLED 0
#define TRACE_S390_PCI_CLP_CAP_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_clp_cap(const char *id, uint32_t cap) {
    (void)id;
    (void)cap;
}
#define TRACE_S390_PCI_CLP_CAP_SIZE 0
#define TRACE_S390_PCI_CLP_CAP_SIZE_ENABLED 0
#define TRACE_S390_PCI_CLP_CAP_SIZE_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_clp_cap_size(const char *id, uint32_t size, uint32_t cap) {
    (void)id;
    (void)size;
    (void)cap;
}
#define TRACE_S390_PCI_CLP_DEV_INFO 0
#define TRACE_S390_PCI_CLP_DEV_INFO_ENABLED 0
#define TRACE_S390_PCI_CLP_DEV_INFO_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_clp_dev_info(const char *id) {
    (void)id;
}
#define TRACE_S390_PCI_INVALID 0
#define TRACE_S390_PCI_INVALID_ENABLED 0
#define TRACE_S390_PCI_INVALID_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_invalid(const char *cmd, uint32_t fh) {
    (void)cmd;
    (void)fh;
}
#define TRACE_S390_PCI_IOMMU_XLATE 0
#define TRACE_S390_PCI_IOMMU_XLATE_ENABLED 0
#define TRACE_S390_PCI_IOMMU_XLATE_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_iommu_xlate(uint64_t addr) {
    (void)addr;
}
#define TRACE_S390_PCI_IRQS 0
#define TRACE_S390_PCI_IRQS_ENABLED 0
#define TRACE_S390_PCI_IRQS_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_irqs(const char *str, uint32_t id) {
    (void)str;
    (void)id;
}
#define TRACE_S390_PCI_KVM_AIF 0
#define TRACE_S390_PCI_KVM_AIF_ENABLED 0
#define TRACE_S390_PCI_KVM_AIF_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_kvm_aif(const char *str) {
    (void)str;
}
#define TRACE_S390_PCI_LIST 0
#define TRACE_S390_PCI_LIST_ENABLED 0
#define TRACE_S390_PCI_LIST_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_list(uint32_t rc) {
    (void)rc;
}
#define TRACE_S390_PCI_LIST_ENTRY 0
#define TRACE_S390_PCI_LIST_ENTRY_ENABLED 0
#define TRACE_S390_PCI_LIST_ENTRY_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_list_entry(uint32_t g_l2, uint32_t vid, uint32_t did, uint32_t fid, uint32_t fh) {
    (void)g_l2;
    (void)vid;
    (void)did;
    (void)fid;
    (void)fh;
}
#define TRACE_S390_PCI_MSI_CTRL_WRITE 0
#define TRACE_S390_PCI_MSI_CTRL_WRITE_ENABLED 0
#define TRACE_S390_PCI_MSI_CTRL_WRITE_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_msi_ctrl_write(uint64_t data, uint32_t idx, uint32_t vec) {
    (void)data;
    (void)idx;
    (void)vec;
}
#define TRACE_S390_PCI_NODEV 0
#define TRACE_S390_PCI_NODEV_ENABLED 0
#define TRACE_S390_PCI_NODEV_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_nodev(const char *cmd, uint32_t fh) {
    (void)cmd;
    (void)fh;
}
#define TRACE_S390_PCI_SCLP_NODEV 0
#define TRACE_S390_PCI_SCLP_NODEV_ENABLED 0
#define TRACE_S390_PCI_SCLP_NODEV_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_sclp_nodev(const char *str, uint32_t aid) {
    (void)str;
    (void)aid;
}
#define TRACE_S390_PCI_UNKNOWN 0
#define TRACE_S390_PCI_UNKNOWN_ENABLED 0
#define TRACE_S390_PCI_UNKNOWN_BACKEND_DSTATE() (0)
static inline void trace_s390_pci_unknown(const char *msg, uint32_t cmd) {
    (void)msg;
    (void)cmd;
}
#define TRACE_S390_PCIHOST 0
#define TRACE_S390_PCIHOST_ENABLED 0
#define TRACE_S390_PCIHOST_BACKEND_DSTATE() (0)
static inline void trace_s390_pcihost(const char *msg) {
    (void)msg;
}
#define TRACE_S390_SKEYS_GET_NONZERO 0
#define TRACE_S390_SKEYS_GET_NONZERO_ENABLED 0
#define TRACE_S390_SKEYS_GET_NONZERO_BACKEND_DSTATE() (0)
static inline void trace_s390_skeys_get_nonzero(int rc) {
    (void)rc;
}
#define TRACE_S390_SKEYS_SET_NONZERO 0
#define TRACE_S390_SKEYS_SET_NONZERO_ENABLED 0
#define TRACE_S390_SKEYS_SET_NONZERO_BACKEND_DSTATE() (0)
static inline void trace_s390_skeys_set_nonzero(int rc) {
    (void)rc;
}
#define TRACE_VIRTIO_CCW_INTERPRET_CCW 0
#define TRACE_VIRTIO_CCW_INTERPRET_CCW_ENABLED 0
#define TRACE_VIRTIO_CCW_INTERPRET_CCW_BACKEND_DSTATE() (0)
static inline void trace_virtio_ccw_interpret_ccw(int cssid, int ssid, int schid, int cmd_code) {
    (void)cssid;
    (void)ssid;
    (void)schid;
    (void)cmd_code;
}
#define TRACE_VIRTIO_CCW_NEW_DEVICE 0
#define TRACE_VIRTIO_CCW_NEW_DEVICE_ENABLED 0
#define TRACE_VIRTIO_CCW_NEW_DEVICE_BACKEND_DSTATE() (0)
static inline void trace_virtio_ccw_new_device(int cssid, int ssid, int schid, int devno, const char *devno_mode) {
    (void)cssid;
    (void)ssid;
    (void)schid;
    (void)devno;
    (void)devno_mode;
}
#define TRACE_VIRTIO_CCW_SET_IND 0
#define TRACE_VIRTIO_CCW_SET_IND_ENABLED 0
#define TRACE_VIRTIO_CCW_SET_IND_BACKEND_DSTATE() (0)
static inline void trace_virtio_ccw_set_ind(uint64_t ind_loc, uint8_t ind_old, uint8_t ind_new) {
    (void)ind_loc;
    (void)ind_old;
    (void)ind_new;
}

#endif