/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_WATCHDOG_H
#define TRACE_TRACE_HW_WATCHDOG_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_ALLWINNER_WDT_EXPIRED 0
#define TRACE_ALLWINNER_WDT_EXPIRED_ENABLED 0
#define TRACE_ALLWINNER_WDT_EXPIRED_BACKEND_DSTATE() (0)
static inline void trace_allwinner_wdt_expired(bool enabled, bool reset_enabled) {
    (void)enabled;
    (void)reset_enabled;
}
#define TRACE_ALLWINNER_WDT_READ 0
#define TRACE_ALLWINNER_WDT_READ_ENABLED 0
#define TRACE_ALLWINNER_WDT_READ_BACKEND_DSTATE() (0)
static inline void trace_allwinner_wdt_read(uint64_t offset, uint64_t data, unsigned size) {
    (void)offset;
    (void)data;
    (void)size;
}
#define TRACE_ALLWINNER_WDT_RESET_ENTER 0
#define TRACE_ALLWINNER_WDT_RESET_ENTER_ENABLED 0
#define TRACE_ALLWINNER_WDT_RESET_ENTER_BACKEND_DSTATE() (0)
static inline void trace_allwinner_wdt_reset_enter(void) {
}
#define TRACE_ALLWINNER_WDT_UPDATE_TIMER 0
#define TRACE_ALLWINNER_WDT_UPDATE_TIMER_ENABLED 0
#define TRACE_ALLWINNER_WDT_UPDATE_TIMER_BACKEND_DSTATE() (0)
static inline void trace_allwinner_wdt_update_timer(uint8_t count) {
    (void)count;
}
#define TRACE_ALLWINNER_WDT_WRITE 0
#define TRACE_ALLWINNER_WDT_WRITE_ENABLED 0
#define TRACE_ALLWINNER_WDT_WRITE_BACKEND_DSTATE() (0)
static inline void trace_allwinner_wdt_write(uint64_t offset, uint64_t data, unsigned size) {
    (void)offset;
    (void)data;
    (void)size;
}
#define TRACE_ASPEED_WDT_READ 0
#define TRACE_ASPEED_WDT_READ_ENABLED 0
#define TRACE_ASPEED_WDT_READ_BACKEND_DSTATE() (0)
static inline void trace_aspeed_wdt_read(uint64_t addr, uint32_t size) {
    (void)addr;
    (void)size;
}
#define TRACE_ASPEED_WDT_WRITE 0
#define TRACE_ASPEED_WDT_WRITE_ENABLED 0
#define TRACE_ASPEED_WDT_WRITE_BACKEND_DSTATE() (0)
static inline void trace_aspeed_wdt_write(uint64_t addr, uint32_t size, uint64_t data) {
    (void)addr;
    (void)size;
    (void)data;
}
#define TRACE_CMSDK_APB_WATCHDOG_LOCK 0
#define TRACE_CMSDK_APB_WATCHDOG_LOCK_ENABLED 0
#define TRACE_CMSDK_APB_WATCHDOG_LOCK_BACKEND_DSTATE() (0)
static inline void trace_cmsdk_apb_watchdog_lock(uint32_t lock) {
    (void)lock;
}
#define TRACE_CMSDK_APB_WATCHDOG_READ 0
#define TRACE_CMSDK_APB_WATCHDOG_READ_ENABLED 0
#define TRACE_CMSDK_APB_WATCHDOG_READ_BACKEND_DSTATE() (0)
static inline void trace_cmsdk_apb_watchdog_read(uint64_t offset, uint64_t data, unsigned size) {
    (void)offset;
    (void)data;
    (void)size;
}
#define TRACE_CMSDK_APB_WATCHDOG_RESET 0
#define TRACE_CMSDK_APB_WATCHDOG_RESET_ENABLED 0
#define TRACE_CMSDK_APB_WATCHDOG_RESET_BACKEND_DSTATE() (0)
static inline void trace_cmsdk_apb_watchdog_reset(void) {
}
#define TRACE_CMSDK_APB_WATCHDOG_WRITE 0
#define TRACE_CMSDK_APB_WATCHDOG_WRITE_ENABLED 0
#define TRACE_CMSDK_APB_WATCHDOG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_cmsdk_apb_watchdog_write(uint64_t offset, uint64_t data, unsigned size) {
    (void)offset;
    (void)data;
    (void)size;
}
#define TRACE_IMX2_WDT_EXPIRED 0
#define TRACE_IMX2_WDT_EXPIRED_ENABLED 0
#define TRACE_IMX2_WDT_EXPIRED_BACKEND_DSTATE() (0)
static inline void trace_imx2_wdt_expired(void) {
}
#define TRACE_IMX2_WDT_INTERRUPT 0
#define TRACE_IMX2_WDT_INTERRUPT_ENABLED 0
#define TRACE_IMX2_WDT_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_imx2_wdt_interrupt(void) {
}
#define TRACE_IMX2_WDT_READ 0
#define TRACE_IMX2_WDT_READ_ENABLED 0
#define TRACE_IMX2_WDT_READ_BACKEND_DSTATE() (0)
static inline void trace_imx2_wdt_read(uint32_t addr, uint16_t data) {
    (void)addr;
    (void)data;
}
#define TRACE_IMX2_WDT_WRITE 0
#define TRACE_IMX2_WDT_WRITE_ENABLED 0
#define TRACE_IMX2_WDT_WRITE_BACKEND_DSTATE() (0)
static inline void trace_imx2_wdt_write(uint32_t addr, uint16_t data) {
    (void)addr;
    (void)data;
}
#define TRACE_SPAPR_WATCHDOG_EXPIRED 0
#define TRACE_SPAPR_WATCHDOG_EXPIRED_ENABLED 0
#define TRACE_SPAPR_WATCHDOG_EXPIRED_BACKEND_DSTATE() (0)
static inline void trace_spapr_watchdog_expired(uint64_t num, unsigned action) {
    (void)num;
    (void)action;
}
#define TRACE_SPAPR_WATCHDOG_QUERY 0
#define TRACE_SPAPR_WATCHDOG_QUERY_ENABLED 0
#define TRACE_SPAPR_WATCHDOG_QUERY_BACKEND_DSTATE() (0)
static inline void trace_spapr_watchdog_query(uint64_t caps) {
    (void)caps;
}
#define TRACE_SPAPR_WATCHDOG_QUERY_LPM 0
#define TRACE_SPAPR_WATCHDOG_QUERY_LPM_ENABLED 0
#define TRACE_SPAPR_WATCHDOG_QUERY_LPM_BACKEND_DSTATE() (0)
static inline void trace_spapr_watchdog_query_lpm(uint64_t caps) {
    (void)caps;
}
#define TRACE_SPAPR_WATCHDOG_START 0
#define TRACE_SPAPR_WATCHDOG_START_ENABLED 0
#define TRACE_SPAPR_WATCHDOG_START_BACKEND_DSTATE() (0)
static inline void trace_spapr_watchdog_start(uint64_t flags, uint64_t num, uint64_t timeout) {
    (void)flags;
    (void)num;
    (void)timeout;
}
#define TRACE_SPAPR_WATCHDOG_STOP 0
#define TRACE_SPAPR_WATCHDOG_STOP_ENABLED 0
#define TRACE_SPAPR_WATCHDOG_STOP_BACKEND_DSTATE() (0)
static inline void trace_spapr_watchdog_stop(uint64_t num, uint64_t ret) {
    (void)num;
    (void)ret;
}
#define TRACE_WATCHDOG_PERFORM_ACTION 0
#define TRACE_WATCHDOG_PERFORM_ACTION_ENABLED 0
#define TRACE_WATCHDOG_PERFORM_ACTION_BACKEND_DSTATE() (0)
static inline void trace_watchdog_perform_action(unsigned int action) {
    (void)action;
}
#define TRACE_WATCHDOG_SET_ACTION 0
#define TRACE_WATCHDOG_SET_ACTION_ENABLED 0
#define TRACE_WATCHDOG_SET_ACTION_BACKEND_DSTATE() (0)
static inline void trace_watchdog_set_action(unsigned int action) {
    (void)action;
}

#endif