/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_RISCV_H
#define TRACE_TRACE_HW_RISCV_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_RISCV_IOMMU_ATS 0
#define TRACE_RISCV_IOMMU_ATS_ENABLED 0
#define TRACE_RISCV_IOMMU_ATS_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_ats(const char *id, unsigned b, unsigned d, unsigned f, uint64_t iova) {
    (void)id;
    (void)b;
    (void)d;
    (void)f;
    (void)iova;
}
#define TRACE_RISCV_IOMMU_ATS_INVAL 0
#define TRACE_RISCV_IOMMU_ATS_INVAL_ENABLED 0
#define TRACE_RISCV_IOMMU_ATS_INVAL_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_ats_inval(const char *id) {
    (void)id;
}
#define TRACE_RISCV_IOMMU_ATS_PRGR 0
#define TRACE_RISCV_IOMMU_ATS_PRGR_ENABLED 0
#define TRACE_RISCV_IOMMU_ATS_PRGR_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_ats_prgr(const char *id) {
    (void)id;
}
#define TRACE_RISCV_IOMMU_CMD 0
#define TRACE_RISCV_IOMMU_CMD_ENABLED 0
#define TRACE_RISCV_IOMMU_CMD_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_cmd(const char *id, uint64_t l, uint64_t u) {
    (void)id;
    (void)l;
    (void)u;
}
#define TRACE_RISCV_IOMMU_DMA 0
#define TRACE_RISCV_IOMMU_DMA_ENABLED 0
#define TRACE_RISCV_IOMMU_DMA_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_dma(const char *id, unsigned b, unsigned d, unsigned f, unsigned pasid, const char *dir, uint64_t iova, uint64_t phys) {
    (void)id;
    (void)b;
    (void)d;
    (void)f;
    (void)pasid;
    (void)dir;
    (void)iova;
    (void)phys;
}
#define TRACE_RISCV_IOMMU_FLT 0
#define TRACE_RISCV_IOMMU_FLT_ENABLED 0
#define TRACE_RISCV_IOMMU_FLT_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_flt(const char *id, unsigned b, unsigned d, unsigned f, uint64_t reason, uint64_t iova) {
    (void)id;
    (void)b;
    (void)d;
    (void)f;
    (void)reason;
    (void)iova;
}
#define TRACE_RISCV_IOMMU_HPM_CYCLE_WRITE 0
#define TRACE_RISCV_IOMMU_HPM_CYCLE_WRITE_ENABLED 0
#define TRACE_RISCV_IOMMU_HPM_CYCLE_WRITE_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_hpm_cycle_write(uint32_t ovf, uint64_t val) {
    (void)ovf;
    (void)val;
}
#define TRACE_RISCV_IOMMU_HPM_EVT_WRITE 0
#define TRACE_RISCV_IOMMU_HPM_EVT_WRITE_ENABLED 0
#define TRACE_RISCV_IOMMU_HPM_EVT_WRITE_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_hpm_evt_write(uint32_t ctr_idx, uint32_t ovf, uint64_t val) {
    (void)ctr_idx;
    (void)ovf;
    (void)val;
}
#define TRACE_RISCV_IOMMU_HPM_INCR_CTR 0
#define TRACE_RISCV_IOMMU_HPM_INCR_CTR_ENABLED 0
#define TRACE_RISCV_IOMMU_HPM_INCR_CTR_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_hpm_incr_ctr(uint64_t cntr_val) {
    (void)cntr_val;
}
#define TRACE_RISCV_IOMMU_HPM_IOCNTINH_CY 0
#define TRACE_RISCV_IOMMU_HPM_IOCNTINH_CY_ENABLED 0
#define TRACE_RISCV_IOMMU_HPM_IOCNTINH_CY_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_hpm_iocntinh_cy(bool prev_cy_inh) {
    (void)prev_cy_inh;
}
#define TRACE_RISCV_IOMMU_HPM_READ 0
#define TRACE_RISCV_IOMMU_HPM_READ_ENABLED 0
#define TRACE_RISCV_IOMMU_HPM_READ_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_hpm_read(uint64_t cycle, uint32_t inhibit, uint64_t ctr_prev, uint64_t ctr_val) {
    (void)cycle;
    (void)inhibit;
    (void)ctr_prev;
    (void)ctr_val;
}
#define TRACE_RISCV_IOMMU_ICVEC_WRITE 0
#define TRACE_RISCV_IOMMU_ICVEC_WRITE_ENABLED 0
#define TRACE_RISCV_IOMMU_ICVEC_WRITE_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_icvec_write(uint32_t orig, uint32_t actual) {
    (void)orig;
    (void)actual;
}
#define TRACE_RISCV_IOMMU_MRIF_NOTIFICATION 0
#define TRACE_RISCV_IOMMU_MRIF_NOTIFICATION_ENABLED 0
#define TRACE_RISCV_IOMMU_MRIF_NOTIFICATION_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_mrif_notification(const char *id, uint32_t nid, uint64_t phys) {
    (void)id;
    (void)nid;
    (void)phys;
}
#define TRACE_RISCV_IOMMU_MSI 0
#define TRACE_RISCV_IOMMU_MSI_ENABLED 0
#define TRACE_RISCV_IOMMU_MSI_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_msi(const char *id, unsigned b, unsigned d, unsigned f, uint64_t iova, uint64_t phys) {
    (void)id;
    (void)b;
    (void)d;
    (void)f;
    (void)iova;
    (void)phys;
}
#define TRACE_RISCV_IOMMU_NEW 0
#define TRACE_RISCV_IOMMU_NEW_ENABLED 0
#define TRACE_RISCV_IOMMU_NEW_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_new(const char *id, unsigned b, unsigned d, unsigned f) {
    (void)id;
    (void)b;
    (void)d;
    (void)f;
}
#define TRACE_RISCV_IOMMU_NOTIFIER_ADD 0
#define TRACE_RISCV_IOMMU_NOTIFIER_ADD_ENABLED 0
#define TRACE_RISCV_IOMMU_NOTIFIER_ADD_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_notifier_add(const char *id) {
    (void)id;
}
#define TRACE_RISCV_IOMMU_NOTIFIER_DEL 0
#define TRACE_RISCV_IOMMU_NOTIFIER_DEL_ENABLED 0
#define TRACE_RISCV_IOMMU_NOTIFIER_DEL_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_notifier_del(const char *id) {
    (void)id;
}
#define TRACE_RISCV_IOMMU_NOTIFY_INT_VECTOR 0
#define TRACE_RISCV_IOMMU_NOTIFY_INT_VECTOR_ENABLED 0
#define TRACE_RISCV_IOMMU_NOTIFY_INT_VECTOR_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_notify_int_vector(uint32_t cause, uint32_t vector) {
    (void)cause;
    (void)vector;
}
#define TRACE_RISCV_IOMMU_PCI_RESET_HOLD 0
#define TRACE_RISCV_IOMMU_PCI_RESET_HOLD_ENABLED 0
#define TRACE_RISCV_IOMMU_PCI_RESET_HOLD_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_pci_reset_hold(int reset_type) {
    (void)reset_type;
}
#define TRACE_RISCV_IOMMU_PRI 0
#define TRACE_RISCV_IOMMU_PRI_ENABLED 0
#define TRACE_RISCV_IOMMU_PRI_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_pri(const char *id, unsigned b, unsigned d, unsigned f, uint64_t iova) {
    (void)id;
    (void)b;
    (void)d;
    (void)f;
    (void)iova;
}
#define TRACE_RISCV_IOMMU_SYS_IRQ_SENT 0
#define TRACE_RISCV_IOMMU_SYS_IRQ_SENT_ENABLED 0
#define TRACE_RISCV_IOMMU_SYS_IRQ_SENT_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_sys_irq_sent(uint32_t vector) {
    (void)vector;
}
#define TRACE_RISCV_IOMMU_SYS_MSI_SENT 0
#define TRACE_RISCV_IOMMU_SYS_MSI_SENT_ENABLED 0
#define TRACE_RISCV_IOMMU_SYS_MSI_SENT_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_sys_msi_sent(uint32_t vector, uint64_t msi_addr, uint32_t msi_data, uint32_t result) {
    (void)vector;
    (void)msi_addr;
    (void)msi_data;
    (void)result;
}
#define TRACE_RISCV_IOMMU_SYS_RESET_HOLD 0
#define TRACE_RISCV_IOMMU_SYS_RESET_HOLD_ENABLED 0
#define TRACE_RISCV_IOMMU_SYS_RESET_HOLD_BACKEND_DSTATE() (0)
static inline void trace_riscv_iommu_sys_reset_hold(int reset_type) {
    (void)reset_type;
}

#endif