/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_QOM_H
#define TRACE_TRACE_QOM_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_OBJECT_CLASS_DYNAMIC_CAST_ASSERT 0
#define TRACE_OBJECT_CLASS_DYNAMIC_CAST_ASSERT_ENABLED 0
#define TRACE_OBJECT_CLASS_DYNAMIC_CAST_ASSERT_BACKEND_DSTATE() (0)
static inline void trace_object_class_dynamic_cast_assert(const char *type, const char *target, const char *file, int line, const char *func) {
    (void)type;
    (void)target;
    (void)file;
    (void)line;
    (void)func;
}
#define TRACE_OBJECT_DYNAMIC_CAST_ASSERT 0
#define TRACE_OBJECT_DYNAMIC_CAST_ASSERT_ENABLED 0
#define TRACE_OBJECT_DYNAMIC_CAST_ASSERT_BACKEND_DSTATE() (0)
static inline void trace_object_dynamic_cast_assert(const char *type, const char *target, const char *file, int line, const char *func) {
    (void)type;
    (void)target;
    (void)file;
    (void)line;
    (void)func;
}

#endif