/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_AUDIO_H
#define TRACE_TRACE_HW_AUDIO_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_ASC_FIFO_GET 0
#define TRACE_ASC_FIFO_GET_ENABLED 0
#define TRACE_ASC_FIFO_GET_BACKEND_DSTATE() (0)
static inline void trace_asc_fifo_get(const char fifo, int rptr, int cnt, uint64_t value) {
    (void)fifo;
    (void)rptr;
    (void)cnt;
    (void)value;
}
#define TRACE_ASC_READ_EXTREG 0
#define TRACE_ASC_READ_EXTREG_ENABLED 0
#define TRACE_ASC_READ_EXTREG_BACKEND_DSTATE() (0)
static inline void trace_asc_read_extreg(const char fifo, int reg, unsigned size, uint64_t value) {
    (void)fifo;
    (void)reg;
    (void)size;
    (void)value;
}
#define TRACE_ASC_READ_FIFO 0
#define TRACE_ASC_READ_FIFO_ENABLED 0
#define TRACE_ASC_READ_FIFO_BACKEND_DSTATE() (0)
static inline void trace_asc_read_fifo(const char fifo, int reg, unsigned size, uint64_t value) {
    (void)fifo;
    (void)reg;
    (void)size;
    (void)value;
}
#define TRACE_ASC_READ_REG 0
#define TRACE_ASC_READ_REG_ENABLED 0
#define TRACE_ASC_READ_REG_BACKEND_DSTATE() (0)
static inline void trace_asc_read_reg(int reg, unsigned size, uint64_t value) {
    (void)reg;
    (void)size;
    (void)value;
}
#define TRACE_ASC_UPDATE_IRQ 0
#define TRACE_ASC_UPDATE_IRQ_ENABLED 0
#define TRACE_ASC_UPDATE_IRQ_BACKEND_DSTATE() (0)
static inline void trace_asc_update_irq(int irq, int a, int b) {
    (void)irq;
    (void)a;
    (void)b;
}
#define TRACE_ASC_WRITE_EXTREG 0
#define TRACE_ASC_WRITE_EXTREG_ENABLED 0
#define TRACE_ASC_WRITE_EXTREG_BACKEND_DSTATE() (0)
static inline void trace_asc_write_extreg(const char fifo, int reg, unsigned size, uint64_t value) {
    (void)fifo;
    (void)reg;
    (void)size;
    (void)value;
}
#define TRACE_ASC_WRITE_FIFO 0
#define TRACE_ASC_WRITE_FIFO_ENABLED 0
#define TRACE_ASC_WRITE_FIFO_BACKEND_DSTATE() (0)
static inline void trace_asc_write_fifo(const char fifo, int reg, unsigned size, int wrptr, int cnt, uint64_t value) {
    (void)fifo;
    (void)reg;
    (void)size;
    (void)wrptr;
    (void)cnt;
    (void)value;
}
#define TRACE_ASC_WRITE_REG 0
#define TRACE_ASC_WRITE_REG_ENABLED 0
#define TRACE_ASC_WRITE_REG_BACKEND_DSTATE() (0)
static inline void trace_asc_write_reg(int reg, unsigned size, uint64_t value) {
    (void)reg;
    (void)size;
    (void)value;
}
#define TRACE_CS4231_MEM_READL_DREG 0
#define TRACE_CS4231_MEM_READL_DREG_ENABLED 0
#define TRACE_CS4231_MEM_READL_DREG_BACKEND_DSTATE() (0)
static inline void trace_cs4231_mem_readl_dreg(uint32_t reg, uint32_t ret) {
    (void)reg;
    (void)ret;
}
#define TRACE_CS4231_MEM_READL_REG 0
#define TRACE_CS4231_MEM_READL_REG_ENABLED 0
#define TRACE_CS4231_MEM_READL_REG_BACKEND_DSTATE() (0)
static inline void trace_cs4231_mem_readl_reg(uint32_t reg, uint32_t ret) {
    (void)reg;
    (void)ret;
}
#define TRACE_CS4231_MEM_WRITEL_DREG 0
#define TRACE_CS4231_MEM_WRITEL_DREG_ENABLED 0
#define TRACE_CS4231_MEM_WRITEL_DREG_BACKEND_DSTATE() (0)
static inline void trace_cs4231_mem_writel_dreg(uint32_t reg, uint32_t old, uint32_t val) {
    (void)reg;
    (void)old;
    (void)val;
}
#define TRACE_CS4231_MEM_WRITEL_REG 0
#define TRACE_CS4231_MEM_WRITEL_REG_ENABLED 0
#define TRACE_CS4231_MEM_WRITEL_REG_BACKEND_DSTATE() (0)
static inline void trace_cs4231_mem_writel_reg(uint32_t reg, uint32_t old, uint32_t val) {
    (void)reg;
    (void)old;
    (void)val;
}
#define TRACE_ES1370_FRAME_ADDRESS_RD 0
#define TRACE_ES1370_FRAME_ADDRESS_RD_ENABLED 0
#define TRACE_ES1370_FRAME_ADDRESS_RD_BACKEND_DSTATE() (0)
static inline void trace_es1370_frame_address_rd(int ch, uint32_t addr) {
    (void)ch;
    (void)addr;
}
#define TRACE_ES1370_FRAME_ADDRESS_WR 0
#define TRACE_ES1370_FRAME_ADDRESS_WR_ENABLED 0
#define TRACE_ES1370_FRAME_ADDRESS_WR_BACKEND_DSTATE() (0)
static inline void trace_es1370_frame_address_wr(int ch, uint32_t addr) {
    (void)ch;
    (void)addr;
}
#define TRACE_ES1370_FRAME_COUNT_RD 0
#define TRACE_ES1370_FRAME_COUNT_RD_ENABLED 0
#define TRACE_ES1370_FRAME_COUNT_RD_BACKEND_DSTATE() (0)
static inline void trace_es1370_frame_count_rd(int ch, uint32_t curr, uint32_t size) {
    (void)ch;
    (void)curr;
    (void)size;
}
#define TRACE_ES1370_FRAME_COUNT_WR 0
#define TRACE_ES1370_FRAME_COUNT_WR_ENABLED 0
#define TRACE_ES1370_FRAME_COUNT_WR_BACKEND_DSTATE() (0)
static inline void trace_es1370_frame_count_wr(int ch, uint32_t curr, uint32_t size) {
    (void)ch;
    (void)curr;
    (void)size;
}
#define TRACE_ES1370_LOST_INTERRUPT 0
#define TRACE_ES1370_LOST_INTERRUPT_ENABLED 0
#define TRACE_ES1370_LOST_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_es1370_lost_interrupt(int ch) {
    (void)ch;
}
#define TRACE_ES1370_SAMPLE_COUNT_RD 0
#define TRACE_ES1370_SAMPLE_COUNT_RD_ENABLED 0
#define TRACE_ES1370_SAMPLE_COUNT_RD_BACKEND_DSTATE() (0)
static inline void trace_es1370_sample_count_rd(int ch, uint32_t curr, uint32_t num) {
    (void)ch;
    (void)curr;
    (void)num;
}
#define TRACE_ES1370_SAMPLE_COUNT_WR 0
#define TRACE_ES1370_SAMPLE_COUNT_WR_ENABLED 0
#define TRACE_ES1370_SAMPLE_COUNT_WR_BACKEND_DSTATE() (0)
static inline void trace_es1370_sample_count_wr(int ch, uint32_t curr, uint32_t num) {
    (void)ch;
    (void)curr;
    (void)num;
}
#define TRACE_ES1370_STREAM_FORMAT 0
#define TRACE_ES1370_STREAM_FORMAT_ENABLED 0
#define TRACE_ES1370_STREAM_FORMAT_BACKEND_DSTATE() (0)
static inline void trace_es1370_stream_format(int ch, uint32_t freq, const char *fmt, const char *mode, uint32_t shift) {
    (void)ch;
    (void)freq;
    (void)fmt;
    (void)mode;
    (void)shift;
}
#define TRACE_ES1370_TRANSFER_AUDIO 0
#define TRACE_ES1370_TRANSFER_AUDIO_ENABLED 0
#define TRACE_ES1370_TRANSFER_AUDIO_BACKEND_DSTATE() (0)
static inline void trace_es1370_transfer_audio(int ch, uint32_t f_curr, uint32_t f_size, uint32_t s_curr, uint32_t s_num, uint32_t leftover, bool irq) {
    (void)ch;
    (void)f_curr;
    (void)f_size;
    (void)s_curr;
    (void)s_num;
    (void)leftover;
    (void)irq;
}
#define TRACE_HDA_AUDIO_ADJUST 0
#define TRACE_HDA_AUDIO_ADJUST_ENABLED 0
#define TRACE_HDA_AUDIO_ADJUST_BACKEND_DSTATE() (0)
static inline void trace_hda_audio_adjust(const char *stream, int pos) {
    (void)stream;
    (void)pos;
}
#define TRACE_HDA_AUDIO_FORMAT 0
#define TRACE_HDA_AUDIO_FORMAT_ENABLED 0
#define TRACE_HDA_AUDIO_FORMAT_BACKEND_DSTATE() (0)
static inline void trace_hda_audio_format(const char *stream, int chan, const char *fmt, int freq) {
    (void)stream;
    (void)chan;
    (void)fmt;
    (void)freq;
}
#define TRACE_HDA_AUDIO_OVERRUN 0
#define TRACE_HDA_AUDIO_OVERRUN_ENABLED 0
#define TRACE_HDA_AUDIO_OVERRUN_BACKEND_DSTATE() (0)
static inline void trace_hda_audio_overrun(const char *stream) {
    (void)stream;
}
#define TRACE_HDA_AUDIO_RUNNING 0
#define TRACE_HDA_AUDIO_RUNNING_ENABLED 0
#define TRACE_HDA_AUDIO_RUNNING_BACKEND_DSTATE() (0)
static inline void trace_hda_audio_running(const char *stream, int nr, bool running) {
    (void)stream;
    (void)nr;
    (void)running;
}
#define TRACE_PCSPK_IO_READ 0
#define TRACE_PCSPK_IO_READ_ENABLED 0
#define TRACE_PCSPK_IO_READ_BACKEND_DSTATE() (0)
static inline void trace_pcspk_io_read(uint16_t addr, uint8_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_PCSPK_IO_WRITE 0
#define TRACE_PCSPK_IO_WRITE_ENABLED 0
#define TRACE_PCSPK_IO_WRITE_BACKEND_DSTATE() (0)
static inline void trace_pcspk_io_write(uint16_t addr, uint8_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_VIA_AC97_CODEC_WRITE 0
#define TRACE_VIA_AC97_CODEC_WRITE_ENABLED 0
#define TRACE_VIA_AC97_CODEC_WRITE_BACKEND_DSTATE() (0)
static inline void trace_via_ac97_codec_write(uint8_t addr, uint16_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_VIA_AC97_SGD_FETCH 0
#define TRACE_VIA_AC97_SGD_FETCH_ENABLED 0
#define TRACE_VIA_AC97_SGD_FETCH_BACKEND_DSTATE() (0)
static inline void trace_via_ac97_sgd_fetch(uint32_t curr, uint32_t addr, char stop, char eol, char flag, uint32_t len) {
    (void)curr;
    (void)addr;
    (void)stop;
    (void)eol;
    (void)flag;
    (void)len;
}
#define TRACE_VIA_AC97_SGD_READ 0
#define TRACE_VIA_AC97_SGD_READ_ENABLED 0
#define TRACE_VIA_AC97_SGD_READ_BACKEND_DSTATE() (0)
static inline void trace_via_ac97_sgd_read(uint64_t addr, unsigned size, uint64_t val) {
    (void)addr;
    (void)size;
    (void)val;
}
#define TRACE_VIA_AC97_SGD_WRITE 0
#define TRACE_VIA_AC97_SGD_WRITE_ENABLED 0
#define TRACE_VIA_AC97_SGD_WRITE_BACKEND_DSTATE() (0)
static inline void trace_via_ac97_sgd_write(uint64_t addr, unsigned size, uint64_t val) {
    (void)addr;
    (void)size;
    (void)val;
}
#define TRACE_VIRTIO_SND_GET_CONFIG 0
#define TRACE_VIRTIO_SND_GET_CONFIG_ENABLED 0
#define TRACE_VIRTIO_SND_GET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_get_config(void *vdev, uint32_t jacks, uint32_t streams, uint32_t chmaps) {
    (void)vdev;
    (void)jacks;
    (void)streams;
    (void)chmaps;
}
#define TRACE_VIRTIO_SND_GET_FEATURES 0
#define TRACE_VIRTIO_SND_GET_FEATURES_ENABLED 0
#define TRACE_VIRTIO_SND_GET_FEATURES_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_get_features(void *vdev, uint64_t features) {
    (void)vdev;
    (void)features;
}
#define TRACE_VIRTIO_SND_HANDLE_CHMAP_INFO 0
#define TRACE_VIRTIO_SND_HANDLE_CHMAP_INFO_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_CHMAP_INFO_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_chmap_info(void) {
}
#define TRACE_VIRTIO_SND_HANDLE_CODE 0
#define TRACE_VIRTIO_SND_HANDLE_CODE_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_CODE_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_code(uint32_t val, const char *code) {
    (void)val;
    (void)code;
}
#define TRACE_VIRTIO_SND_HANDLE_CTRL 0
#define TRACE_VIRTIO_SND_HANDLE_CTRL_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_CTRL_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_ctrl(void *vdev, void *vq) {
    (void)vdev;
    (void)vq;
}
#define TRACE_VIRTIO_SND_HANDLE_EVENT 0
#define TRACE_VIRTIO_SND_HANDLE_EVENT_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_EVENT_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_event(void) {
}
#define TRACE_VIRTIO_SND_HANDLE_PCM_INFO 0
#define TRACE_VIRTIO_SND_HANDLE_PCM_INFO_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_PCM_INFO_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_pcm_info(uint32_t stream) {
    (void)stream;
}
#define TRACE_VIRTIO_SND_HANDLE_PCM_RELEASE 0
#define TRACE_VIRTIO_SND_HANDLE_PCM_RELEASE_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_PCM_RELEASE_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_pcm_release(uint32_t stream) {
    (void)stream;
}
#define TRACE_VIRTIO_SND_HANDLE_PCM_SET_PARAMS 0
#define TRACE_VIRTIO_SND_HANDLE_PCM_SET_PARAMS_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_PCM_SET_PARAMS_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_pcm_set_params(uint32_t stream) {
    (void)stream;
}
#define TRACE_VIRTIO_SND_HANDLE_PCM_START_STOP 0
#define TRACE_VIRTIO_SND_HANDLE_PCM_START_STOP_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_PCM_START_STOP_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_pcm_start_stop(const char *code, uint32_t stream) {
    (void)code;
    (void)stream;
}
#define TRACE_VIRTIO_SND_HANDLE_RX_XFER 0
#define TRACE_VIRTIO_SND_HANDLE_RX_XFER_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_RX_XFER_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_rx_xfer(void) {
}
#define TRACE_VIRTIO_SND_HANDLE_TX_XFER 0
#define TRACE_VIRTIO_SND_HANDLE_TX_XFER_ENABLED 0
#define TRACE_VIRTIO_SND_HANDLE_TX_XFER_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_handle_tx_xfer(void) {
}
#define TRACE_VIRTIO_SND_PCM_STREAM_FLUSH 0
#define TRACE_VIRTIO_SND_PCM_STREAM_FLUSH_ENABLED 0
#define TRACE_VIRTIO_SND_PCM_STREAM_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_pcm_stream_flush(uint32_t stream) {
    (void)stream;
}
#define TRACE_VIRTIO_SND_REALIZE 0
#define TRACE_VIRTIO_SND_REALIZE_ENABLED 0
#define TRACE_VIRTIO_SND_REALIZE_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_realize(void *snd) {
    (void)snd;
}
#define TRACE_VIRTIO_SND_UNREALIZE 0
#define TRACE_VIRTIO_SND_UNREALIZE_ENABLED 0
#define TRACE_VIRTIO_SND_UNREALIZE_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_unrealize(void *snd) {
    (void)snd;
}
#define TRACE_VIRTIO_SND_VM_STATE_RUNNING 0
#define TRACE_VIRTIO_SND_VM_STATE_RUNNING_ENABLED 0
#define TRACE_VIRTIO_SND_VM_STATE_RUNNING_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_vm_state_running(void) {
}
#define TRACE_VIRTIO_SND_VM_STATE_STOPPED 0
#define TRACE_VIRTIO_SND_VM_STATE_STOPPED_ENABLED 0
#define TRACE_VIRTIO_SND_VM_STATE_STOPPED_BACKEND_DSTATE() (0)
static inline void trace_virtio_snd_vm_state_stopped(void) {
}

#endif