/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_XBOX_MCPX_APU_DSP_H
#define TRACE_TRACE_HW_XBOX_MCPX_APU_DSP_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_DSP_READ_PERIPHERAL 0
#define TRACE_DSP_READ_PERIPHERAL_ENABLED 0
#define TRACE_DSP_READ_PERIPHERAL_BACKEND_DSTATE() (0)
static inline void trace_dsp_read_peripheral(uint32_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_DSP_WRITE_PERIPHERAL 0
#define TRACE_DSP_WRITE_PERIPHERAL_ENABLED 0
#define TRACE_DSP_WRITE_PERIPHERAL_BACKEND_DSTATE() (0)
static inline void trace_dsp_write_peripheral(uint32_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_DSP56K_EXECUTE_INSTRUCTION 0
#define TRACE_DSP56K_EXECUTE_INSTRUCTION_ENABLED 0
#define TRACE_DSP56K_EXECUTE_INSTRUCTION_BACKEND_DSTATE() (0)
static inline void trace_dsp56k_execute_instruction(uint32_t id, uint32_t pc) {
    (void)id;
    (void)pc;
}
#define TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM 0
#define TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_ENABLED 0
#define TRACE_DSP56K_EXECUTE_INSTRUCTION_DISASM_BACKEND_DSTATE() (0)
static inline void trace_dsp56k_execute_instruction_disasm(const char *disasm) {
    (void)disasm;
}

#endif