/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_MISC_MACIO_H
#define TRACE_TRACE_HW_MISC_MACIO_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_CUDA_DATA_RECV 0
#define TRACE_CUDA_DATA_RECV_ENABLED 0
#define TRACE_CUDA_DATA_RECV_BACKEND_DSTATE() (0)
static inline void trace_cuda_data_recv(uint8_t data) {
    (void)data;
}
#define TRACE_CUDA_DATA_SEND 0
#define TRACE_CUDA_DATA_SEND_ENABLED 0
#define TRACE_CUDA_DATA_SEND_BACKEND_DSTATE() (0)
static inline void trace_cuda_data_send(uint8_t data) {
    (void)data;
}
#define TRACE_CUDA_DELAY_SET_SR_INT 0
#define TRACE_CUDA_DELAY_SET_SR_INT_ENABLED 0
#define TRACE_CUDA_DELAY_SET_SR_INT_BACKEND_DSTATE() (0)
static inline void trace_cuda_delay_set_sr_int(void) {
}
#define TRACE_CUDA_PACKET_RECEIVE 0
#define TRACE_CUDA_PACKET_RECEIVE_ENABLED 0
#define TRACE_CUDA_PACKET_RECEIVE_BACKEND_DSTATE() (0)
static inline void trace_cuda_packet_receive(int len) {
    (void)len;
}
#define TRACE_CUDA_PACKET_RECEIVE_DATA 0
#define TRACE_CUDA_PACKET_RECEIVE_DATA_ENABLED 0
#define TRACE_CUDA_PACKET_RECEIVE_DATA_BACKEND_DSTATE() (0)
static inline void trace_cuda_packet_receive_data(int i, const uint8_t data) {
    (void)i;
    (void)data;
}
#define TRACE_CUDA_PACKET_SEND 0
#define TRACE_CUDA_PACKET_SEND_ENABLED 0
#define TRACE_CUDA_PACKET_SEND_BACKEND_DSTATE() (0)
static inline void trace_cuda_packet_send(int len) {
    (void)len;
}
#define TRACE_CUDA_PACKET_SEND_DATA 0
#define TRACE_CUDA_PACKET_SEND_DATA_ENABLED 0
#define TRACE_CUDA_PACKET_SEND_DATA_BACKEND_DSTATE() (0)
static inline void trace_cuda_packet_send_data(int i, const uint8_t data) {
    (void)i;
    (void)data;
}
#define TRACE_CUDA_RECEIVE_PACKET_CMD 0
#define TRACE_CUDA_RECEIVE_PACKET_CMD_ENABLED 0
#define TRACE_CUDA_RECEIVE_PACKET_CMD_BACKEND_DSTATE() (0)
static inline void trace_cuda_receive_packet_cmd(const char *cmd) {
    (void)cmd;
}
#define TRACE_MACIO_GPIO_IRQ_ASSERT 0
#define TRACE_MACIO_GPIO_IRQ_ASSERT_ENABLED 0
#define TRACE_MACIO_GPIO_IRQ_ASSERT_BACKEND_DSTATE() (0)
static inline void trace_macio_gpio_irq_assert(int gpio) {
    (void)gpio;
}
#define TRACE_MACIO_GPIO_IRQ_DEASSERT 0
#define TRACE_MACIO_GPIO_IRQ_DEASSERT_ENABLED 0
#define TRACE_MACIO_GPIO_IRQ_DEASSERT_BACKEND_DSTATE() (0)
static inline void trace_macio_gpio_irq_deassert(int gpio) {
    (void)gpio;
}
#define TRACE_MACIO_GPIO_READ 0
#define TRACE_MACIO_GPIO_READ_ENABLED 0
#define TRACE_MACIO_GPIO_READ_BACKEND_DSTATE() (0)
static inline void trace_macio_gpio_read(uint64_t addr, uint64_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_MACIO_GPIO_WRITE 0
#define TRACE_MACIO_GPIO_WRITE_ENABLED 0
#define TRACE_MACIO_GPIO_WRITE_BACKEND_DSTATE() (0)
static inline void trace_macio_gpio_write(uint64_t addr, uint64_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_MACIO_SET_GPIO 0
#define TRACE_MACIO_SET_GPIO_ENABLED 0
#define TRACE_MACIO_SET_GPIO_BACKEND_DSTATE() (0)
static inline void trace_macio_set_gpio(int gpio, bool state) {
    (void)gpio;
    (void)state;
}
#define TRACE_MACIO_TIMER_READ 0
#define TRACE_MACIO_TIMER_READ_ENABLED 0
#define TRACE_MACIO_TIMER_READ_BACKEND_DSTATE() (0)
static inline void trace_macio_timer_read(uint64_t addr, unsigned len, uint32_t val) {
    (void)addr;
    (void)len;
    (void)val;
}
#define TRACE_MACIO_TIMER_WRITE 0
#define TRACE_MACIO_TIMER_WRITE_ENABLED 0
#define TRACE_MACIO_TIMER_WRITE_BACKEND_DSTATE() (0)
static inline void trace_macio_timer_write(uint64_t addr, unsigned len, uint64_t val) {
    (void)addr;
    (void)len;
    (void)val;
}
#define TRACE_PMU_ADB_POLL 0
#define TRACE_PMU_ADB_POLL_ENABLED 0
#define TRACE_PMU_ADB_POLL_BACKEND_DSTATE() (0)
static inline void trace_pmu_adb_poll(int olen) {
    (void)olen;
}
#define TRACE_PMU_CMD_ADB_NOBUS 0
#define TRACE_PMU_CMD_ADB_NOBUS_ENABLED 0
#define TRACE_PMU_CMD_ADB_NOBUS_BACKEND_DSTATE() (0)
static inline void trace_pmu_cmd_adb_nobus(void) {
}
#define TRACE_PMU_CMD_ADB_REPLY 0
#define TRACE_PMU_CMD_ADB_REPLY_ENABLED 0
#define TRACE_PMU_CMD_ADB_REPLY_BACKEND_DSTATE() (0)
static inline void trace_pmu_cmd_adb_reply(int len) {
    (void)len;
}
#define TRACE_PMU_CMD_ADB_REQUEST 0
#define TRACE_PMU_CMD_ADB_REQUEST_ENABLED 0
#define TRACE_PMU_CMD_ADB_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_pmu_cmd_adb_request(int inlen, int indata0, int indata1, int indata2, int indata3, int indata4) {
    (void)inlen;
    (void)indata0;
    (void)indata1;
    (void)indata2;
    (void)indata3;
    (void)indata4;
}
#define TRACE_PMU_CMD_SET_ADB_AUTOPOLL 0
#define TRACE_PMU_CMD_SET_ADB_AUTOPOLL_ENABLED 0
#define TRACE_PMU_CMD_SET_ADB_AUTOPOLL_BACKEND_DSTATE() (0)
static inline void trace_pmu_cmd_set_adb_autopoll(int mask) {
    (void)mask;
}
#define TRACE_PMU_CMD_SET_INT_MASK 0
#define TRACE_PMU_CMD_SET_INT_MASK_ENABLED 0
#define TRACE_PMU_CMD_SET_INT_MASK_BACKEND_DSTATE() (0)
static inline void trace_pmu_cmd_set_int_mask(int intmask) {
    (void)intmask;
}
#define TRACE_PMU_DEBUG_PROTOCOL_CLEAR_TREQ 0
#define TRACE_PMU_DEBUG_PROTOCOL_CLEAR_TREQ_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_CLEAR_TREQ_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_clear_treq(int state) {
    (void)state;
}
#define TRACE_PMU_DEBUG_PROTOCOL_CMD 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_cmd(int cmd, int cmdlen, int rsplen) {
    (void)cmd;
    (void)cmdlen;
    (void)rsplen;
}
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_RESP_COMPLETE 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_RESP_COMPLETE_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_RESP_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_cmd_resp_complete(int ier) {
    (void)ier;
}
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_SEND_RESP 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_SEND_RESP_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_SEND_RESP_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_cmd_send_resp(int pos, int len) {
    (void)pos;
    (void)len;
}
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_SEND_RESP_SIZE 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_SEND_RESP_SIZE_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_SEND_RESP_SIZE_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_cmd_send_resp_size(int len) {
    (void)len;
}
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_TOOBIG 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_TOOBIG_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMD_TOOBIG_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_cmd_toobig(int len) {
    (void)len;
}
#define TRACE_PMU_DEBUG_PROTOCOL_CMDLEN 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMDLEN_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_CMDLEN_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_cmdlen(int len) {
    (void)len;
}
#define TRACE_PMU_DEBUG_PROTOCOL_ERROR 0
#define TRACE_PMU_DEBUG_PROTOCOL_ERROR_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_ERROR_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_error(int portB) {
    (void)portB;
}
#define TRACE_PMU_DEBUG_PROTOCOL_RESP_SIZE 0
#define TRACE_PMU_DEBUG_PROTOCOL_RESP_SIZE_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_RESP_SIZE_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_resp_size(int size) {
    (void)size;
}
#define TRACE_PMU_DEBUG_PROTOCOL_STRING 0
#define TRACE_PMU_DEBUG_PROTOCOL_STRING_ENABLED 0
#define TRACE_PMU_DEBUG_PROTOCOL_STRING_BACKEND_DSTATE() (0)
static inline void trace_pmu_debug_protocol_string(const char *str) {
    (void)str;
}
#define TRACE_PMU_DISPATCH_CMD 0
#define TRACE_PMU_DISPATCH_CMD_ENABLED 0
#define TRACE_PMU_DISPATCH_CMD_BACKEND_DSTATE() (0)
static inline void trace_pmu_dispatch_cmd(const char *name) {
    (void)name;
}
#define TRACE_PMU_DISPATCH_UNKNOWN_CMD 0
#define TRACE_PMU_DISPATCH_UNKNOWN_CMD_ENABLED 0
#define TRACE_PMU_DISPATCH_UNKNOWN_CMD_BACKEND_DSTATE() (0)
static inline void trace_pmu_dispatch_unknown_cmd(int cmd) {
    (void)cmd;
}
#define TRACE_PMU_ONE_SEC_TIMER 0
#define TRACE_PMU_ONE_SEC_TIMER_ENABLED 0
#define TRACE_PMU_ONE_SEC_TIMER_BACKEND_DSTATE() (0)
static inline void trace_pmu_one_sec_timer(void) {
}

#endif