/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_TARGET_I386_H
#define TRACE_TRACE_TARGET_I386_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_KVM_MEMCRYPT_REGISTER_REGION 0
#define TRACE_KVM_MEMCRYPT_REGISTER_REGION_ENABLED 0
#define TRACE_KVM_MEMCRYPT_REGISTER_REGION_BACKEND_DSTATE() (0)
static inline void trace_kvm_memcrypt_register_region(void *addr, size_t len) {
    (void)addr;
    (void)len;
}
#define TRACE_KVM_MEMCRYPT_UNREGISTER_REGION 0
#define TRACE_KVM_MEMCRYPT_UNREGISTER_REGION_ENABLED 0
#define TRACE_KVM_MEMCRYPT_UNREGISTER_REGION_BACKEND_DSTATE() (0)
static inline void trace_kvm_memcrypt_unregister_region(void *addr, size_t len) {
    (void)addr;
    (void)len;
}
#define TRACE_KVM_SEV_ATTESTATION_REPORT 0
#define TRACE_KVM_SEV_ATTESTATION_REPORT_ENABLED 0
#define TRACE_KVM_SEV_ATTESTATION_REPORT_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_attestation_report(const char *mnonce, const char *data) {
    (void)mnonce;
    (void)data;
}
#define TRACE_KVM_SEV_CHANGE_STATE 0
#define TRACE_KVM_SEV_CHANGE_STATE_ENABLED 0
#define TRACE_KVM_SEV_CHANGE_STATE_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_change_state(const char *old, const char *new) {
    (void)old;
    (void)new;
}
#define TRACE_KVM_SEV_INIT 0
#define TRACE_KVM_SEV_INIT_ENABLED 0
#define TRACE_KVM_SEV_INIT_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_init(void) {
}
#define TRACE_KVM_SEV_LAUNCH_FINISH 0
#define TRACE_KVM_SEV_LAUNCH_FINISH_ENABLED 0
#define TRACE_KVM_SEV_LAUNCH_FINISH_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_launch_finish(void) {
}
#define TRACE_KVM_SEV_LAUNCH_MEASUREMENT 0
#define TRACE_KVM_SEV_LAUNCH_MEASUREMENT_ENABLED 0
#define TRACE_KVM_SEV_LAUNCH_MEASUREMENT_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_launch_measurement(const char *value) {
    (void)value;
}
#define TRACE_KVM_SEV_LAUNCH_SECRET 0
#define TRACE_KVM_SEV_LAUNCH_SECRET_ENABLED 0
#define TRACE_KVM_SEV_LAUNCH_SECRET_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_launch_secret(uint64_t hpa, uint64_t hva, uint64_t secret, int len) {
    (void)hpa;
    (void)hva;
    (void)secret;
    (void)len;
}
#define TRACE_KVM_SEV_LAUNCH_START 0
#define TRACE_KVM_SEV_LAUNCH_START_ENABLED 0
#define TRACE_KVM_SEV_LAUNCH_START_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_launch_start(int policy, void *session, void *pdh) {
    (void)policy;
    (void)session;
    (void)pdh;
}
#define TRACE_KVM_SEV_LAUNCH_UPDATE_DATA 0
#define TRACE_KVM_SEV_LAUNCH_UPDATE_DATA_ENABLED 0
#define TRACE_KVM_SEV_LAUNCH_UPDATE_DATA_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_launch_update_data(void *addr, size_t len) {
    (void)addr;
    (void)len;
}
#define TRACE_KVM_SEV_SNP_LAUNCH_FINISH 0
#define TRACE_KVM_SEV_SNP_LAUNCH_FINISH_ENABLED 0
#define TRACE_KVM_SEV_SNP_LAUNCH_FINISH_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_snp_launch_finish(char *id_block, char *id_auth, char *host_data) {
    (void)id_block;
    (void)id_auth;
    (void)host_data;
}
#define TRACE_KVM_SEV_SNP_LAUNCH_START 0
#define TRACE_KVM_SEV_SNP_LAUNCH_START_ENABLED 0
#define TRACE_KVM_SEV_SNP_LAUNCH_START_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_snp_launch_start(uint64_t policy, char *gosvw) {
    (void)policy;
    (void)gosvw;
}
#define TRACE_KVM_SEV_SNP_LAUNCH_UPDATE 0
#define TRACE_KVM_SEV_SNP_LAUNCH_UPDATE_ENABLED 0
#define TRACE_KVM_SEV_SNP_LAUNCH_UPDATE_BACKEND_DSTATE() (0)
static inline void trace_kvm_sev_snp_launch_update(uint64_t src, uint64_t gpa, uint64_t len, const char *type) {
    (void)src;
    (void)gpa;
    (void)len;
    (void)type;
}

#endif