/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_USB_H
#define TRACE_TRACE_HW_USB_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_CANOKEY_EMU_PREPARE_RECEIVE 0
#define TRACE_CANOKEY_EMU_PREPARE_RECEIVE_ENABLED 0
#define TRACE_CANOKEY_EMU_PREPARE_RECEIVE_BACKEND_DSTATE() (0)
static inline void trace_canokey_emu_prepare_receive(uint8_t ep, uint16_t size) {
    (void)ep;
    (void)size;
}
#define TRACE_CANOKEY_EMU_SET_ADDRESS 0
#define TRACE_CANOKEY_EMU_SET_ADDRESS_ENABLED 0
#define TRACE_CANOKEY_EMU_SET_ADDRESS_BACKEND_DSTATE() (0)
static inline void trace_canokey_emu_set_address(uint8_t addr) {
    (void)addr;
}
#define TRACE_CANOKEY_EMU_STALL_EP 0
#define TRACE_CANOKEY_EMU_STALL_EP_ENABLED 0
#define TRACE_CANOKEY_EMU_STALL_EP_BACKEND_DSTATE() (0)
static inline void trace_canokey_emu_stall_ep(uint8_t ep) {
    (void)ep;
}
#define TRACE_CANOKEY_EMU_TRANSMIT 0
#define TRACE_CANOKEY_EMU_TRANSMIT_ENABLED 0
#define TRACE_CANOKEY_EMU_TRANSMIT_BACKEND_DSTATE() (0)
static inline void trace_canokey_emu_transmit(uint8_t ep, uint16_t size) {
    (void)ep;
    (void)size;
}
#define TRACE_CANOKEY_HANDLE_CONTROL_IN 0
#define TRACE_CANOKEY_HANDLE_CONTROL_IN_ENABLED 0
#define TRACE_CANOKEY_HANDLE_CONTROL_IN_BACKEND_DSTATE() (0)
static inline void trace_canokey_handle_control_in(int actual_len) {
    (void)actual_len;
}
#define TRACE_CANOKEY_HANDLE_CONTROL_OUT 0
#define TRACE_CANOKEY_HANDLE_CONTROL_OUT_ENABLED 0
#define TRACE_CANOKEY_HANDLE_CONTROL_OUT_BACKEND_DSTATE() (0)
static inline void trace_canokey_handle_control_out(void) {
}
#define TRACE_CANOKEY_HANDLE_CONTROL_SETUP 0
#define TRACE_CANOKEY_HANDLE_CONTROL_SETUP_ENABLED 0
#define TRACE_CANOKEY_HANDLE_CONTROL_SETUP_BACKEND_DSTATE() (0)
static inline void trace_canokey_handle_control_setup(int request, int value, int index, int length) {
    (void)request;
    (void)value;
    (void)index;
    (void)length;
}
#define TRACE_CANOKEY_HANDLE_DATA_IN 0
#define TRACE_CANOKEY_HANDLE_DATA_IN_ENABLED 0
#define TRACE_CANOKEY_HANDLE_DATA_IN_BACKEND_DSTATE() (0)
static inline void trace_canokey_handle_data_in(uint8_t ep_in, uint32_t in_len) {
    (void)ep_in;
    (void)in_len;
}
#define TRACE_CANOKEY_HANDLE_DATA_OUT 0
#define TRACE_CANOKEY_HANDLE_DATA_OUT_ENABLED 0
#define TRACE_CANOKEY_HANDLE_DATA_OUT_BACKEND_DSTATE() (0)
static inline void trace_canokey_handle_data_out(uint8_t ep_out, uint32_t out_len) {
    (void)ep_out;
    (void)out_len;
}
#define TRACE_CANOKEY_HANDLE_RESET 0
#define TRACE_CANOKEY_HANDLE_RESET_ENABLED 0
#define TRACE_CANOKEY_HANDLE_RESET_BACKEND_DSTATE() (0)
static inline void trace_canokey_handle_reset(void) {
}
#define TRACE_CANOKEY_REALIZE 0
#define TRACE_CANOKEY_REALIZE_ENABLED 0
#define TRACE_CANOKEY_REALIZE_BACKEND_DSTATE() (0)
static inline void trace_canokey_realize(void) {
}
#define TRACE_CANOKEY_THREAD_START 0
#define TRACE_CANOKEY_THREAD_START_ENABLED 0
#define TRACE_CANOKEY_THREAD_START_BACKEND_DSTATE() (0)
static inline void trace_canokey_thread_start(void) {
}
#define TRACE_CANOKEY_THREAD_STOP 0
#define TRACE_CANOKEY_THREAD_STOP_ENABLED 0
#define TRACE_CANOKEY_THREAD_STOP_BACKEND_DSTATE() (0)
static inline void trace_canokey_thread_stop(void) {
}
#define TRACE_CANOKEY_UNREALIZE 0
#define TRACE_CANOKEY_UNREALIZE_ENABLED 0
#define TRACE_CANOKEY_UNREALIZE_BACKEND_DSTATE() (0)
static inline void trace_canokey_unrealize(void) {
}
#define TRACE_USB_CLEAR_DEVICE_FEATURE 0
#define TRACE_USB_CLEAR_DEVICE_FEATURE_ENABLED 0
#define TRACE_USB_CLEAR_DEVICE_FEATURE_BACKEND_DSTATE() (0)
static inline void trace_usb_clear_device_feature(int addr, int feature, int ret) {
    (void)addr;
    (void)feature;
    (void)ret;
}
#define TRACE_USB_DESC_BOS 0
#define TRACE_USB_DESC_BOS_ENABLED 0
#define TRACE_USB_DESC_BOS_BACKEND_DSTATE() (0)
static inline void trace_usb_desc_bos(int addr, int len, int ret) {
    (void)addr;
    (void)len;
    (void)ret;
}
#define TRACE_USB_DESC_CONFIG 0
#define TRACE_USB_DESC_CONFIG_ENABLED 0
#define TRACE_USB_DESC_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_usb_desc_config(int addr, int index, int len, int ret) {
    (void)addr;
    (void)index;
    (void)len;
    (void)ret;
}
#define TRACE_USB_DESC_DEVICE 0
#define TRACE_USB_DESC_DEVICE_ENABLED 0
#define TRACE_USB_DESC_DEVICE_BACKEND_DSTATE() (0)
static inline void trace_usb_desc_device(int addr, int len, int ret) {
    (void)addr;
    (void)len;
    (void)ret;
}
#define TRACE_USB_DESC_DEVICE_QUALIFIER 0
#define TRACE_USB_DESC_DEVICE_QUALIFIER_ENABLED 0
#define TRACE_USB_DESC_DEVICE_QUALIFIER_BACKEND_DSTATE() (0)
static inline void trace_usb_desc_device_qualifier(int addr, int len, int ret) {
    (void)addr;
    (void)len;
    (void)ret;
}
#define TRACE_USB_DESC_MSOS 0
#define TRACE_USB_DESC_MSOS_ENABLED 0
#define TRACE_USB_DESC_MSOS_BACKEND_DSTATE() (0)
static inline void trace_usb_desc_msos(int addr, int index, int len, int ret) {
    (void)addr;
    (void)index;
    (void)len;
    (void)ret;
}
#define TRACE_USB_DESC_OTHER_SPEED_CONFIG 0
#define TRACE_USB_DESC_OTHER_SPEED_CONFIG_ENABLED 0
#define TRACE_USB_DESC_OTHER_SPEED_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_usb_desc_other_speed_config(int addr, int index, int len, int ret) {
    (void)addr;
    (void)index;
    (void)len;
    (void)ret;
}
#define TRACE_USB_DESC_STRING 0
#define TRACE_USB_DESC_STRING_ENABLED 0
#define TRACE_USB_DESC_STRING_BACKEND_DSTATE() (0)
static inline void trace_usb_desc_string(int addr, int index, int len, int ret) {
    (void)addr;
    (void)index;
    (void)len;
    (void)ret;
}
#define TRACE_USB_DWC2_ASYNC_PACKET 0
#define TRACE_USB_DWC2_ASYNC_PACKET_ENABLED 0
#define TRACE_USB_DWC2_ASYNC_PACKET_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_async_packet(void *pkt, uint32_t chan, void *dev, uint32_t ep, const char *dir, uint32_t len) {
    (void)pkt;
    (void)chan;
    (void)dev;
    (void)ep;
    (void)dir;
    (void)len;
}
#define TRACE_USB_DWC2_ASYNC_PACKET_COMPLETE 0
#define TRACE_USB_DWC2_ASYNC_PACKET_COMPLETE_ENABLED 0
#define TRACE_USB_DWC2_ASYNC_PACKET_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_async_packet_complete(void *port, void *pkt, uint32_t chan, void *dev, uint32_t ep, const char *dir, uint32_t len) {
    (void)port;
    (void)pkt;
    (void)chan;
    (void)dev;
    (void)ep;
    (void)dir;
    (void)len;
}
#define TRACE_USB_DWC2_ATTACH 0
#define TRACE_USB_DWC2_ATTACH_ENABLED 0
#define TRACE_USB_DWC2_ATTACH_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_attach(void *port) {
    (void)port;
}
#define TRACE_USB_DWC2_ATTACH_SPEED 0
#define TRACE_USB_DWC2_ATTACH_SPEED_ENABLED 0
#define TRACE_USB_DWC2_ATTACH_SPEED_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_attach_speed(const char *speed) {
    (void)speed;
}
#define TRACE_USB_DWC2_BUS_START 0
#define TRACE_USB_DWC2_BUS_START_ENABLED 0
#define TRACE_USB_DWC2_BUS_START_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_bus_start(void) {
}
#define TRACE_USB_DWC2_BUS_STOP 0
#define TRACE_USB_DWC2_BUS_STOP_ENABLED 0
#define TRACE_USB_DWC2_BUS_STOP_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_bus_stop(void) {
}
#define TRACE_USB_DWC2_CHILD_DETACH 0
#define TRACE_USB_DWC2_CHILD_DETACH_ENABLED 0
#define TRACE_USB_DWC2_CHILD_DETACH_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_child_detach(void *port, void *child) {
    (void)port;
    (void)child;
}
#define TRACE_USB_DWC2_DETACH 0
#define TRACE_USB_DWC2_DETACH_ENABLED 0
#define TRACE_USB_DWC2_DETACH_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_detach(void *port) {
    (void)port;
}
#define TRACE_USB_DWC2_DEVICE_FOUND 0
#define TRACE_USB_DWC2_DEVICE_FOUND_ENABLED 0
#define TRACE_USB_DWC2_DEVICE_FOUND_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_device_found(uint32_t pnum) {
    (void)pnum;
}
#define TRACE_USB_DWC2_DEVICE_NOT_FOUND 0
#define TRACE_USB_DWC2_DEVICE_NOT_FOUND_ENABLED 0
#define TRACE_USB_DWC2_DEVICE_NOT_FOUND_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_device_not_found(void) {
}
#define TRACE_USB_DWC2_ENABLE_CHAN 0
#define TRACE_USB_DWC2_ENABLE_CHAN_ENABLED 0
#define TRACE_USB_DWC2_ENABLE_CHAN_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_enable_chan(uint32_t chan, void *dev, void *pkt, uint32_t ep) {
    (void)chan;
    (void)dev;
    (void)pkt;
    (void)ep;
}
#define TRACE_USB_DWC2_FIND_DEVICE 0
#define TRACE_USB_DWC2_FIND_DEVICE_ENABLED 0
#define TRACE_USB_DWC2_FIND_DEVICE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_find_device(uint8_t addr) {
    (void)addr;
}
#define TRACE_USB_DWC2_FSZREG_READ 0
#define TRACE_USB_DWC2_FSZREG_READ_ENABLED 0
#define TRACE_USB_DWC2_FSZREG_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_fszreg_read(uint64_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_USB_DWC2_FSZREG_WRITE 0
#define TRACE_USB_DWC2_FSZREG_WRITE_ENABLED 0
#define TRACE_USB_DWC2_FSZREG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_fszreg_write(uint64_t addr, uint64_t val, uint32_t old, uint64_t result) {
    (void)addr;
    (void)val;
    (void)old;
    (void)result;
}
#define TRACE_USB_DWC2_GLBREG_READ 0
#define TRACE_USB_DWC2_GLBREG_READ_ENABLED 0
#define TRACE_USB_DWC2_GLBREG_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_glbreg_read(uint64_t addr, const char *reg, uint32_t val) {
    (void)addr;
    (void)reg;
    (void)val;
}
#define TRACE_USB_DWC2_GLBREG_WRITE 0
#define TRACE_USB_DWC2_GLBREG_WRITE_ENABLED 0
#define TRACE_USB_DWC2_GLBREG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_glbreg_write(uint64_t addr, const char *reg, uint64_t val, uint32_t old, uint64_t result) {
    (void)addr;
    (void)reg;
    (void)val;
    (void)old;
    (void)result;
}
#define TRACE_USB_DWC2_HANDLE_PACKET 0
#define TRACE_USB_DWC2_HANDLE_PACKET_ENABLED 0
#define TRACE_USB_DWC2_HANDLE_PACKET_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_handle_packet(uint32_t chan, void *dev, void *pkt, uint32_t ep, const char *type, const char *dir, uint32_t mps, uint32_t len, uint32_t pcnt) {
    (void)chan;
    (void)dev;
    (void)pkt;
    (void)ep;
    (void)type;
    (void)dir;
    (void)mps;
    (void)len;
    (void)pcnt;
}
#define TRACE_USB_DWC2_HREG0_ACTION 0
#define TRACE_USB_DWC2_HREG0_ACTION_ENABLED 0
#define TRACE_USB_DWC2_HREG0_ACTION_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_hreg0_action(const char *s) {
    (void)s;
}
#define TRACE_USB_DWC2_HREG0_READ 0
#define TRACE_USB_DWC2_HREG0_READ_ENABLED 0
#define TRACE_USB_DWC2_HREG0_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_hreg0_read(uint64_t addr, const char *reg, uint32_t val) {
    (void)addr;
    (void)reg;
    (void)val;
}
#define TRACE_USB_DWC2_HREG0_WRITE 0
#define TRACE_USB_DWC2_HREG0_WRITE_ENABLED 0
#define TRACE_USB_DWC2_HREG0_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_hreg0_write(uint64_t addr, const char *reg, uint64_t val, uint32_t old, uint64_t result) {
    (void)addr;
    (void)reg;
    (void)val;
    (void)old;
    (void)result;
}
#define TRACE_USB_DWC2_HREG1_READ 0
#define TRACE_USB_DWC2_HREG1_READ_ENABLED 0
#define TRACE_USB_DWC2_HREG1_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_hreg1_read(uint64_t addr, const char *reg, uint64_t chan, uint32_t val) {
    (void)addr;
    (void)reg;
    (void)chan;
    (void)val;
}
#define TRACE_USB_DWC2_HREG1_WRITE 0
#define TRACE_USB_DWC2_HREG1_WRITE_ENABLED 0
#define TRACE_USB_DWC2_HREG1_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_hreg1_write(uint64_t addr, const char *reg, uint64_t chan, uint64_t val, uint32_t old, uint64_t result) {
    (void)addr;
    (void)reg;
    (void)chan;
    (void)val;
    (void)old;
    (void)result;
}
#define TRACE_USB_DWC2_HREG2_READ 0
#define TRACE_USB_DWC2_HREG2_READ_ENABLED 0
#define TRACE_USB_DWC2_HREG2_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_hreg2_read(uint64_t addr, uint64_t fifo, uint32_t val) {
    (void)addr;
    (void)fifo;
    (void)val;
}
#define TRACE_USB_DWC2_HREG2_WRITE 0
#define TRACE_USB_DWC2_HREG2_WRITE_ENABLED 0
#define TRACE_USB_DWC2_HREG2_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_hreg2_write(uint64_t addr, uint64_t fifo, uint64_t val, uint32_t old, uint64_t result) {
    (void)addr;
    (void)fifo;
    (void)val;
    (void)old;
    (void)result;
}
#define TRACE_USB_DWC2_LOWER_GLOBAL_IRQ 0
#define TRACE_USB_DWC2_LOWER_GLOBAL_IRQ_ENABLED 0
#define TRACE_USB_DWC2_LOWER_GLOBAL_IRQ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_lower_global_irq(uint32_t intr) {
    (void)intr;
}
#define TRACE_USB_DWC2_LOWER_HOST_IRQ 0
#define TRACE_USB_DWC2_LOWER_HOST_IRQ_ENABLED 0
#define TRACE_USB_DWC2_LOWER_HOST_IRQ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_lower_host_irq(uint32_t intr) {
    (void)intr;
}
#define TRACE_USB_DWC2_MEMORY_READ 0
#define TRACE_USB_DWC2_MEMORY_READ_ENABLED 0
#define TRACE_USB_DWC2_MEMORY_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_memory_read(uint32_t addr, uint32_t len) {
    (void)addr;
    (void)len;
}
#define TRACE_USB_DWC2_MEMORY_WRITE 0
#define TRACE_USB_DWC2_MEMORY_WRITE_ENABLED 0
#define TRACE_USB_DWC2_MEMORY_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_memory_write(uint32_t addr, uint32_t len) {
    (void)addr;
    (void)len;
}
#define TRACE_USB_DWC2_PACKET_DONE 0
#define TRACE_USB_DWC2_PACKET_DONE_ENABLED 0
#define TRACE_USB_DWC2_PACKET_DONE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_packet_done(const char *status, uint32_t actual, uint32_t len, uint32_t pcnt) {
    (void)status;
    (void)actual;
    (void)len;
    (void)pcnt;
}
#define TRACE_USB_DWC2_PACKET_ERROR 0
#define TRACE_USB_DWC2_PACKET_ERROR_ENABLED 0
#define TRACE_USB_DWC2_PACKET_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_packet_error(const char *status) {
    (void)status;
}
#define TRACE_USB_DWC2_PACKET_NEXT 0
#define TRACE_USB_DWC2_PACKET_NEXT_ENABLED 0
#define TRACE_USB_DWC2_PACKET_NEXT_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_packet_next(const char *status, uint32_t len, uint32_t pcnt) {
    (void)status;
    (void)len;
    (void)pcnt;
}
#define TRACE_USB_DWC2_PACKET_STATUS 0
#define TRACE_USB_DWC2_PACKET_STATUS_ENABLED 0
#define TRACE_USB_DWC2_PACKET_STATUS_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_packet_status(const char *status, uint32_t len) {
    (void)status;
    (void)len;
}
#define TRACE_USB_DWC2_PCGREG_READ 0
#define TRACE_USB_DWC2_PCGREG_READ_ENABLED 0
#define TRACE_USB_DWC2_PCGREG_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_pcgreg_read(uint64_t addr, const char *reg, uint32_t val) {
    (void)addr;
    (void)reg;
    (void)val;
}
#define TRACE_USB_DWC2_PCGREG_WRITE 0
#define TRACE_USB_DWC2_PCGREG_WRITE_ENABLED 0
#define TRACE_USB_DWC2_PCGREG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_pcgreg_write(uint64_t addr, const char *reg, uint64_t val, uint32_t old, uint64_t result) {
    (void)addr;
    (void)reg;
    (void)val;
    (void)old;
    (void)result;
}
#define TRACE_USB_DWC2_PORT_DISABLED 0
#define TRACE_USB_DWC2_PORT_DISABLED_ENABLED 0
#define TRACE_USB_DWC2_PORT_DISABLED_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_port_disabled(uint32_t pnum) {
    (void)pnum;
}
#define TRACE_USB_DWC2_RAISE_GLOBAL_IRQ 0
#define TRACE_USB_DWC2_RAISE_GLOBAL_IRQ_ENABLED 0
#define TRACE_USB_DWC2_RAISE_GLOBAL_IRQ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_raise_global_irq(uint32_t intr) {
    (void)intr;
}
#define TRACE_USB_DWC2_RAISE_HOST_IRQ 0
#define TRACE_USB_DWC2_RAISE_HOST_IRQ_ENABLED 0
#define TRACE_USB_DWC2_RAISE_HOST_IRQ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_raise_host_irq(uint32_t intr) {
    (void)intr;
}
#define TRACE_USB_DWC2_RESET_ENTER 0
#define TRACE_USB_DWC2_RESET_ENTER_ENABLED 0
#define TRACE_USB_DWC2_RESET_ENTER_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_reset_enter(void) {
}
#define TRACE_USB_DWC2_RESET_EXIT 0
#define TRACE_USB_DWC2_RESET_EXIT_ENABLED 0
#define TRACE_USB_DWC2_RESET_EXIT_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_reset_exit(void) {
}
#define TRACE_USB_DWC2_RESET_HOLD 0
#define TRACE_USB_DWC2_RESET_HOLD_ENABLED 0
#define TRACE_USB_DWC2_RESET_HOLD_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_reset_hold(void) {
}
#define TRACE_USB_DWC2_SOF 0
#define TRACE_USB_DWC2_SOF_ENABLED 0
#define TRACE_USB_DWC2_SOF_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_sof(int64_t next) {
    (void)next;
}
#define TRACE_USB_DWC2_UPDATE_IRQ 0
#define TRACE_USB_DWC2_UPDATE_IRQ_ENABLED 0
#define TRACE_USB_DWC2_UPDATE_IRQ_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_update_irq(uint32_t level) {
    (void)level;
}
#define TRACE_USB_DWC2_WAKEUP 0
#define TRACE_USB_DWC2_WAKEUP_ENABLED 0
#define TRACE_USB_DWC2_WAKEUP_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_wakeup(void *port) {
    (void)port;
}
#define TRACE_USB_DWC2_WAKEUP_ENDPOINT 0
#define TRACE_USB_DWC2_WAKEUP_ENDPOINT_ENABLED 0
#define TRACE_USB_DWC2_WAKEUP_ENDPOINT_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_wakeup_endpoint(void *ep, uint32_t stream) {
    (void)ep;
    (void)stream;
}
#define TRACE_USB_DWC2_WORK_BH 0
#define TRACE_USB_DWC2_WORK_BH_ENABLED 0
#define TRACE_USB_DWC2_WORK_BH_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_work_bh(void) {
}
#define TRACE_USB_DWC2_WORK_BH_NEXT 0
#define TRACE_USB_DWC2_WORK_BH_NEXT_ENABLED 0
#define TRACE_USB_DWC2_WORK_BH_NEXT_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_work_bh_next(uint32_t chan) {
    (void)chan;
}
#define TRACE_USB_DWC2_WORK_BH_SERVICE 0
#define TRACE_USB_DWC2_WORK_BH_SERVICE_ENABLED 0
#define TRACE_USB_DWC2_WORK_BH_SERVICE_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_work_bh_service(uint32_t first, uint32_t current, void *dev, uint32_t ep) {
    (void)first;
    (void)current;
    (void)dev;
    (void)ep;
}
#define TRACE_USB_DWC2_WORK_TIMER 0
#define TRACE_USB_DWC2_WORK_TIMER_ENABLED 0
#define TRACE_USB_DWC2_WORK_TIMER_BACKEND_DSTATE() (0)
static inline void trace_usb_dwc2_work_timer(void) {
}
#define TRACE_USB_EHCI_DMA_ERROR 0
#define TRACE_USB_EHCI_DMA_ERROR_ENABLED 0
#define TRACE_USB_EHCI_DMA_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_dma_error(void) {
}
#define TRACE_USB_EHCI_DOORBELL_ACK 0
#define TRACE_USB_EHCI_DOORBELL_ACK_ENABLED 0
#define TRACE_USB_EHCI_DOORBELL_ACK_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_doorbell_ack(void) {
}
#define TRACE_USB_EHCI_DOORBELL_RING 0
#define TRACE_USB_EHCI_DOORBELL_RING_ENABLED 0
#define TRACE_USB_EHCI_DOORBELL_RING_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_doorbell_ring(void) {
}
#define TRACE_USB_EHCI_GUEST_BUG 0
#define TRACE_USB_EHCI_GUEST_BUG_ENABLED 0
#define TRACE_USB_EHCI_GUEST_BUG_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_guest_bug(const char *reason) {
    (void)reason;
}
#define TRACE_USB_EHCI_IRQ 0
#define TRACE_USB_EHCI_IRQ_ENABLED 0
#define TRACE_USB_EHCI_IRQ_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_irq(uint32_t level, uint32_t frindex, uint32_t sts, uint32_t mask) {
    (void)level;
    (void)frindex;
    (void)sts;
    (void)mask;
}
#define TRACE_USB_EHCI_ITD 0
#define TRACE_USB_EHCI_ITD_ENABLED 0
#define TRACE_USB_EHCI_ITD_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_itd(uint32_t addr, uint32_t nxt, uint32_t mplen, uint32_t mult, uint32_t ep, uint32_t devaddr) {
    (void)addr;
    (void)nxt;
    (void)mplen;
    (void)mult;
    (void)ep;
    (void)devaddr;
}
#define TRACE_USB_EHCI_OPREG_CHANGE 0
#define TRACE_USB_EHCI_OPREG_CHANGE_ENABLED 0
#define TRACE_USB_EHCI_OPREG_CHANGE_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_opreg_change(uint32_t addr, const char *str, uint32_t new, uint32_t old) {
    (void)addr;
    (void)str;
    (void)new;
    (void)old;
}
#define TRACE_USB_EHCI_OPREG_READ 0
#define TRACE_USB_EHCI_OPREG_READ_ENABLED 0
#define TRACE_USB_EHCI_OPREG_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_opreg_read(uint32_t addr, const char *str, uint32_t val) {
    (void)addr;
    (void)str;
    (void)val;
}
#define TRACE_USB_EHCI_OPREG_WRITE 0
#define TRACE_USB_EHCI_OPREG_WRITE_ENABLED 0
#define TRACE_USB_EHCI_OPREG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_opreg_write(uint32_t addr, const char *str, uint32_t val) {
    (void)addr;
    (void)str;
    (void)val;
}
#define TRACE_USB_EHCI_PACKET_ACTION 0
#define TRACE_USB_EHCI_PACKET_ACTION_ENABLED 0
#define TRACE_USB_EHCI_PACKET_ACTION_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_packet_action(void *q, void *p, const char *action) {
    (void)q;
    (void)p;
    (void)action;
}
#define TRACE_USB_EHCI_PORT_ATTACH 0
#define TRACE_USB_EHCI_PORT_ATTACH_ENABLED 0
#define TRACE_USB_EHCI_PORT_ATTACH_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_port_attach(uint32_t port, const char *owner, const char *device) {
    (void)port;
    (void)owner;
    (void)device;
}
#define TRACE_USB_EHCI_PORT_DETACH 0
#define TRACE_USB_EHCI_PORT_DETACH_ENABLED 0
#define TRACE_USB_EHCI_PORT_DETACH_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_port_detach(uint32_t port, const char *owner) {
    (void)port;
    (void)owner;
}
#define TRACE_USB_EHCI_PORT_RESET 0
#define TRACE_USB_EHCI_PORT_RESET_ENABLED 0
#define TRACE_USB_EHCI_PORT_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_port_reset(uint32_t port, int enable) {
    (void)port;
    (void)enable;
}
#define TRACE_USB_EHCI_PORT_RESUME 0
#define TRACE_USB_EHCI_PORT_RESUME_ENABLED 0
#define TRACE_USB_EHCI_PORT_RESUME_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_port_resume(uint32_t port) {
    (void)port;
}
#define TRACE_USB_EHCI_PORT_SUSPEND 0
#define TRACE_USB_EHCI_PORT_SUSPEND_ENABLED 0
#define TRACE_USB_EHCI_PORT_SUSPEND_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_port_suspend(uint32_t port) {
    (void)port;
}
#define TRACE_USB_EHCI_PORT_WAKEUP 0
#define TRACE_USB_EHCI_PORT_WAKEUP_ENABLED 0
#define TRACE_USB_EHCI_PORT_WAKEUP_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_port_wakeup(uint32_t port) {
    (void)port;
}
#define TRACE_USB_EHCI_PORTSC_CHANGE 0
#define TRACE_USB_EHCI_PORTSC_CHANGE_ENABLED 0
#define TRACE_USB_EHCI_PORTSC_CHANGE_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_portsc_change(uint32_t addr, uint32_t port, uint32_t new, uint32_t old) {
    (void)addr;
    (void)port;
    (void)new;
    (void)old;
}
#define TRACE_USB_EHCI_PORTSC_READ 0
#define TRACE_USB_EHCI_PORTSC_READ_ENABLED 0
#define TRACE_USB_EHCI_PORTSC_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_portsc_read(uint32_t addr, uint32_t port, uint32_t val) {
    (void)addr;
    (void)port;
    (void)val;
}
#define TRACE_USB_EHCI_PORTSC_WRITE 0
#define TRACE_USB_EHCI_PORTSC_WRITE_ENABLED 0
#define TRACE_USB_EHCI_PORTSC_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_portsc_write(uint32_t addr, uint32_t port, uint32_t val) {
    (void)addr;
    (void)port;
    (void)val;
}
#define TRACE_USB_EHCI_QH_BITS 0
#define TRACE_USB_EHCI_QH_BITS_ENABLED 0
#define TRACE_USB_EHCI_QH_BITS_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_qh_bits(uint32_t addr, int c, int h, int dtc, int i) {
    (void)addr;
    (void)c;
    (void)h;
    (void)dtc;
    (void)i;
}
#define TRACE_USB_EHCI_QH_FIELDS 0
#define TRACE_USB_EHCI_QH_FIELDS_ENABLED 0
#define TRACE_USB_EHCI_QH_FIELDS_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_qh_fields(uint32_t addr, int rl, int mplen, int eps, int ep, int devaddr) {
    (void)addr;
    (void)rl;
    (void)mplen;
    (void)eps;
    (void)ep;
    (void)devaddr;
}
#define TRACE_USB_EHCI_QH_PTRS 0
#define TRACE_USB_EHCI_QH_PTRS_ENABLED 0
#define TRACE_USB_EHCI_QH_PTRS_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_qh_ptrs(void *q, uint32_t addr, uint32_t nxt, uint32_t c_qtd, uint32_t n_qtd, uint32_t a_qtd) {
    (void)q;
    (void)addr;
    (void)nxt;
    (void)c_qtd;
    (void)n_qtd;
    (void)a_qtd;
}
#define TRACE_USB_EHCI_QTD_BITS 0
#define TRACE_USB_EHCI_QTD_BITS_ENABLED 0
#define TRACE_USB_EHCI_QTD_BITS_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_qtd_bits(uint32_t addr, int ioc, int active, int halt, int babble, int xacterr) {
    (void)addr;
    (void)ioc;
    (void)active;
    (void)halt;
    (void)babble;
    (void)xacterr;
}
#define TRACE_USB_EHCI_QTD_FIELDS 0
#define TRACE_USB_EHCI_QTD_FIELDS_ENABLED 0
#define TRACE_USB_EHCI_QTD_FIELDS_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_qtd_fields(uint32_t addr, int tbytes, int cpage, int cerr, int pid) {
    (void)addr;
    (void)tbytes;
    (void)cpage;
    (void)cerr;
    (void)pid;
}
#define TRACE_USB_EHCI_QTD_PTRS 0
#define TRACE_USB_EHCI_QTD_PTRS_ENABLED 0
#define TRACE_USB_EHCI_QTD_PTRS_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_qtd_ptrs(void *q, uint32_t addr, uint32_t nxt, uint32_t altnext) {
    (void)q;
    (void)addr;
    (void)nxt;
    (void)altnext;
}
#define TRACE_USB_EHCI_QUEUE_ACTION 0
#define TRACE_USB_EHCI_QUEUE_ACTION_ENABLED 0
#define TRACE_USB_EHCI_QUEUE_ACTION_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_queue_action(void *q, const char *action) {
    (void)q;
    (void)action;
}
#define TRACE_USB_EHCI_RESET 0
#define TRACE_USB_EHCI_RESET_ENABLED 0
#define TRACE_USB_EHCI_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_reset(void) {
}
#define TRACE_USB_EHCI_SITD 0
#define TRACE_USB_EHCI_SITD_ENABLED 0
#define TRACE_USB_EHCI_SITD_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_sitd(uint32_t addr, uint32_t nxt, uint32_t active) {
    (void)addr;
    (void)nxt;
    (void)active;
}
#define TRACE_USB_EHCI_STATE 0
#define TRACE_USB_EHCI_STATE_ENABLED 0
#define TRACE_USB_EHCI_STATE_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_state(const char *schedule, const char *state) {
    (void)schedule;
    (void)state;
}
#define TRACE_USB_EHCI_UNREALIZE 0
#define TRACE_USB_EHCI_UNREALIZE_ENABLED 0
#define TRACE_USB_EHCI_UNREALIZE_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_unrealize(void) {
}
#define TRACE_USB_EHCI_USBSTS 0
#define TRACE_USB_EHCI_USBSTS_ENABLED 0
#define TRACE_USB_EHCI_USBSTS_BACKEND_DSTATE() (0)
static inline void trace_usb_ehci_usbsts(const char *sts, int state) {
    (void)sts;
    (void)state;
}
#define TRACE_USB_HOST_ATTACH_KERNEL 0
#define TRACE_USB_HOST_ATTACH_KERNEL_ENABLED 0
#define TRACE_USB_HOST_ATTACH_KERNEL_BACKEND_DSTATE() (0)
static inline void trace_usb_host_attach_kernel(int bus, int addr, int interface) {
    (void)bus;
    (void)addr;
    (void)interface;
}
#define TRACE_USB_HOST_AUTO_SCAN_DISABLED 0
#define TRACE_USB_HOST_AUTO_SCAN_DISABLED_ENABLED 0
#define TRACE_USB_HOST_AUTO_SCAN_DISABLED_BACKEND_DSTATE() (0)
static inline void trace_usb_host_auto_scan_disabled(void) {
}
#define TRACE_USB_HOST_AUTO_SCAN_ENABLED 0
#define TRACE_USB_HOST_AUTO_SCAN_ENABLED_ENABLED 0
#define TRACE_USB_HOST_AUTO_SCAN_ENABLED_BACKEND_DSTATE() (0)
static inline void trace_usb_host_auto_scan_enabled(void) {
}
#define TRACE_USB_HOST_CLAIM_INTERFACE 0
#define TRACE_USB_HOST_CLAIM_INTERFACE_ENABLED 0
#define TRACE_USB_HOST_CLAIM_INTERFACE_BACKEND_DSTATE() (0)
static inline void trace_usb_host_claim_interface(int bus, int addr, int config, int interface) {
    (void)bus;
    (void)addr;
    (void)config;
    (void)interface;
}
#define TRACE_USB_HOST_CLOSE 0
#define TRACE_USB_HOST_CLOSE_ENABLED 0
#define TRACE_USB_HOST_CLOSE_BACKEND_DSTATE() (0)
static inline void trace_usb_host_close(int bus, int addr) {
    (void)bus;
    (void)addr;
}
#define TRACE_USB_HOST_DETACH_KERNEL 0
#define TRACE_USB_HOST_DETACH_KERNEL_ENABLED 0
#define TRACE_USB_HOST_DETACH_KERNEL_BACKEND_DSTATE() (0)
static inline void trace_usb_host_detach_kernel(int bus, int addr, int interface) {
    (void)bus;
    (void)addr;
    (void)interface;
}
#define TRACE_USB_HOST_ISO_OUT_OF_BUFS 0
#define TRACE_USB_HOST_ISO_OUT_OF_BUFS_ENABLED 0
#define TRACE_USB_HOST_ISO_OUT_OF_BUFS_BACKEND_DSTATE() (0)
static inline void trace_usb_host_iso_out_of_bufs(int bus, int addr, int ep) {
    (void)bus;
    (void)addr;
    (void)ep;
}
#define TRACE_USB_HOST_ISO_START 0
#define TRACE_USB_HOST_ISO_START_ENABLED 0
#define TRACE_USB_HOST_ISO_START_BACKEND_DSTATE() (0)
static inline void trace_usb_host_iso_start(int bus, int addr, int ep) {
    (void)bus;
    (void)addr;
    (void)ep;
}
#define TRACE_USB_HOST_ISO_STOP 0
#define TRACE_USB_HOST_ISO_STOP_ENABLED 0
#define TRACE_USB_HOST_ISO_STOP_BACKEND_DSTATE() (0)
static inline void trace_usb_host_iso_stop(int bus, int addr, int ep) {
    (void)bus;
    (void)addr;
    (void)ep;
}
#define TRACE_USB_HOST_OPEN_FAILURE 0
#define TRACE_USB_HOST_OPEN_FAILURE_ENABLED 0
#define TRACE_USB_HOST_OPEN_FAILURE_BACKEND_DSTATE() (0)
static inline void trace_usb_host_open_failure(int bus, int addr) {
    (void)bus;
    (void)addr;
}
#define TRACE_USB_HOST_OPEN_HOSTFD 0
#define TRACE_USB_HOST_OPEN_HOSTFD_ENABLED 0
#define TRACE_USB_HOST_OPEN_HOSTFD_BACKEND_DSTATE() (0)
static inline void trace_usb_host_open_hostfd(int hostfd) {
    (void)hostfd;
}
#define TRACE_USB_HOST_OPEN_STARTED 0
#define TRACE_USB_HOST_OPEN_STARTED_ENABLED 0
#define TRACE_USB_HOST_OPEN_STARTED_BACKEND_DSTATE() (0)
static inline void trace_usb_host_open_started(int bus, int addr) {
    (void)bus;
    (void)addr;
}
#define TRACE_USB_HOST_OPEN_SUCCESS 0
#define TRACE_USB_HOST_OPEN_SUCCESS_ENABLED 0
#define TRACE_USB_HOST_OPEN_SUCCESS_BACKEND_DSTATE() (0)
static inline void trace_usb_host_open_success(int bus, int addr) {
    (void)bus;
    (void)addr;
}
#define TRACE_USB_HOST_PARSE_CONFIG 0
#define TRACE_USB_HOST_PARSE_CONFIG_ENABLED 0
#define TRACE_USB_HOST_PARSE_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_usb_host_parse_config(int bus, int addr, int value, int active) {
    (void)bus;
    (void)addr;
    (void)value;
    (void)active;
}
#define TRACE_USB_HOST_PARSE_ENDPOINT 0
#define TRACE_USB_HOST_PARSE_ENDPOINT_ENABLED 0
#define TRACE_USB_HOST_PARSE_ENDPOINT_BACKEND_DSTATE() (0)
static inline void trace_usb_host_parse_endpoint(int bus, int addr, int ep, const char *dir, const char *type, int active) {
    (void)bus;
    (void)addr;
    (void)ep;
    (void)dir;
    (void)type;
    (void)active;
}
#define TRACE_USB_HOST_PARSE_ERROR 0
#define TRACE_USB_HOST_PARSE_ERROR_ENABLED 0
#define TRACE_USB_HOST_PARSE_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_host_parse_error(int bus, int addr, const char *errmsg) {
    (void)bus;
    (void)addr;
    (void)errmsg;
}
#define TRACE_USB_HOST_PARSE_INTERFACE 0
#define TRACE_USB_HOST_PARSE_INTERFACE_ENABLED 0
#define TRACE_USB_HOST_PARSE_INTERFACE_BACKEND_DSTATE() (0)
static inline void trace_usb_host_parse_interface(int bus, int addr, int num, int alt, int active) {
    (void)bus;
    (void)addr;
    (void)num;
    (void)alt;
    (void)active;
}
#define TRACE_USB_HOST_RELEASE_INTERFACE 0
#define TRACE_USB_HOST_RELEASE_INTERFACE_ENABLED 0
#define TRACE_USB_HOST_RELEASE_INTERFACE_BACKEND_DSTATE() (0)
static inline void trace_usb_host_release_interface(int bus, int addr, int interface) {
    (void)bus;
    (void)addr;
    (void)interface;
}
#define TRACE_USB_HOST_REMOTE_WAKEUP_REMOVED 0
#define TRACE_USB_HOST_REMOTE_WAKEUP_REMOVED_ENABLED 0
#define TRACE_USB_HOST_REMOTE_WAKEUP_REMOVED_BACKEND_DSTATE() (0)
static inline void trace_usb_host_remote_wakeup_removed(int bus, int addr) {
    (void)bus;
    (void)addr;
}
#define TRACE_USB_HOST_REQ_CANCELED 0
#define TRACE_USB_HOST_REQ_CANCELED_ENABLED 0
#define TRACE_USB_HOST_REQ_CANCELED_BACKEND_DSTATE() (0)
static inline void trace_usb_host_req_canceled(int bus, int addr, void *p) {
    (void)bus;
    (void)addr;
    (void)p;
}
#define TRACE_USB_HOST_REQ_COMPLETE 0
#define TRACE_USB_HOST_REQ_COMPLETE_ENABLED 0
#define TRACE_USB_HOST_REQ_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_usb_host_req_complete(int bus, int addr, void *p, int status, int length) {
    (void)bus;
    (void)addr;
    (void)p;
    (void)status;
    (void)length;
}
#define TRACE_USB_HOST_REQ_CONTROL 0
#define TRACE_USB_HOST_REQ_CONTROL_ENABLED 0
#define TRACE_USB_HOST_REQ_CONTROL_BACKEND_DSTATE() (0)
static inline void trace_usb_host_req_control(int bus, int addr, void *p, int req, int value, int index) {
    (void)bus;
    (void)addr;
    (void)p;
    (void)req;
    (void)value;
    (void)index;
}
#define TRACE_USB_HOST_REQ_DATA 0
#define TRACE_USB_HOST_REQ_DATA_ENABLED 0
#define TRACE_USB_HOST_REQ_DATA_BACKEND_DSTATE() (0)
static inline void trace_usb_host_req_data(int bus, int addr, void *p, int in, int ep, int size) {
    (void)bus;
    (void)addr;
    (void)p;
    (void)in;
    (void)ep;
    (void)size;
}
#define TRACE_USB_HOST_REQ_EMULATED 0
#define TRACE_USB_HOST_REQ_EMULATED_ENABLED 0
#define TRACE_USB_HOST_REQ_EMULATED_BACKEND_DSTATE() (0)
static inline void trace_usb_host_req_emulated(int bus, int addr, void *p, int status) {
    (void)bus;
    (void)addr;
    (void)p;
    (void)status;
}
#define TRACE_USB_HOST_RESET 0
#define TRACE_USB_HOST_RESET_ENABLED 0
#define TRACE_USB_HOST_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_host_reset(int bus, int addr) {
    (void)bus;
    (void)addr;
}
#define TRACE_USB_HOST_SET_ADDRESS 0
#define TRACE_USB_HOST_SET_ADDRESS_ENABLED 0
#define TRACE_USB_HOST_SET_ADDRESS_BACKEND_DSTATE() (0)
static inline void trace_usb_host_set_address(int bus, int addr, int config) {
    (void)bus;
    (void)addr;
    (void)config;
}
#define TRACE_USB_HOST_SET_CONFIG 0
#define TRACE_USB_HOST_SET_CONFIG_ENABLED 0
#define TRACE_USB_HOST_SET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_usb_host_set_config(int bus, int addr, int config) {
    (void)bus;
    (void)addr;
    (void)config;
}
#define TRACE_USB_HOST_SET_INTERFACE 0
#define TRACE_USB_HOST_SET_INTERFACE_ENABLED 0
#define TRACE_USB_HOST_SET_INTERFACE_BACKEND_DSTATE() (0)
static inline void trace_usb_host_set_interface(int bus, int addr, int interface, int alt) {
    (void)bus;
    (void)addr;
    (void)interface;
    (void)alt;
}
#define TRACE_USB_HUB_ATTACH 0
#define TRACE_USB_HUB_ATTACH_ENABLED 0
#define TRACE_USB_HUB_ATTACH_BACKEND_DSTATE() (0)
static inline void trace_usb_hub_attach(int addr, int nr) {
    (void)addr;
    (void)nr;
}
#define TRACE_USB_HUB_CLEAR_PORT_FEATURE 0
#define TRACE_USB_HUB_CLEAR_PORT_FEATURE_ENABLED 0
#define TRACE_USB_HUB_CLEAR_PORT_FEATURE_BACKEND_DSTATE() (0)
static inline void trace_usb_hub_clear_port_feature(int addr, int nr, const char *f) {
    (void)addr;
    (void)nr;
    (void)f;
}
#define TRACE_USB_HUB_CONTROL 0
#define TRACE_USB_HUB_CONTROL_ENABLED 0
#define TRACE_USB_HUB_CONTROL_BACKEND_DSTATE() (0)
static inline void trace_usb_hub_control(int addr, int request, int value, int index, int length) {
    (void)addr;
    (void)request;
    (void)value;
    (void)index;
    (void)length;
}
#define TRACE_USB_HUB_DETACH 0
#define TRACE_USB_HUB_DETACH_ENABLED 0
#define TRACE_USB_HUB_DETACH_BACKEND_DSTATE() (0)
static inline void trace_usb_hub_detach(int addr, int nr) {
    (void)addr;
    (void)nr;
}
#define TRACE_USB_HUB_GET_PORT_STATUS 0
#define TRACE_USB_HUB_GET_PORT_STATUS_ENABLED 0
#define TRACE_USB_HUB_GET_PORT_STATUS_BACKEND_DSTATE() (0)
static inline void trace_usb_hub_get_port_status(int addr, int nr, int status, int changed) {
    (void)addr;
    (void)nr;
    (void)status;
    (void)changed;
}
#define TRACE_USB_HUB_RESET 0
#define TRACE_USB_HUB_RESET_ENABLED 0
#define TRACE_USB_HUB_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_hub_reset(int addr) {
    (void)addr;
}
#define TRACE_USB_HUB_SET_PORT_FEATURE 0
#define TRACE_USB_HUB_SET_PORT_FEATURE_ENABLED 0
#define TRACE_USB_HUB_SET_PORT_FEATURE_BACKEND_DSTATE() (0)
static inline void trace_usb_hub_set_port_feature(int addr, int nr, const char *f) {
    (void)addr;
    (void)nr;
    (void)f;
}
#define TRACE_USB_HUB_STATUS_REPORT 0
#define TRACE_USB_HUB_STATUS_REPORT_ENABLED 0
#define TRACE_USB_HUB_STATUS_REPORT_BACKEND_DSTATE() (0)
static inline void trace_usb_hub_status_report(int addr, int status) {
    (void)addr;
    (void)status;
}
#define TRACE_USB_MSD_CMD_CANCEL 0
#define TRACE_USB_MSD_CMD_CANCEL_ENABLED 0
#define TRACE_USB_MSD_CMD_CANCEL_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_cmd_cancel(unsigned tag) {
    (void)tag;
}
#define TRACE_USB_MSD_CMD_COMPLETE 0
#define TRACE_USB_MSD_CMD_COMPLETE_ENABLED 0
#define TRACE_USB_MSD_CMD_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_cmd_complete(unsigned status, unsigned tag) {
    (void)status;
    (void)tag;
}
#define TRACE_USB_MSD_CMD_SUBMIT 0
#define TRACE_USB_MSD_CMD_SUBMIT_ENABLED 0
#define TRACE_USB_MSD_CMD_SUBMIT_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_cmd_submit(unsigned lun, unsigned tag, unsigned flags, unsigned len, unsigned data_len) {
    (void)lun;
    (void)tag;
    (void)flags;
    (void)len;
    (void)data_len;
}
#define TRACE_USB_MSD_DATA_IN 0
#define TRACE_USB_MSD_DATA_IN_ENABLED 0
#define TRACE_USB_MSD_DATA_IN_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_data_in(unsigned packet, unsigned remaining, unsigned total) {
    (void)packet;
    (void)remaining;
    (void)total;
}
#define TRACE_USB_MSD_DATA_OUT 0
#define TRACE_USB_MSD_DATA_OUT_ENABLED 0
#define TRACE_USB_MSD_DATA_OUT_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_data_out(unsigned packet, unsigned remaining) {
    (void)packet;
    (void)remaining;
}
#define TRACE_USB_MSD_FATAL_ERROR 0
#define TRACE_USB_MSD_FATAL_ERROR_ENABLED 0
#define TRACE_USB_MSD_FATAL_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_fatal_error(void) {
}
#define TRACE_USB_MSD_MAXLUN 0
#define TRACE_USB_MSD_MAXLUN_ENABLED 0
#define TRACE_USB_MSD_MAXLUN_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_maxlun(unsigned maxlun) {
    (void)maxlun;
}
#define TRACE_USB_MSD_PACKET_ASYNC 0
#define TRACE_USB_MSD_PACKET_ASYNC_ENABLED 0
#define TRACE_USB_MSD_PACKET_ASYNC_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_packet_async(void) {
}
#define TRACE_USB_MSD_PACKET_COMPLETE 0
#define TRACE_USB_MSD_PACKET_COMPLETE_ENABLED 0
#define TRACE_USB_MSD_PACKET_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_packet_complete(void) {
}
#define TRACE_USB_MSD_RESET 0
#define TRACE_USB_MSD_RESET_ENABLED 0
#define TRACE_USB_MSD_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_reset(void) {
}
#define TRACE_USB_MSD_SEND_STATUS 0
#define TRACE_USB_MSD_SEND_STATUS_ENABLED 0
#define TRACE_USB_MSD_SEND_STATUS_BACKEND_DSTATE() (0)
static inline void trace_usb_msd_send_status(unsigned status, unsigned tag, size_t size) {
    (void)status;
    (void)tag;
    (void)size;
}
#define TRACE_USB_MTP_ADD_CHILD 0
#define TRACE_USB_MTP_ADD_CHILD_ENABLED 0
#define TRACE_USB_MTP_ADD_CHILD_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_add_child(int dev, uint32_t handle, const char *path) {
    (void)dev;
    (void)handle;
    (void)path;
}
#define TRACE_USB_MTP_COMMAND 0
#define TRACE_USB_MTP_COMMAND_ENABLED 0
#define TRACE_USB_MTP_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_command(int dev, uint16_t code, uint32_t trans, uint32_t arg0, uint32_t arg1, uint32_t arg2, uint32_t arg3, uint32_t arg4) {
    (void)dev;
    (void)code;
    (void)trans;
    (void)arg0;
    (void)arg1;
    (void)arg2;
    (void)arg3;
    (void)arg4;
}
#define TRACE_USB_MTP_DATA_IN 0
#define TRACE_USB_MTP_DATA_IN_ENABLED 0
#define TRACE_USB_MTP_DATA_IN_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_data_in(int dev, uint32_t trans, uint32_t len) {
    (void)dev;
    (void)trans;
    (void)len;
}
#define TRACE_USB_MTP_ERROR 0
#define TRACE_USB_MTP_ERROR_ENABLED 0
#define TRACE_USB_MTP_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_error(int dev, uint16_t code, uint32_t trans, uint32_t arg0, uint32_t arg1) {
    (void)dev;
    (void)code;
    (void)trans;
    (void)arg0;
    (void)arg1;
}
#define TRACE_USB_MTP_FILE_MONITOR_EVENT 0
#define TRACE_USB_MTP_FILE_MONITOR_EVENT_ENABLED 0
#define TRACE_USB_MTP_FILE_MONITOR_EVENT_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_file_monitor_event(int dev, const char *path, const char *s) {
    (void)dev;
    (void)path;
    (void)s;
}
#define TRACE_USB_MTP_NAK 0
#define TRACE_USB_MTP_NAK_ENABLED 0
#define TRACE_USB_MTP_NAK_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_nak(int dev, uint32_t ep) {
    (void)dev;
    (void)ep;
}
#define TRACE_USB_MTP_OBJECT_ALLOC 0
#define TRACE_USB_MTP_OBJECT_ALLOC_ENABLED 0
#define TRACE_USB_MTP_OBJECT_ALLOC_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_object_alloc(int dev, uint32_t handle, const char *path) {
    (void)dev;
    (void)handle;
    (void)path;
}
#define TRACE_USB_MTP_OBJECT_FREE 0
#define TRACE_USB_MTP_OBJECT_FREE_ENABLED 0
#define TRACE_USB_MTP_OBJECT_FREE_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_object_free(int dev, uint32_t handle, const char *path) {
    (void)dev;
    (void)handle;
    (void)path;
}
#define TRACE_USB_MTP_OP_CLOSE_SESSION 0
#define TRACE_USB_MTP_OP_CLOSE_SESSION_ENABLED 0
#define TRACE_USB_MTP_OP_CLOSE_SESSION_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_close_session(int dev) {
    (void)dev;
}
#define TRACE_USB_MTP_OP_GET_DEVICE_INFO 0
#define TRACE_USB_MTP_OP_GET_DEVICE_INFO_ENABLED 0
#define TRACE_USB_MTP_OP_GET_DEVICE_INFO_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_get_device_info(int dev) {
    (void)dev;
}
#define TRACE_USB_MTP_OP_GET_NUM_OBJECTS 0
#define TRACE_USB_MTP_OP_GET_NUM_OBJECTS_ENABLED 0
#define TRACE_USB_MTP_OP_GET_NUM_OBJECTS_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_get_num_objects(int dev, uint32_t handle, const char *path) {
    (void)dev;
    (void)handle;
    (void)path;
}
#define TRACE_USB_MTP_OP_GET_OBJECT 0
#define TRACE_USB_MTP_OP_GET_OBJECT_ENABLED 0
#define TRACE_USB_MTP_OP_GET_OBJECT_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_get_object(int dev, uint32_t handle, const char *path) {
    (void)dev;
    (void)handle;
    (void)path;
}
#define TRACE_USB_MTP_OP_GET_OBJECT_HANDLES 0
#define TRACE_USB_MTP_OP_GET_OBJECT_HANDLES_ENABLED 0
#define TRACE_USB_MTP_OP_GET_OBJECT_HANDLES_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_get_object_handles(int dev, uint32_t handle, const char *path) {
    (void)dev;
    (void)handle;
    (void)path;
}
#define TRACE_USB_MTP_OP_GET_OBJECT_INFO 0
#define TRACE_USB_MTP_OP_GET_OBJECT_INFO_ENABLED 0
#define TRACE_USB_MTP_OP_GET_OBJECT_INFO_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_get_object_info(int dev, uint32_t handle, const char *path) {
    (void)dev;
    (void)handle;
    (void)path;
}
#define TRACE_USB_MTP_OP_GET_PARTIAL_OBJECT 0
#define TRACE_USB_MTP_OP_GET_PARTIAL_OBJECT_ENABLED 0
#define TRACE_USB_MTP_OP_GET_PARTIAL_OBJECT_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_get_partial_object(int dev, uint32_t handle, const char *path, uint32_t offset, uint32_t length) {
    (void)dev;
    (void)handle;
    (void)path;
    (void)offset;
    (void)length;
}
#define TRACE_USB_MTP_OP_GET_STORAGE_IDS 0
#define TRACE_USB_MTP_OP_GET_STORAGE_IDS_ENABLED 0
#define TRACE_USB_MTP_OP_GET_STORAGE_IDS_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_get_storage_ids(int dev) {
    (void)dev;
}
#define TRACE_USB_MTP_OP_GET_STORAGE_INFO 0
#define TRACE_USB_MTP_OP_GET_STORAGE_INFO_ENABLED 0
#define TRACE_USB_MTP_OP_GET_STORAGE_INFO_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_get_storage_info(int dev) {
    (void)dev;
}
#define TRACE_USB_MTP_OP_OPEN_SESSION 0
#define TRACE_USB_MTP_OP_OPEN_SESSION_ENABLED 0
#define TRACE_USB_MTP_OP_OPEN_SESSION_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_open_session(int dev) {
    (void)dev;
}
#define TRACE_USB_MTP_OP_UNKNOWN 0
#define TRACE_USB_MTP_OP_UNKNOWN_ENABLED 0
#define TRACE_USB_MTP_OP_UNKNOWN_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_op_unknown(int dev, uint32_t code) {
    (void)dev;
    (void)code;
}
#define TRACE_USB_MTP_RESET 0
#define TRACE_USB_MTP_RESET_ENABLED 0
#define TRACE_USB_MTP_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_reset(int addr) {
    (void)addr;
}
#define TRACE_USB_MTP_STALL 0
#define TRACE_USB_MTP_STALL_ENABLED 0
#define TRACE_USB_MTP_STALL_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_stall(int dev, const char *reason) {
    (void)dev;
    (void)reason;
}
#define TRACE_USB_MTP_SUCCESS 0
#define TRACE_USB_MTP_SUCCESS_ENABLED 0
#define TRACE_USB_MTP_SUCCESS_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_success(int dev, uint32_t trans, uint32_t arg0, uint32_t arg1) {
    (void)dev;
    (void)trans;
    (void)arg0;
    (void)arg1;
}
#define TRACE_USB_MTP_XFER 0
#define TRACE_USB_MTP_XFER_ENABLED 0
#define TRACE_USB_MTP_XFER_BACKEND_DSTATE() (0)
static inline void trace_usb_mtp_xfer(int dev, uint32_t ep, uint32_t dlen, uint32_t plen) {
    (void)dev;
    (void)ep;
    (void)dlen;
    (void)plen;
}
#define TRACE_USB_OHCI_ASYNC_COMPLETE 0
#define TRACE_USB_OHCI_ASYNC_COMPLETE_ENABLED 0
#define TRACE_USB_OHCI_ASYNC_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_async_complete(void) {
}
#define TRACE_USB_OHCI_DIE 0
#define TRACE_USB_OHCI_DIE_ENABLED 0
#define TRACE_USB_OHCI_DIE_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_die(void) {
}
#define TRACE_USB_OHCI_ED_PKT 0
#define TRACE_USB_OHCI_ED_PKT_ENABLED 0
#define TRACE_USB_OHCI_ED_PKT_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_ed_pkt(uint32_t cur, int h, int c, uint32_t head, uint32_t tail, uint32_t next) {
    (void)cur;
    (void)h;
    (void)c;
    (void)head;
    (void)tail;
    (void)next;
}
#define TRACE_USB_OHCI_ED_PKT_FLAGS 0
#define TRACE_USB_OHCI_ED_PKT_FLAGS_ENABLED 0
#define TRACE_USB_OHCI_ED_PKT_FLAGS_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_ed_pkt_flags(uint32_t fa, uint32_t en, uint32_t d, int s, int k, int f, uint32_t mps) {
    (void)fa;
    (void)en;
    (void)d;
    (void)s;
    (void)k;
    (void)f;
    (void)mps;
}
#define TRACE_USB_OHCI_ED_READ_ERROR 0
#define TRACE_USB_OHCI_ED_READ_ERROR_ENABLED 0
#define TRACE_USB_OHCI_ED_READ_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_ed_read_error(uint32_t addr) {
    (void)addr;
}
#define TRACE_USB_OHCI_EXIT 0
#define TRACE_USB_OHCI_EXIT_ENABLED 0
#define TRACE_USB_OHCI_EXIT_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_exit(const char *s) {
    (void)s;
}
#define TRACE_USB_OHCI_HCCA_READ_ERROR 0
#define TRACE_USB_OHCI_HCCA_READ_ERROR_ENABLED 0
#define TRACE_USB_OHCI_HCCA_READ_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_hcca_read_error(uint32_t addr) {
    (void)addr;
}
#define TRACE_USB_OHCI_HUB_POWER_DOWN 0
#define TRACE_USB_OHCI_HUB_POWER_DOWN_ENABLED 0
#define TRACE_USB_OHCI_HUB_POWER_DOWN_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_hub_power_down(void) {
}
#define TRACE_USB_OHCI_HUB_POWER_UP 0
#define TRACE_USB_OHCI_HUB_POWER_UP_ENABLED 0
#define TRACE_USB_OHCI_HUB_POWER_UP_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_hub_power_up(void) {
}
#define TRACE_USB_OHCI_INIT_TIME 0
#define TRACE_USB_OHCI_INIT_TIME_ENABLED 0
#define TRACE_USB_OHCI_INIT_TIME_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_init_time(int64_t frametime, int64_t bittime) {
    (void)frametime;
    (void)bittime;
}
#define TRACE_USB_OHCI_ISO_TD_BAD_BP_BE 0
#define TRACE_USB_OHCI_ISO_TD_BAD_BP_BE_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_BAD_BP_BE_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_bad_bp_be(uint32_t bp, uint32_t be) {
    (void)bp;
    (void)be;
}
#define TRACE_USB_OHCI_ISO_TD_BAD_CC_NOT_ACCESSED 0
#define TRACE_USB_OHCI_ISO_TD_BAD_CC_NOT_ACCESSED_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_BAD_CC_NOT_ACCESSED_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_bad_cc_not_accessed(uint32_t start, uint32_t next) {
    (void)start;
    (void)next;
}
#define TRACE_USB_OHCI_ISO_TD_BAD_CC_OVERRUN 0
#define TRACE_USB_OHCI_ISO_TD_BAD_CC_OVERRUN_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_BAD_CC_OVERRUN_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_bad_cc_overrun(uint32_t start, uint32_t next) {
    (void)start;
    (void)next;
}
#define TRACE_USB_OHCI_ISO_TD_BAD_DIRECTION 0
#define TRACE_USB_OHCI_ISO_TD_BAD_DIRECTION_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_BAD_DIRECTION_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_bad_direction(int dir) {
    (void)dir;
}
#define TRACE_USB_OHCI_ISO_TD_BAD_RESPONSE 0
#define TRACE_USB_OHCI_ISO_TD_BAD_RESPONSE_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_BAD_RESPONSE_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_bad_response(int ret) {
    (void)ret;
}
#define TRACE_USB_OHCI_ISO_TD_DATA_OVERRUN 0
#define TRACE_USB_OHCI_ISO_TD_DATA_OVERRUN_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_DATA_OVERRUN_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_data_overrun(int ret, ssize_t len) {
    (void)ret;
    (void)len;
}
#define TRACE_USB_OHCI_ISO_TD_DATA_UNDERRUN 0
#define TRACE_USB_OHCI_ISO_TD_DATA_UNDERRUN_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_DATA_UNDERRUN_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_data_underrun(int ret) {
    (void)ret;
}
#define TRACE_USB_OHCI_ISO_TD_HEAD 0
#define TRACE_USB_OHCI_ISO_TD_HEAD_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_HEAD_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_head(uint32_t head, uint32_t tail, uint32_t flags, uint32_t bp, uint32_t next, uint32_t be, uint32_t framenum, uint32_t startframe, uint32_t framecount, int rel_frame_num) {
    (void)head;
    (void)tail;
    (void)flags;
    (void)bp;
    (void)next;
    (void)be;
    (void)framenum;
    (void)startframe;
    (void)framecount;
    (void)rel_frame_num;
}
#define TRACE_USB_OHCI_ISO_TD_HEAD_OFFSET 0
#define TRACE_USB_OHCI_ISO_TD_HEAD_OFFSET_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_HEAD_OFFSET_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_head_offset(uint32_t o0, uint32_t o1, uint32_t o2, uint32_t o3, uint32_t o4, uint32_t o5, uint32_t o6, uint32_t o7) {
    (void)o0;
    (void)o1;
    (void)o2;
    (void)o3;
    (void)o4;
    (void)o5;
    (void)o6;
    (void)o7;
}
#define TRACE_USB_OHCI_ISO_TD_NAK 0
#define TRACE_USB_OHCI_ISO_TD_NAK_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_NAK_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_nak(int ret) {
    (void)ret;
}
#define TRACE_USB_OHCI_ISO_TD_READ_FAILED 0
#define TRACE_USB_OHCI_ISO_TD_READ_FAILED_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_READ_FAILED_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_read_failed(uint32_t addr) {
    (void)addr;
}
#define TRACE_USB_OHCI_ISO_TD_RELATIVE_FRAME_NUMBER_BIG 0
#define TRACE_USB_OHCI_ISO_TD_RELATIVE_FRAME_NUMBER_BIG_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_RELATIVE_FRAME_NUMBER_BIG_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_relative_frame_number_big(int rel, int count) {
    (void)rel;
    (void)count;
}
#define TRACE_USB_OHCI_ISO_TD_RELATIVE_FRAME_NUMBER_NEG 0
#define TRACE_USB_OHCI_ISO_TD_RELATIVE_FRAME_NUMBER_NEG_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_RELATIVE_FRAME_NUMBER_NEG_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_relative_frame_number_neg(int rel) {
    (void)rel;
}
#define TRACE_USB_OHCI_ISO_TD_SO 0
#define TRACE_USB_OHCI_ISO_TD_SO_ENABLED 0
#define TRACE_USB_OHCI_ISO_TD_SO_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_iso_td_so(uint32_t so, uint32_t eo, uint32_t s, uint32_t e, const char *str, ssize_t len, int ret) {
    (void)so;
    (void)eo;
    (void)s;
    (void)e;
    (void)str;
    (void)len;
    (void)ret;
}
#define TRACE_USB_OHCI_MEM_PORT_READ 0
#define TRACE_USB_OHCI_MEM_PORT_READ_ENABLED 0
#define TRACE_USB_OHCI_MEM_PORT_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_mem_port_read(uint32_t size, const char *name, uint32_t port, uint32_t addr, uint32_t offs, uint32_t val) {
    (void)size;
    (void)name;
    (void)port;
    (void)addr;
    (void)offs;
    (void)val;
}
#define TRACE_USB_OHCI_MEM_PORT_WRITE 0
#define TRACE_USB_OHCI_MEM_PORT_WRITE_ENABLED 0
#define TRACE_USB_OHCI_MEM_PORT_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_mem_port_write(uint32_t size, const char *name, uint32_t port, uint32_t addr, uint32_t offs, uint32_t val) {
    (void)size;
    (void)name;
    (void)port;
    (void)addr;
    (void)offs;
    (void)val;
}
#define TRACE_USB_OHCI_MEM_READ 0
#define TRACE_USB_OHCI_MEM_READ_ENABLED 0
#define TRACE_USB_OHCI_MEM_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_mem_read(uint32_t size, const char *name, uint32_t addr, uint32_t offs, uint32_t val) {
    (void)size;
    (void)name;
    (void)addr;
    (void)offs;
    (void)val;
}
#define TRACE_USB_OHCI_MEM_READ_BAD_OFFSET 0
#define TRACE_USB_OHCI_MEM_READ_BAD_OFFSET_ENABLED 0
#define TRACE_USB_OHCI_MEM_READ_BAD_OFFSET_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_mem_read_bad_offset(uint32_t addr) {
    (void)addr;
}
#define TRACE_USB_OHCI_MEM_READ_UNALIGNED 0
#define TRACE_USB_OHCI_MEM_READ_UNALIGNED_ENABLED 0
#define TRACE_USB_OHCI_MEM_READ_UNALIGNED_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_mem_read_unaligned(uint32_t addr) {
    (void)addr;
}
#define TRACE_USB_OHCI_MEM_WRITE 0
#define TRACE_USB_OHCI_MEM_WRITE_ENABLED 0
#define TRACE_USB_OHCI_MEM_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_mem_write(uint32_t size, const char *name, uint32_t addr, uint32_t offs, uint32_t val) {
    (void)size;
    (void)name;
    (void)addr;
    (void)offs;
    (void)val;
}
#define TRACE_USB_OHCI_MEM_WRITE_BAD_OFFSET 0
#define TRACE_USB_OHCI_MEM_WRITE_BAD_OFFSET_ENABLED 0
#define TRACE_USB_OHCI_MEM_WRITE_BAD_OFFSET_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_mem_write_bad_offset(uint32_t addr) {
    (void)addr;
}
#define TRACE_USB_OHCI_MEM_WRITE_UNALIGNED 0
#define TRACE_USB_OHCI_MEM_WRITE_UNALIGNED_ENABLED 0
#define TRACE_USB_OHCI_MEM_WRITE_UNALIGNED_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_mem_write_unaligned(uint32_t addr) {
    (void)addr;
}
#define TRACE_USB_OHCI_PORT_ATTACH 0
#define TRACE_USB_OHCI_PORT_ATTACH_ENABLED 0
#define TRACE_USB_OHCI_PORT_ATTACH_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_port_attach(int index) {
    (void)index;
}
#define TRACE_USB_OHCI_PORT_DETACH 0
#define TRACE_USB_OHCI_PORT_DETACH_ENABLED 0
#define TRACE_USB_OHCI_PORT_DETACH_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_port_detach(int index) {
    (void)index;
}
#define TRACE_USB_OHCI_PORT_RESET 0
#define TRACE_USB_OHCI_PORT_RESET_ENABLED 0
#define TRACE_USB_OHCI_PORT_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_port_reset(int index) {
    (void)index;
}
#define TRACE_USB_OHCI_PORT_SUSPEND 0
#define TRACE_USB_OHCI_PORT_SUSPEND_ENABLED 0
#define TRACE_USB_OHCI_PORT_SUSPEND_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_port_suspend(int index) {
    (void)index;
}
#define TRACE_USB_OHCI_PORT_WAKEUP 0
#define TRACE_USB_OHCI_PORT_WAKEUP_ENABLED 0
#define TRACE_USB_OHCI_PORT_WAKEUP_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_port_wakeup(int index) {
    (void)index;
}
#define TRACE_USB_OHCI_PROCESS_LISTS 0
#define TRACE_USB_OHCI_PROCESS_LISTS_ENABLED 0
#define TRACE_USB_OHCI_PROCESS_LISTS_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_process_lists(uint32_t head, uint32_t cur) {
    (void)head;
    (void)cur;
}
#define TRACE_USB_OHCI_REMOTE_WAKEUP 0
#define TRACE_USB_OHCI_REMOTE_WAKEUP_ENABLED 0
#define TRACE_USB_OHCI_REMOTE_WAKEUP_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_remote_wakeup(const char *s) {
    (void)s;
}
#define TRACE_USB_OHCI_RESET 0
#define TRACE_USB_OHCI_RESET_ENABLED 0
#define TRACE_USB_OHCI_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_reset(const char *s) {
    (void)s;
}
#define TRACE_USB_OHCI_RESUME 0
#define TRACE_USB_OHCI_RESUME_ENABLED 0
#define TRACE_USB_OHCI_RESUME_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_resume(const char *s) {
    (void)s;
}
#define TRACE_USB_OHCI_SET_CTL 0
#define TRACE_USB_OHCI_SET_CTL_ENABLED 0
#define TRACE_USB_OHCI_SET_CTL_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_set_ctl(const char *s, uint32_t new_state) {
    (void)s;
    (void)new_state;
}
#define TRACE_USB_OHCI_SET_FRAME_INTERVAL 0
#define TRACE_USB_OHCI_SET_FRAME_INTERVAL_ENABLED 0
#define TRACE_USB_OHCI_SET_FRAME_INTERVAL_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_set_frame_interval(const char *name, uint16_t fi_x, uint16_t fi_u) {
    (void)name;
    (void)fi_x;
    (void)fi_u;
}
#define TRACE_USB_OHCI_START 0
#define TRACE_USB_OHCI_START_ENABLED 0
#define TRACE_USB_OHCI_START_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_start(const char *s) {
    (void)s;
}
#define TRACE_USB_OHCI_STOP 0
#define TRACE_USB_OHCI_STOP_ENABLED 0
#define TRACE_USB_OHCI_STOP_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_stop(const char *s) {
    (void)s;
}
#define TRACE_USB_OHCI_TD_BABBLE 0
#define TRACE_USB_OHCI_TD_BABBLE_ENABLED 0
#define TRACE_USB_OHCI_TD_BABBLE_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_babble(void) {
}
#define TRACE_USB_OHCI_TD_BAD_BUF 0
#define TRACE_USB_OHCI_TD_BAD_BUF_ENABLED 0
#define TRACE_USB_OHCI_TD_BAD_BUF_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_bad_buf(uint32_t cbp, uint32_t be) {
    (void)cbp;
    (void)be;
}
#define TRACE_USB_OHCI_TD_BAD_DEVICE_RESPONSE 0
#define TRACE_USB_OHCI_TD_BAD_DEVICE_RESPONSE_ENABLED 0
#define TRACE_USB_OHCI_TD_BAD_DEVICE_RESPONSE_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_bad_device_response(int rc) {
    (void)rc;
}
#define TRACE_USB_OHCI_TD_BAD_DIRECTION 0
#define TRACE_USB_OHCI_TD_BAD_DIRECTION_ENABLED 0
#define TRACE_USB_OHCI_TD_BAD_DIRECTION_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_bad_direction(int dir) {
    (void)dir;
}
#define TRACE_USB_OHCI_TD_BAD_PID 0
#define TRACE_USB_OHCI_TD_BAD_PID_ENABLED 0
#define TRACE_USB_OHCI_TD_BAD_PID_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_bad_pid(const char *s, uint32_t edf, uint32_t tdf) {
    (void)s;
    (void)edf;
    (void)tdf;
}
#define TRACE_USB_OHCI_TD_DEV_ERROR 0
#define TRACE_USB_OHCI_TD_DEV_ERROR_ENABLED 0
#define TRACE_USB_OHCI_TD_DEV_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_dev_error(void) {
}
#define TRACE_USB_OHCI_TD_NAK 0
#define TRACE_USB_OHCI_TD_NAK_ENABLED 0
#define TRACE_USB_OHCI_TD_NAK_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_nak(void) {
}
#define TRACE_USB_OHCI_TD_PACKET_STATUS 0
#define TRACE_USB_OHCI_TD_PACKET_STATUS_ENABLED 0
#define TRACE_USB_OHCI_TD_PACKET_STATUS_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_packet_status(int status) {
    (void)status;
}
#define TRACE_USB_OHCI_TD_PKT_FULL 0
#define TRACE_USB_OHCI_TD_PKT_FULL_ENABLED 0
#define TRACE_USB_OHCI_TD_PKT_FULL_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_pkt_full(const char *dir, const char *buf) {
    (void)dir;
    (void)buf;
}
#define TRACE_USB_OHCI_TD_PKT_HDR 0
#define TRACE_USB_OHCI_TD_PKT_HDR_ENABLED 0
#define TRACE_USB_OHCI_TD_PKT_HDR_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_pkt_hdr(uint32_t addr, int64_t pktlen, int64_t len, const char *s, int flag_r, uint32_t cbp, uint32_t be) {
    (void)addr;
    (void)pktlen;
    (void)len;
    (void)s;
    (void)flag_r;
    (void)cbp;
    (void)be;
}
#define TRACE_USB_OHCI_TD_PKT_SHORT 0
#define TRACE_USB_OHCI_TD_PKT_SHORT_ENABLED 0
#define TRACE_USB_OHCI_TD_PKT_SHORT_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_pkt_short(const char *dir, const char *buf) {
    (void)dir;
    (void)buf;
}
#define TRACE_USB_OHCI_TD_READ_ERROR 0
#define TRACE_USB_OHCI_TD_READ_ERROR_ENABLED 0
#define TRACE_USB_OHCI_TD_READ_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_read_error(uint32_t addr) {
    (void)addr;
}
#define TRACE_USB_OHCI_TD_SKIP_ASYNC 0
#define TRACE_USB_OHCI_TD_SKIP_ASYNC_ENABLED 0
#define TRACE_USB_OHCI_TD_SKIP_ASYNC_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_skip_async(void) {
}
#define TRACE_USB_OHCI_TD_STALL 0
#define TRACE_USB_OHCI_TD_STALL_ENABLED 0
#define TRACE_USB_OHCI_TD_STALL_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_stall(void) {
}
#define TRACE_USB_OHCI_TD_TOO_MANY_PENDING 0
#define TRACE_USB_OHCI_TD_TOO_MANY_PENDING_ENABLED 0
#define TRACE_USB_OHCI_TD_TOO_MANY_PENDING_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_too_many_pending(int ep) {
    (void)ep;
}
#define TRACE_USB_OHCI_TD_UNDERRUN 0
#define TRACE_USB_OHCI_TD_UNDERRUN_ENABLED 0
#define TRACE_USB_OHCI_TD_UNDERRUN_BACKEND_DSTATE() (0)
static inline void trace_usb_ohci_td_underrun(void) {
}
#define TRACE_USB_PACKET_STATE_CHANGE 0
#define TRACE_USB_PACKET_STATE_CHANGE_ENABLED 0
#define TRACE_USB_PACKET_STATE_CHANGE_BACKEND_DSTATE() (0)
static inline void trace_usb_packet_state_change(int bus, const char *port, int ep, void *p, const char *o, const char *n) {
    (void)bus;
    (void)port;
    (void)ep;
    (void)p;
    (void)o;
    (void)n;
}
#define TRACE_USB_PACKET_STATE_FAULT 0
#define TRACE_USB_PACKET_STATE_FAULT_ENABLED 0
#define TRACE_USB_PACKET_STATE_FAULT_BACKEND_DSTATE() (0)
static inline void trace_usb_packet_state_fault(int bus, const char *port, int ep, void *p, const char *o, const char *n) {
    (void)bus;
    (void)port;
    (void)ep;
    (void)p;
    (void)o;
    (void)n;
}
#define TRACE_USB_PORT_ATTACH 0
#define TRACE_USB_PORT_ATTACH_ENABLED 0
#define TRACE_USB_PORT_ATTACH_BACKEND_DSTATE() (0)
static inline void trace_usb_port_attach(int bus, const char *port, const char *devspeed, const char *portspeed) {
    (void)bus;
    (void)port;
    (void)devspeed;
    (void)portspeed;
}
#define TRACE_USB_PORT_CLAIM 0
#define TRACE_USB_PORT_CLAIM_ENABLED 0
#define TRACE_USB_PORT_CLAIM_BACKEND_DSTATE() (0)
static inline void trace_usb_port_claim(int bus, const char *port) {
    (void)bus;
    (void)port;
}
#define TRACE_USB_PORT_DETACH 0
#define TRACE_USB_PORT_DETACH_ENABLED 0
#define TRACE_USB_PORT_DETACH_BACKEND_DSTATE() (0)
static inline void trace_usb_port_detach(int bus, const char *port) {
    (void)bus;
    (void)port;
}
#define TRACE_USB_PORT_RELEASE 0
#define TRACE_USB_PORT_RELEASE_ENABLED 0
#define TRACE_USB_PORT_RELEASE_BACKEND_DSTATE() (0)
static inline void trace_usb_port_release(int bus, const char *port) {
    (void)bus;
    (void)port;
}
#define TRACE_USB_SERIAL_BAD_TOKEN 0
#define TRACE_USB_SERIAL_BAD_TOKEN_ENABLED 0
#define TRACE_USB_SERIAL_BAD_TOKEN_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_bad_token(int bus, int addr) {
    (void)bus;
    (void)addr;
}
#define TRACE_USB_SERIAL_HANDLE_CONTROL 0
#define TRACE_USB_SERIAL_HANDLE_CONTROL_ENABLED 0
#define TRACE_USB_SERIAL_HANDLE_CONTROL_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_handle_control(int bus, int addr, int request, int value) {
    (void)bus;
    (void)addr;
    (void)request;
    (void)value;
}
#define TRACE_USB_SERIAL_RESET 0
#define TRACE_USB_SERIAL_RESET_ENABLED 0
#define TRACE_USB_SERIAL_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_reset(int bus, int addr) {
    (void)bus;
    (void)addr;
}
#define TRACE_USB_SERIAL_SET_BAUD 0
#define TRACE_USB_SERIAL_SET_BAUD_ENABLED 0
#define TRACE_USB_SERIAL_SET_BAUD_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_set_baud(int bus, int addr, int baud) {
    (void)bus;
    (void)addr;
    (void)baud;
}
#define TRACE_USB_SERIAL_SET_DATA 0
#define TRACE_USB_SERIAL_SET_DATA_ENABLED 0
#define TRACE_USB_SERIAL_SET_DATA_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_set_data(int bus, int addr, int parity, int data, int stop) {
    (void)bus;
    (void)addr;
    (void)parity;
    (void)data;
    (void)stop;
}
#define TRACE_USB_SERIAL_SET_FLOW_CONTROL 0
#define TRACE_USB_SERIAL_SET_FLOW_CONTROL_ENABLED 0
#define TRACE_USB_SERIAL_SET_FLOW_CONTROL_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_set_flow_control(int bus, int addr, int index) {
    (void)bus;
    (void)addr;
    (void)index;
}
#define TRACE_USB_SERIAL_SET_XONXOFF 0
#define TRACE_USB_SERIAL_SET_XONXOFF_ENABLED 0
#define TRACE_USB_SERIAL_SET_XONXOFF_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_set_xonxoff(int bus, int addr, uint8_t xon, uint8_t xoff) {
    (void)bus;
    (void)addr;
    (void)xon;
    (void)xoff;
}
#define TRACE_USB_SERIAL_UNSUPPORTED_CONTROL 0
#define TRACE_USB_SERIAL_UNSUPPORTED_CONTROL_ENABLED 0
#define TRACE_USB_SERIAL_UNSUPPORTED_CONTROL_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_unsupported_control(int bus, int addr, int request, int value) {
    (void)bus;
    (void)addr;
    (void)request;
    (void)value;
}
#define TRACE_USB_SERIAL_UNSUPPORTED_DATA_BITS 0
#define TRACE_USB_SERIAL_UNSUPPORTED_DATA_BITS_ENABLED 0
#define TRACE_USB_SERIAL_UNSUPPORTED_DATA_BITS_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_unsupported_data_bits(int bus, int addr, int value) {
    (void)bus;
    (void)addr;
    (void)value;
}
#define TRACE_USB_SERIAL_UNSUPPORTED_PARITY 0
#define TRACE_USB_SERIAL_UNSUPPORTED_PARITY_ENABLED 0
#define TRACE_USB_SERIAL_UNSUPPORTED_PARITY_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_unsupported_parity(int bus, int addr, int value) {
    (void)bus;
    (void)addr;
    (void)value;
}
#define TRACE_USB_SERIAL_UNSUPPORTED_STOPBITS 0
#define TRACE_USB_SERIAL_UNSUPPORTED_STOPBITS_ENABLED 0
#define TRACE_USB_SERIAL_UNSUPPORTED_STOPBITS_BACKEND_DSTATE() (0)
static inline void trace_usb_serial_unsupported_stopbits(int bus, int addr, int value) {
    (void)bus;
    (void)addr;
    (void)value;
}
#define TRACE_USB_SET_ADDR 0
#define TRACE_USB_SET_ADDR_ENABLED 0
#define TRACE_USB_SET_ADDR_BACKEND_DSTATE() (0)
static inline void trace_usb_set_addr(int addr) {
    (void)addr;
}
#define TRACE_USB_SET_CONFIG 0
#define TRACE_USB_SET_CONFIG_ENABLED 0
#define TRACE_USB_SET_CONFIG_BACKEND_DSTATE() (0)
static inline void trace_usb_set_config(int addr, int config, int ret) {
    (void)addr;
    (void)config;
    (void)ret;
}
#define TRACE_USB_SET_DEVICE_FEATURE 0
#define TRACE_USB_SET_DEVICE_FEATURE_ENABLED 0
#define TRACE_USB_SET_DEVICE_FEATURE_BACKEND_DSTATE() (0)
static inline void trace_usb_set_device_feature(int addr, int feature, int ret) {
    (void)addr;
    (void)feature;
    (void)ret;
}
#define TRACE_USB_SET_INTERFACE 0
#define TRACE_USB_SET_INTERFACE_ENABLED 0
#define TRACE_USB_SET_INTERFACE_BACKEND_DSTATE() (0)
static inline void trace_usb_set_interface(int addr, int iface, int alt, int ret) {
    (void)addr;
    (void)iface;
    (void)alt;
    (void)ret;
}
#define TRACE_USB_UAS_COMMAND 0
#define TRACE_USB_UAS_COMMAND_ENABLED 0
#define TRACE_USB_UAS_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_command(int addr, uint16_t tag, int lun, uint32_t lun64_1, uint32_t lun64_2) {
    (void)addr;
    (void)tag;
    (void)lun;
    (void)lun64_1;
    (void)lun64_2;
}
#define TRACE_USB_UAS_READ_READY 0
#define TRACE_USB_UAS_READ_READY_ENABLED 0
#define TRACE_USB_UAS_READ_READY_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_read_ready(int addr, uint16_t tag) {
    (void)addr;
    (void)tag;
}
#define TRACE_USB_UAS_RESET 0
#define TRACE_USB_UAS_RESET_ENABLED 0
#define TRACE_USB_UAS_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_reset(int addr) {
    (void)addr;
}
#define TRACE_USB_UAS_RESPONSE 0
#define TRACE_USB_UAS_RESPONSE_ENABLED 0
#define TRACE_USB_UAS_RESPONSE_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_response(int addr, uint16_t tag, uint8_t code) {
    (void)addr;
    (void)tag;
    (void)code;
}
#define TRACE_USB_UAS_SCSI_COMPLETE 0
#define TRACE_USB_UAS_SCSI_COMPLETE_ENABLED 0
#define TRACE_USB_UAS_SCSI_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_scsi_complete(int addr, uint16_t tag, uint32_t status, uint32_t resid) {
    (void)addr;
    (void)tag;
    (void)status;
    (void)resid;
}
#define TRACE_USB_UAS_SCSI_DATA 0
#define TRACE_USB_UAS_SCSI_DATA_ENABLED 0
#define TRACE_USB_UAS_SCSI_DATA_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_scsi_data(int addr, uint16_t tag, uint32_t bytes) {
    (void)addr;
    (void)tag;
    (void)bytes;
}
#define TRACE_USB_UAS_SENSE 0
#define TRACE_USB_UAS_SENSE_ENABLED 0
#define TRACE_USB_UAS_SENSE_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_sense(int addr, uint16_t tag, uint8_t status) {
    (void)addr;
    (void)tag;
    (void)status;
}
#define TRACE_USB_UAS_TMF_ABORT_TASK 0
#define TRACE_USB_UAS_TMF_ABORT_TASK_ENABLED 0
#define TRACE_USB_UAS_TMF_ABORT_TASK_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_tmf_abort_task(int addr, uint16_t tag, uint16_t task_tag) {
    (void)addr;
    (void)tag;
    (void)task_tag;
}
#define TRACE_USB_UAS_TMF_LOGICAL_UNIT_RESET 0
#define TRACE_USB_UAS_TMF_LOGICAL_UNIT_RESET_ENABLED 0
#define TRACE_USB_UAS_TMF_LOGICAL_UNIT_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_tmf_logical_unit_reset(int addr, uint16_t tag, int lun) {
    (void)addr;
    (void)tag;
    (void)lun;
}
#define TRACE_USB_UAS_TMF_UNSUPPORTED 0
#define TRACE_USB_UAS_TMF_UNSUPPORTED_ENABLED 0
#define TRACE_USB_UAS_TMF_UNSUPPORTED_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_tmf_unsupported(int addr, uint16_t tag, uint32_t function) {
    (void)addr;
    (void)tag;
    (void)function;
}
#define TRACE_USB_UAS_WRITE_READY 0
#define TRACE_USB_UAS_WRITE_READY_ENABLED 0
#define TRACE_USB_UAS_WRITE_READY_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_write_ready(int addr, uint16_t tag) {
    (void)addr;
    (void)tag;
}
#define TRACE_USB_UAS_XFER_DATA 0
#define TRACE_USB_UAS_XFER_DATA_ENABLED 0
#define TRACE_USB_UAS_XFER_DATA_BACKEND_DSTATE() (0)
static inline void trace_usb_uas_xfer_data(int addr, uint16_t tag, uint32_t copy, uint32_t uoff, uint32_t usize, uint32_t soff, uint32_t ssize) {
    (void)addr;
    (void)tag;
    (void)copy;
    (void)uoff;
    (void)usize;
    (void)soff;
    (void)ssize;
}
#define TRACE_USB_UHCI_EXIT 0
#define TRACE_USB_UHCI_EXIT_ENABLED 0
#define TRACE_USB_UHCI_EXIT_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_exit(void) {
}
#define TRACE_USB_UHCI_FRAME_LOOP_CONTINUE 0
#define TRACE_USB_UHCI_FRAME_LOOP_CONTINUE_ENABLED 0
#define TRACE_USB_UHCI_FRAME_LOOP_CONTINUE_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_frame_loop_continue(void) {
}
#define TRACE_USB_UHCI_FRAME_LOOP_STOP_IDLE 0
#define TRACE_USB_UHCI_FRAME_LOOP_STOP_IDLE_ENABLED 0
#define TRACE_USB_UHCI_FRAME_LOOP_STOP_IDLE_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_frame_loop_stop_idle(void) {
}
#define TRACE_USB_UHCI_FRAME_START 0
#define TRACE_USB_UHCI_FRAME_START_ENABLED 0
#define TRACE_USB_UHCI_FRAME_START_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_frame_start(uint32_t num) {
    (void)num;
}
#define TRACE_USB_UHCI_FRAME_STOP_BANDWIDTH 0
#define TRACE_USB_UHCI_FRAME_STOP_BANDWIDTH_ENABLED 0
#define TRACE_USB_UHCI_FRAME_STOP_BANDWIDTH_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_frame_stop_bandwidth(void) {
}
#define TRACE_USB_UHCI_MMIO_READW 0
#define TRACE_USB_UHCI_MMIO_READW_ENABLED 0
#define TRACE_USB_UHCI_MMIO_READW_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_mmio_readw(uint32_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_USB_UHCI_MMIO_WRITEW 0
#define TRACE_USB_UHCI_MMIO_WRITEW_ENABLED 0
#define TRACE_USB_UHCI_MMIO_WRITEW_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_mmio_writew(uint32_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_USB_UHCI_PACKET_ADD 0
#define TRACE_USB_UHCI_PACKET_ADD_ENABLED 0
#define TRACE_USB_UHCI_PACKET_ADD_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_add(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_PACKET_CANCEL 0
#define TRACE_USB_UHCI_PACKET_CANCEL_ENABLED 0
#define TRACE_USB_UHCI_PACKET_CANCEL_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_cancel(uint32_t token, uint32_t addr, int done) {
    (void)token;
    (void)addr;
    (void)done;
}
#define TRACE_USB_UHCI_PACKET_COMPLETE_BABBLE 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_BABBLE_ENABLED 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_BABBLE_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_complete_babble(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_PACKET_COMPLETE_ERROR 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_ERROR_ENABLED 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_complete_error(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_PACKET_COMPLETE_SHORTXFER 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_SHORTXFER_ENABLED 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_SHORTXFER_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_complete_shortxfer(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_PACKET_COMPLETE_STALL 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_STALL_ENABLED 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_STALL_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_complete_stall(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_PACKET_COMPLETE_SUCCESS 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_SUCCESS_ENABLED 0
#define TRACE_USB_UHCI_PACKET_COMPLETE_SUCCESS_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_complete_success(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_PACKET_DEL 0
#define TRACE_USB_UHCI_PACKET_DEL_ENABLED 0
#define TRACE_USB_UHCI_PACKET_DEL_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_del(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_PACKET_LINK_ASYNC 0
#define TRACE_USB_UHCI_PACKET_LINK_ASYNC_ENABLED 0
#define TRACE_USB_UHCI_PACKET_LINK_ASYNC_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_link_async(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_PACKET_UNLINK_ASYNC 0
#define TRACE_USB_UHCI_PACKET_UNLINK_ASYNC_ENABLED 0
#define TRACE_USB_UHCI_PACKET_UNLINK_ASYNC_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_packet_unlink_async(uint32_t token, uint32_t addr) {
    (void)token;
    (void)addr;
}
#define TRACE_USB_UHCI_QH_LOAD 0
#define TRACE_USB_UHCI_QH_LOAD_ENABLED 0
#define TRACE_USB_UHCI_QH_LOAD_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_qh_load(uint32_t qh) {
    (void)qh;
}
#define TRACE_USB_UHCI_QUEUE_ADD 0
#define TRACE_USB_UHCI_QUEUE_ADD_ENABLED 0
#define TRACE_USB_UHCI_QUEUE_ADD_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_queue_add(uint32_t token) {
    (void)token;
}
#define TRACE_USB_UHCI_QUEUE_DEL 0
#define TRACE_USB_UHCI_QUEUE_DEL_ENABLED 0
#define TRACE_USB_UHCI_QUEUE_DEL_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_queue_del(uint32_t token, const char *reason) {
    (void)token;
    (void)reason;
}
#define TRACE_USB_UHCI_RESET 0
#define TRACE_USB_UHCI_RESET_ENABLED 0
#define TRACE_USB_UHCI_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_reset(void) {
}
#define TRACE_USB_UHCI_SCHEDULE_START 0
#define TRACE_USB_UHCI_SCHEDULE_START_ENABLED 0
#define TRACE_USB_UHCI_SCHEDULE_START_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_schedule_start(void) {
}
#define TRACE_USB_UHCI_SCHEDULE_STOP 0
#define TRACE_USB_UHCI_SCHEDULE_STOP_ENABLED 0
#define TRACE_USB_UHCI_SCHEDULE_STOP_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_schedule_stop(void) {
}
#define TRACE_USB_UHCI_TD_ASYNC 0
#define TRACE_USB_UHCI_TD_ASYNC_ENABLED 0
#define TRACE_USB_UHCI_TD_ASYNC_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_td_async(uint32_t qh, uint32_t td) {
    (void)qh;
    (void)td;
}
#define TRACE_USB_UHCI_TD_COMPLETE 0
#define TRACE_USB_UHCI_TD_COMPLETE_ENABLED 0
#define TRACE_USB_UHCI_TD_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_td_complete(uint32_t qh, uint32_t td) {
    (void)qh;
    (void)td;
}
#define TRACE_USB_UHCI_TD_LOAD 0
#define TRACE_USB_UHCI_TD_LOAD_ENABLED 0
#define TRACE_USB_UHCI_TD_LOAD_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_td_load(uint32_t qh, uint32_t td, uint32_t ctrl, uint32_t token) {
    (void)qh;
    (void)td;
    (void)ctrl;
    (void)token;
}
#define TRACE_USB_UHCI_TD_NEXTQH 0
#define TRACE_USB_UHCI_TD_NEXTQH_ENABLED 0
#define TRACE_USB_UHCI_TD_NEXTQH_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_td_nextqh(uint32_t qh, uint32_t td) {
    (void)qh;
    (void)td;
}
#define TRACE_USB_UHCI_TD_QUEUE 0
#define TRACE_USB_UHCI_TD_QUEUE_ENABLED 0
#define TRACE_USB_UHCI_TD_QUEUE_BACKEND_DSTATE() (0)
static inline void trace_usb_uhci_td_queue(uint32_t td, uint32_t ctrl, uint32_t token) {
    (void)td;
    (void)ctrl;
    (void)token;
}
#define TRACE_USB_XHCI_CAP_READ 0
#define TRACE_USB_XHCI_CAP_READ_ENABLED 0
#define TRACE_USB_XHCI_CAP_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_cap_read(uint32_t off, uint32_t val) {
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_DOORBELL_READ 0
#define TRACE_USB_XHCI_DOORBELL_READ_ENABLED 0
#define TRACE_USB_XHCI_DOORBELL_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_doorbell_read(uint32_t off, uint32_t val) {
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_DOORBELL_WRITE 0
#define TRACE_USB_XHCI_DOORBELL_WRITE_ENABLED 0
#define TRACE_USB_XHCI_DOORBELL_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_doorbell_write(uint32_t off, uint32_t val) {
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_ENFORCED_LIMIT 0
#define TRACE_USB_XHCI_ENFORCED_LIMIT_ENABLED 0
#define TRACE_USB_XHCI_ENFORCED_LIMIT_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_enforced_limit(const char *item) {
    (void)item;
}
#define TRACE_USB_XHCI_EP_DISABLE 0
#define TRACE_USB_XHCI_EP_DISABLE_ENABLED 0
#define TRACE_USB_XHCI_EP_DISABLE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_ep_disable(uint32_t slotid, uint32_t epid) {
    (void)slotid;
    (void)epid;
}
#define TRACE_USB_XHCI_EP_ENABLE 0
#define TRACE_USB_XHCI_EP_ENABLE_ENABLED 0
#define TRACE_USB_XHCI_EP_ENABLE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_ep_enable(uint32_t slotid, uint32_t epid) {
    (void)slotid;
    (void)epid;
}
#define TRACE_USB_XHCI_EP_KICK 0
#define TRACE_USB_XHCI_EP_KICK_ENABLED 0
#define TRACE_USB_XHCI_EP_KICK_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_ep_kick(uint32_t slotid, uint32_t epid, uint32_t streamid) {
    (void)slotid;
    (void)epid;
    (void)streamid;
}
#define TRACE_USB_XHCI_EP_RESET 0
#define TRACE_USB_XHCI_EP_RESET_ENABLED 0
#define TRACE_USB_XHCI_EP_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_ep_reset(uint32_t slotid, uint32_t epid) {
    (void)slotid;
    (void)epid;
}
#define TRACE_USB_XHCI_EP_SET_DEQUEUE 0
#define TRACE_USB_XHCI_EP_SET_DEQUEUE_ENABLED 0
#define TRACE_USB_XHCI_EP_SET_DEQUEUE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_ep_set_dequeue(uint32_t slotid, uint32_t epid, uint32_t streamid, uint64_t param) {
    (void)slotid;
    (void)epid;
    (void)streamid;
    (void)param;
}
#define TRACE_USB_XHCI_EP_STATE 0
#define TRACE_USB_XHCI_EP_STATE_ENABLED 0
#define TRACE_USB_XHCI_EP_STATE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_ep_state(uint32_t slotid, uint32_t epid, const char *os, const char *ns) {
    (void)slotid;
    (void)epid;
    (void)os;
    (void)ns;
}
#define TRACE_USB_XHCI_EP_STOP 0
#define TRACE_USB_XHCI_EP_STOP_ENABLED 0
#define TRACE_USB_XHCI_EP_STOP_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_ep_stop(uint32_t slotid, uint32_t epid) {
    (void)slotid;
    (void)epid;
}
#define TRACE_USB_XHCI_EXIT 0
#define TRACE_USB_XHCI_EXIT_ENABLED 0
#define TRACE_USB_XHCI_EXIT_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_exit(void) {
}
#define TRACE_USB_XHCI_FETCH_TRB 0
#define TRACE_USB_XHCI_FETCH_TRB_ENABLED 0
#define TRACE_USB_XHCI_FETCH_TRB_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_fetch_trb(uint64_t addr, const char *name, uint64_t param, uint32_t status, uint32_t control) {
    (void)addr;
    (void)name;
    (void)param;
    (void)status;
    (void)control;
}
#define TRACE_USB_XHCI_IRQ_INTX 0
#define TRACE_USB_XHCI_IRQ_INTX_ENABLED 0
#define TRACE_USB_XHCI_IRQ_INTX_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_irq_intx(uint32_t level) {
    (void)level;
}
#define TRACE_USB_XHCI_IRQ_MSI 0
#define TRACE_USB_XHCI_IRQ_MSI_ENABLED 0
#define TRACE_USB_XHCI_IRQ_MSI_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_irq_msi(uint32_t nr) {
    (void)nr;
}
#define TRACE_USB_XHCI_IRQ_MSIX 0
#define TRACE_USB_XHCI_IRQ_MSIX_ENABLED 0
#define TRACE_USB_XHCI_IRQ_MSIX_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_irq_msix(uint32_t nr) {
    (void)nr;
}
#define TRACE_USB_XHCI_IRQ_MSIX_UNUSE 0
#define TRACE_USB_XHCI_IRQ_MSIX_UNUSE_ENABLED 0
#define TRACE_USB_XHCI_IRQ_MSIX_UNUSE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_irq_msix_unuse(uint32_t nr) {
    (void)nr;
}
#define TRACE_USB_XHCI_IRQ_MSIX_USE 0
#define TRACE_USB_XHCI_IRQ_MSIX_USE_ENABLED 0
#define TRACE_USB_XHCI_IRQ_MSIX_USE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_irq_msix_use(uint32_t nr) {
    (void)nr;
}
#define TRACE_USB_XHCI_OPER_READ 0
#define TRACE_USB_XHCI_OPER_READ_ENABLED 0
#define TRACE_USB_XHCI_OPER_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_oper_read(uint32_t off, uint32_t val) {
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_OPER_WRITE 0
#define TRACE_USB_XHCI_OPER_WRITE_ENABLED 0
#define TRACE_USB_XHCI_OPER_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_oper_write(uint32_t off, uint32_t val) {
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_PORT_LINK 0
#define TRACE_USB_XHCI_PORT_LINK_ENABLED 0
#define TRACE_USB_XHCI_PORT_LINK_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_port_link(uint32_t port, uint32_t pls) {
    (void)port;
    (void)pls;
}
#define TRACE_USB_XHCI_PORT_NOTIFY 0
#define TRACE_USB_XHCI_PORT_NOTIFY_ENABLED 0
#define TRACE_USB_XHCI_PORT_NOTIFY_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_port_notify(uint32_t port, uint32_t pls) {
    (void)port;
    (void)pls;
}
#define TRACE_USB_XHCI_PORT_READ 0
#define TRACE_USB_XHCI_PORT_READ_ENABLED 0
#define TRACE_USB_XHCI_PORT_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_port_read(uint32_t port, uint32_t off, uint32_t val) {
    (void)port;
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_PORT_RESET 0
#define TRACE_USB_XHCI_PORT_RESET_ENABLED 0
#define TRACE_USB_XHCI_PORT_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_port_reset(uint32_t port, bool warm) {
    (void)port;
    (void)warm;
}
#define TRACE_USB_XHCI_PORT_WRITE 0
#define TRACE_USB_XHCI_PORT_WRITE_ENABLED 0
#define TRACE_USB_XHCI_PORT_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_port_write(uint32_t port, uint32_t off, uint32_t val) {
    (void)port;
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_QUEUE_EVENT 0
#define TRACE_USB_XHCI_QUEUE_EVENT_ENABLED 0
#define TRACE_USB_XHCI_QUEUE_EVENT_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_queue_event(uint32_t vector, uint32_t idx, const char *trb, const char *evt, uint64_t param, uint32_t status, uint32_t control) {
    (void)vector;
    (void)idx;
    (void)trb;
    (void)evt;
    (void)param;
    (void)status;
    (void)control;
}
#define TRACE_USB_XHCI_RESET 0
#define TRACE_USB_XHCI_RESET_ENABLED 0
#define TRACE_USB_XHCI_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_reset(void) {
}
#define TRACE_USB_XHCI_RUN 0
#define TRACE_USB_XHCI_RUN_ENABLED 0
#define TRACE_USB_XHCI_RUN_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_run(void) {
}
#define TRACE_USB_XHCI_RUNTIME_READ 0
#define TRACE_USB_XHCI_RUNTIME_READ_ENABLED 0
#define TRACE_USB_XHCI_RUNTIME_READ_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_runtime_read(uint32_t off, uint32_t val) {
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_RUNTIME_WRITE 0
#define TRACE_USB_XHCI_RUNTIME_WRITE_ENABLED 0
#define TRACE_USB_XHCI_RUNTIME_WRITE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_runtime_write(uint32_t off, uint32_t val) {
    (void)off;
    (void)val;
}
#define TRACE_USB_XHCI_SLOT_ADDRESS 0
#define TRACE_USB_XHCI_SLOT_ADDRESS_ENABLED 0
#define TRACE_USB_XHCI_SLOT_ADDRESS_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_slot_address(uint32_t slotid, const char *port) {
    (void)slotid;
    (void)port;
}
#define TRACE_USB_XHCI_SLOT_CONFIGURE 0
#define TRACE_USB_XHCI_SLOT_CONFIGURE_ENABLED 0
#define TRACE_USB_XHCI_SLOT_CONFIGURE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_slot_configure(uint32_t slotid) {
    (void)slotid;
}
#define TRACE_USB_XHCI_SLOT_DISABLE 0
#define TRACE_USB_XHCI_SLOT_DISABLE_ENABLED 0
#define TRACE_USB_XHCI_SLOT_DISABLE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_slot_disable(uint32_t slotid) {
    (void)slotid;
}
#define TRACE_USB_XHCI_SLOT_ENABLE 0
#define TRACE_USB_XHCI_SLOT_ENABLE_ENABLED 0
#define TRACE_USB_XHCI_SLOT_ENABLE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_slot_enable(uint32_t slotid) {
    (void)slotid;
}
#define TRACE_USB_XHCI_SLOT_EVALUATE 0
#define TRACE_USB_XHCI_SLOT_EVALUATE_ENABLED 0
#define TRACE_USB_XHCI_SLOT_EVALUATE_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_slot_evaluate(uint32_t slotid) {
    (void)slotid;
}
#define TRACE_USB_XHCI_SLOT_RESET 0
#define TRACE_USB_XHCI_SLOT_RESET_ENABLED 0
#define TRACE_USB_XHCI_SLOT_RESET_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_slot_reset(uint32_t slotid) {
    (void)slotid;
}
#define TRACE_USB_XHCI_STOP 0
#define TRACE_USB_XHCI_STOP_ENABLED 0
#define TRACE_USB_XHCI_STOP_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_stop(void) {
}
#define TRACE_USB_XHCI_UNIMPLEMENTED 0
#define TRACE_USB_XHCI_UNIMPLEMENTED_ENABLED 0
#define TRACE_USB_XHCI_UNIMPLEMENTED_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_unimplemented(const char *item, int nr) {
    (void)item;
    (void)nr;
}
#define TRACE_USB_XHCI_XFER_ASYNC 0
#define TRACE_USB_XHCI_XFER_ASYNC_ENABLED 0
#define TRACE_USB_XHCI_XFER_ASYNC_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_xfer_async(void *xfer) {
    (void)xfer;
}
#define TRACE_USB_XHCI_XFER_ERROR 0
#define TRACE_USB_XHCI_XFER_ERROR_ENABLED 0
#define TRACE_USB_XHCI_XFER_ERROR_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_xfer_error(void *xfer, uint32_t ret) {
    (void)xfer;
    (void)ret;
}
#define TRACE_USB_XHCI_XFER_NAK 0
#define TRACE_USB_XHCI_XFER_NAK_ENABLED 0
#define TRACE_USB_XHCI_XFER_NAK_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_xfer_nak(void *xfer) {
    (void)xfer;
}
#define TRACE_USB_XHCI_XFER_RETRY 0
#define TRACE_USB_XHCI_XFER_RETRY_ENABLED 0
#define TRACE_USB_XHCI_XFER_RETRY_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_xfer_retry(void *xfer) {
    (void)xfer;
}
#define TRACE_USB_XHCI_XFER_START 0
#define TRACE_USB_XHCI_XFER_START_ENABLED 0
#define TRACE_USB_XHCI_XFER_START_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_xfer_start(void *xfer, uint32_t slotid, uint32_t epid, uint32_t streamid) {
    (void)xfer;
    (void)slotid;
    (void)epid;
    (void)streamid;
}
#define TRACE_USB_XHCI_XFER_SUCCESS 0
#define TRACE_USB_XHCI_XFER_SUCCESS_ENABLED 0
#define TRACE_USB_XHCI_XFER_SUCCESS_BACKEND_DSTATE() (0)
static inline void trace_usb_xhci_xfer_success(void *xfer, uint32_t bytes) {
    (void)xfer;
    (void)bytes;
}

#endif