/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_ACCEL_KVM_H
#define TRACE_TRACE_ACCEL_KVM_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_KVM_CLEAR_DIRTY_LOG 0
#define TRACE_KVM_CLEAR_DIRTY_LOG_ENABLED 0
#define TRACE_KVM_CLEAR_DIRTY_LOG_BACKEND_DSTATE() (0)
static inline void trace_kvm_clear_dirty_log(uint32_t slot, uint64_t start, uint32_t size) {
    (void)slot;
    (void)start;
    (void)size;
}
#define TRACE_KVM_CONVERT_MEMORY 0
#define TRACE_KVM_CONVERT_MEMORY_ENABLED 0
#define TRACE_KVM_CONVERT_MEMORY_BACKEND_DSTATE() (0)
static inline void trace_kvm_convert_memory(uint64_t start, uint64_t size, const char *msg) {
    (void)start;
    (void)size;
    (void)msg;
}
#define TRACE_KVM_CPU_EXEC 0
#define TRACE_KVM_CPU_EXEC_ENABLED 0
#define TRACE_KVM_CPU_EXEC_BACKEND_DSTATE() (0)
static inline void trace_kvm_cpu_exec(void) {
}
#define TRACE_KVM_CREATE_VCPU 0
#define TRACE_KVM_CREATE_VCPU_ENABLED 0
#define TRACE_KVM_CREATE_VCPU_BACKEND_DSTATE() (0)
static inline void trace_kvm_create_vcpu(int cpu_index, unsigned long arch_cpu_id, int kvm_fd) {
    (void)cpu_index;
    (void)arch_cpu_id;
    (void)kvm_fd;
}
#define TRACE_KVM_DESTROY_VCPU 0
#define TRACE_KVM_DESTROY_VCPU_ENABLED 0
#define TRACE_KVM_DESTROY_VCPU_BACKEND_DSTATE() (0)
static inline void trace_kvm_destroy_vcpu(int cpu_index, unsigned long arch_cpu_id) {
    (void)cpu_index;
    (void)arch_cpu_id;
}
#define TRACE_KVM_DEVICE_IOCTL 0
#define TRACE_KVM_DEVICE_IOCTL_ENABLED 0
#define TRACE_KVM_DEVICE_IOCTL_BACKEND_DSTATE() (0)
static inline void trace_kvm_device_ioctl(int fd, unsigned long type, void *arg) {
    (void)fd;
    (void)type;
    (void)arg;
}
#define TRACE_KVM_DIRTY_RING_FLUSH 0
#define TRACE_KVM_DIRTY_RING_FLUSH_ENABLED 0
#define TRACE_KVM_DIRTY_RING_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_kvm_dirty_ring_flush(int finished) {
    (void)finished;
}
#define TRACE_KVM_DIRTY_RING_FULL 0
#define TRACE_KVM_DIRTY_RING_FULL_ENABLED 0
#define TRACE_KVM_DIRTY_RING_FULL_BACKEND_DSTATE() (0)
static inline void trace_kvm_dirty_ring_full(int id) {
    (void)id;
}
#define TRACE_KVM_DIRTY_RING_PAGE 0
#define TRACE_KVM_DIRTY_RING_PAGE_ENABLED 0
#define TRACE_KVM_DIRTY_RING_PAGE_BACKEND_DSTATE() (0)
static inline void trace_kvm_dirty_ring_page(int vcpu, uint32_t slot, uint64_t offset) {
    (void)vcpu;
    (void)slot;
    (void)offset;
}
#define TRACE_KVM_DIRTY_RING_REAP 0
#define TRACE_KVM_DIRTY_RING_REAP_ENABLED 0
#define TRACE_KVM_DIRTY_RING_REAP_BACKEND_DSTATE() (0)
static inline void trace_kvm_dirty_ring_reap(uint64_t count, int64_t t) {
    (void)count;
    (void)t;
}
#define TRACE_KVM_DIRTY_RING_REAP_VCPU 0
#define TRACE_KVM_DIRTY_RING_REAP_VCPU_ENABLED 0
#define TRACE_KVM_DIRTY_RING_REAP_VCPU_BACKEND_DSTATE() (0)
static inline void trace_kvm_dirty_ring_reap_vcpu(int id) {
    (void)id;
}
#define TRACE_KVM_DIRTY_RING_REAPER 0
#define TRACE_KVM_DIRTY_RING_REAPER_ENABLED 0
#define TRACE_KVM_DIRTY_RING_REAPER_BACKEND_DSTATE() (0)
static inline void trace_kvm_dirty_ring_reaper(const char *s) {
    (void)s;
}
#define TRACE_KVM_DIRTY_RING_REAPER_KICK 0
#define TRACE_KVM_DIRTY_RING_REAPER_KICK_ENABLED 0
#define TRACE_KVM_DIRTY_RING_REAPER_KICK_BACKEND_DSTATE() (0)
static inline void trace_kvm_dirty_ring_reaper_kick(const char *reason) {
    (void)reason;
}
#define TRACE_KVM_FAILED_GET_VCPU_MMAP_SIZE 0
#define TRACE_KVM_FAILED_GET_VCPU_MMAP_SIZE_ENABLED 0
#define TRACE_KVM_FAILED_GET_VCPU_MMAP_SIZE_BACKEND_DSTATE() (0)
static inline void trace_kvm_failed_get_vcpu_mmap_size(void) {
}
#define TRACE_KVM_FAILED_REG_GET 0
#define TRACE_KVM_FAILED_REG_GET_ENABLED 0
#define TRACE_KVM_FAILED_REG_GET_BACKEND_DSTATE() (0)
static inline void trace_kvm_failed_reg_get(uint64_t id, const char *msg) {
    (void)id;
    (void)msg;
}
#define TRACE_KVM_FAILED_REG_SET 0
#define TRACE_KVM_FAILED_REG_SET_ENABLED 0
#define TRACE_KVM_FAILED_REG_SET_BACKEND_DSTATE() (0)
static inline void trace_kvm_failed_reg_set(uint64_t id, const char *msg) {
    (void)id;
    (void)msg;
}
#define TRACE_KVM_INIT_VCPU 0
#define TRACE_KVM_INIT_VCPU_ENABLED 0
#define TRACE_KVM_INIT_VCPU_BACKEND_DSTATE() (0)
static inline void trace_kvm_init_vcpu(int cpu_index, unsigned long arch_cpu_id) {
    (void)cpu_index;
    (void)arch_cpu_id;
}
#define TRACE_KVM_INTERRUPT_EXIT_REQUEST 0
#define TRACE_KVM_INTERRUPT_EXIT_REQUEST_ENABLED 0
#define TRACE_KVM_INTERRUPT_EXIT_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_kvm_interrupt_exit_request(void) {
}
#define TRACE_KVM_IO_WINDOW_EXIT 0
#define TRACE_KVM_IO_WINDOW_EXIT_ENABLED 0
#define TRACE_KVM_IO_WINDOW_EXIT_BACKEND_DSTATE() (0)
static inline void trace_kvm_io_window_exit(void) {
}
#define TRACE_KVM_IOCTL 0
#define TRACE_KVM_IOCTL_ENABLED 0
#define TRACE_KVM_IOCTL_BACKEND_DSTATE() (0)
static inline void trace_kvm_ioctl(unsigned long type, void *arg) {
    (void)type;
    (void)arg;
}
#define TRACE_KVM_IRQCHIP_ADD_MSI_ROUTE 0
#define TRACE_KVM_IRQCHIP_ADD_MSI_ROUTE_ENABLED 0
#define TRACE_KVM_IRQCHIP_ADD_MSI_ROUTE_BACKEND_DSTATE() (0)
static inline void trace_kvm_irqchip_add_msi_route(char *name, int vector, int virq) {
    (void)name;
    (void)vector;
    (void)virq;
}
#define TRACE_KVM_IRQCHIP_COMMIT_ROUTES 0
#define TRACE_KVM_IRQCHIP_COMMIT_ROUTES_ENABLED 0
#define TRACE_KVM_IRQCHIP_COMMIT_ROUTES_BACKEND_DSTATE() (0)
static inline void trace_kvm_irqchip_commit_routes(void) {
}
#define TRACE_KVM_IRQCHIP_RELEASE_VIRQ 0
#define TRACE_KVM_IRQCHIP_RELEASE_VIRQ_ENABLED 0
#define TRACE_KVM_IRQCHIP_RELEASE_VIRQ_BACKEND_DSTATE() (0)
static inline void trace_kvm_irqchip_release_virq(int virq) {
    (void)virq;
}
#define TRACE_KVM_IRQCHIP_UPDATE_MSI_ROUTE 0
#define TRACE_KVM_IRQCHIP_UPDATE_MSI_ROUTE_ENABLED 0
#define TRACE_KVM_IRQCHIP_UPDATE_MSI_ROUTE_BACKEND_DSTATE() (0)
static inline void trace_kvm_irqchip_update_msi_route(int virq) {
    (void)virq;
}
#define TRACE_KVM_MEMORY_FAULT 0
#define TRACE_KVM_MEMORY_FAULT_ENABLED 0
#define TRACE_KVM_MEMORY_FAULT_BACKEND_DSTATE() (0)
static inline void trace_kvm_memory_fault(uint64_t start, uint64_t size, uint64_t flags) {
    (void)start;
    (void)size;
    (void)flags;
}
#define TRACE_KVM_PARK_VCPU 0
#define TRACE_KVM_PARK_VCPU_ENABLED 0
#define TRACE_KVM_PARK_VCPU_BACKEND_DSTATE() (0)
static inline void trace_kvm_park_vcpu(int cpu_index, unsigned long arch_cpu_id) {
    (void)cpu_index;
    (void)arch_cpu_id;
}
#define TRACE_KVM_RESAMPLE_FD_NOTIFY 0
#define TRACE_KVM_RESAMPLE_FD_NOTIFY_ENABLED 0
#define TRACE_KVM_RESAMPLE_FD_NOTIFY_BACKEND_DSTATE() (0)
static inline void trace_kvm_resample_fd_notify(int gsi) {
    (void)gsi;
}
#define TRACE_KVM_RUN_EXIT 0
#define TRACE_KVM_RUN_EXIT_ENABLED 0
#define TRACE_KVM_RUN_EXIT_BACKEND_DSTATE() (0)
static inline void trace_kvm_run_exit(int cpu_index, uint32_t reason) {
    (void)cpu_index;
    (void)reason;
}
#define TRACE_KVM_RUN_EXIT_SYSTEM_EVENT 0
#define TRACE_KVM_RUN_EXIT_SYSTEM_EVENT_ENABLED 0
#define TRACE_KVM_RUN_EXIT_SYSTEM_EVENT_BACKEND_DSTATE() (0)
static inline void trace_kvm_run_exit_system_event(int cpu_index, uint32_t event_type) {
    (void)cpu_index;
    (void)event_type;
}
#define TRACE_KVM_SET_IOEVENTFD_MMIO 0
#define TRACE_KVM_SET_IOEVENTFD_MMIO_ENABLED 0
#define TRACE_KVM_SET_IOEVENTFD_MMIO_BACKEND_DSTATE() (0)
static inline void trace_kvm_set_ioeventfd_mmio(int fd, uint64_t addr, uint32_t val, bool assign, uint32_t size, bool datamatch) {
    (void)fd;
    (void)addr;
    (void)val;
    (void)assign;
    (void)size;
    (void)datamatch;
}
#define TRACE_KVM_SET_IOEVENTFD_PIO 0
#define TRACE_KVM_SET_IOEVENTFD_PIO_ENABLED 0
#define TRACE_KVM_SET_IOEVENTFD_PIO_BACKEND_DSTATE() (0)
static inline void trace_kvm_set_ioeventfd_pio(int fd, uint16_t addr, uint32_t val, bool assign, uint32_t size, bool datamatch) {
    (void)fd;
    (void)addr;
    (void)val;
    (void)assign;
    (void)size;
    (void)datamatch;
}
#define TRACE_KVM_SET_USER_MEMORY 0
#define TRACE_KVM_SET_USER_MEMORY_ENABLED 0
#define TRACE_KVM_SET_USER_MEMORY_BACKEND_DSTATE() (0)
static inline void trace_kvm_set_user_memory(uint16_t as, uint16_t slot, uint32_t flags, uint64_t guest_phys_addr, uint64_t memory_size, uint64_t userspace_addr, uint32_t fd, uint64_t fd_offset, int ret) {
    (void)as;
    (void)slot;
    (void)flags;
    (void)guest_phys_addr;
    (void)memory_size;
    (void)userspace_addr;
    (void)fd;
    (void)fd_offset;
    (void)ret;
}
#define TRACE_KVM_SLOTS_GROW 0
#define TRACE_KVM_SLOTS_GROW_ENABLED 0
#define TRACE_KVM_SLOTS_GROW_BACKEND_DSTATE() (0)
static inline void trace_kvm_slots_grow(unsigned int old, unsigned int new) {
    (void)old;
    (void)new;
}
#define TRACE_KVM_UNPARK_VCPU 0
#define TRACE_KVM_UNPARK_VCPU_ENABLED 0
#define TRACE_KVM_UNPARK_VCPU_BACKEND_DSTATE() (0)
static inline void trace_kvm_unpark_vcpu(unsigned long arch_cpu_id, const char *msg) {
    (void)arch_cpu_id;
    (void)msg;
}
#define TRACE_KVM_VCPU_IOCTL 0
#define TRACE_KVM_VCPU_IOCTL_ENABLED 0
#define TRACE_KVM_VCPU_IOCTL_BACKEND_DSTATE() (0)
static inline void trace_kvm_vcpu_ioctl(int cpu_index, unsigned long type, void *arg) {
    (void)cpu_index;
    (void)type;
    (void)arg;
}
#define TRACE_KVM_VM_IOCTL 0
#define TRACE_KVM_VM_IOCTL_ENABLED 0
#define TRACE_KVM_VM_IOCTL_BACKEND_DSTATE() (0)
static inline void trace_kvm_vm_ioctl(unsigned long type, void *arg) {
    (void)type;
    (void)arg;
}

#endif