/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_I386_XEN_H
#define TRACE_TRACE_HW_I386_XEN_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_XEN_PLATFORM_LOG 0
#define TRACE_XEN_PLATFORM_LOG_ENABLED 0
#define TRACE_XEN_PLATFORM_LOG_BACKEND_DSTATE() (0)
static inline void trace_xen_platform_log(char *s) {
    (void)s;
}
#define TRACE_XEN_PV_MMIO_READ 0
#define TRACE_XEN_PV_MMIO_READ_ENABLED 0
#define TRACE_XEN_PV_MMIO_READ_BACKEND_DSTATE() (0)
static inline void trace_xen_pv_mmio_read(uint64_t addr) {
    (void)addr;
}
#define TRACE_XEN_PV_MMIO_WRITE 0
#define TRACE_XEN_PV_MMIO_WRITE_ENABLED 0
#define TRACE_XEN_PV_MMIO_WRITE_BACKEND_DSTATE() (0)
static inline void trace_xen_pv_mmio_write(uint64_t addr) {
    (void)addr;
}

#endif