/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_GDBSTUB_H
#define TRACE_TRACE_GDBSTUB_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_GDBSTUB_ERR_CHECKSUM_INCORRECT 0
#define TRACE_GDBSTUB_ERR_CHECKSUM_INCORRECT_ENABLED 0
#define TRACE_GDBSTUB_ERR_CHECKSUM_INCORRECT_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_err_checksum_incorrect(uint8_t expected, uint8_t got) {
    (void)expected;
    (void)got;
}
#define TRACE_GDBSTUB_ERR_CHECKSUM_INVALID 0
#define TRACE_GDBSTUB_ERR_CHECKSUM_INVALID_ENABLED 0
#define TRACE_GDBSTUB_ERR_CHECKSUM_INVALID_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_err_checksum_invalid(uint8_t ch) {
    (void)ch;
}
#define TRACE_GDBSTUB_ERR_GARBAGE 0
#define TRACE_GDBSTUB_ERR_GARBAGE_ENABLED 0
#define TRACE_GDBSTUB_ERR_GARBAGE_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_err_garbage(uint8_t ch) {
    (void)ch;
}
#define TRACE_GDBSTUB_ERR_GOT_NACK 0
#define TRACE_GDBSTUB_ERR_GOT_NACK_ENABLED 0
#define TRACE_GDBSTUB_ERR_GOT_NACK_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_err_got_nack(void) {
}
#define TRACE_GDBSTUB_ERR_INVALID_REPEAT 0
#define TRACE_GDBSTUB_ERR_INVALID_REPEAT_ENABLED 0
#define TRACE_GDBSTUB_ERR_INVALID_REPEAT_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_err_invalid_repeat(uint8_t ch) {
    (void)ch;
}
#define TRACE_GDBSTUB_ERR_INVALID_RLE 0
#define TRACE_GDBSTUB_ERR_INVALID_RLE_ENABLED 0
#define TRACE_GDBSTUB_ERR_INVALID_RLE_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_err_invalid_rle(void) {
}
#define TRACE_GDBSTUB_ERR_OVERRUN 0
#define TRACE_GDBSTUB_ERR_OVERRUN_ENABLED 0
#define TRACE_GDBSTUB_ERR_OVERRUN_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_err_overrun(void) {
}
#define TRACE_GDBSTUB_ERR_UNEXPECTED_RUNPKT 0
#define TRACE_GDBSTUB_ERR_UNEXPECTED_RUNPKT_ENABLED 0
#define TRACE_GDBSTUB_ERR_UNEXPECTED_RUNPKT_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_err_unexpected_runpkt(uint8_t ch) {
    (void)ch;
}
#define TRACE_GDBSTUB_HIT_BREAK 0
#define TRACE_GDBSTUB_HIT_BREAK_ENABLED 0
#define TRACE_GDBSTUB_HIT_BREAK_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_hit_break(void) {
}
#define TRACE_GDBSTUB_HIT_INTERNAL_ERROR 0
#define TRACE_GDBSTUB_HIT_INTERNAL_ERROR_ENABLED 0
#define TRACE_GDBSTUB_HIT_INTERNAL_ERROR_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_hit_internal_error(void) {
}
#define TRACE_GDBSTUB_HIT_IO_ERROR 0
#define TRACE_GDBSTUB_HIT_IO_ERROR_ENABLED 0
#define TRACE_GDBSTUB_HIT_IO_ERROR_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_hit_io_error(void) {
}
#define TRACE_GDBSTUB_HIT_PAUSED 0
#define TRACE_GDBSTUB_HIT_PAUSED_ENABLED 0
#define TRACE_GDBSTUB_HIT_PAUSED_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_hit_paused(void) {
}
#define TRACE_GDBSTUB_HIT_SHUTDOWN 0
#define TRACE_GDBSTUB_HIT_SHUTDOWN_ENABLED 0
#define TRACE_GDBSTUB_HIT_SHUTDOWN_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_hit_shutdown(void) {
}
#define TRACE_GDBSTUB_HIT_UNKNOWN 0
#define TRACE_GDBSTUB_HIT_UNKNOWN_ENABLED 0
#define TRACE_GDBSTUB_HIT_UNKNOWN_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_hit_unknown(int state) {
    (void)state;
}
#define TRACE_GDBSTUB_HIT_WATCHDOG 0
#define TRACE_GDBSTUB_HIT_WATCHDOG_ENABLED 0
#define TRACE_GDBSTUB_HIT_WATCHDOG_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_hit_watchdog(void) {
}
#define TRACE_GDBSTUB_HIT_WATCHPOINT 0
#define TRACE_GDBSTUB_HIT_WATCHPOINT_ENABLED 0
#define TRACE_GDBSTUB_HIT_WATCHPOINT_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_hit_watchpoint(const char *type, int cpu_gdb_index, uint64_t vaddr) {
    (void)type;
    (void)cpu_gdb_index;
    (void)vaddr;
}
#define TRACE_GDBSTUB_IO_BINARYREPLY 0
#define TRACE_GDBSTUB_IO_BINARYREPLY_ENABLED 0
#define TRACE_GDBSTUB_IO_BINARYREPLY_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_io_binaryreply(size_t ofs, const char *line) {
    (void)ofs;
    (void)line;
}
#define TRACE_GDBSTUB_IO_COMMAND 0
#define TRACE_GDBSTUB_IO_COMMAND_ENABLED 0
#define TRACE_GDBSTUB_IO_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_io_command(const char *command) {
    (void)command;
}
#define TRACE_GDBSTUB_IO_GOT_ACK 0
#define TRACE_GDBSTUB_IO_GOT_ACK_ENABLED 0
#define TRACE_GDBSTUB_IO_GOT_ACK_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_io_got_ack(void) {
}
#define TRACE_GDBSTUB_IO_GOT_UNEXPECTED 0
#define TRACE_GDBSTUB_IO_GOT_UNEXPECTED_ENABLED 0
#define TRACE_GDBSTUB_IO_GOT_UNEXPECTED_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_io_got_unexpected(uint8_t ch) {
    (void)ch;
}
#define TRACE_GDBSTUB_IO_REPLY 0
#define TRACE_GDBSTUB_IO_REPLY_ENABLED 0
#define TRACE_GDBSTUB_IO_REPLY_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_io_reply(const char *message) {
    (void)message;
}
#define TRACE_GDBSTUB_OP_CONTINUE 0
#define TRACE_GDBSTUB_OP_CONTINUE_ENABLED 0
#define TRACE_GDBSTUB_OP_CONTINUE_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_op_continue(void) {
}
#define TRACE_GDBSTUB_OP_CONTINUE_CPU 0
#define TRACE_GDBSTUB_OP_CONTINUE_CPU_ENABLED 0
#define TRACE_GDBSTUB_OP_CONTINUE_CPU_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_op_continue_cpu(int cpu_index) {
    (void)cpu_index;
}
#define TRACE_GDBSTUB_OP_EXITING 0
#define TRACE_GDBSTUB_OP_EXITING_ENABLED 0
#define TRACE_GDBSTUB_OP_EXITING_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_op_exiting(uint8_t code) {
    (void)code;
}
#define TRACE_GDBSTUB_OP_EXTRA_INFO 0
#define TRACE_GDBSTUB_OP_EXTRA_INFO_ENABLED 0
#define TRACE_GDBSTUB_OP_EXTRA_INFO_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_op_extra_info(const char *info) {
    (void)info;
}
#define TRACE_GDBSTUB_OP_START 0
#define TRACE_GDBSTUB_OP_START_ENABLED 0
#define TRACE_GDBSTUB_OP_START_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_op_start(const char *device) {
    (void)device;
}
#define TRACE_GDBSTUB_OP_STEPPING 0
#define TRACE_GDBSTUB_OP_STEPPING_ENABLED 0
#define TRACE_GDBSTUB_OP_STEPPING_BACKEND_DSTATE() (0)
static inline void trace_gdbstub_op_stepping(int cpu_index) {
    (void)cpu_index;
}

#endif