/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_AUTHZ_H
#define TRACE_TRACE_AUTHZ_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_QAUTHZ_IS_ALLOWED 0
#define TRACE_QAUTHZ_IS_ALLOWED_ENABLED 0
#define TRACE_QAUTHZ_IS_ALLOWED_BACKEND_DSTATE() (0)
static inline void trace_qauthz_is_allowed(void *authz, const char *identity, bool allowed) {
    (void)authz;
    (void)identity;
    (void)allowed;
}
#define TRACE_QAUTHZ_LIST_CHECK_RULE 0
#define TRACE_QAUTHZ_LIST_CHECK_RULE_ENABLED 0
#define TRACE_QAUTHZ_LIST_CHECK_RULE_BACKEND_DSTATE() (0)
static inline void trace_qauthz_list_check_rule(void *authz, const char *identity, const char *rule, int format, int policy) {
    (void)authz;
    (void)identity;
    (void)rule;
    (void)format;
    (void)policy;
}
#define TRACE_QAUTHZ_LIST_DEFAULT_POLICY 0
#define TRACE_QAUTHZ_LIST_DEFAULT_POLICY_ENABLED 0
#define TRACE_QAUTHZ_LIST_DEFAULT_POLICY_BACKEND_DSTATE() (0)
static inline void trace_qauthz_list_default_policy(void *authz, const char *identity, int policy) {
    (void)authz;
    (void)identity;
    (void)policy;
}
#define TRACE_QAUTHZ_LIST_FILE_LOAD 0
#define TRACE_QAUTHZ_LIST_FILE_LOAD_ENABLED 0
#define TRACE_QAUTHZ_LIST_FILE_LOAD_BACKEND_DSTATE() (0)
static inline void trace_qauthz_list_file_load(void *authz, const char *filename) {
    (void)authz;
    (void)filename;
}
#define TRACE_QAUTHZ_LIST_FILE_REFRESH 0
#define TRACE_QAUTHZ_LIST_FILE_REFRESH_ENABLED 0
#define TRACE_QAUTHZ_LIST_FILE_REFRESH_BACKEND_DSTATE() (0)
static inline void trace_qauthz_list_file_refresh(void *authz, const char *filename, int success) {
    (void)authz;
    (void)filename;
    (void)success;
}
#define TRACE_QAUTHZ_PAM_CHECK 0
#define TRACE_QAUTHZ_PAM_CHECK_ENABLED 0
#define TRACE_QAUTHZ_PAM_CHECK_BACKEND_DSTATE() (0)
static inline void trace_qauthz_pam_check(void *authz, const char *identity, const char *service) {
    (void)authz;
    (void)identity;
    (void)service;
}
#define TRACE_QAUTHZ_SIMPLE_IS_ALLOWED 0
#define TRACE_QAUTHZ_SIMPLE_IS_ALLOWED_ENABLED 0
#define TRACE_QAUTHZ_SIMPLE_IS_ALLOWED_BACKEND_DSTATE() (0)
static inline void trace_qauthz_simple_is_allowed(void *authz, const char *wantidentity, const char *gotidentity) {
    (void)authz;
    (void)wantidentity;
    (void)gotidentity;
}

#endif