/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_QAPI_H
#define TRACE_TRACE_QAPI_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_VISIT_CHECK_LIST 0
#define TRACE_VISIT_CHECK_LIST_ENABLED 0
#define TRACE_VISIT_CHECK_LIST_BACKEND_DSTATE() (0)
static inline void trace_visit_check_list(void *v) {
    (void)v;
}
#define TRACE_VISIT_CHECK_STRUCT 0
#define TRACE_VISIT_CHECK_STRUCT_ENABLED 0
#define TRACE_VISIT_CHECK_STRUCT_BACKEND_DSTATE() (0)
static inline void trace_visit_check_struct(void *v) {
    (void)v;
}
#define TRACE_VISIT_COMPLETE 0
#define TRACE_VISIT_COMPLETE_ENABLED 0
#define TRACE_VISIT_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_visit_complete(void *v, void *opaque) {
    (void)v;
    (void)opaque;
}
#define TRACE_VISIT_END_ALTERNATE 0
#define TRACE_VISIT_END_ALTERNATE_ENABLED 0
#define TRACE_VISIT_END_ALTERNATE_BACKEND_DSTATE() (0)
static inline void trace_visit_end_alternate(void *v, void *obj) {
    (void)v;
    (void)obj;
}
#define TRACE_VISIT_END_LIST 0
#define TRACE_VISIT_END_LIST_ENABLED 0
#define TRACE_VISIT_END_LIST_BACKEND_DSTATE() (0)
static inline void trace_visit_end_list(void *v, void *obj) {
    (void)v;
    (void)obj;
}
#define TRACE_VISIT_END_STRUCT 0
#define TRACE_VISIT_END_STRUCT_ENABLED 0
#define TRACE_VISIT_END_STRUCT_BACKEND_DSTATE() (0)
static inline void trace_visit_end_struct(void *v, void *obj) {
    (void)v;
    (void)obj;
}
#define TRACE_VISIT_FREE 0
#define TRACE_VISIT_FREE_ENABLED 0
#define TRACE_VISIT_FREE_BACKEND_DSTATE() (0)
static inline void trace_visit_free(void *v) {
    (void)v;
}
#define TRACE_VISIT_NEXT_LIST 0
#define TRACE_VISIT_NEXT_LIST_ENABLED 0
#define TRACE_VISIT_NEXT_LIST_BACKEND_DSTATE() (0)
static inline void trace_visit_next_list(void *v, void *tail, size_t size) {
    (void)v;
    (void)tail;
    (void)size;
}
#define TRACE_VISIT_OPTIONAL 0
#define TRACE_VISIT_OPTIONAL_ENABLED 0
#define TRACE_VISIT_OPTIONAL_BACKEND_DSTATE() (0)
static inline void trace_visit_optional(void *v, const char *name, bool *present) {
    (void)v;
    (void)name;
    (void)present;
}
#define TRACE_VISIT_POLICY_REJECT 0
#define TRACE_VISIT_POLICY_REJECT_ENABLED 0
#define TRACE_VISIT_POLICY_REJECT_BACKEND_DSTATE() (0)
static inline void trace_visit_policy_reject(void *v, const char *name) {
    (void)v;
    (void)name;
}
#define TRACE_VISIT_POLICY_SKIP 0
#define TRACE_VISIT_POLICY_SKIP_ENABLED 0
#define TRACE_VISIT_POLICY_SKIP_BACKEND_DSTATE() (0)
static inline void trace_visit_policy_skip(void *v, const char *name) {
    (void)v;
    (void)name;
}
#define TRACE_VISIT_START_ALTERNATE 0
#define TRACE_VISIT_START_ALTERNATE_ENABLED 0
#define TRACE_VISIT_START_ALTERNATE_BACKEND_DSTATE() (0)
static inline void trace_visit_start_alternate(void *v, const char *name, void *obj, size_t size) {
    (void)v;
    (void)name;
    (void)obj;
    (void)size;
}
#define TRACE_VISIT_START_LIST 0
#define TRACE_VISIT_START_LIST_ENABLED 0
#define TRACE_VISIT_START_LIST_BACKEND_DSTATE() (0)
static inline void trace_visit_start_list(void *v, const char *name, void *obj, size_t size) {
    (void)v;
    (void)name;
    (void)obj;
    (void)size;
}
#define TRACE_VISIT_START_STRUCT 0
#define TRACE_VISIT_START_STRUCT_ENABLED 0
#define TRACE_VISIT_START_STRUCT_BACKEND_DSTATE() (0)
static inline void trace_visit_start_struct(void *v, const char *name, void *obj, size_t size) {
    (void)v;
    (void)name;
    (void)obj;
    (void)size;
}
#define TRACE_VISIT_TYPE_ANY 0
#define TRACE_VISIT_TYPE_ANY_ENABLED 0
#define TRACE_VISIT_TYPE_ANY_BACKEND_DSTATE() (0)
static inline void trace_visit_type_any(void *v, const char *name, void *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_BOOL 0
#define TRACE_VISIT_TYPE_BOOL_ENABLED 0
#define TRACE_VISIT_TYPE_BOOL_BACKEND_DSTATE() (0)
static inline void trace_visit_type_bool(void *v, const char *name, bool *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_ENUM 0
#define TRACE_VISIT_TYPE_ENUM_ENABLED 0
#define TRACE_VISIT_TYPE_ENUM_BACKEND_DSTATE() (0)
static inline void trace_visit_type_enum(void *v, const char *name, int *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_INT 0
#define TRACE_VISIT_TYPE_INT_ENABLED 0
#define TRACE_VISIT_TYPE_INT_BACKEND_DSTATE() (0)
static inline void trace_visit_type_int(void *v, const char *name, int64_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_INT16 0
#define TRACE_VISIT_TYPE_INT16_ENABLED 0
#define TRACE_VISIT_TYPE_INT16_BACKEND_DSTATE() (0)
static inline void trace_visit_type_int16(void *v, const char *name, int16_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_INT32 0
#define TRACE_VISIT_TYPE_INT32_ENABLED 0
#define TRACE_VISIT_TYPE_INT32_BACKEND_DSTATE() (0)
static inline void trace_visit_type_int32(void *v, const char *name, int32_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_INT64 0
#define TRACE_VISIT_TYPE_INT64_ENABLED 0
#define TRACE_VISIT_TYPE_INT64_BACKEND_DSTATE() (0)
static inline void trace_visit_type_int64(void *v, const char *name, int64_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_INT8 0
#define TRACE_VISIT_TYPE_INT8_ENABLED 0
#define TRACE_VISIT_TYPE_INT8_BACKEND_DSTATE() (0)
static inline void trace_visit_type_int8(void *v, const char *name, int8_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_NULL 0
#define TRACE_VISIT_TYPE_NULL_ENABLED 0
#define TRACE_VISIT_TYPE_NULL_BACKEND_DSTATE() (0)
static inline void trace_visit_type_null(void *v, const char *name, void *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_NUMBER 0
#define TRACE_VISIT_TYPE_NUMBER_ENABLED 0
#define TRACE_VISIT_TYPE_NUMBER_BACKEND_DSTATE() (0)
static inline void trace_visit_type_number(void *v, const char *name, void *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_SIZE 0
#define TRACE_VISIT_TYPE_SIZE_ENABLED 0
#define TRACE_VISIT_TYPE_SIZE_BACKEND_DSTATE() (0)
static inline void trace_visit_type_size(void *v, const char *name, uint64_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_STR 0
#define TRACE_VISIT_TYPE_STR_ENABLED 0
#define TRACE_VISIT_TYPE_STR_BACKEND_DSTATE() (0)
static inline void trace_visit_type_str(void *v, const char *name, char **obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_UINT16 0
#define TRACE_VISIT_TYPE_UINT16_ENABLED 0
#define TRACE_VISIT_TYPE_UINT16_BACKEND_DSTATE() (0)
static inline void trace_visit_type_uint16(void *v, const char *name, uint16_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_UINT32 0
#define TRACE_VISIT_TYPE_UINT32_ENABLED 0
#define TRACE_VISIT_TYPE_UINT32_BACKEND_DSTATE() (0)
static inline void trace_visit_type_uint32(void *v, const char *name, uint32_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_UINT64 0
#define TRACE_VISIT_TYPE_UINT64_ENABLED 0
#define TRACE_VISIT_TYPE_UINT64_BACKEND_DSTATE() (0)
static inline void trace_visit_type_uint64(void *v, const char *name, uint64_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}
#define TRACE_VISIT_TYPE_UINT8 0
#define TRACE_VISIT_TYPE_UINT8_ENABLED 0
#define TRACE_VISIT_TYPE_UINT8_BACKEND_DSTATE() (0)
static inline void trace_visit_type_uint8(void *v, const char *name, uint8_t *obj) {
    (void)v;
    (void)name;
    (void)obj;
}

#endif