/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_VFIO_USER_H
#define TRACE_TRACE_HW_VFIO_USER_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_VFIO_USER_DMA_MAP 0
#define TRACE_VFIO_USER_DMA_MAP_ENABLED 0
#define TRACE_VFIO_USER_DMA_MAP_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_dma_map(uint64_t iova, uint64_t size, uint64_t off, uint32_t flags, bool async_ops) {
    (void)iova;
    (void)size;
    (void)off;
    (void)flags;
    (void)async_ops;
}
#define TRACE_VFIO_USER_DMA_UNMAP 0
#define TRACE_VFIO_USER_DMA_UNMAP_ENABLED 0
#define TRACE_VFIO_USER_DMA_UNMAP_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_dma_unmap(uint64_t iova, uint64_t size, uint32_t flags,  bool async_ops) {
    (void)iova;
    (void)size;
    (void)flags;
    (void)async_ops;
}
#define TRACE_VFIO_USER_GET_INFO 0
#define TRACE_VFIO_USER_GET_INFO_ENABLED 0
#define TRACE_VFIO_USER_GET_INFO_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_get_info(uint32_t nregions, uint32_t nirqs) {
    (void)nregions;
    (void)nirqs;
}
#define TRACE_VFIO_USER_GET_IRQ_INFO 0
#define TRACE_VFIO_USER_GET_IRQ_INFO_ENABLED 0
#define TRACE_VFIO_USER_GET_IRQ_INFO_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_get_irq_info(uint32_t index, uint32_t flags, uint32_t count) {
    (void)index;
    (void)flags;
    (void)count;
}
#define TRACE_VFIO_USER_GET_REGION_INFO 0
#define TRACE_VFIO_USER_GET_REGION_INFO_ENABLED 0
#define TRACE_VFIO_USER_GET_REGION_INFO_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_get_region_info(uint32_t index, uint32_t flags, uint64_t size) {
    (void)index;
    (void)flags;
    (void)size;
}
#define TRACE_VFIO_USER_RECV_HDR 0
#define TRACE_VFIO_USER_RECV_HDR_ENABLED 0
#define TRACE_VFIO_USER_RECV_HDR_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_recv_hdr(const char *name, uint16_t id, uint16_t cmd, uint32_t size, uint32_t flags) {
    (void)name;
    (void)id;
    (void)cmd;
    (void)size;
    (void)flags;
}
#define TRACE_VFIO_USER_RECV_READ 0
#define TRACE_VFIO_USER_RECV_READ_ENABLED 0
#define TRACE_VFIO_USER_RECV_READ_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_recv_read(uint16_t id, int read) {
    (void)id;
    (void)read;
}
#define TRACE_VFIO_USER_RECV_REQUEST 0
#define TRACE_VFIO_USER_RECV_REQUEST_ENABLED 0
#define TRACE_VFIO_USER_RECV_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_recv_request(uint16_t cmd) {
    (void)cmd;
}
#define TRACE_VFIO_USER_REGION_RW 0
#define TRACE_VFIO_USER_REGION_RW_ENABLED 0
#define TRACE_VFIO_USER_REGION_RW_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_region_rw(uint32_t region, uint64_t off, uint32_t count) {
    (void)region;
    (void)off;
    (void)count;
}
#define TRACE_VFIO_USER_SEND_WRITE 0
#define TRACE_VFIO_USER_SEND_WRITE_ENABLED 0
#define TRACE_VFIO_USER_SEND_WRITE_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_send_write(uint16_t id, int wrote) {
    (void)id;
    (void)wrote;
}
#define TRACE_VFIO_USER_SET_IRQS 0
#define TRACE_VFIO_USER_SET_IRQS_ENABLED 0
#define TRACE_VFIO_USER_SET_IRQS_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_set_irqs(uint32_t index, uint32_t start, uint32_t count, uint32_t flags) {
    (void)index;
    (void)start;
    (void)count;
    (void)flags;
}
#define TRACE_VFIO_USER_VERSION 0
#define TRACE_VFIO_USER_VERSION_ENABLED 0
#define TRACE_VFIO_USER_VERSION_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_version(uint16_t major, uint16_t minor, const char *caps) {
    (void)major;
    (void)minor;
    (void)caps;
}
#define TRACE_VFIO_USER_WRMULTI 0
#define TRACE_VFIO_USER_WRMULTI_ENABLED 0
#define TRACE_VFIO_USER_WRMULTI_BACKEND_DSTATE() (0)
static inline void trace_vfio_user_wrmulti(const char *s, uint64_t wr_cnt) {
    (void)s;
    (void)wr_cnt;
}

#endif