/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_I2C_H
#define TRACE_TRACE_HW_I2C_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_ALLWINNER_I2C_READ 0
#define TRACE_ALLWINNER_I2C_READ_ENABLED 0
#define TRACE_ALLWINNER_I2C_READ_BACKEND_DSTATE() (0)
static inline void trace_allwinner_i2c_read(const char* reg_name, uint64_t offset, uint64_t value) {
    (void)reg_name;
    (void)offset;
    (void)value;
}
#define TRACE_ALLWINNER_I2C_WRITE 0
#define TRACE_ALLWINNER_I2C_WRITE_ENABLED 0
#define TRACE_ALLWINNER_I2C_WRITE_BACKEND_DSTATE() (0)
static inline void trace_allwinner_i2c_write(const char* reg_name, uint64_t offset, uint64_t value) {
    (void)reg_name;
    (void)offset;
    (void)value;
}
#define TRACE_ASPEED_I2C_BUS_CMD 0
#define TRACE_ASPEED_I2C_BUS_CMD_ENABLED 0
#define TRACE_ASPEED_I2C_BUS_CMD_BACKEND_DSTATE() (0)
static inline void trace_aspeed_i2c_bus_cmd(uint32_t cmd, const char *cmd_flags, uint32_t count, uint32_t intr_status) {
    (void)cmd;
    (void)cmd_flags;
    (void)count;
    (void)intr_status;
}
#define TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT 0
#define TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT_ENABLED 0
#define TRACE_ASPEED_I2C_BUS_RAISE_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_aspeed_i2c_bus_raise_interrupt(uint32_t intr_status, const char *s) {
    (void)intr_status;
    (void)s;
}
#define TRACE_ASPEED_I2C_BUS_READ 0
#define TRACE_ASPEED_I2C_BUS_READ_ENABLED 0
#define TRACE_ASPEED_I2C_BUS_READ_BACKEND_DSTATE() (0)
static inline void trace_aspeed_i2c_bus_read(uint32_t busid, uint64_t offset, unsigned size, uint64_t value) {
    (void)busid;
    (void)offset;
    (void)size;
    (void)value;
}
#define TRACE_ASPEED_I2C_BUS_RECV 0
#define TRACE_ASPEED_I2C_BUS_RECV_ENABLED 0
#define TRACE_ASPEED_I2C_BUS_RECV_BACKEND_DSTATE() (0)
static inline void trace_aspeed_i2c_bus_recv(const char *mode, int i, int count, uint8_t byte) {
    (void)mode;
    (void)i;
    (void)count;
    (void)byte;
}
#define TRACE_ASPEED_I2C_BUS_SEND 0
#define TRACE_ASPEED_I2C_BUS_SEND_ENABLED 0
#define TRACE_ASPEED_I2C_BUS_SEND_BACKEND_DSTATE() (0)
static inline void trace_aspeed_i2c_bus_send(const char *mode, int i, int count, uint8_t byte) {
    (void)mode;
    (void)i;
    (void)count;
    (void)byte;
}
#define TRACE_ASPEED_I2C_BUS_WRITE 0
#define TRACE_ASPEED_I2C_BUS_WRITE_ENABLED 0
#define TRACE_ASPEED_I2C_BUS_WRITE_BACKEND_DSTATE() (0)
static inline void trace_aspeed_i2c_bus_write(uint32_t busid, uint64_t offset, unsigned size, uint64_t value) {
    (void)busid;
    (void)offset;
    (void)size;
    (void)value;
}
#define TRACE_BITBANG_I2C_ADDR 0
#define TRACE_BITBANG_I2C_ADDR_ENABLED 0
#define TRACE_BITBANG_I2C_ADDR_BACKEND_DSTATE() (0)
static inline void trace_bitbang_i2c_addr(uint8_t addr) {
    (void)addr;
}
#define TRACE_BITBANG_I2C_DATA 0
#define TRACE_BITBANG_I2C_DATA_ENABLED 0
#define TRACE_BITBANG_I2C_DATA_BACKEND_DSTATE() (0)
static inline void trace_bitbang_i2c_data(unsigned clk, unsigned dat, unsigned old_out, unsigned new_out) {
    (void)clk;
    (void)dat;
    (void)old_out;
    (void)new_out;
}
#define TRACE_BITBANG_I2C_RECV 0
#define TRACE_BITBANG_I2C_RECV_ENABLED 0
#define TRACE_BITBANG_I2C_RECV_BACKEND_DSTATE() (0)
static inline void trace_bitbang_i2c_recv(uint8_t byte) {
    (void)byte;
}
#define TRACE_BITBANG_I2C_SEND 0
#define TRACE_BITBANG_I2C_SEND_ENABLED 0
#define TRACE_BITBANG_I2C_SEND_BACKEND_DSTATE() (0)
static inline void trace_bitbang_i2c_send(uint8_t byte) {
    (void)byte;
}
#define TRACE_BITBANG_I2C_STATE 0
#define TRACE_BITBANG_I2C_STATE_ENABLED 0
#define TRACE_BITBANG_I2C_STATE_BACKEND_DSTATE() (0)
static inline void trace_bitbang_i2c_state(const char *old_state, const char *new_state) {
    (void)old_state;
    (void)new_state;
}
#define TRACE_I2C_ACK 0
#define TRACE_I2C_ACK_ENABLED 0
#define TRACE_I2C_ACK_BACKEND_DSTATE() (0)
static inline void trace_i2c_ack(void) {
}
#define TRACE_I2C_EVENT 0
#define TRACE_I2C_EVENT_ENABLED 0
#define TRACE_I2C_EVENT_BACKEND_DSTATE() (0)
static inline void trace_i2c_event(const char *event, uint8_t address) {
    (void)event;
    (void)address;
}
#define TRACE_I2C_RECV 0
#define TRACE_I2C_RECV_ENABLED 0
#define TRACE_I2C_RECV_BACKEND_DSTATE() (0)
static inline void trace_i2c_recv(uint8_t address, uint8_t data) {
    (void)address;
    (void)data;
}
#define TRACE_I2C_SEND 0
#define TRACE_I2C_SEND_ENABLED 0
#define TRACE_I2C_SEND_BACKEND_DSTATE() (0)
static inline void trace_i2c_send(uint8_t address, uint8_t data) {
    (void)address;
    (void)data;
}
#define TRACE_I2C_SEND_ASYNC 0
#define TRACE_I2C_SEND_ASYNC_ENABLED 0
#define TRACE_I2C_SEND_ASYNC_BACKEND_DSTATE() (0)
static inline void trace_i2c_send_async(uint8_t address, uint8_t data) {
    (void)address;
    (void)data;
}
#define TRACE_IMX_I2C_READ 0
#define TRACE_IMX_I2C_READ_ENABLED 0
#define TRACE_IMX_I2C_READ_BACKEND_DSTATE() (0)
static inline void trace_imx_i2c_read(const char *id, const char *reg, uint64_t ofs, uint64_t value) {
    (void)id;
    (void)reg;
    (void)ofs;
    (void)value;
}
#define TRACE_IMX_I2C_WRITE 0
#define TRACE_IMX_I2C_WRITE_ENABLED 0
#define TRACE_IMX_I2C_WRITE_BACKEND_DSTATE() (0)
static inline void trace_imx_i2c_write(const char *id, const char *reg, uint64_t ofs, uint64_t value) {
    (void)id;
    (void)reg;
    (void)ofs;
    (void)value;
}
#define TRACE_MPC_I2C_READ 0
#define TRACE_MPC_I2C_READ_ENABLED 0
#define TRACE_MPC_I2C_READ_BACKEND_DSTATE() (0)
static inline void trace_mpc_i2c_read(uint64_t addr, uint32_t value) {
    (void)addr;
    (void)value;
}
#define TRACE_MPC_I2C_WRITE 0
#define TRACE_MPC_I2C_WRITE_ENABLED 0
#define TRACE_MPC_I2C_WRITE_BACKEND_DSTATE() (0)
static inline void trace_mpc_i2c_write(uint64_t addr, uint32_t value) {
    (void)addr;
    (void)value;
}
#define TRACE_NPCM7XX_SMBUS_NACK 0
#define TRACE_NPCM7XX_SMBUS_NACK_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_NACK_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_nack(const char *id) {
    (void)id;
}
#define TRACE_NPCM7XX_SMBUS_READ 0
#define TRACE_NPCM7XX_SMBUS_READ_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_READ_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_read(const char *id, uint64_t offset, uint64_t value, unsigned size) {
    (void)id;
    (void)offset;
    (void)value;
    (void)size;
}
#define TRACE_NPCM7XX_SMBUS_RECV_BYTE 0
#define TRACE_NPCM7XX_SMBUS_RECV_BYTE_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_RECV_BYTE_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_recv_byte(const char *id, uint8_t value) {
    (void)id;
    (void)value;
}
#define TRACE_NPCM7XX_SMBUS_RECV_FIFO 0
#define TRACE_NPCM7XX_SMBUS_RECV_FIFO_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_RECV_FIFO_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_recv_fifo(const char *id, uint8_t received, uint8_t expected) {
    (void)id;
    (void)received;
    (void)expected;
}
#define TRACE_NPCM7XX_SMBUS_SEND_ADDRESS 0
#define TRACE_NPCM7XX_SMBUS_SEND_ADDRESS_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_SEND_ADDRESS_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_send_address(const char *id, uint8_t addr, int recv, int success) {
    (void)id;
    (void)addr;
    (void)recv;
    (void)success;
}
#define TRACE_NPCM7XX_SMBUS_SEND_BYTE 0
#define TRACE_NPCM7XX_SMBUS_SEND_BYTE_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_SEND_BYTE_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_send_byte(const char *id, uint8_t value, int success) {
    (void)id;
    (void)value;
    (void)success;
}
#define TRACE_NPCM7XX_SMBUS_START 0
#define TRACE_NPCM7XX_SMBUS_START_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_START_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_start(const char *id, int success) {
    (void)id;
    (void)success;
}
#define TRACE_NPCM7XX_SMBUS_STOP 0
#define TRACE_NPCM7XX_SMBUS_STOP_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_STOP_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_stop(const char *id) {
    (void)id;
}
#define TRACE_NPCM7XX_SMBUS_WRITE 0
#define TRACE_NPCM7XX_SMBUS_WRITE_ENABLED 0
#define TRACE_NPCM7XX_SMBUS_WRITE_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_smbus_write(const char *id, uint64_t offset, uint64_t value, unsigned size) {
    (void)id;
    (void)offset;
    (void)value;
    (void)size;
}
#define TRACE_PCA954X_READ_DATA 0
#define TRACE_PCA954X_READ_DATA_ENABLED 0
#define TRACE_PCA954X_READ_DATA_BACKEND_DSTATE() (0)
static inline void trace_pca954x_read_data(uint8_t value) {
    (void)value;
}
#define TRACE_PCA954X_WRITE_BYTES 0
#define TRACE_PCA954X_WRITE_BYTES_ENABLED 0
#define TRACE_PCA954X_WRITE_BYTES_BACKEND_DSTATE() (0)
static inline void trace_pca954x_write_bytes(uint8_t value) {
    (void)value;
}
#define TRACE_SMBUS_IOPORT_READB 0
#define TRACE_SMBUS_IOPORT_READB_ENABLED 0
#define TRACE_SMBUS_IOPORT_READB_BACKEND_DSTATE() (0)
static inline void trace_smbus_ioport_readb(uint16_t addr, uint8_t data) {
    (void)addr;
    (void)data;
}
#define TRACE_SMBUS_IOPORT_WRITEB 0
#define TRACE_SMBUS_IOPORT_WRITEB_ENABLED 0
#define TRACE_SMBUS_IOPORT_WRITEB_BACKEND_DSTATE() (0)
static inline void trace_smbus_ioport_writeb(uint16_t addr, uint8_t data) {
    (void)addr;
    (void)data;
}
#define TRACE_SMBUS_TRANSACTION 0
#define TRACE_SMBUS_TRANSACTION_ENABLED 0
#define TRACE_SMBUS_TRANSACTION_BACKEND_DSTATE() (0)
static inline void trace_smbus_transaction(uint8_t addr, uint8_t prot) {
    (void)addr;
    (void)prot;
}

#endif