/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_REPLAY_H
#define TRACE_TRACE_REPLAY_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_REPLAY_ADVANCE_CURRENT_ICOUNT 0
#define TRACE_REPLAY_ADVANCE_CURRENT_ICOUNT_ENABLED 0
#define TRACE_REPLAY_ADVANCE_CURRENT_ICOUNT_BACKEND_DSTATE() (0)
static inline void trace_replay_advance_current_icount(uint64_t current_icount, int diff) {
    (void)current_icount;
    (void)diff;
}
#define TRACE_REPLAY_FETCH_DATA_KIND 0
#define TRACE_REPLAY_FETCH_DATA_KIND_ENABLED 0
#define TRACE_REPLAY_FETCH_DATA_KIND_BACKEND_DSTATE() (0)
static inline void trace_replay_fetch_data_kind(void) {
}
#define TRACE_REPLAY_GET_BYTE 0
#define TRACE_REPLAY_GET_BYTE_ENABLED 0
#define TRACE_REPLAY_GET_BYTE_BACKEND_DSTATE() (0)
static inline void trace_replay_get_byte(uint8_t byte) {
    (void)byte;
}
#define TRACE_REPLAY_GET_DWORD 0
#define TRACE_REPLAY_GET_DWORD_ENABLED 0
#define TRACE_REPLAY_GET_DWORD_BACKEND_DSTATE() (0)
static inline void trace_replay_get_dword(uint32_t dword) {
    (void)dword;
}
#define TRACE_REPLAY_GET_EVENT 0
#define TRACE_REPLAY_GET_EVENT_ENABLED 0
#define TRACE_REPLAY_GET_EVENT_BACKEND_DSTATE() (0)
static inline void trace_replay_get_event(uint32_t current, uint8_t data) {
    (void)current;
    (void)data;
}
#define TRACE_REPLAY_GET_QWORD 0
#define TRACE_REPLAY_GET_QWORD_ENABLED 0
#define TRACE_REPLAY_GET_QWORD_BACKEND_DSTATE() (0)
static inline void trace_replay_get_qword(uint64_t qword) {
    (void)qword;
}
#define TRACE_REPLAY_GET_WORD 0
#define TRACE_REPLAY_GET_WORD_ENABLED 0
#define TRACE_REPLAY_GET_WORD_BACKEND_DSTATE() (0)
static inline void trace_replay_get_word(uint16_t word) {
    (void)word;
}
#define TRACE_REPLAY_PUT_BYTE 0
#define TRACE_REPLAY_PUT_BYTE_ENABLED 0
#define TRACE_REPLAY_PUT_BYTE_BACKEND_DSTATE() (0)
static inline void trace_replay_put_byte(uint8_t event) {
    (void)event;
}
#define TRACE_REPLAY_PUT_DWORD 0
#define TRACE_REPLAY_PUT_DWORD_ENABLED 0
#define TRACE_REPLAY_PUT_DWORD_BACKEND_DSTATE() (0)
static inline void trace_replay_put_dword(uint32_t event) {
    (void)event;
}
#define TRACE_REPLAY_PUT_EVENT 0
#define TRACE_REPLAY_PUT_EVENT_ENABLED 0
#define TRACE_REPLAY_PUT_EVENT_BACKEND_DSTATE() (0)
static inline void trace_replay_put_event(uint8_t event) {
    (void)event;
}
#define TRACE_REPLAY_PUT_QWORD 0
#define TRACE_REPLAY_PUT_QWORD_ENABLED 0
#define TRACE_REPLAY_PUT_QWORD_BACKEND_DSTATE() (0)
static inline void trace_replay_put_qword(uint64_t event) {
    (void)event;
}
#define TRACE_REPLAY_PUT_WORD 0
#define TRACE_REPLAY_PUT_WORD_ENABLED 0
#define TRACE_REPLAY_PUT_WORD_BACKEND_DSTATE() (0)
static inline void trace_replay_put_word(uint16_t event) {
    (void)event;
}

#endif