/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_BLOCK_H
#define TRACE_TRACE_BLOCK_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_BACKUP_DO_COW_ENTER 0
#define TRACE_BACKUP_DO_COW_ENTER_ENABLED 0
#define TRACE_BACKUP_DO_COW_ENTER_BACKEND_DSTATE() (0)
static inline void trace_backup_do_cow_enter(void *job, int64_t start, int64_t offset, uint64_t bytes) {
    (void)job;
    (void)start;
    (void)offset;
    (void)bytes;
}
#define TRACE_BACKUP_DO_COW_RETURN 0
#define TRACE_BACKUP_DO_COW_RETURN_ENABLED 0
#define TRACE_BACKUP_DO_COW_RETURN_BACKEND_DSTATE() (0)
static inline void trace_backup_do_cow_return(void *job, int64_t offset, uint64_t bytes, int ret) {
    (void)job;
    (void)offset;
    (void)bytes;
    (void)ret;
}
#define TRACE_BDRV_CO_COPY_RANGE_FROM 0
#define TRACE_BDRV_CO_COPY_RANGE_FROM_ENABLED 0
#define TRACE_BDRV_CO_COPY_RANGE_FROM_BACKEND_DSTATE() (0)
static inline void trace_bdrv_co_copy_range_from(void *src, int64_t src_offset, void *dst, int64_t dst_offset, int64_t bytes, int read_flags, int write_flags) {
    (void)src;
    (void)src_offset;
    (void)dst;
    (void)dst_offset;
    (void)bytes;
    (void)read_flags;
    (void)write_flags;
}
#define TRACE_BDRV_CO_COPY_RANGE_TO 0
#define TRACE_BDRV_CO_COPY_RANGE_TO_ENABLED 0
#define TRACE_BDRV_CO_COPY_RANGE_TO_BACKEND_DSTATE() (0)
static inline void trace_bdrv_co_copy_range_to(void *src, int64_t src_offset, void *dst, int64_t dst_offset, int64_t bytes, int read_flags, int write_flags) {
    (void)src;
    (void)src_offset;
    (void)dst;
    (void)dst_offset;
    (void)bytes;
    (void)read_flags;
    (void)write_flags;
}
#define TRACE_BDRV_CO_DO_COPY_ON_READV 0
#define TRACE_BDRV_CO_DO_COPY_ON_READV_ENABLED 0
#define TRACE_BDRV_CO_DO_COPY_ON_READV_BACKEND_DSTATE() (0)
static inline void trace_bdrv_co_do_copy_on_readv(void *bs, int64_t offset, int64_t bytes, int64_t cluster_offset, int64_t cluster_bytes) {
    (void)bs;
    (void)offset;
    (void)bytes;
    (void)cluster_offset;
    (void)cluster_bytes;
}
#define TRACE_BDRV_CO_PREADV_PART 0
#define TRACE_BDRV_CO_PREADV_PART_ENABLED 0
#define TRACE_BDRV_CO_PREADV_PART_BACKEND_DSTATE() (0)
static inline void trace_bdrv_co_preadv_part(void *bs, int64_t offset, int64_t bytes, unsigned int flags) {
    (void)bs;
    (void)offset;
    (void)bytes;
    (void)flags;
}
#define TRACE_BDRV_CO_PWRITE_ZEROES 0
#define TRACE_BDRV_CO_PWRITE_ZEROES_ENABLED 0
#define TRACE_BDRV_CO_PWRITE_ZEROES_BACKEND_DSTATE() (0)
static inline void trace_bdrv_co_pwrite_zeroes(void *bs, int64_t offset, int64_t bytes, int flags) {
    (void)bs;
    (void)offset;
    (void)bytes;
    (void)flags;
}
#define TRACE_BDRV_CO_PWRITEV_PART 0
#define TRACE_BDRV_CO_PWRITEV_PART_ENABLED 0
#define TRACE_BDRV_CO_PWRITEV_PART_BACKEND_DSTATE() (0)
static inline void trace_bdrv_co_pwritev_part(void *bs, int64_t offset, int64_t bytes, unsigned int flags) {
    (void)bs;
    (void)offset;
    (void)bytes;
    (void)flags;
}
#define TRACE_BDRV_LOCK_MEDIUM 0
#define TRACE_BDRV_LOCK_MEDIUM_ENABLED 0
#define TRACE_BDRV_LOCK_MEDIUM_BACKEND_DSTATE() (0)
static inline void trace_bdrv_lock_medium(void *bs, bool locked) {
    (void)bs;
    (void)locked;
}
#define TRACE_BDRV_OPEN_COMMON 0
#define TRACE_BDRV_OPEN_COMMON_ENABLED 0
#define TRACE_BDRV_OPEN_COMMON_BACKEND_DSTATE() (0)
static inline void trace_bdrv_open_common(void *bs, const char *filename, int flags, const char *format_name) {
    (void)bs;
    (void)filename;
    (void)flags;
    (void)format_name;
}
#define TRACE_BLK_CO_PREADV 0
#define TRACE_BLK_CO_PREADV_ENABLED 0
#define TRACE_BLK_CO_PREADV_BACKEND_DSTATE() (0)
static inline void trace_blk_co_preadv(void *blk, void *bs, int64_t offset, int64_t bytes, int flags) {
    (void)blk;
    (void)bs;
    (void)offset;
    (void)bytes;
    (void)flags;
}
#define TRACE_BLK_CO_PWRITEV 0
#define TRACE_BLK_CO_PWRITEV_ENABLED 0
#define TRACE_BLK_CO_PWRITEV_BACKEND_DSTATE() (0)
static inline void trace_blk_co_pwritev(void *blk, void *bs, int64_t offset, int64_t bytes, int flags) {
    (void)blk;
    (void)bs;
    (void)offset;
    (void)bytes;
    (void)flags;
}
#define TRACE_BLK_ROOT_ATTACH 0
#define TRACE_BLK_ROOT_ATTACH_ENABLED 0
#define TRACE_BLK_ROOT_ATTACH_BACKEND_DSTATE() (0)
static inline void trace_blk_root_attach(void *child, void *blk, void *bs) {
    (void)child;
    (void)blk;
    (void)bs;
}
#define TRACE_BLK_ROOT_DETACH 0
#define TRACE_BLK_ROOT_DETACH_ENABLED 0
#define TRACE_BLK_ROOT_DETACH_BACKEND_DSTATE() (0)
static inline void trace_blk_root_detach(void *child, void *blk, void *bs) {
    (void)child;
    (void)blk;
    (void)bs;
}
#define TRACE_BLOCK_COPY_COPY_RANGE_FAIL 0
#define TRACE_BLOCK_COPY_COPY_RANGE_FAIL_ENABLED 0
#define TRACE_BLOCK_COPY_COPY_RANGE_FAIL_BACKEND_DSTATE() (0)
static inline void trace_block_copy_copy_range_fail(void *bcs, int64_t start, int ret) {
    (void)bcs;
    (void)start;
    (void)ret;
}
#define TRACE_BLOCK_COPY_PROCESS 0
#define TRACE_BLOCK_COPY_PROCESS_ENABLED 0
#define TRACE_BLOCK_COPY_PROCESS_BACKEND_DSTATE() (0)
static inline void trace_block_copy_process(void *bcs, int64_t start) {
    (void)bcs;
    (void)start;
}
#define TRACE_BLOCK_COPY_READ_FAIL 0
#define TRACE_BLOCK_COPY_READ_FAIL_ENABLED 0
#define TRACE_BLOCK_COPY_READ_FAIL_BACKEND_DSTATE() (0)
static inline void trace_block_copy_read_fail(void *bcs, int64_t start, int ret) {
    (void)bcs;
    (void)start;
    (void)ret;
}
#define TRACE_BLOCK_COPY_SKIP_RANGE 0
#define TRACE_BLOCK_COPY_SKIP_RANGE_ENABLED 0
#define TRACE_BLOCK_COPY_SKIP_RANGE_BACKEND_DSTATE() (0)
static inline void trace_block_copy_skip_range(void *bcs, int64_t start, uint64_t bytes) {
    (void)bcs;
    (void)start;
    (void)bytes;
}
#define TRACE_BLOCK_COPY_WRITE_FAIL 0
#define TRACE_BLOCK_COPY_WRITE_FAIL_ENABLED 0
#define TRACE_BLOCK_COPY_WRITE_FAIL_BACKEND_DSTATE() (0)
static inline void trace_block_copy_write_fail(void *bcs, int64_t start, int ret) {
    (void)bcs;
    (void)start;
    (void)ret;
}
#define TRACE_BLOCK_COPY_WRITE_ZEROES_FAIL 0
#define TRACE_BLOCK_COPY_WRITE_ZEROES_FAIL_ENABLED 0
#define TRACE_BLOCK_COPY_WRITE_ZEROES_FAIL_BACKEND_DSTATE() (0)
static inline void trace_block_copy_write_zeroes_fail(void *bcs, int64_t start, int ret) {
    (void)bcs;
    (void)start;
    (void)ret;
}
#define TRACE_COMMIT_ONE_ITERATION 0
#define TRACE_COMMIT_ONE_ITERATION_ENABLED 0
#define TRACE_COMMIT_ONE_ITERATION_BACKEND_DSTATE() (0)
static inline void trace_commit_one_iteration(void *s, int64_t offset, uint64_t bytes, int is_allocated) {
    (void)s;
    (void)offset;
    (void)bytes;
    (void)is_allocated;
}
#define TRACE_COMMIT_START 0
#define TRACE_COMMIT_START_ENABLED 0
#define TRACE_COMMIT_START_BACKEND_DSTATE() (0)
static inline void trace_commit_start(void *bs, void *base, void *top, void *s) {
    (void)bs;
    (void)base;
    (void)top;
    (void)s;
}
#define TRACE_CURL_CLOSE 0
#define TRACE_CURL_CLOSE_ENABLED 0
#define TRACE_CURL_CLOSE_BACKEND_DSTATE() (0)
static inline void trace_curl_close(void) {
}
#define TRACE_CURL_OPEN 0
#define TRACE_CURL_OPEN_ENABLED 0
#define TRACE_CURL_OPEN_BACKEND_DSTATE() (0)
static inline void trace_curl_open(const char *file) {
    (void)file;
}
#define TRACE_CURL_OPEN_SIZE 0
#define TRACE_CURL_OPEN_SIZE_ENABLED 0
#define TRACE_CURL_OPEN_SIZE_BACKEND_DSTATE() (0)
static inline void trace_curl_open_size(uint64_t size) {
    (void)size;
}
#define TRACE_CURL_READ_CB 0
#define TRACE_CURL_READ_CB_ENABLED 0
#define TRACE_CURL_READ_CB_BACKEND_DSTATE() (0)
static inline void trace_curl_read_cb(size_t realsize) {
    (void)realsize;
}
#define TRACE_CURL_SETUP_PREADV 0
#define TRACE_CURL_SETUP_PREADV_ENABLED 0
#define TRACE_CURL_SETUP_PREADV_BACKEND_DSTATE() (0)
static inline void trace_curl_setup_preadv(uint64_t bytes, uint64_t start, const char *range) {
    (void)bytes;
    (void)start;
    (void)range;
}
#define TRACE_CURL_SOCK_CB 0
#define TRACE_CURL_SOCK_CB_ENABLED 0
#define TRACE_CURL_SOCK_CB_BACKEND_DSTATE() (0)
static inline void trace_curl_sock_cb(int action, int fd) {
    (void)action;
    (void)fd;
}
#define TRACE_CURL_TIMER_CB 0
#define TRACE_CURL_TIMER_CB_ENABLED 0
#define TRACE_CURL_TIMER_CB_BACKEND_DSTATE() (0)
static inline void trace_curl_timer_cb(long timeout_ms) {
    (void)timeout_ms;
}
#define TRACE_FILE_COPY_FILE_RANGE 0
#define TRACE_FILE_COPY_FILE_RANGE_ENABLED 0
#define TRACE_FILE_COPY_FILE_RANGE_BACKEND_DSTATE() (0)
static inline void trace_file_copy_file_range(void *bs, int src, int64_t src_off, int dst, int64_t dst_off, int64_t bytes, int flags, int64_t ret) {
    (void)bs;
    (void)src;
    (void)src_off;
    (void)dst;
    (void)dst_off;
    (void)bytes;
    (void)flags;
    (void)ret;
}
#define TRACE_FILE_FINDEJECTABLEOPTICALMEDIA 0
#define TRACE_FILE_FINDEJECTABLEOPTICALMEDIA_ENABLED 0
#define TRACE_FILE_FINDEJECTABLEOPTICALMEDIA_BACKEND_DSTATE() (0)
static inline void trace_file_FindEjectableOpticalMedia(const char *media) {
    (void)media;
}
#define TRACE_FILE_FLUSH_FDATASYNC_FAILED 0
#define TRACE_FILE_FLUSH_FDATASYNC_FAILED_ENABLED 0
#define TRACE_FILE_FLUSH_FDATASYNC_FAILED_BACKEND_DSTATE() (0)
static inline void trace_file_flush_fdatasync_failed(int err) {
    (void)err;
}
#define TRACE_FILE_HDEV_IS_SG 0
#define TRACE_FILE_HDEV_IS_SG_ENABLED 0
#define TRACE_FILE_HDEV_IS_SG_BACKEND_DSTATE() (0)
static inline void trace_file_hdev_is_sg(int type, int version) {
    (void)type;
    (void)version;
}
#define TRACE_FILE_PAIO_SUBMIT 0
#define TRACE_FILE_PAIO_SUBMIT_ENABLED 0
#define TRACE_FILE_PAIO_SUBMIT_BACKEND_DSTATE() (0)
static inline void trace_file_paio_submit(void *acb, void *opaque, int64_t offset, int count, int type) {
    (void)acb;
    (void)opaque;
    (void)offset;
    (void)count;
    (void)type;
}
#define TRACE_FILE_SETUP_CDROM 0
#define TRACE_FILE_SETUP_CDROM_ENABLED 0
#define TRACE_FILE_SETUP_CDROM_BACKEND_DSTATE() (0)
static inline void trace_file_setup_cdrom(const char *partition) {
    (void)partition;
}
#define TRACE_ISCSI_XCOPY 0
#define TRACE_ISCSI_XCOPY_ENABLED 0
#define TRACE_ISCSI_XCOPY_BACKEND_DSTATE() (0)
static inline void trace_iscsi_xcopy(void *src_lun, uint64_t src_off, void *dst_lun, uint64_t dst_off, uint64_t bytes, int ret) {
    (void)src_lun;
    (void)src_off;
    (void)dst_lun;
    (void)dst_off;
    (void)bytes;
    (void)ret;
}
#define TRACE_LURING_CO_SUBMIT 0
#define TRACE_LURING_CO_SUBMIT_ENABLED 0
#define TRACE_LURING_CO_SUBMIT_BACKEND_DSTATE() (0)
static inline void trace_luring_co_submit(void *bs, void *req, int fd, uint64_t offset, size_t nbytes, int type) {
    (void)bs;
    (void)req;
    (void)fd;
    (void)offset;
    (void)nbytes;
    (void)type;
}
#define TRACE_LURING_CQE_HANDLER 0
#define TRACE_LURING_CQE_HANDLER_ENABLED 0
#define TRACE_LURING_CQE_HANDLER_BACKEND_DSTATE() (0)
static inline void trace_luring_cqe_handler(void *req, int ret) {
    (void)req;
    (void)ret;
}
#define TRACE_LURING_RESUBMIT_SHORT_READ 0
#define TRACE_LURING_RESUBMIT_SHORT_READ_ENABLED 0
#define TRACE_LURING_RESUBMIT_SHORT_READ_BACKEND_DSTATE() (0)
static inline void trace_luring_resubmit_short_read(void *req, int nread) {
    (void)req;
    (void)nread;
}
#define TRACE_MIRROR_BEFORE_DRAIN 0
#define TRACE_MIRROR_BEFORE_DRAIN_ENABLED 0
#define TRACE_MIRROR_BEFORE_DRAIN_BACKEND_DSTATE() (0)
static inline void trace_mirror_before_drain(void *s, int64_t cnt) {
    (void)s;
    (void)cnt;
}
#define TRACE_MIRROR_BEFORE_FLUSH 0
#define TRACE_MIRROR_BEFORE_FLUSH_ENABLED 0
#define TRACE_MIRROR_BEFORE_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_mirror_before_flush(void *s) {
    (void)s;
}
#define TRACE_MIRROR_BEFORE_SLEEP 0
#define TRACE_MIRROR_BEFORE_SLEEP_ENABLED 0
#define TRACE_MIRROR_BEFORE_SLEEP_BACKEND_DSTATE() (0)
static inline void trace_mirror_before_sleep(void *s, int64_t cnt, int synced, uint64_t delay_ns) {
    (void)s;
    (void)cnt;
    (void)synced;
    (void)delay_ns;
}
#define TRACE_MIRROR_ITERATION_DONE 0
#define TRACE_MIRROR_ITERATION_DONE_ENABLED 0
#define TRACE_MIRROR_ITERATION_DONE_BACKEND_DSTATE() (0)
static inline void trace_mirror_iteration_done(void *s, int64_t offset, uint64_t bytes, int ret) {
    (void)s;
    (void)offset;
    (void)bytes;
    (void)ret;
}
#define TRACE_MIRROR_ONE_ITERATION 0
#define TRACE_MIRROR_ONE_ITERATION_ENABLED 0
#define TRACE_MIRROR_ONE_ITERATION_BACKEND_DSTATE() (0)
static inline void trace_mirror_one_iteration(void *s, int64_t offset, uint64_t bytes) {
    (void)s;
    (void)offset;
    (void)bytes;
}
#define TRACE_MIRROR_RESTART_ITER 0
#define TRACE_MIRROR_RESTART_ITER_ENABLED 0
#define TRACE_MIRROR_RESTART_ITER_BACKEND_DSTATE() (0)
static inline void trace_mirror_restart_iter(void *s, int64_t cnt) {
    (void)s;
    (void)cnt;
}
#define TRACE_MIRROR_START 0
#define TRACE_MIRROR_START_ENABLED 0
#define TRACE_MIRROR_START_BACKEND_DSTATE() (0)
static inline void trace_mirror_start(void *bs, void *s, void *opaque) {
    (void)bs;
    (void)s;
    (void)opaque;
}
#define TRACE_MIRROR_YIELD 0
#define TRACE_MIRROR_YIELD_ENABLED 0
#define TRACE_MIRROR_YIELD_BACKEND_DSTATE() (0)
static inline void trace_mirror_yield(void *s, int64_t cnt, int buf_free_count, int in_flight) {
    (void)s;
    (void)cnt;
    (void)buf_free_count;
    (void)in_flight;
}
#define TRACE_MIRROR_YIELD_IN_FLIGHT 0
#define TRACE_MIRROR_YIELD_IN_FLIGHT_ENABLED 0
#define TRACE_MIRROR_YIELD_IN_FLIGHT_BACKEND_DSTATE() (0)
static inline void trace_mirror_yield_in_flight(void *s, int64_t offset, int in_flight) {
    (void)s;
    (void)offset;
    (void)in_flight;
}
#define TRACE_NBD_CLIENT_HANDSHAKE 0
#define TRACE_NBD_CLIENT_HANDSHAKE_ENABLED 0
#define TRACE_NBD_CLIENT_HANDSHAKE_BACKEND_DSTATE() (0)
static inline void trace_nbd_client_handshake(const char *export_name) {
    (void)export_name;
}
#define TRACE_NBD_CLIENT_HANDSHAKE_SUCCESS 0
#define TRACE_NBD_CLIENT_HANDSHAKE_SUCCESS_ENABLED 0
#define TRACE_NBD_CLIENT_HANDSHAKE_SUCCESS_BACKEND_DSTATE() (0)
static inline void trace_nbd_client_handshake_success(const char *export_name) {
    (void)export_name;
}
#define TRACE_NBD_CO_REQUEST_FAIL 0
#define TRACE_NBD_CO_REQUEST_FAIL_ENABLED 0
#define TRACE_NBD_CO_REQUEST_FAIL_BACKEND_DSTATE() (0)
static inline void trace_nbd_co_request_fail(uint64_t from, uint64_t len, uint64_t handle, uint16_t flags, uint16_t type, const char *name, int ret, const char *err) {
    (void)from;
    (void)len;
    (void)handle;
    (void)flags;
    (void)type;
    (void)name;
    (void)ret;
    (void)err;
}
#define TRACE_NBD_EXTENDED_HEADERS_COMPLIANCE 0
#define TRACE_NBD_EXTENDED_HEADERS_COMPLIANCE_ENABLED 0
#define TRACE_NBD_EXTENDED_HEADERS_COMPLIANCE_BACKEND_DSTATE() (0)
static inline void trace_nbd_extended_headers_compliance(const char *type) {
    (void)type;
}
#define TRACE_NBD_PARSE_BLOCKSTATUS_COMPLIANCE 0
#define TRACE_NBD_PARSE_BLOCKSTATUS_COMPLIANCE_ENABLED 0
#define TRACE_NBD_PARSE_BLOCKSTATUS_COMPLIANCE_BACKEND_DSTATE() (0)
static inline void trace_nbd_parse_blockstatus_compliance(const char *err) {
    (void)err;
}
#define TRACE_NBD_READ_REPLY_ENTRY_FAIL 0
#define TRACE_NBD_READ_REPLY_ENTRY_FAIL_ENABLED 0
#define TRACE_NBD_READ_REPLY_ENTRY_FAIL_BACKEND_DSTATE() (0)
static inline void trace_nbd_read_reply_entry_fail(int ret, const char *err) {
    (void)ret;
    (void)err;
}
#define TRACE_NBD_RECONNECT_ATTEMPT 0
#define TRACE_NBD_RECONNECT_ATTEMPT_ENABLED 0
#define TRACE_NBD_RECONNECT_ATTEMPT_BACKEND_DSTATE() (0)
static inline void trace_nbd_reconnect_attempt(unsigned in_flight) {
    (void)in_flight;
}
#define TRACE_NBD_RECONNECT_ATTEMPT_RESULT 0
#define TRACE_NBD_RECONNECT_ATTEMPT_RESULT_ENABLED 0
#define TRACE_NBD_RECONNECT_ATTEMPT_RESULT_BACKEND_DSTATE() (0)
static inline void trace_nbd_reconnect_attempt_result(int ret, unsigned in_flight) {
    (void)ret;
    (void)in_flight;
}
#define TRACE_NBD_STRUCTURED_READ_COMPLIANCE 0
#define TRACE_NBD_STRUCTURED_READ_COMPLIANCE_ENABLED 0
#define TRACE_NBD_STRUCTURED_READ_COMPLIANCE_BACKEND_DSTATE() (0)
static inline void trace_nbd_structured_read_compliance(const char *type) {
    (void)type;
}
#define TRACE_NVME_CMD_MAP_QIOV 0
#define TRACE_NVME_CMD_MAP_QIOV_ENABLED 0
#define TRACE_NVME_CMD_MAP_QIOV_BACKEND_DSTATE() (0)
static inline void trace_nvme_cmd_map_qiov(void *s, void *cmd, void *req, void *qiov, int entries) {
    (void)s;
    (void)cmd;
    (void)req;
    (void)qiov;
    (void)entries;
}
#define TRACE_NVME_CMD_MAP_QIOV_IOV 0
#define TRACE_NVME_CMD_MAP_QIOV_IOV_ENABLED 0
#define TRACE_NVME_CMD_MAP_QIOV_IOV_BACKEND_DSTATE() (0)
static inline void trace_nvme_cmd_map_qiov_iov(void *s, int i, void *page, int pages) {
    (void)s;
    (void)i;
    (void)page;
    (void)pages;
}
#define TRACE_NVME_CMD_MAP_QIOV_PAGES 0
#define TRACE_NVME_CMD_MAP_QIOV_PAGES_ENABLED 0
#define TRACE_NVME_CMD_MAP_QIOV_PAGES_BACKEND_DSTATE() (0)
static inline void trace_nvme_cmd_map_qiov_pages(void *s, int i, uint64_t page) {
    (void)s;
    (void)i;
    (void)page;
}
#define TRACE_NVME_COMPLETE_COMMAND 0
#define TRACE_NVME_COMPLETE_COMMAND_ENABLED 0
#define TRACE_NVME_COMPLETE_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_nvme_complete_command(void *s, unsigned q_index, int cid) {
    (void)s;
    (void)q_index;
    (void)cid;
}
#define TRACE_NVME_CONTROLLER_CAPABILITY 0
#define TRACE_NVME_CONTROLLER_CAPABILITY_ENABLED 0
#define TRACE_NVME_CONTROLLER_CAPABILITY_BACKEND_DSTATE() (0)
static inline void trace_nvme_controller_capability(const char *desc, uint64_t value) {
    (void)desc;
    (void)value;
}
#define TRACE_NVME_CONTROLLER_CAPABILITY_RAW 0
#define TRACE_NVME_CONTROLLER_CAPABILITY_RAW_ENABLED 0
#define TRACE_NVME_CONTROLLER_CAPABILITY_RAW_BACKEND_DSTATE() (0)
static inline void trace_nvme_controller_capability_raw(uint64_t value) {
    (void)value;
}
#define TRACE_NVME_CONTROLLER_SPEC_VERSION 0
#define TRACE_NVME_CONTROLLER_SPEC_VERSION_ENABLED 0
#define TRACE_NVME_CONTROLLER_SPEC_VERSION_BACKEND_DSTATE() (0)
static inline void trace_nvme_controller_spec_version(uint32_t mjr, uint32_t mnr, uint32_t ter) {
    (void)mjr;
    (void)mnr;
    (void)ter;
}
#define TRACE_NVME_CREATE_QUEUE_PAIR 0
#define TRACE_NVME_CREATE_QUEUE_PAIR_ENABLED 0
#define TRACE_NVME_CREATE_QUEUE_PAIR_BACKEND_DSTATE() (0)
static inline void trace_nvme_create_queue_pair(unsigned q_index, void *q, size_t size, void *aio_context, int fd) {
    (void)q_index;
    (void)q;
    (void)size;
    (void)aio_context;
    (void)fd;
}
#define TRACE_NVME_DMA_FLUSH_QUEUE_WAIT 0
#define TRACE_NVME_DMA_FLUSH_QUEUE_WAIT_ENABLED 0
#define TRACE_NVME_DMA_FLUSH_QUEUE_WAIT_BACKEND_DSTATE() (0)
static inline void trace_nvme_dma_flush_queue_wait(void *s) {
    (void)s;
}
#define TRACE_NVME_DMA_MAP_FLUSH 0
#define TRACE_NVME_DMA_MAP_FLUSH_ENABLED 0
#define TRACE_NVME_DMA_MAP_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_nvme_dma_map_flush(void *s) {
    (void)s;
}
#define TRACE_NVME_DSM 0
#define TRACE_NVME_DSM_ENABLED 0
#define TRACE_NVME_DSM_BACKEND_DSTATE() (0)
static inline void trace_nvme_dsm(void *s, int64_t offset, int64_t bytes) {
    (void)s;
    (void)offset;
    (void)bytes;
}
#define TRACE_NVME_DSM_DONE 0
#define TRACE_NVME_DSM_DONE_ENABLED 0
#define TRACE_NVME_DSM_DONE_BACKEND_DSTATE() (0)
static inline void trace_nvme_dsm_done(void *s, int64_t offset, int64_t bytes, int ret) {
    (void)s;
    (void)offset;
    (void)bytes;
    (void)ret;
}
#define TRACE_NVME_ERROR 0
#define TRACE_NVME_ERROR_ENABLED 0
#define TRACE_NVME_ERROR_BACKEND_DSTATE() (0)
static inline void trace_nvme_error(int cmd_specific, int sq_head, int sqid, int cid, int status) {
    (void)cmd_specific;
    (void)sq_head;
    (void)sqid;
    (void)cid;
    (void)status;
}
#define TRACE_NVME_FREE_QUEUE_PAIR 0
#define TRACE_NVME_FREE_QUEUE_PAIR_ENABLED 0
#define TRACE_NVME_FREE_QUEUE_PAIR_BACKEND_DSTATE() (0)
static inline void trace_nvme_free_queue_pair(unsigned q_index, void *q, void *cq, void *sq) {
    (void)q_index;
    (void)q;
    (void)cq;
    (void)sq;
}
#define TRACE_NVME_FREE_REQ_QUEUE_WAIT 0
#define TRACE_NVME_FREE_REQ_QUEUE_WAIT_ENABLED 0
#define TRACE_NVME_FREE_REQ_QUEUE_WAIT_BACKEND_DSTATE() (0)
static inline void trace_nvme_free_req_queue_wait(void *s, unsigned q_index) {
    (void)s;
    (void)q_index;
}
#define TRACE_NVME_HANDLE_EVENT 0
#define TRACE_NVME_HANDLE_EVENT_ENABLED 0
#define TRACE_NVME_HANDLE_EVENT_BACKEND_DSTATE() (0)
static inline void trace_nvme_handle_event(void *s) {
    (void)s;
}
#define TRACE_NVME_KICK 0
#define TRACE_NVME_KICK_ENABLED 0
#define TRACE_NVME_KICK_BACKEND_DSTATE() (0)
static inline void trace_nvme_kick(void *s, unsigned q_index) {
    (void)s;
    (void)q_index;
}
#define TRACE_NVME_POLL_QUEUE 0
#define TRACE_NVME_POLL_QUEUE_ENABLED 0
#define TRACE_NVME_POLL_QUEUE_BACKEND_DSTATE() (0)
static inline void trace_nvme_poll_queue(void *s, unsigned q_index) {
    (void)s;
    (void)q_index;
}
#define TRACE_NVME_PROCESS_COMPLETION 0
#define TRACE_NVME_PROCESS_COMPLETION_ENABLED 0
#define TRACE_NVME_PROCESS_COMPLETION_BACKEND_DSTATE() (0)
static inline void trace_nvme_process_completion(void *s, unsigned q_index, int inflight) {
    (void)s;
    (void)q_index;
    (void)inflight;
}
#define TRACE_NVME_PRW_ALIGNED 0
#define TRACE_NVME_PRW_ALIGNED_ENABLED 0
#define TRACE_NVME_PRW_ALIGNED_BACKEND_DSTATE() (0)
static inline void trace_nvme_prw_aligned(void *s, int is_write, uint64_t offset, uint64_t bytes, int flags, int niov) {
    (void)s;
    (void)is_write;
    (void)offset;
    (void)bytes;
    (void)flags;
    (void)niov;
}
#define TRACE_NVME_PRW_BUFFERED 0
#define TRACE_NVME_PRW_BUFFERED_ENABLED 0
#define TRACE_NVME_PRW_BUFFERED_BACKEND_DSTATE() (0)
static inline void trace_nvme_prw_buffered(void *s, uint64_t offset, uint64_t bytes, int niov, int is_write) {
    (void)s;
    (void)offset;
    (void)bytes;
    (void)niov;
    (void)is_write;
}
#define TRACE_NVME_QIOV_UNALIGNED 0
#define TRACE_NVME_QIOV_UNALIGNED_ENABLED 0
#define TRACE_NVME_QIOV_UNALIGNED_BACKEND_DSTATE() (0)
static inline void trace_nvme_qiov_unaligned(const void *qiov, int n, void *base, size_t size, int align) {
    (void)qiov;
    (void)n;
    (void)base;
    (void)size;
    (void)align;
}
#define TRACE_NVME_RW_DONE 0
#define TRACE_NVME_RW_DONE_ENABLED 0
#define TRACE_NVME_RW_DONE_BACKEND_DSTATE() (0)
static inline void trace_nvme_rw_done(void *s, int is_write, uint64_t offset, uint64_t bytes, int ret) {
    (void)s;
    (void)is_write;
    (void)offset;
    (void)bytes;
    (void)ret;
}
#define TRACE_NVME_SUBMIT_COMMAND 0
#define TRACE_NVME_SUBMIT_COMMAND_ENABLED 0
#define TRACE_NVME_SUBMIT_COMMAND_BACKEND_DSTATE() (0)
static inline void trace_nvme_submit_command(void *s, unsigned q_index, int cid) {
    (void)s;
    (void)q_index;
    (void)cid;
}
#define TRACE_NVME_SUBMIT_COMMAND_RAW 0
#define TRACE_NVME_SUBMIT_COMMAND_RAW_ENABLED 0
#define TRACE_NVME_SUBMIT_COMMAND_RAW_BACKEND_DSTATE() (0)
static inline void trace_nvme_submit_command_raw(int c0, int c1, int c2, int c3, int c4, int c5, int c6, int c7) {
    (void)c0;
    (void)c1;
    (void)c2;
    (void)c3;
    (void)c4;
    (void)c5;
    (void)c6;
    (void)c7;
}
#define TRACE_NVME_WRITE_ZEROES 0
#define TRACE_NVME_WRITE_ZEROES_ENABLED 0
#define TRACE_NVME_WRITE_ZEROES_BACKEND_DSTATE() (0)
static inline void trace_nvme_write_zeroes(void *s, uint64_t offset, uint64_t bytes, int flags) {
    (void)s;
    (void)offset;
    (void)bytes;
    (void)flags;
}
#define TRACE_QCOW2_ADD_TASK 0
#define TRACE_QCOW2_ADD_TASK_ENABLED 0
#define TRACE_QCOW2_ADD_TASK_BACKEND_DSTATE() (0)
static inline void trace_qcow2_add_task(void *co, void *bs, void *pool, const char *action, int cluster_type, uint64_t host_offset, uint64_t offset, uint64_t bytes, void *qiov, size_t qiov_offset) {
    (void)co;
    (void)bs;
    (void)pool;
    (void)action;
    (void)cluster_type;
    (void)host_offset;
    (void)offset;
    (void)bytes;
    (void)qiov;
    (void)qiov_offset;
}
#define TRACE_QCOW2_ALLOC_CLUSTERS_OFFSET 0
#define TRACE_QCOW2_ALLOC_CLUSTERS_OFFSET_ENABLED 0
#define TRACE_QCOW2_ALLOC_CLUSTERS_OFFSET_BACKEND_DSTATE() (0)
static inline void trace_qcow2_alloc_clusters_offset(void *co, uint64_t offset, int bytes) {
    (void)co;
    (void)offset;
    (void)bytes;
}
#define TRACE_QCOW2_CACHE_ENTRY_FLUSH 0
#define TRACE_QCOW2_CACHE_ENTRY_FLUSH_ENABLED 0
#define TRACE_QCOW2_CACHE_ENTRY_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_qcow2_cache_entry_flush(void *co, int c, int i) {
    (void)co;
    (void)c;
    (void)i;
}
#define TRACE_QCOW2_CACHE_FLUSH 0
#define TRACE_QCOW2_CACHE_FLUSH_ENABLED 0
#define TRACE_QCOW2_CACHE_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_qcow2_cache_flush(void *co, int c) {
    (void)co;
    (void)c;
}
#define TRACE_QCOW2_CACHE_GET 0
#define TRACE_QCOW2_CACHE_GET_ENABLED 0
#define TRACE_QCOW2_CACHE_GET_BACKEND_DSTATE() (0)
static inline void trace_qcow2_cache_get(void *co, int c, uint64_t offset, bool read_from_disk) {
    (void)co;
    (void)c;
    (void)offset;
    (void)read_from_disk;
}
#define TRACE_QCOW2_CACHE_GET_DONE 0
#define TRACE_QCOW2_CACHE_GET_DONE_ENABLED 0
#define TRACE_QCOW2_CACHE_GET_DONE_BACKEND_DSTATE() (0)
static inline void trace_qcow2_cache_get_done(void *co, int c, int i) {
    (void)co;
    (void)c;
    (void)i;
}
#define TRACE_QCOW2_CACHE_GET_READ 0
#define TRACE_QCOW2_CACHE_GET_READ_ENABLED 0
#define TRACE_QCOW2_CACHE_GET_READ_BACKEND_DSTATE() (0)
static inline void trace_qcow2_cache_get_read(void *co, int c, int i) {
    (void)co;
    (void)c;
    (void)i;
}
#define TRACE_QCOW2_CACHE_GET_REPLACE_ENTRY 0
#define TRACE_QCOW2_CACHE_GET_REPLACE_ENTRY_ENABLED 0
#define TRACE_QCOW2_CACHE_GET_REPLACE_ENTRY_BACKEND_DSTATE() (0)
static inline void trace_qcow2_cache_get_replace_entry(void *co, int c, int i) {
    (void)co;
    (void)c;
    (void)i;
}
#define TRACE_QCOW2_CLUSTER_ALLOC_PHYS 0
#define TRACE_QCOW2_CLUSTER_ALLOC_PHYS_ENABLED 0
#define TRACE_QCOW2_CLUSTER_ALLOC_PHYS_BACKEND_DSTATE() (0)
static inline void trace_qcow2_cluster_alloc_phys(void *co) {
    (void)co;
}
#define TRACE_QCOW2_CLUSTER_LINK_L2 0
#define TRACE_QCOW2_CLUSTER_LINK_L2_ENABLED 0
#define TRACE_QCOW2_CLUSTER_LINK_L2_BACKEND_DSTATE() (0)
static inline void trace_qcow2_cluster_link_l2(void *co, int nb_clusters) {
    (void)co;
    (void)nb_clusters;
}
#define TRACE_QCOW2_DO_ALLOC_CLUSTERS_OFFSET 0
#define TRACE_QCOW2_DO_ALLOC_CLUSTERS_OFFSET_ENABLED 0
#define TRACE_QCOW2_DO_ALLOC_CLUSTERS_OFFSET_BACKEND_DSTATE() (0)
static inline void trace_qcow2_do_alloc_clusters_offset(void *co, uint64_t guest_offset, uint64_t host_offset, int nb_clusters) {
    (void)co;
    (void)guest_offset;
    (void)host_offset;
    (void)nb_clusters;
}
#define TRACE_QCOW2_HANDLE_ALLOC 0
#define TRACE_QCOW2_HANDLE_ALLOC_ENABLED 0
#define TRACE_QCOW2_HANDLE_ALLOC_BACKEND_DSTATE() (0)
static inline void trace_qcow2_handle_alloc(void *co, uint64_t guest_offset, uint64_t host_offset, uint64_t bytes) {
    (void)co;
    (void)guest_offset;
    (void)host_offset;
    (void)bytes;
}
#define TRACE_QCOW2_HANDLE_COPIED 0
#define TRACE_QCOW2_HANDLE_COPIED_ENABLED 0
#define TRACE_QCOW2_HANDLE_COPIED_BACKEND_DSTATE() (0)
static inline void trace_qcow2_handle_copied(void *co, uint64_t guest_offset, uint64_t host_offset, uint64_t bytes) {
    (void)co;
    (void)guest_offset;
    (void)host_offset;
    (void)bytes;
}
#define TRACE_QCOW2_L2_ALLOCATE 0
#define TRACE_QCOW2_L2_ALLOCATE_ENABLED 0
#define TRACE_QCOW2_L2_ALLOCATE_BACKEND_DSTATE() (0)
static inline void trace_qcow2_l2_allocate(void *bs, int l1_index) {
    (void)bs;
    (void)l1_index;
}
#define TRACE_QCOW2_L2_ALLOCATE_DONE 0
#define TRACE_QCOW2_L2_ALLOCATE_DONE_ENABLED 0
#define TRACE_QCOW2_L2_ALLOCATE_DONE_BACKEND_DSTATE() (0)
static inline void trace_qcow2_l2_allocate_done(void *bs, int l1_index, int ret) {
    (void)bs;
    (void)l1_index;
    (void)ret;
}
#define TRACE_QCOW2_L2_ALLOCATE_GET_EMPTY 0
#define TRACE_QCOW2_L2_ALLOCATE_GET_EMPTY_ENABLED 0
#define TRACE_QCOW2_L2_ALLOCATE_GET_EMPTY_BACKEND_DSTATE() (0)
static inline void trace_qcow2_l2_allocate_get_empty(void *bs, int l1_index) {
    (void)bs;
    (void)l1_index;
}
#define TRACE_QCOW2_L2_ALLOCATE_WRITE_L1 0
#define TRACE_QCOW2_L2_ALLOCATE_WRITE_L1_ENABLED 0
#define TRACE_QCOW2_L2_ALLOCATE_WRITE_L1_BACKEND_DSTATE() (0)
static inline void trace_qcow2_l2_allocate_write_l1(void *bs, int l1_index) {
    (void)bs;
    (void)l1_index;
}
#define TRACE_QCOW2_L2_ALLOCATE_WRITE_L2 0
#define TRACE_QCOW2_L2_ALLOCATE_WRITE_L2_ENABLED 0
#define TRACE_QCOW2_L2_ALLOCATE_WRITE_L2_BACKEND_DSTATE() (0)
static inline void trace_qcow2_l2_allocate_write_l2(void *bs, int l1_index) {
    (void)bs;
    (void)l1_index;
}
#define TRACE_QCOW2_PROCESS_DISCARDS_FAILED_REGION 0
#define TRACE_QCOW2_PROCESS_DISCARDS_FAILED_REGION_ENABLED 0
#define TRACE_QCOW2_PROCESS_DISCARDS_FAILED_REGION_BACKEND_DSTATE() (0)
static inline void trace_qcow2_process_discards_failed_region(uint64_t offset, uint64_t bytes, int ret) {
    (void)offset;
    (void)bytes;
    (void)ret;
}
#define TRACE_QCOW2_PWRITE_ZEROES 0
#define TRACE_QCOW2_PWRITE_ZEROES_ENABLED 0
#define TRACE_QCOW2_PWRITE_ZEROES_BACKEND_DSTATE() (0)
static inline void trace_qcow2_pwrite_zeroes(void *co, int64_t offset, int64_t bytes) {
    (void)co;
    (void)offset;
    (void)bytes;
}
#define TRACE_QCOW2_PWRITE_ZEROES_START_REQ 0
#define TRACE_QCOW2_PWRITE_ZEROES_START_REQ_ENABLED 0
#define TRACE_QCOW2_PWRITE_ZEROES_START_REQ_BACKEND_DSTATE() (0)
static inline void trace_qcow2_pwrite_zeroes_start_req(void *co, int64_t offset, int64_t bytes) {
    (void)co;
    (void)offset;
    (void)bytes;
}
#define TRACE_QCOW2_SKIP_COW 0
#define TRACE_QCOW2_SKIP_COW_ENABLED 0
#define TRACE_QCOW2_SKIP_COW_BACKEND_DSTATE() (0)
static inline void trace_qcow2_skip_cow(void *co, uint64_t offset, int nb_clusters) {
    (void)co;
    (void)offset;
    (void)nb_clusters;
}
#define TRACE_QCOW2_WRITEV_DATA 0
#define TRACE_QCOW2_WRITEV_DATA_ENABLED 0
#define TRACE_QCOW2_WRITEV_DATA_BACKEND_DSTATE() (0)
static inline void trace_qcow2_writev_data(void *co, uint64_t offset) {
    (void)co;
    (void)offset;
}
#define TRACE_QCOW2_WRITEV_DONE_PART 0
#define TRACE_QCOW2_WRITEV_DONE_PART_ENABLED 0
#define TRACE_QCOW2_WRITEV_DONE_PART_BACKEND_DSTATE() (0)
static inline void trace_qcow2_writev_done_part(void *co, int cur_bytes) {
    (void)co;
    (void)cur_bytes;
}
#define TRACE_QCOW2_WRITEV_DONE_REQ 0
#define TRACE_QCOW2_WRITEV_DONE_REQ_ENABLED 0
#define TRACE_QCOW2_WRITEV_DONE_REQ_BACKEND_DSTATE() (0)
static inline void trace_qcow2_writev_done_req(void *co, int ret) {
    (void)co;
    (void)ret;
}
#define TRACE_QCOW2_WRITEV_START_PART 0
#define TRACE_QCOW2_WRITEV_START_PART_ENABLED 0
#define TRACE_QCOW2_WRITEV_START_PART_BACKEND_DSTATE() (0)
static inline void trace_qcow2_writev_start_part(void *co) {
    (void)co;
}
#define TRACE_QCOW2_WRITEV_START_REQ 0
#define TRACE_QCOW2_WRITEV_START_REQ_ENABLED 0
#define TRACE_QCOW2_WRITEV_START_REQ_BACKEND_DSTATE() (0)
static inline void trace_qcow2_writev_start_req(void *co, int64_t offset, int64_t bytes) {
    (void)co;
    (void)offset;
    (void)bytes;
}
#define TRACE_QED_AIO_COMPLETE 0
#define TRACE_QED_AIO_COMPLETE_ENABLED 0
#define TRACE_QED_AIO_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_qed_aio_complete(void *s, void *acb, int ret) {
    (void)s;
    (void)acb;
    (void)ret;
}
#define TRACE_QED_AIO_NEXT_IO 0
#define TRACE_QED_AIO_NEXT_IO_ENABLED 0
#define TRACE_QED_AIO_NEXT_IO_BACKEND_DSTATE() (0)
static inline void trace_qed_aio_next_io(void *s, void *acb, int ret, uint64_t cur_pos) {
    (void)s;
    (void)acb;
    (void)ret;
    (void)cur_pos;
}
#define TRACE_QED_AIO_READ_DATA 0
#define TRACE_QED_AIO_READ_DATA_ENABLED 0
#define TRACE_QED_AIO_READ_DATA_BACKEND_DSTATE() (0)
static inline void trace_qed_aio_read_data(void *s, void *acb, int ret, uint64_t offset, size_t len) {
    (void)s;
    (void)acb;
    (void)ret;
    (void)offset;
    (void)len;
}
#define TRACE_QED_AIO_SETUP 0
#define TRACE_QED_AIO_SETUP_ENABLED 0
#define TRACE_QED_AIO_SETUP_BACKEND_DSTATE() (0)
static inline void trace_qed_aio_setup(void *s, void *acb, int64_t sector_num, int nb_sectors, void *opaque, int flags) {
    (void)s;
    (void)acb;
    (void)sector_num;
    (void)nb_sectors;
    (void)opaque;
    (void)flags;
}
#define TRACE_QED_AIO_WRITE_DATA 0
#define TRACE_QED_AIO_WRITE_DATA_ENABLED 0
#define TRACE_QED_AIO_WRITE_DATA_BACKEND_DSTATE() (0)
static inline void trace_qed_aio_write_data(void *s, void *acb, int ret, uint64_t offset, size_t len) {
    (void)s;
    (void)acb;
    (void)ret;
    (void)offset;
    (void)len;
}
#define TRACE_QED_AIO_WRITE_MAIN 0
#define TRACE_QED_AIO_WRITE_MAIN_ENABLED 0
#define TRACE_QED_AIO_WRITE_MAIN_BACKEND_DSTATE() (0)
static inline void trace_qed_aio_write_main(void *s, void *acb, int ret, uint64_t offset, size_t len) {
    (void)s;
    (void)acb;
    (void)ret;
    (void)offset;
    (void)len;
}
#define TRACE_QED_AIO_WRITE_POSTFILL 0
#define TRACE_QED_AIO_WRITE_POSTFILL_ENABLED 0
#define TRACE_QED_AIO_WRITE_POSTFILL_BACKEND_DSTATE() (0)
static inline void trace_qed_aio_write_postfill(void *s, void *acb, uint64_t start, size_t len, uint64_t offset) {
    (void)s;
    (void)acb;
    (void)start;
    (void)len;
    (void)offset;
}
#define TRACE_QED_AIO_WRITE_PREFILL 0
#define TRACE_QED_AIO_WRITE_PREFILL_ENABLED 0
#define TRACE_QED_AIO_WRITE_PREFILL_BACKEND_DSTATE() (0)
static inline void trace_qed_aio_write_prefill(void *s, void *acb, uint64_t start, size_t len, uint64_t offset) {
    (void)s;
    (void)acb;
    (void)start;
    (void)len;
    (void)offset;
}
#define TRACE_QED_ALLOC_L2_CACHE_ENTRY 0
#define TRACE_QED_ALLOC_L2_CACHE_ENTRY_ENABLED 0
#define TRACE_QED_ALLOC_L2_CACHE_ENTRY_BACKEND_DSTATE() (0)
static inline void trace_qed_alloc_l2_cache_entry(void *l2_cache, void *entry) {
    (void)l2_cache;
    (void)entry;
}
#define TRACE_QED_CANCEL_NEED_CHECK_TIMER 0
#define TRACE_QED_CANCEL_NEED_CHECK_TIMER_ENABLED 0
#define TRACE_QED_CANCEL_NEED_CHECK_TIMER_BACKEND_DSTATE() (0)
static inline void trace_qed_cancel_need_check_timer(void *s) {
    (void)s;
}
#define TRACE_QED_FIND_L2_CACHE_ENTRY 0
#define TRACE_QED_FIND_L2_CACHE_ENTRY_ENABLED 0
#define TRACE_QED_FIND_L2_CACHE_ENTRY_BACKEND_DSTATE() (0)
static inline void trace_qed_find_l2_cache_entry(void *l2_cache, void *entry, uint64_t offset, int ref) {
    (void)l2_cache;
    (void)entry;
    (void)offset;
    (void)ref;
}
#define TRACE_QED_NEED_CHECK_TIMER_CB 0
#define TRACE_QED_NEED_CHECK_TIMER_CB_ENABLED 0
#define TRACE_QED_NEED_CHECK_TIMER_CB_BACKEND_DSTATE() (0)
static inline void trace_qed_need_check_timer_cb(void *s) {
    (void)s;
}
#define TRACE_QED_READ_TABLE 0
#define TRACE_QED_READ_TABLE_ENABLED 0
#define TRACE_QED_READ_TABLE_BACKEND_DSTATE() (0)
static inline void trace_qed_read_table(void *s, uint64_t offset, void *table) {
    (void)s;
    (void)offset;
    (void)table;
}
#define TRACE_QED_READ_TABLE_CB 0
#define TRACE_QED_READ_TABLE_CB_ENABLED 0
#define TRACE_QED_READ_TABLE_CB_BACKEND_DSTATE() (0)
static inline void trace_qed_read_table_cb(void *s, void *table, int ret) {
    (void)s;
    (void)table;
    (void)ret;
}
#define TRACE_QED_START_NEED_CHECK_TIMER 0
#define TRACE_QED_START_NEED_CHECK_TIMER_ENABLED 0
#define TRACE_QED_START_NEED_CHECK_TIMER_BACKEND_DSTATE() (0)
static inline void trace_qed_start_need_check_timer(void *s) {
    (void)s;
}
#define TRACE_QED_UNREF_L2_CACHE_ENTRY 0
#define TRACE_QED_UNREF_L2_CACHE_ENTRY_ENABLED 0
#define TRACE_QED_UNREF_L2_CACHE_ENTRY_BACKEND_DSTATE() (0)
static inline void trace_qed_unref_l2_cache_entry(void *entry, int ref) {
    (void)entry;
    (void)ref;
}
#define TRACE_QED_WRITE_TABLE 0
#define TRACE_QED_WRITE_TABLE_ENABLED 0
#define TRACE_QED_WRITE_TABLE_BACKEND_DSTATE() (0)
static inline void trace_qed_write_table(void *s, uint64_t offset, void *table, unsigned int index, unsigned int n) {
    (void)s;
    (void)offset;
    (void)table;
    (void)index;
    (void)n;
}
#define TRACE_QED_WRITE_TABLE_CB 0
#define TRACE_QED_WRITE_TABLE_CB_ENABLED 0
#define TRACE_QED_WRITE_TABLE_CB_BACKEND_DSTATE() (0)
static inline void trace_qed_write_table_cb(void *s, void *table, int flush, int ret) {
    (void)s;
    (void)table;
    (void)flush;
    (void)ret;
}
#define TRACE_QMP_BLOCK_JOB_CANCEL 0
#define TRACE_QMP_BLOCK_JOB_CANCEL_ENABLED 0
#define TRACE_QMP_BLOCK_JOB_CANCEL_BACKEND_DSTATE() (0)
static inline void trace_qmp_block_job_cancel(void *job) {
    (void)job;
}
#define TRACE_QMP_BLOCK_JOB_COMPLETE 0
#define TRACE_QMP_BLOCK_JOB_COMPLETE_ENABLED 0
#define TRACE_QMP_BLOCK_JOB_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_qmp_block_job_complete(void *job) {
    (void)job;
}
#define TRACE_QMP_BLOCK_JOB_DISMISS 0
#define TRACE_QMP_BLOCK_JOB_DISMISS_ENABLED 0
#define TRACE_QMP_BLOCK_JOB_DISMISS_BACKEND_DSTATE() (0)
static inline void trace_qmp_block_job_dismiss(void *job) {
    (void)job;
}
#define TRACE_QMP_BLOCK_JOB_FINALIZE 0
#define TRACE_QMP_BLOCK_JOB_FINALIZE_ENABLED 0
#define TRACE_QMP_BLOCK_JOB_FINALIZE_BACKEND_DSTATE() (0)
static inline void trace_qmp_block_job_finalize(void *job) {
    (void)job;
}
#define TRACE_QMP_BLOCK_JOB_PAUSE 0
#define TRACE_QMP_BLOCK_JOB_PAUSE_ENABLED 0
#define TRACE_QMP_BLOCK_JOB_PAUSE_BACKEND_DSTATE() (0)
static inline void trace_qmp_block_job_pause(void *job) {
    (void)job;
}
#define TRACE_QMP_BLOCK_JOB_RESUME 0
#define TRACE_QMP_BLOCK_JOB_RESUME_ENABLED 0
#define TRACE_QMP_BLOCK_JOB_RESUME_BACKEND_DSTATE() (0)
static inline void trace_qmp_block_job_resume(void *job) {
    (void)job;
}
#define TRACE_QMP_BLOCK_STREAM 0
#define TRACE_QMP_BLOCK_STREAM_ENABLED 0
#define TRACE_QMP_BLOCK_STREAM_BACKEND_DSTATE() (0)
static inline void trace_qmp_block_stream(void *bs) {
    (void)bs;
}
#define TRACE_SFTP_ERROR 0
#define TRACE_SFTP_ERROR_ENABLED 0
#define TRACE_SFTP_ERROR_BACKEND_DSTATE() (0)
static inline void trace_sftp_error(const char *op, const char *ssh_err, int ssh_err_code, int sftp_err_code) {
    (void)op;
    (void)ssh_err;
    (void)ssh_err_code;
    (void)sftp_err_code;
}
#define TRACE_SSH_AUTH_METHODS 0
#define TRACE_SSH_AUTH_METHODS_ENABLED 0
#define TRACE_SSH_AUTH_METHODS_BACKEND_DSTATE() (0)
static inline void trace_ssh_auth_methods(int methods) {
    (void)methods;
}
#define TRACE_SSH_CHECK_HOST_KEY_KNOWNHOSTS 0
#define TRACE_SSH_CHECK_HOST_KEY_KNOWNHOSTS_ENABLED 0
#define TRACE_SSH_CHECK_HOST_KEY_KNOWNHOSTS_BACKEND_DSTATE() (0)
static inline void trace_ssh_check_host_key_knownhosts(void) {
}
#define TRACE_SSH_CO_CREATE_OPTS 0
#define TRACE_SSH_CO_CREATE_OPTS_ENABLED 0
#define TRACE_SSH_CO_CREATE_OPTS_BACKEND_DSTATE() (0)
static inline void trace_ssh_co_create_opts(uint64_t size) {
    (void)size;
}
#define TRACE_SSH_CO_YIELD 0
#define TRACE_SSH_CO_YIELD_ENABLED 0
#define TRACE_SSH_CO_YIELD_BACKEND_DSTATE() (0)
static inline void trace_ssh_co_yield(int sock, void *rd_handler, void *wr_handler) {
    (void)sock;
    (void)rd_handler;
    (void)wr_handler;
}
#define TRACE_SSH_CO_YIELD_BACK 0
#define TRACE_SSH_CO_YIELD_BACK_ENABLED 0
#define TRACE_SSH_CO_YIELD_BACK_BACKEND_DSTATE() (0)
static inline void trace_ssh_co_yield_back(int sock) {
    (void)sock;
}
#define TRACE_SSH_CONNECT_TO_SSH 0
#define TRACE_SSH_CONNECT_TO_SSH_ENABLED 0
#define TRACE_SSH_CONNECT_TO_SSH_BACKEND_DSTATE() (0)
static inline void trace_ssh_connect_to_ssh(char *path, int flags, int mode) {
    (void)path;
    (void)flags;
    (void)mode;
}
#define TRACE_SSH_FLUSH 0
#define TRACE_SSH_FLUSH_ENABLED 0
#define TRACE_SSH_FLUSH_BACKEND_DSTATE() (0)
static inline void trace_ssh_flush(void) {
}
#define TRACE_SSH_GETLENGTH 0
#define TRACE_SSH_GETLENGTH_ENABLED 0
#define TRACE_SSH_GETLENGTH_BACKEND_DSTATE() (0)
static inline void trace_ssh_getlength(int64_t length) {
    (void)length;
}
#define TRACE_SSH_READ 0
#define TRACE_SSH_READ_ENABLED 0
#define TRACE_SSH_READ_BACKEND_DSTATE() (0)
static inline void trace_ssh_read(int64_t offset, size_t size) {
    (void)offset;
    (void)size;
}
#define TRACE_SSH_READ_BUF 0
#define TRACE_SSH_READ_BUF_ENABLED 0
#define TRACE_SSH_READ_BUF_BACKEND_DSTATE() (0)
static inline void trace_ssh_read_buf(void *buf, size_t size, size_t actual_size) {
    (void)buf;
    (void)size;
    (void)actual_size;
}
#define TRACE_SSH_READ_RETURN 0
#define TRACE_SSH_READ_RETURN_ENABLED 0
#define TRACE_SSH_READ_RETURN_BACKEND_DSTATE() (0)
static inline void trace_ssh_read_return(ssize_t ret, int sftp_err) {
    (void)ret;
    (void)sftp_err;
}
#define TRACE_SSH_RESTART_COROUTINE 0
#define TRACE_SSH_RESTART_COROUTINE_ENABLED 0
#define TRACE_SSH_RESTART_COROUTINE_BACKEND_DSTATE() (0)
static inline void trace_ssh_restart_coroutine(void *co) {
    (void)co;
}
#define TRACE_SSH_SEEK 0
#define TRACE_SSH_SEEK_ENABLED 0
#define TRACE_SSH_SEEK_BACKEND_DSTATE() (0)
static inline void trace_ssh_seek(int64_t offset) {
    (void)offset;
}
#define TRACE_SSH_SERVER_STATUS 0
#define TRACE_SSH_SERVER_STATUS_ENABLED 0
#define TRACE_SSH_SERVER_STATUS_BACKEND_DSTATE() (0)
static inline void trace_ssh_server_status(int status) {
    (void)status;
}
#define TRACE_SSH_WRITE 0
#define TRACE_SSH_WRITE_ENABLED 0
#define TRACE_SSH_WRITE_BACKEND_DSTATE() (0)
static inline void trace_ssh_write(int64_t offset, size_t size) {
    (void)offset;
    (void)size;
}
#define TRACE_SSH_WRITE_BUF 0
#define TRACE_SSH_WRITE_BUF_ENABLED 0
#define TRACE_SSH_WRITE_BUF_BACKEND_DSTATE() (0)
static inline void trace_ssh_write_buf(void *buf, size_t size, size_t actual_size) {
    (void)buf;
    (void)size;
    (void)actual_size;
}
#define TRACE_SSH_WRITE_RETURN 0
#define TRACE_SSH_WRITE_RETURN_ENABLED 0
#define TRACE_SSH_WRITE_RETURN_BACKEND_DSTATE() (0)
static inline void trace_ssh_write_return(ssize_t ret, int sftp_err) {
    (void)ret;
    (void)sftp_err;
}
#define TRACE_STREAM_ONE_ITERATION 0
#define TRACE_STREAM_ONE_ITERATION_ENABLED 0
#define TRACE_STREAM_ONE_ITERATION_BACKEND_DSTATE() (0)
static inline void trace_stream_one_iteration(void *s, int64_t offset, uint64_t bytes, int is_allocated) {
    (void)s;
    (void)offset;
    (void)bytes;
    (void)is_allocated;
}
#define TRACE_STREAM_START 0
#define TRACE_STREAM_START_ENABLED 0
#define TRACE_STREAM_START_BACKEND_DSTATE() (0)
static inline void trace_stream_start(void *bs, void *base, void *s) {
    (void)bs;
    (void)base;
    (void)s;
}
#define TRACE_ZBD_ZONE_APPEND 0
#define TRACE_ZBD_ZONE_APPEND_ENABLED 0
#define TRACE_ZBD_ZONE_APPEND_BACKEND_DSTATE() (0)
static inline void trace_zbd_zone_append(void *bs, int64_t sector) {
    (void)bs;
    (void)sector;
}
#define TRACE_ZBD_ZONE_APPEND_COMPLETE 0
#define TRACE_ZBD_ZONE_APPEND_COMPLETE_ENABLED 0
#define TRACE_ZBD_ZONE_APPEND_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_zbd_zone_append_complete(void *bs, int64_t sector) {
    (void)bs;
    (void)sector;
}
#define TRACE_ZBD_ZONE_MGMT 0
#define TRACE_ZBD_ZONE_MGMT_ENABLED 0
#define TRACE_ZBD_ZONE_MGMT_BACKEND_DSTATE() (0)
static inline void trace_zbd_zone_mgmt(void *bs, const char *op_name, int64_t sector, int64_t len) {
    (void)bs;
    (void)op_name;
    (void)sector;
    (void)len;
}
#define TRACE_ZBD_ZONE_REPORT 0
#define TRACE_ZBD_ZONE_REPORT_ENABLED 0
#define TRACE_ZBD_ZONE_REPORT_BACKEND_DSTATE() (0)
static inline void trace_zbd_zone_report(void *bs, unsigned int nr_zones, int64_t sector) {
    (void)bs;
    (void)nr_zones;
    (void)sector;
}

#endif