/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_REMOTE_H
#define TRACE_TRACE_HW_REMOTE_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_MPQEMU_RECV_IO_ERROR 0
#define TRACE_MPQEMU_RECV_IO_ERROR_ENABLED 0
#define TRACE_MPQEMU_RECV_IO_ERROR_BACKEND_DSTATE() (0)
static inline void trace_mpqemu_recv_io_error(int cmd, int size, int nfds) {
    (void)cmd;
    (void)size;
    (void)nfds;
}
#define TRACE_MPQEMU_SEND_IO_ERROR 0
#define TRACE_MPQEMU_SEND_IO_ERROR_ENABLED 0
#define TRACE_MPQEMU_SEND_IO_ERROR_BACKEND_DSTATE() (0)
static inline void trace_mpqemu_send_io_error(int cmd, int size, int nfds) {
    (void)cmd;
    (void)size;
    (void)nfds;
}
#define TRACE_VFU_BAR_REGISTER 0
#define TRACE_VFU_BAR_REGISTER_ENABLED 0
#define TRACE_VFU_BAR_REGISTER_BACKEND_DSTATE() (0)
static inline void trace_vfu_bar_register(int i, uint64_t addr, uint64_t size) {
    (void)i;
    (void)addr;
    (void)size;
}
#define TRACE_VFU_BAR_RW_ENTER 0
#define TRACE_VFU_BAR_RW_ENTER_ENABLED 0
#define TRACE_VFU_BAR_RW_ENTER_BACKEND_DSTATE() (0)
static inline void trace_vfu_bar_rw_enter(const char *op, uint64_t addr) {
    (void)op;
    (void)addr;
}
#define TRACE_VFU_BAR_RW_EXIT 0
#define TRACE_VFU_BAR_RW_EXIT_ENABLED 0
#define TRACE_VFU_BAR_RW_EXIT_BACKEND_DSTATE() (0)
static inline void trace_vfu_bar_rw_exit(const char *op, uint64_t addr) {
    (void)op;
    (void)addr;
}
#define TRACE_VFU_CFG_READ 0
#define TRACE_VFU_CFG_READ_ENABLED 0
#define TRACE_VFU_CFG_READ_BACKEND_DSTATE() (0)
static inline void trace_vfu_cfg_read(uint32_t offset, uint32_t val) {
    (void)offset;
    (void)val;
}
#define TRACE_VFU_CFG_WRITE 0
#define TRACE_VFU_CFG_WRITE_ENABLED 0
#define TRACE_VFU_CFG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_vfu_cfg_write(uint32_t offset, uint32_t val) {
    (void)offset;
    (void)val;
}
#define TRACE_VFU_DMA_REGISTER 0
#define TRACE_VFU_DMA_REGISTER_ENABLED 0
#define TRACE_VFU_DMA_REGISTER_BACKEND_DSTATE() (0)
static inline void trace_vfu_dma_register(uint64_t gpa, size_t len) {
    (void)gpa;
    (void)len;
}
#define TRACE_VFU_DMA_UNREGISTER 0
#define TRACE_VFU_DMA_UNREGISTER_ENABLED 0
#define TRACE_VFU_DMA_UNREGISTER_BACKEND_DSTATE() (0)
static inline void trace_vfu_dma_unregister(uint64_t gpa) {
    (void)gpa;
}
#define TRACE_VFU_INTERRUPT 0
#define TRACE_VFU_INTERRUPT_ENABLED 0
#define TRACE_VFU_INTERRUPT_BACKEND_DSTATE() (0)
static inline void trace_vfu_interrupt(int pirq) {
    (void)pirq;
}
#define TRACE_VFU_PROP 0
#define TRACE_VFU_PROP_ENABLED 0
#define TRACE_VFU_PROP_BACKEND_DSTATE() (0)
static inline void trace_vfu_prop(const char *prop, const char *val) {
    (void)prop;
    (void)val;
}

#endif