/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_TARGET_RISCV_H
#define TRACE_TRACE_TARGET_RISCV_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_MSECCFG_CSR_READ 0
#define TRACE_MSECCFG_CSR_READ_ENABLED 0
#define TRACE_MSECCFG_CSR_READ_BACKEND_DSTATE() (0)
static inline void trace_mseccfg_csr_read(uint64_t mhartid, uint64_t val) {
    (void)mhartid;
    (void)val;
}
#define TRACE_MSECCFG_CSR_WRITE 0
#define TRACE_MSECCFG_CSR_WRITE_ENABLED 0
#define TRACE_MSECCFG_CSR_WRITE_BACKEND_DSTATE() (0)
static inline void trace_mseccfg_csr_write(uint64_t mhartid, uint64_t val) {
    (void)mhartid;
    (void)val;
}
#define TRACE_PMPADDR_CSR_READ 0
#define TRACE_PMPADDR_CSR_READ_ENABLED 0
#define TRACE_PMPADDR_CSR_READ_BACKEND_DSTATE() (0)
static inline void trace_pmpaddr_csr_read(uint64_t mhartid, uint32_t addr_index, uint64_t val) {
    (void)mhartid;
    (void)addr_index;
    (void)val;
}
#define TRACE_PMPADDR_CSR_WRITE 0
#define TRACE_PMPADDR_CSR_WRITE_ENABLED 0
#define TRACE_PMPADDR_CSR_WRITE_BACKEND_DSTATE() (0)
static inline void trace_pmpaddr_csr_write(uint64_t mhartid, uint32_t addr_index, uint64_t val) {
    (void)mhartid;
    (void)addr_index;
    (void)val;
}
#define TRACE_PMPCFG_CSR_READ 0
#define TRACE_PMPCFG_CSR_READ_ENABLED 0
#define TRACE_PMPCFG_CSR_READ_BACKEND_DSTATE() (0)
static inline void trace_pmpcfg_csr_read(uint64_t mhartid, uint32_t reg_index, uint64_t val) {
    (void)mhartid;
    (void)reg_index;
    (void)val;
}
#define TRACE_PMPCFG_CSR_WRITE 0
#define TRACE_PMPCFG_CSR_WRITE_ENABLED 0
#define TRACE_PMPCFG_CSR_WRITE_BACKEND_DSTATE() (0)
static inline void trace_pmpcfg_csr_write(uint64_t mhartid, uint32_t reg_index, uint64_t val) {
    (void)mhartid;
    (void)reg_index;
    (void)val;
}
#define TRACE_RISCV_EXCEPTION 0
#define TRACE_RISCV_EXCEPTION_ENABLED 0
#define TRACE_RISCV_EXCEPTION_BACKEND_DSTATE() (0)
static inline void trace_riscv_exception(uint32_t exception, const char *desc, uint64_t epc) {
    (void)exception;
    (void)desc;
    (void)epc;
}
#define TRACE_RISCV_TRAP 0
#define TRACE_RISCV_TRAP_ENABLED 0
#define TRACE_RISCV_TRAP_BACKEND_DSTATE() (0)
static inline void trace_riscv_trap(uint64_t hartid, bool async, uint64_t cause, uint64_t epc, uint64_t tval, const char *desc) {
    (void)hartid;
    (void)async;
    (void)cause;
    (void)epc;
    (void)tval;
    (void)desc;
}

#endif