/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_TARGET_I386_KVM_H
#define TRACE_TRACE_TARGET_I386_KVM_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_KVM_HC_MAP_GPA_RANGE 0
#define TRACE_KVM_HC_MAP_GPA_RANGE_ENABLED 0
#define TRACE_KVM_HC_MAP_GPA_RANGE_BACKEND_DSTATE() (0)
static inline void trace_kvm_hc_map_gpa_range(uint64_t gpa, uint64_t size, uint64_t attributes, uint64_t flags) {
    (void)gpa;
    (void)size;
    (void)attributes;
    (void)flags;
}
#define TRACE_KVM_X86_ADD_MSI_ROUTE 0
#define TRACE_KVM_X86_ADD_MSI_ROUTE_ENABLED 0
#define TRACE_KVM_X86_ADD_MSI_ROUTE_BACKEND_DSTATE() (0)
static inline void trace_kvm_x86_add_msi_route(int virq) {
    (void)virq;
}
#define TRACE_KVM_X86_FIXUP_MSI_ERROR 0
#define TRACE_KVM_X86_FIXUP_MSI_ERROR_ENABLED 0
#define TRACE_KVM_X86_FIXUP_MSI_ERROR_BACKEND_DSTATE() (0)
static inline void trace_kvm_x86_fixup_msi_error(uint32_t gsi) {
    (void)gsi;
}
#define TRACE_KVM_X86_REMOVE_MSI_ROUTE 0
#define TRACE_KVM_X86_REMOVE_MSI_ROUTE_ENABLED 0
#define TRACE_KVM_X86_REMOVE_MSI_ROUTE_BACKEND_DSTATE() (0)
static inline void trace_kvm_x86_remove_msi_route(int virq) {
    (void)virq;
}
#define TRACE_KVM_X86_UPDATE_MSI_ROUTES 0
#define TRACE_KVM_X86_UPDATE_MSI_ROUTES_ENABLED 0
#define TRACE_KVM_X86_UPDATE_MSI_ROUTES_BACKEND_DSTATE() (0)
static inline void trace_kvm_x86_update_msi_routes(int num) {
    (void)num;
}
#define TRACE_KVM_XEN_HYPERCALL 0
#define TRACE_KVM_XEN_HYPERCALL_ENABLED 0
#define TRACE_KVM_XEN_HYPERCALL_BACKEND_DSTATE() (0)
static inline void trace_kvm_xen_hypercall(int cpu, uint8_t cpl, uint64_t input, uint64_t a0, uint64_t a1, uint64_t a2, uint64_t ret) {
    (void)cpu;
    (void)cpl;
    (void)input;
    (void)a0;
    (void)a1;
    (void)a2;
    (void)ret;
}
#define TRACE_KVM_XEN_SET_SHARED_INFO 0
#define TRACE_KVM_XEN_SET_SHARED_INFO_ENABLED 0
#define TRACE_KVM_XEN_SET_SHARED_INFO_BACKEND_DSTATE() (0)
static inline void trace_kvm_xen_set_shared_info(uint64_t gfn) {
    (void)gfn;
}
#define TRACE_KVM_XEN_SET_VCPU_ATTR 0
#define TRACE_KVM_XEN_SET_VCPU_ATTR_ENABLED 0
#define TRACE_KVM_XEN_SET_VCPU_ATTR_BACKEND_DSTATE() (0)
static inline void trace_kvm_xen_set_vcpu_attr(int cpu, int type, uint64_t gpa) {
    (void)cpu;
    (void)type;
    (void)gpa;
}
#define TRACE_KVM_XEN_SET_VCPU_CALLBACK 0
#define TRACE_KVM_XEN_SET_VCPU_CALLBACK_ENABLED 0
#define TRACE_KVM_XEN_SET_VCPU_CALLBACK_BACKEND_DSTATE() (0)
static inline void trace_kvm_xen_set_vcpu_callback(int cpu, int vector) {
    (void)cpu;
    (void)vector;
}
#define TRACE_KVM_XEN_SOFT_RESET 0
#define TRACE_KVM_XEN_SOFT_RESET_ENABLED 0
#define TRACE_KVM_XEN_SOFT_RESET_BACKEND_DSTATE() (0)
static inline void trace_kvm_xen_soft_reset(void) {
}

#endif