/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_SH4_H
#define TRACE_TRACE_HW_SH4_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_SH7750_PORTA 0
#define TRACE_SH7750_PORTA_ENABLED 0
#define TRACE_SH7750_PORTA_BACKEND_DSTATE() (0)
static inline void trace_sh7750_porta(uint16_t prev, uint16_t cur, uint16_t pdtr, uint16_t pctr) {
    (void)prev;
    (void)cur;
    (void)pdtr;
    (void)pctr;
}
#define TRACE_SH7750_PORTB 0
#define TRACE_SH7750_PORTB_ENABLED 0
#define TRACE_SH7750_PORTB_BACKEND_DSTATE() (0)
static inline void trace_sh7750_portb(uint16_t prev, uint16_t cur, uint16_t pdtr, uint16_t pctr) {
    (void)prev;
    (void)cur;
    (void)pdtr;
    (void)pctr;
}

#endif