/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_BACKENDS_TPM_H
#define TRACE_TRACE_BACKENDS_TPM_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_TPM_EMULATOR_CANCEL_CMD_NOT_SUPT 0
#define TRACE_TPM_EMULATOR_CANCEL_CMD_NOT_SUPT_ENABLED 0
#define TRACE_TPM_EMULATOR_CANCEL_CMD_NOT_SUPT_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_cancel_cmd_not_supt(void) {
}
#define TRACE_TPM_EMULATOR_GET_STATE_BLOB 0
#define TRACE_TPM_EMULATOR_GET_STATE_BLOB_ENABLED 0
#define TRACE_TPM_EMULATOR_GET_STATE_BLOB_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_get_state_blob(uint8_t type, uint32_t size, uint32_t flags) {
    (void)type;
    (void)size;
    (void)flags;
}
#define TRACE_TPM_EMULATOR_GET_TPM_ESTABLISHED_FLAG 0
#define TRACE_TPM_EMULATOR_GET_TPM_ESTABLISHED_FLAG_ENABLED 0
#define TRACE_TPM_EMULATOR_GET_TPM_ESTABLISHED_FLAG_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_get_tpm_established_flag(uint8_t flag) {
    (void)flag;
}
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_STARTUP_ERROR 0
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_STARTUP_ERROR_ENABLED 0
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_STARTUP_ERROR_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_handle_device_opts_startup_error(void) {
}
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_TPM12 0
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_TPM12_ENABLED 0
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_TPM12_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_handle_device_opts_tpm12(void) {
}
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_TPM2 0
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_TPM2_ENABLED 0
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_TPM2_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_handle_device_opts_tpm2(void) {
}
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_UNSPEC 0
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_UNSPEC_ENABLED 0
#define TRACE_TPM_EMULATOR_HANDLE_DEVICE_OPTS_UNSPEC_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_handle_device_opts_unspec(void) {
}
#define TRACE_TPM_EMULATOR_HANDLE_REQUEST 0
#define TRACE_TPM_EMULATOR_HANDLE_REQUEST_ENABLED 0
#define TRACE_TPM_EMULATOR_HANDLE_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_handle_request(void) {
}
#define TRACE_TPM_EMULATOR_INST_INIT 0
#define TRACE_TPM_EMULATOR_INST_INIT_ENABLED 0
#define TRACE_TPM_EMULATOR_INST_INIT_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_inst_init(void) {
}
#define TRACE_TPM_EMULATOR_LOCK_STORAGE_CMD_NOT_SUPT 0
#define TRACE_TPM_EMULATOR_LOCK_STORAGE_CMD_NOT_SUPT_ENABLED 0
#define TRACE_TPM_EMULATOR_LOCK_STORAGE_CMD_NOT_SUPT_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_lock_storage_cmd_not_supt(void) {
}
#define TRACE_TPM_EMULATOR_PRE_SAVE 0
#define TRACE_TPM_EMULATOR_PRE_SAVE_ENABLED 0
#define TRACE_TPM_EMULATOR_PRE_SAVE_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_pre_save(void) {
}
#define TRACE_TPM_EMULATOR_PROBE_CAPS 0
#define TRACE_TPM_EMULATOR_PROBE_CAPS_ENABLED 0
#define TRACE_TPM_EMULATOR_PROBE_CAPS_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_probe_caps(uint32_t caps) {
    (void)caps;
}
#define TRACE_TPM_EMULATOR_SET_BUFFER_SIZE 0
#define TRACE_TPM_EMULATOR_SET_BUFFER_SIZE_ENABLED 0
#define TRACE_TPM_EMULATOR_SET_BUFFER_SIZE_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_set_buffer_size(uint32_t buffersize, uint32_t minsize, uint32_t maxsize) {
    (void)buffersize;
    (void)minsize;
    (void)maxsize;
}
#define TRACE_TPM_EMULATOR_SET_LOCALITY 0
#define TRACE_TPM_EMULATOR_SET_LOCALITY_ENABLED 0
#define TRACE_TPM_EMULATOR_SET_LOCALITY_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_set_locality(uint8_t locty) {
    (void)locty;
}
#define TRACE_TPM_EMULATOR_SET_STATE_BLOB 0
#define TRACE_TPM_EMULATOR_SET_STATE_BLOB_ENABLED 0
#define TRACE_TPM_EMULATOR_SET_STATE_BLOB_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_set_state_blob(uint8_t type, uint32_t size, uint32_t flags) {
    (void)type;
    (void)size;
    (void)flags;
}
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS 0
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS_ENABLED 0
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_set_state_blobs(void) {
}
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS_DONE 0
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS_DONE_ENABLED 0
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS_DONE_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_set_state_blobs_done(void) {
}
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS_ERROR 0
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS_ERROR_ENABLED 0
#define TRACE_TPM_EMULATOR_SET_STATE_BLOBS_ERROR_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_set_state_blobs_error(const char *msg) {
    (void)msg;
}
#define TRACE_TPM_EMULATOR_STARTUP_TPM_RESUME 0
#define TRACE_TPM_EMULATOR_STARTUP_TPM_RESUME_ENABLED 0
#define TRACE_TPM_EMULATOR_STARTUP_TPM_RESUME_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_startup_tpm_resume(bool is_resume, size_t buffersize) {
    (void)is_resume;
    (void)buffersize;
}
#define TRACE_TPM_EMULATOR_VM_STATE_CHANGE 0
#define TRACE_TPM_EMULATOR_VM_STATE_CHANGE_ENABLED 0
#define TRACE_TPM_EMULATOR_VM_STATE_CHANGE_BACKEND_DSTATE() (0)
static inline void trace_tpm_emulator_vm_state_change(int running, int state) {
    (void)running;
    (void)state;
}
#define TRACE_TPM_PASSTHROUGH_HANDLE_REQUEST 0
#define TRACE_TPM_PASSTHROUGH_HANDLE_REQUEST_ENABLED 0
#define TRACE_TPM_PASSTHROUGH_HANDLE_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_tpm_passthrough_handle_request(void *cmd) {
    (void)cmd;
}
#define TRACE_TPM_PASSTHROUGH_RESET 0
#define TRACE_TPM_PASSTHROUGH_RESET_ENABLED 0
#define TRACE_TPM_PASSTHROUGH_RESET_BACKEND_DSTATE() (0)
static inline void trace_tpm_passthrough_reset(void) {
}
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_ENABLED 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_BACKEND_DSTATE() (0)
static inline void trace_tpm_util_get_buffer_size(size_t len) {
    (void)len;
}
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_HDR_LEN 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_HDR_LEN_ENABLED 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_HDR_LEN_BACKEND_DSTATE() (0)
static inline void trace_tpm_util_get_buffer_size_hdr_len(uint32_t len, size_t expected) {
    (void)len;
    (void)expected;
}
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_HDR_LEN2 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_HDR_LEN2_ENABLED 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_HDR_LEN2_BACKEND_DSTATE() (0)
static inline void trace_tpm_util_get_buffer_size_hdr_len2(uint32_t len, size_t expected) {
    (void)len;
    (void)expected;
}
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_LEN 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_LEN_ENABLED 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_LEN_BACKEND_DSTATE() (0)
static inline void trace_tpm_util_get_buffer_size_len(uint32_t len, size_t expected) {
    (void)len;
    (void)expected;
}
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_LEN2 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_LEN2_ENABLED 0
#define TRACE_TPM_UTIL_GET_BUFFER_SIZE_LEN2_BACKEND_DSTATE() (0)
static inline void trace_tpm_util_get_buffer_size_len2(uint32_t len, size_t expected) {
    (void)len;
    (void)expected;
}
#define TRACE_TPM_UTIL_SHOW_BUFFER_CONTENT 0
#define TRACE_TPM_UTIL_SHOW_BUFFER_CONTENT_ENABLED 0
#define TRACE_TPM_UTIL_SHOW_BUFFER_CONTENT_BACKEND_DSTATE() (0)
static inline void trace_tpm_util_show_buffer_content(const char *buf) {
    (void)buf;
}
#define TRACE_TPM_UTIL_SHOW_BUFFER_HEADER 0
#define TRACE_TPM_UTIL_SHOW_BUFFER_HEADER_ENABLED 0
#define TRACE_TPM_UTIL_SHOW_BUFFER_HEADER_BACKEND_DSTATE() (0)
static inline void trace_tpm_util_show_buffer_header(const char *direction, size_t len) {
    (void)direction;
    (void)len;
}

#endif