/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_ADC_H
#define TRACE_TRACE_HW_ADC_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_ASPEED_ADC_ENGINE_READ 0
#define TRACE_ASPEED_ADC_ENGINE_READ_ENABLED 0
#define TRACE_ASPEED_ADC_ENGINE_READ_BACKEND_DSTATE() (0)
static inline void trace_aspeed_adc_engine_read(uint32_t engine_id, uint64_t addr, uint64_t value) {
    (void)engine_id;
    (void)addr;
    (void)value;
}
#define TRACE_ASPEED_ADC_ENGINE_WRITE 0
#define TRACE_ASPEED_ADC_ENGINE_WRITE_ENABLED 0
#define TRACE_ASPEED_ADC_ENGINE_WRITE_BACKEND_DSTATE() (0)
static inline void trace_aspeed_adc_engine_write(uint32_t engine_id, uint64_t addr, uint64_t value) {
    (void)engine_id;
    (void)addr;
    (void)value;
}
#define TRACE_NPCM7XX_ADC_READ 0
#define TRACE_NPCM7XX_ADC_READ_ENABLED 0
#define TRACE_NPCM7XX_ADC_READ_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_adc_read(const char *id, uint64_t offset, uint32_t value) {
    (void)id;
    (void)offset;
    (void)value;
}
#define TRACE_NPCM7XX_ADC_WRITE 0
#define TRACE_NPCM7XX_ADC_WRITE_ENABLED 0
#define TRACE_NPCM7XX_ADC_WRITE_BACKEND_DSTATE() (0)
static inline void trace_npcm7xx_adc_write(const char *id, uint64_t offset, uint32_t value) {
    (void)id;
    (void)offset;
    (void)value;
}

#endif