/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_SYSTEM_H
#define TRACE_TRACE_SYSTEM_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_ADDRESS_SPACE_MAP 0
#define TRACE_ADDRESS_SPACE_MAP_ENABLED 0
#define TRACE_ADDRESS_SPACE_MAP_BACKEND_DSTATE() (0)
static inline void trace_address_space_map(void *as, uint64_t addr, uint64_t len, bool is_write, uint32_t attrs) {
    (void)as;
    (void)addr;
    (void)len;
    (void)is_write;
    (void)attrs;
}
#define TRACE_BALLOON_EVENT 0
#define TRACE_BALLOON_EVENT_ENABLED 0
#define TRACE_BALLOON_EVENT_BACKEND_DSTATE() (0)
static inline void trace_balloon_event(void *opaque, unsigned long addr) {
    (void)opaque;
    (void)addr;
}
#define TRACE_CPU_IN 0
#define TRACE_CPU_IN_ENABLED 0
#define TRACE_CPU_IN_BACKEND_DSTATE() (0)
static inline void trace_cpu_in(unsigned int addr, char size, unsigned int val) {
    (void)addr;
    (void)size;
    (void)val;
}
#define TRACE_CPU_OUT 0
#define TRACE_CPU_OUT_ENABLED 0
#define TRACE_CPU_OUT_BACKEND_DSTATE() (0)
static inline void trace_cpu_out(unsigned int addr, char size, unsigned int val) {
    (void)addr;
    (void)size;
    (void)val;
}
#define TRACE_DIRTYLIMIT_SET_VCPU 0
#define TRACE_DIRTYLIMIT_SET_VCPU_ENABLED 0
#define TRACE_DIRTYLIMIT_SET_VCPU_BACKEND_DSTATE() (0)
static inline void trace_dirtylimit_set_vcpu(int cpu_index, uint64_t quota) {
    (void)cpu_index;
    (void)quota;
}
#define TRACE_DIRTYLIMIT_STATE_FINALIZE 0
#define TRACE_DIRTYLIMIT_STATE_FINALIZE_ENABLED 0
#define TRACE_DIRTYLIMIT_STATE_FINALIZE_BACKEND_DSTATE() (0)
static inline void trace_dirtylimit_state_finalize(void) {
}
#define TRACE_DIRTYLIMIT_STATE_INITIALIZE 0
#define TRACE_DIRTYLIMIT_STATE_INITIALIZE_ENABLED 0
#define TRACE_DIRTYLIMIT_STATE_INITIALIZE_BACKEND_DSTATE() (0)
static inline void trace_dirtylimit_state_initialize(int max_cpus) {
    (void)max_cpus;
}
#define TRACE_DIRTYLIMIT_THROTTLE_PCT 0
#define TRACE_DIRTYLIMIT_THROTTLE_PCT_ENABLED 0
#define TRACE_DIRTYLIMIT_THROTTLE_PCT_BACKEND_DSTATE() (0)
static inline void trace_dirtylimit_throttle_pct(int cpu_index, uint64_t pct, int64_t time_us) {
    (void)cpu_index;
    (void)pct;
    (void)time_us;
}
#define TRACE_DIRTYLIMIT_VCPU_EXECUTE 0
#define TRACE_DIRTYLIMIT_VCPU_EXECUTE_ENABLED 0
#define TRACE_DIRTYLIMIT_VCPU_EXECUTE_BACKEND_DSTATE() (0)
static inline void trace_dirtylimit_vcpu_execute(int cpu_index, int64_t sleep_time_us) {
    (void)cpu_index;
    (void)sleep_time_us;
}
#define TRACE_DMA_AIO_CANCEL 0
#define TRACE_DMA_AIO_CANCEL_ENABLED 0
#define TRACE_DMA_AIO_CANCEL_BACKEND_DSTATE() (0)
static inline void trace_dma_aio_cancel(void *dbs) {
    (void)dbs;
}
#define TRACE_DMA_BLK_CB 0
#define TRACE_DMA_BLK_CB_ENABLED 0
#define TRACE_DMA_BLK_CB_BACKEND_DSTATE() (0)
static inline void trace_dma_blk_cb(void *dbs, int ret) {
    (void)dbs;
    (void)ret;
}
#define TRACE_DMA_BLK_IO 0
#define TRACE_DMA_BLK_IO_ENABLED 0
#define TRACE_DMA_BLK_IO_BACKEND_DSTATE() (0)
static inline void trace_dma_blk_io(void *dbs, void *bs, int64_t offset, bool to_dev) {
    (void)dbs;
    (void)bs;
    (void)offset;
    (void)to_dev;
}
#define TRACE_DMA_COMPLETE 0
#define TRACE_DMA_COMPLETE_ENABLED 0
#define TRACE_DMA_COMPLETE_BACKEND_DSTATE() (0)
static inline void trace_dma_complete(void *dbs, int ret, void *cb) {
    (void)dbs;
    (void)ret;
    (void)cb;
}
#define TRACE_DMA_MAP_WAIT 0
#define TRACE_DMA_MAP_WAIT_ENABLED 0
#define TRACE_DMA_MAP_WAIT_BACKEND_DSTATE() (0)
static inline void trace_dma_map_wait(void *dbs) {
    (void)dbs;
}
#define TRACE_FIND_RAM_OFFSET 0
#define TRACE_FIND_RAM_OFFSET_ENABLED 0
#define TRACE_FIND_RAM_OFFSET_BACKEND_DSTATE() (0)
static inline void trace_find_ram_offset(uint64_t size, uint64_t offset) {
    (void)size;
    (void)offset;
}
#define TRACE_FIND_RAM_OFFSET_LOOP 0
#define TRACE_FIND_RAM_OFFSET_LOOP_ENABLED 0
#define TRACE_FIND_RAM_OFFSET_LOOP_BACKEND_DSTATE() (0)
static inline void trace_find_ram_offset_loop(uint64_t size, uint64_t candidate, uint64_t offset, uint64_t next, uint64_t mingap) {
    (void)size;
    (void)candidate;
    (void)offset;
    (void)next;
    (void)mingap;
}
#define TRACE_FLATVIEW_DESTROY 0
#define TRACE_FLATVIEW_DESTROY_ENABLED 0
#define TRACE_FLATVIEW_DESTROY_BACKEND_DSTATE() (0)
static inline void trace_flatview_destroy(void *view, void *root) {
    (void)view;
    (void)root;
}
#define TRACE_FLATVIEW_DESTROY_RCU 0
#define TRACE_FLATVIEW_DESTROY_RCU_ENABLED 0
#define TRACE_FLATVIEW_DESTROY_RCU_BACKEND_DSTATE() (0)
static inline void trace_flatview_destroy_rcu(void *view, void *root) {
    (void)view;
    (void)root;
}
#define TRACE_FLATVIEW_NEW 0
#define TRACE_FLATVIEW_NEW_ENABLED 0
#define TRACE_FLATVIEW_NEW_BACKEND_DSTATE() (0)
static inline void trace_flatview_new(void *view, void *root) {
    (void)view;
    (void)root;
}
#define TRACE_GLOBAL_DIRTY_CHANGED 0
#define TRACE_GLOBAL_DIRTY_CHANGED_ENABLED 0
#define TRACE_GLOBAL_DIRTY_CHANGED_BACKEND_DSTATE() (0)
static inline void trace_global_dirty_changed(unsigned int bitmask) {
    (void)bitmask;
}
#define TRACE_LOAD_FILE 0
#define TRACE_LOAD_FILE_ENABLED 0
#define TRACE_LOAD_FILE_BACKEND_DSTATE() (0)
static inline void trace_load_file(const char *name, const char *path) {
    (void)name;
    (void)path;
}
#define TRACE_MEMORY_REGION_OPS_READ 0
#define TRACE_MEMORY_REGION_OPS_READ_ENABLED 0
#define TRACE_MEMORY_REGION_OPS_READ_BACKEND_DSTATE() (0)
static inline void trace_memory_region_ops_read(int cpu_index, void *mr, uint64_t addr, uint64_t value, unsigned size, const char *name) {
    (void)cpu_index;
    (void)mr;
    (void)addr;
    (void)value;
    (void)size;
    (void)name;
}
#define TRACE_MEMORY_REGION_OPS_WRITE 0
#define TRACE_MEMORY_REGION_OPS_WRITE_ENABLED 0
#define TRACE_MEMORY_REGION_OPS_WRITE_BACKEND_DSTATE() (0)
static inline void trace_memory_region_ops_write(int cpu_index, void *mr, uint64_t addr, uint64_t value, unsigned size, const char *name) {
    (void)cpu_index;
    (void)mr;
    (void)addr;
    (void)value;
    (void)size;
    (void)name;
}
#define TRACE_MEMORY_REGION_RAM_DEVICE_READ 0
#define TRACE_MEMORY_REGION_RAM_DEVICE_READ_ENABLED 0
#define TRACE_MEMORY_REGION_RAM_DEVICE_READ_BACKEND_DSTATE() (0)
static inline void trace_memory_region_ram_device_read(int cpu_index, void *mr, uint64_t addr, uint64_t value, unsigned size) {
    (void)cpu_index;
    (void)mr;
    (void)addr;
    (void)value;
    (void)size;
}
#define TRACE_MEMORY_REGION_RAM_DEVICE_WRITE 0
#define TRACE_MEMORY_REGION_RAM_DEVICE_WRITE_ENABLED 0
#define TRACE_MEMORY_REGION_RAM_DEVICE_WRITE_BACKEND_DSTATE() (0)
static inline void trace_memory_region_ram_device_write(int cpu_index, void *mr, uint64_t addr, uint64_t value, unsigned size) {
    (void)cpu_index;
    (void)mr;
    (void)addr;
    (void)value;
    (void)size;
}
#define TRACE_MEMORY_REGION_SUBPAGE_READ 0
#define TRACE_MEMORY_REGION_SUBPAGE_READ_ENABLED 0
#define TRACE_MEMORY_REGION_SUBPAGE_READ_BACKEND_DSTATE() (0)
static inline void trace_memory_region_subpage_read(int cpu_index, void *mr, uint64_t offset, uint64_t value, unsigned size) {
    (void)cpu_index;
    (void)mr;
    (void)offset;
    (void)value;
    (void)size;
}
#define TRACE_MEMORY_REGION_SUBPAGE_WRITE 0
#define TRACE_MEMORY_REGION_SUBPAGE_WRITE_ENABLED 0
#define TRACE_MEMORY_REGION_SUBPAGE_WRITE_BACKEND_DSTATE() (0)
static inline void trace_memory_region_subpage_write(int cpu_index, void *mr, uint64_t offset, uint64_t value, unsigned size) {
    (void)cpu_index;
    (void)mr;
    (void)offset;
    (void)value;
    (void)size;
}
#define TRACE_MEMORY_REGION_SYNC_DIRTY 0
#define TRACE_MEMORY_REGION_SYNC_DIRTY_ENABLED 0
#define TRACE_MEMORY_REGION_SYNC_DIRTY_BACKEND_DSTATE() (0)
static inline void trace_memory_region_sync_dirty(const char *mr, const char *listener, int global) {
    (void)mr;
    (void)listener;
    (void)global;
}
#define TRACE_QEMU_RAM_ALLOC_SHARED 0
#define TRACE_QEMU_RAM_ALLOC_SHARED_ENABLED 0
#define TRACE_QEMU_RAM_ALLOC_SHARED_BACKEND_DSTATE() (0)
static inline void trace_qemu_ram_alloc_shared(const char *name, size_t size, size_t max_size, int fd, void *host) {
    (void)name;
    (void)size;
    (void)max_size;
    (void)fd;
    (void)host;
}
#define TRACE_QEMU_SYSTEM_POWERDOWN_REQUEST 0
#define TRACE_QEMU_SYSTEM_POWERDOWN_REQUEST_ENABLED 0
#define TRACE_QEMU_SYSTEM_POWERDOWN_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_qemu_system_powerdown_request(void) {
}
#define TRACE_QEMU_SYSTEM_SHUTDOWN_REQUEST 0
#define TRACE_QEMU_SYSTEM_SHUTDOWN_REQUEST_ENABLED 0
#define TRACE_QEMU_SYSTEM_SHUTDOWN_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_qemu_system_shutdown_request(int reason) {
    (void)reason;
}
#define TRACE_RAM_BLOCK_ATTRIBUTES_STATE_CHANGE 0
#define TRACE_RAM_BLOCK_ATTRIBUTES_STATE_CHANGE_ENABLED 0
#define TRACE_RAM_BLOCK_ATTRIBUTES_STATE_CHANGE_BACKEND_DSTATE() (0)
static inline void trace_ram_block_attributes_state_change(uint64_t offset, uint64_t size, const char *from, const char *to) {
    (void)offset;
    (void)size;
    (void)from;
    (void)to;
}
#define TRACE_RAM_BLOCK_DISCARD_RANGE 0
#define TRACE_RAM_BLOCK_DISCARD_RANGE_ENABLED 0
#define TRACE_RAM_BLOCK_DISCARD_RANGE_BACKEND_DSTATE() (0)
static inline void trace_ram_block_discard_range(const char *rbname, void *hva, size_t length, bool need_madvise, bool need_fallocate, int ret) {
    (void)rbname;
    (void)hva;
    (void)length;
    (void)need_madvise;
    (void)need_fallocate;
    (void)ret;
}
#define TRACE_RUNSTATE_SET 0
#define TRACE_RUNSTATE_SET_ENABLED 0
#define TRACE_RUNSTATE_SET_BACKEND_DSTATE() (0)
static inline void trace_runstate_set(int current_state, const char *current_state_str, int new_state, const char *new_state_str) {
    (void)current_state;
    (void)current_state_str;
    (void)new_state;
    (void)new_state_str;
}
#define TRACE_SYSTEM_WAKEUP_REQUEST 0
#define TRACE_SYSTEM_WAKEUP_REQUEST_ENABLED 0
#define TRACE_SYSTEM_WAKEUP_REQUEST_BACKEND_DSTATE() (0)
static inline void trace_system_wakeup_request(int reason) {
    (void)reason;
}
#define TRACE_VM_STATE_NOTIFY 0
#define TRACE_VM_STATE_NOTIFY_ENABLED 0
#define TRACE_VM_STATE_NOTIFY_BACKEND_DSTATE() (0)
static inline void trace_vm_state_notify(int running, int reason, const char *reason_str) {
    (void)running;
    (void)reason;
    (void)reason_str;
}
#define TRACE_VM_STOP_FLUSH_ALL 0
#define TRACE_VM_STOP_FLUSH_ALL_ENABLED 0
#define TRACE_VM_STOP_FLUSH_ALL_BACKEND_DSTATE() (0)
static inline void trace_vm_stop_flush_all(int ret) {
    (void)ret;
}

#endif