/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_SPARC_H
#define TRACE_TRACE_HW_SPARC_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_INT_HELPER_DCACHE_FREEZE 0
#define TRACE_INT_HELPER_DCACHE_FREEZE_ENABLED 0
#define TRACE_INT_HELPER_DCACHE_FREEZE_BACKEND_DSTATE() (0)
static inline void trace_int_helper_dcache_freeze(void) {
}
#define TRACE_INT_HELPER_ICACHE_FREEZE 0
#define TRACE_INT_HELPER_ICACHE_FREEZE_ENABLED 0
#define TRACE_INT_HELPER_ICACHE_FREEZE_BACKEND_DSTATE() (0)
static inline void trace_int_helper_icache_freeze(void) {
}
#define TRACE_LEON3_RESET_IRQ 0
#define TRACE_LEON3_RESET_IRQ_ENABLED 0
#define TRACE_LEON3_RESET_IRQ_BACKEND_DSTATE() (0)
static inline void trace_leon3_reset_irq(int intno) {
    (void)intno;
}
#define TRACE_LEON3_SET_IRQ 0
#define TRACE_LEON3_SET_IRQ_ENABLED 0
#define TRACE_LEON3_SET_IRQ_BACKEND_DSTATE() (0)
static inline void trace_leon3_set_irq(int intno) {
    (void)intno;
}
#define TRACE_SUN4M_CPU_SET_IRQ_LOWER 0
#define TRACE_SUN4M_CPU_SET_IRQ_LOWER_ENABLED 0
#define TRACE_SUN4M_CPU_SET_IRQ_LOWER_BACKEND_DSTATE() (0)
static inline void trace_sun4m_cpu_set_irq_lower(int level) {
    (void)level;
}
#define TRACE_SUN4M_CPU_SET_IRQ_RAISE 0
#define TRACE_SUN4M_CPU_SET_IRQ_RAISE_ENABLED 0
#define TRACE_SUN4M_CPU_SET_IRQ_RAISE_BACKEND_DSTATE() (0)
static inline void trace_sun4m_cpu_set_irq_raise(int level) {
    (void)level;
}
#define TRACE_SUN4M_IOMMU_BAD_ADDR 0
#define TRACE_SUN4M_IOMMU_BAD_ADDR_ENABLED 0
#define TRACE_SUN4M_IOMMU_BAD_ADDR_BACKEND_DSTATE() (0)
static inline void trace_sun4m_iommu_bad_addr(uint64_t addr) {
    (void)addr;
}
#define TRACE_SUN4M_IOMMU_MEM_READL 0
#define TRACE_SUN4M_IOMMU_MEM_READL_ENABLED 0
#define TRACE_SUN4M_IOMMU_MEM_READL_BACKEND_DSTATE() (0)
static inline void trace_sun4m_iommu_mem_readl(uint64_t addr, uint32_t ret) {
    (void)addr;
    (void)ret;
}
#define TRACE_SUN4M_IOMMU_MEM_WRITEL 0
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_ENABLED 0
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_BACKEND_DSTATE() (0)
static inline void trace_sun4m_iommu_mem_writel(uint64_t addr, uint32_t val) {
    (void)addr;
    (void)val;
}
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_CTRL 0
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_CTRL_ENABLED 0
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_CTRL_BACKEND_DSTATE() (0)
static inline void trace_sun4m_iommu_mem_writel_ctrl(uint64_t iostart) {
    (void)iostart;
}
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_PGFLUSH 0
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_PGFLUSH_ENABLED 0
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_PGFLUSH_BACKEND_DSTATE() (0)
static inline void trace_sun4m_iommu_mem_writel_pgflush(uint32_t val) {
    (void)val;
}
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_TLBFLUSH 0
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_TLBFLUSH_ENABLED 0
#define TRACE_SUN4M_IOMMU_MEM_WRITEL_TLBFLUSH_BACKEND_DSTATE() (0)
static inline void trace_sun4m_iommu_mem_writel_tlbflush(uint32_t val) {
    (void)val;
}
#define TRACE_SUN4M_IOMMU_PAGE_GET_FLAGS 0
#define TRACE_SUN4M_IOMMU_PAGE_GET_FLAGS_ENABLED 0
#define TRACE_SUN4M_IOMMU_PAGE_GET_FLAGS_BACKEND_DSTATE() (0)
static inline void trace_sun4m_iommu_page_get_flags(uint64_t pa, uint64_t iopte, uint32_t ret) {
    (void)pa;
    (void)iopte;
    (void)ret;
}
#define TRACE_SUN4M_IOMMU_TRANSLATE_PA 0
#define TRACE_SUN4M_IOMMU_TRANSLATE_PA_ENABLED 0
#define TRACE_SUN4M_IOMMU_TRANSLATE_PA_BACKEND_DSTATE() (0)
static inline void trace_sun4m_iommu_translate_pa(uint64_t addr, uint64_t pa, uint32_t iopte) {
    (void)addr;
    (void)pa;
    (void)iopte;
}

#endif