/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_XBOX_NV2A_H
#define TRACE_TRACE_HW_XBOX_NV2A_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_NV2A_DMA_MAP 0
#define TRACE_NV2A_DMA_MAP_ENABLED 0
#define TRACE_NV2A_DMA_MAP_BACKEND_DSTATE() (0)
static inline void trace_nv2a_dma_map(uint32_t obj_address, uint32_t dma_class, uint32_t dma_target, uint32_t dma_addr, uint32_t dma_limit) {
    (void)obj_address;
    (void)dma_class;
    (void)dma_target;
    (void)dma_addr;
    (void)dma_limit;
}
#define TRACE_NV2A_IRQ 0
#define TRACE_NV2A_IRQ_ENABLED 0
#define TRACE_NV2A_IRQ_BACKEND_DSTATE() (0)
static inline void trace_nv2a_irq(uint32_t pending) {
    (void)pending;
}
#define TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE 0
#define TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE_ENABLED 0
#define TRACE_NV2A_PGRAPH_FLIP_INCREMENT_WRITE_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_flip_increment_write(uint32_t write3d_old, uint32_t write3d_new) {
    (void)write3d_old;
    (void)write3d_new;
}
#define TRACE_NV2A_PGRAPH_FLIP_STALL 0
#define TRACE_NV2A_PGRAPH_FLIP_STALL_ENABLED 0
#define TRACE_NV2A_PGRAPH_FLIP_STALL_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_flip_stall(void) {
}
#define TRACE_NV2A_PGRAPH_METHOD 0
#define TRACE_NV2A_PGRAPH_METHOD_ENABLED 0
#define TRACE_NV2A_PGRAPH_METHOD_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_method(uint32_t subchannel, uint32_t graphics_class, uint32_t method, const char *name, uint32_t offset, uint32_t parameter) {
    (void)subchannel;
    (void)graphics_class;
    (void)method;
    (void)name;
    (void)offset;
    (void)parameter;
}
#define TRACE_NV2A_PGRAPH_METHOD_ABBREV 0
#define TRACE_NV2A_PGRAPH_METHOD_ABBREV_ENABLED 0
#define TRACE_NV2A_PGRAPH_METHOD_ABBREV_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_method_abbrev(uint32_t subchannel, uint32_t graphics_class, uint32_t method, const char *name, unsigned int count) {
    (void)subchannel;
    (void)graphics_class;
    (void)method;
    (void)name;
    (void)count;
}
#define TRACE_NV2A_PGRAPH_METHOD_UNHANDLED 0
#define TRACE_NV2A_PGRAPH_METHOD_UNHANDLED_ENABLED 0
#define TRACE_NV2A_PGRAPH_METHOD_UNHANDLED_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_method_unhandled(uint32_t subchannel, uint32_t graphics_class, uint32_t method, uint32_t parameter) {
    (void)subchannel;
    (void)graphics_class;
    (void)method;
    (void)parameter;
}
#define TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH 0
#define TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_COMPARE_MISMATCH_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_compare_mismatch(const char *field, long int a, long int b) {
    (void)field;
    (void)a;
    (void)b;
}
#define TRACE_NV2A_PGRAPH_SURFACE_CPU_READ 0
#define TRACE_NV2A_PGRAPH_SURFACE_CPU_READ_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_CPU_READ_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_cpu_read(uint32_t addr, uint32_t offset) {
    (void)addr;
    (void)offset;
}
#define TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE 0
#define TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_CPU_WRITE_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_cpu_write(uint32_t addr, uint32_t offset) {
    (void)addr;
    (void)offset;
}
#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR 0
#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_COLOR_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_create_color(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch) {
    (void)addr;
    (void)width;
    (void)height;
    (void)layout;
    (void)anti_aliasing;
    (void)clip_x;
    (void)clip_width;
    (void)clip_y;
    (void)clip_height;
    (void)pitch;
}
#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA 0
#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_CREATE_ZETA_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_create_zeta(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch) {
    (void)addr;
    (void)width;
    (void)height;
    (void)layout;
    (void)anti_aliasing;
    (void)clip_x;
    (void)clip_width;
    (void)clip_y;
    (void)clip_height;
    (void)pitch;
}
#define TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD 0
#define TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_DOWNLOAD_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_download(const char *binding, const char *layout, uint32_t addr, uint32_t width, uint32_t height, uint32_t pitch, uint32_t bytes_per_pixel) {
    (void)binding;
    (void)layout;
    (void)addr;
    (void)width;
    (void)height;
    (void)pitch;
    (void)bytes_per_pixel;
}
#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING 0
#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_OVERLAPPING_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_evict_overlapping(uint32_t addr, uint32_t width, uint32_t height, uint32_t pitch) {
    (void)addr;
    (void)width;
    (void)height;
    (void)pitch;
}
#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON 0
#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_EVICT_REASON_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_evict_reason(const char *reason, uint32_t addr) {
    (void)reason;
    (void)addr;
}
#define TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR 0
#define TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_HIT_COLOR_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_hit_color(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch) {
    (void)addr;
    (void)width;
    (void)height;
    (void)layout;
    (void)anti_aliasing;
    (void)clip_x;
    (void)clip_width;
    (void)clip_y;
    (void)clip_height;
    (void)pitch;
}
#define TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA 0
#define TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_HIT_ZETA_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_hit_zeta(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch) {
    (void)addr;
    (void)width;
    (void)height;
    (void)layout;
    (void)anti_aliasing;
    (void)clip_x;
    (void)clip_width;
    (void)clip_y;
    (void)clip_height;
    (void)pitch;
}
#define TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED 0
#define TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_INVALIDATED_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_invalidated(uint32_t addr) {
    (void)addr;
}
#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR 0
#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_COLOR_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_match_color(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch) {
    (void)addr;
    (void)width;
    (void)height;
    (void)layout;
    (void)anti_aliasing;
    (void)clip_x;
    (void)clip_width;
    (void)clip_y;
    (void)clip_height;
    (void)pitch;
}
#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA 0
#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_MATCH_ZETA_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_match_zeta(uint32_t addr, uint32_t width, uint32_t height, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height, uint32_t pitch) {
    (void)addr;
    (void)width;
    (void)height;
    (void)layout;
    (void)anti_aliasing;
    (void)clip_x;
    (void)clip_width;
    (void)clip_y;
    (void)clip_height;
    (void)pitch;
}
#define TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE 0
#define TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_MIGRATE_TYPE_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_migrate_type(const char *new_type) {
    (void)new_type;
}
#define TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE 0
#define TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_RENDER_TO_TEXTURE_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_render_to_texture(uint32_t addr, uint32_t width, uint32_t height) {
    (void)addr;
    (void)width;
    (void)height;
}
#define TRACE_NV2A_PGRAPH_SURFACE_TARGET 0
#define TRACE_NV2A_PGRAPH_SURFACE_TARGET_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_TARGET_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_target(const char *binding, uint32_t addr, const char *layout, uint32_t anti_aliasing, uint32_t clip_x, uint32_t clip_width, uint32_t clip_y, uint32_t clip_height) {
    (void)binding;
    (void)addr;
    (void)layout;
    (void)anti_aliasing;
    (void)clip_x;
    (void)clip_width;
    (void)clip_y;
    (void)clip_height;
}
#define TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED 0
#define TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_TEXTURE_COMPAT_FAILED_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_texture_compat_failed(int32_t surface_fmt, int32_t texture_fmt) {
    (void)surface_fmt;
    (void)texture_fmt;
}
#define TRACE_NV2A_PGRAPH_SURFACE_UPLOAD 0
#define TRACE_NV2A_PGRAPH_SURFACE_UPLOAD_ENABLED 0
#define TRACE_NV2A_PGRAPH_SURFACE_UPLOAD_BACKEND_DSTATE() (0)
static inline void trace_nv2a_pgraph_surface_upload(const char *binding, const char *layout, uint32_t addr, uint32_t width, uint32_t height, uint32_t pitch, uint32_t bytes_per_pixel) {
    (void)binding;
    (void)layout;
    (void)addr;
    (void)width;
    (void)height;
    (void)pitch;
    (void)bytes_per_pixel;
}
#define TRACE_NV2A_REG_READ 0
#define TRACE_NV2A_REG_READ_ENABLED 0
#define TRACE_NV2A_REG_READ_BACKEND_DSTATE() (0)
static inline void trace_nv2a_reg_read(const char *block, uint32_t addr, unsigned int size, uint64_t val) {
    (void)block;
    (void)addr;
    (void)size;
    (void)val;
}
#define TRACE_NV2A_REG_WRITE 0
#define TRACE_NV2A_REG_WRITE_ENABLED 0
#define TRACE_NV2A_REG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_nv2a_reg_write(const char *block, uint32_t addr, unsigned int size, uint64_t val) {
    (void)block;
    (void)addr;
    (void)size;
    (void)val;
}

#endif