/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_BACKENDS_H
#define TRACE_TRACE_BACKENDS_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_DBUS_VMSTATE_LOADING 0
#define TRACE_DBUS_VMSTATE_LOADING_ENABLED 0
#define TRACE_DBUS_VMSTATE_LOADING_BACKEND_DSTATE() (0)
static inline void trace_dbus_vmstate_loading(const char *id) {
    (void)id;
}
#define TRACE_DBUS_VMSTATE_POST_LOAD 0
#define TRACE_DBUS_VMSTATE_POST_LOAD_ENABLED 0
#define TRACE_DBUS_VMSTATE_POST_LOAD_BACKEND_DSTATE() (0)
static inline void trace_dbus_vmstate_post_load(int version_id) {
    (void)version_id;
}
#define TRACE_DBUS_VMSTATE_PRE_SAVE 0
#define TRACE_DBUS_VMSTATE_PRE_SAVE_ENABLED 0
#define TRACE_DBUS_VMSTATE_PRE_SAVE_BACKEND_DSTATE() (0)
static inline void trace_dbus_vmstate_pre_save(void) {
}
#define TRACE_DBUS_VMSTATE_SAVING 0
#define TRACE_DBUS_VMSTATE_SAVING_ENABLED 0
#define TRACE_DBUS_VMSTATE_SAVING_BACKEND_DSTATE() (0)
static inline void trace_dbus_vmstate_saving(const char *id) {
    (void)id;
}
#define TRACE_IOMMU_BACKEND_SET_FD 0
#define TRACE_IOMMU_BACKEND_SET_FD_ENABLED 0
#define TRACE_IOMMU_BACKEND_SET_FD_BACKEND_DSTATE() (0)
static inline void trace_iommu_backend_set_fd(int fd) {
    (void)fd;
}
#define TRACE_IOMMUFD_BACKEND_ALLOC_HWPT 0
#define TRACE_IOMMUFD_BACKEND_ALLOC_HWPT_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_ALLOC_HWPT_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_alloc_hwpt(int iommufd, uint32_t dev_id, uint32_t pt_id, uint32_t flags, uint32_t hwpt_type, uint32_t len, uint64_t data_ptr, uint32_t out_hwpt_id, int ret) {
    (void)iommufd;
    (void)dev_id;
    (void)pt_id;
    (void)flags;
    (void)hwpt_type;
    (void)len;
    (void)data_ptr;
    (void)out_hwpt_id;
    (void)ret;
}
#define TRACE_IOMMUFD_BACKEND_ALLOC_IOAS 0
#define TRACE_IOMMUFD_BACKEND_ALLOC_IOAS_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_ALLOC_IOAS_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_alloc_ioas(int iommufd, uint32_t ioas) {
    (void)iommufd;
    (void)ioas;
}
#define TRACE_IOMMUFD_BACKEND_CONNECT 0
#define TRACE_IOMMUFD_BACKEND_CONNECT_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_CONNECT_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_connect(int fd, bool owned, uint32_t users) {
    (void)fd;
    (void)owned;
    (void)users;
}
#define TRACE_IOMMUFD_BACKEND_DISCONNECT 0
#define TRACE_IOMMUFD_BACKEND_DISCONNECT_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_DISCONNECT_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_disconnect(int fd, uint32_t users) {
    (void)fd;
    (void)users;
}
#define TRACE_IOMMUFD_BACKEND_FREE_ID 0
#define TRACE_IOMMUFD_BACKEND_FREE_ID_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_FREE_ID_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_free_id(int iommufd, uint32_t id, int ret) {
    (void)iommufd;
    (void)id;
    (void)ret;
}
#define TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP 0
#define TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_GET_DIRTY_BITMAP_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_get_dirty_bitmap(int iommufd, uint32_t hwpt_id, uint64_t iova, uint64_t size, uint64_t page_size, int ret) {
    (void)iommufd;
    (void)hwpt_id;
    (void)iova;
    (void)size;
    (void)page_size;
    (void)ret;
}
#define TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE 0
#define TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_INVALIDATE_CACHE_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_invalidate_cache(int iommufd, uint32_t id, uint32_t data_type, uint32_t entry_len, uint32_t entry_num, uint32_t done_num, uint64_t data_ptr, int ret) {
    (void)iommufd;
    (void)id;
    (void)data_type;
    (void)entry_len;
    (void)entry_num;
    (void)done_num;
    (void)data_ptr;
    (void)ret;
}
#define TRACE_IOMMUFD_BACKEND_MAP_DMA 0
#define TRACE_IOMMUFD_BACKEND_MAP_DMA_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_MAP_DMA_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_map_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, void *vaddr, bool readonly, int ret) {
    (void)iommufd;
    (void)ioas;
    (void)iova;
    (void)size;
    (void)vaddr;
    (void)readonly;
    (void)ret;
}
#define TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA 0
#define TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_MAP_FILE_DMA_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_map_file_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int fd, unsigned long start, bool readonly, int ret) {
    (void)iommufd;
    (void)ioas;
    (void)iova;
    (void)size;
    (void)fd;
    (void)start;
    (void)readonly;
    (void)ret;
}
#define TRACE_IOMMUFD_BACKEND_SET_DIRTY 0
#define TRACE_IOMMUFD_BACKEND_SET_DIRTY_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_SET_DIRTY_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_set_dirty(int iommufd, uint32_t hwpt_id, bool start, int ret) {
    (void)iommufd;
    (void)hwpt_id;
    (void)start;
    (void)ret;
}
#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA 0
#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_unmap_dma(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int ret) {
    (void)iommufd;
    (void)ioas;
    (void)iova;
    (void)size;
    (void)ret;
}
#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST 0
#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST_ENABLED 0
#define TRACE_IOMMUFD_BACKEND_UNMAP_DMA_NON_EXIST_BACKEND_DSTATE() (0)
static inline void trace_iommufd_backend_unmap_dma_non_exist(int iommufd, uint32_t ioas, uint64_t iova, uint64_t size, int ret) {
    (void)iommufd;
    (void)ioas;
    (void)iova;
    (void)size;
    (void)ret;
}
#define TRACE_IOMMUFD_CHANGE_PROCESS 0
#define TRACE_IOMMUFD_CHANGE_PROCESS_ENABLED 0
#define TRACE_IOMMUFD_CHANGE_PROCESS_BACKEND_DSTATE() (0)
static inline void trace_iommufd_change_process(int fd, bool ret) {
    (void)fd;
    (void)ret;
}

#endif