/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_TARGET_S390X_KVM_H
#define TRACE_TRACE_TARGET_S390X_KVM_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD 0
#define TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD_ENABLED 0
#define TRACE_KVM_ASSIGN_SUBCH_IOEVENTFD_BACKEND_DSTATE() (0)
static inline void trace_kvm_assign_subch_ioeventfd(int fd, uint32_t addr, bool assign, int datamatch) {
    (void)fd;
    (void)addr;
    (void)assign;
    (void)datamatch;
}
#define TRACE_KVM_CLEAR_CMMA 0
#define TRACE_KVM_CLEAR_CMMA_ENABLED 0
#define TRACE_KVM_CLEAR_CMMA_BACKEND_DSTATE() (0)
static inline void trace_kvm_clear_cmma(int rc) {
    (void)rc;
}
#define TRACE_KVM_ENABLE_CMMA 0
#define TRACE_KVM_ENABLE_CMMA_ENABLED 0
#define TRACE_KVM_ENABLE_CMMA_BACKEND_DSTATE() (0)
static inline void trace_kvm_enable_cmma(int rc) {
    (void)rc;
}
#define TRACE_KVM_FAILED_CPU_STATE_SET 0
#define TRACE_KVM_FAILED_CPU_STATE_SET_ENABLED 0
#define TRACE_KVM_FAILED_CPU_STATE_SET_BACKEND_DSTATE() (0)
static inline void trace_kvm_failed_cpu_state_set(int cpu_index, uint8_t state, const char *msg) {
    (void)cpu_index;
    (void)state;
    (void)msg;
}
#define TRACE_KVM_INSN 0
#define TRACE_KVM_INSN_ENABLED 0
#define TRACE_KVM_INSN_BACKEND_DSTATE() (0)
static inline void trace_kvm_insn(uint32_t ipa, uint32_t ipb) {
    (void)ipa;
    (void)ipb;
}
#define TRACE_KVM_INSN_DIAG 0
#define TRACE_KVM_INSN_DIAG_ENABLED 0
#define TRACE_KVM_INSN_DIAG_BACKEND_DSTATE() (0)
static inline void trace_kvm_insn_diag(uint32_t x) {
    (void)x;
}
#define TRACE_KVM_INSN_UNHANDLED_PRIV 0
#define TRACE_KVM_INSN_UNHANDLED_PRIV_ENABLED 0
#define TRACE_KVM_INSN_UNHANDLED_PRIV_BACKEND_DSTATE() (0)
static inline void trace_kvm_insn_unhandled_priv(uint32_t x) {
    (void)x;
}
#define TRACE_KVM_INTERCEPT 0
#define TRACE_KVM_INTERCEPT_ENABLED 0
#define TRACE_KVM_INTERCEPT_BACKEND_DSTATE() (0)
static inline void trace_kvm_intercept(uint32_t icpt_code, uint64_t psw_addr) {
    (void)icpt_code;
    (void)psw_addr;
}
#define TRACE_KVM_MSI_ROUTE_FIXUP 0
#define TRACE_KVM_MSI_ROUTE_FIXUP_ENABLED 0
#define TRACE_KVM_MSI_ROUTE_FIXUP_BACKEND_DSTATE() (0)
static inline void trace_kvm_msi_route_fixup(const char* msg) {
    (void)msg;
}
#define TRACE_KVM_SW_BREAKPOINT 0
#define TRACE_KVM_SW_BREAKPOINT_ENABLED 0
#define TRACE_KVM_SW_BREAKPOINT_BACKEND_DSTATE() (0)
static inline void trace_kvm_sw_breakpoint(uint32_t n) {
    (void)n;
}

#endif