/* AUTOGENERATED STUB FOR ANDROID BUILD */
#ifndef TRACE_TRACE_HW_UEFI_H
#define TRACE_TRACE_HW_UEFI_H

/* No-op trace events */
#ifndef trace_event_get_state_backends
#define trace_event_get_state_backends(id) (0)
#endif
#ifndef trace_event_get_state
#define trace_event_get_state(id) (0)
#endif
#define TRACE_UEFI_EVENT 0
#define TRACE_UEFI_EVENT_ENABLED 0
#define TRACE_UEFI_EVENT_BACKEND_DSTATE() (0)
static inline void trace_uefi_event(const char *name) {
    (void)name;
}
#define TRACE_UEFI_HARD_RESET 0
#define TRACE_UEFI_HARD_RESET_ENABLED 0
#define TRACE_UEFI_HARD_RESET_BACKEND_DSTATE() (0)
static inline void trace_uefi_hard_reset(void) {
}
#define TRACE_UEFI_REG_READ 0
#define TRACE_UEFI_REG_READ_ENABLED 0
#define TRACE_UEFI_REG_READ_BACKEND_DSTATE() (0)
static inline void trace_uefi_reg_read(uint64_t addr, unsigned size) {
    (void)addr;
    (void)size;
}
#define TRACE_UEFI_REG_WRITE 0
#define TRACE_UEFI_REG_WRITE_ENABLED 0
#define TRACE_UEFI_REG_WRITE_BACKEND_DSTATE() (0)
static inline void trace_uefi_reg_write(uint64_t addr, uint64_t val, unsigned size) {
    (void)addr;
    (void)val;
    (void)size;
}
#define TRACE_UEFI_STATUS 0
#define TRACE_UEFI_STATUS_ENABLED 0
#define TRACE_UEFI_STATUS_BACKEND_DSTATE() (0)
static inline void trace_uefi_status(const char *context, const char *name) {
    (void)context;
    (void)name;
}
#define TRACE_UEFI_VARIABLE 0
#define TRACE_UEFI_VARIABLE_ENABLED 0
#define TRACE_UEFI_VARIABLE_BACKEND_DSTATE() (0)
static inline void trace_uefi_variable(const char *context, const char *name, uint64_t size, const char *uuid) {
    (void)context;
    (void)name;
    (void)size;
    (void)uuid;
}
#define TRACE_UEFI_VARS_POLICY_CMD 0
#define TRACE_UEFI_VARS_POLICY_CMD_ENABLED 0
#define TRACE_UEFI_VARS_POLICY_CMD_BACKEND_DSTATE() (0)
static inline void trace_uefi_vars_policy_cmd(const char *cmd) {
    (void)cmd;
}
#define TRACE_UEFI_VARS_POLICY_DENY 0
#define TRACE_UEFI_VARS_POLICY_DENY_ENABLED 0
#define TRACE_UEFI_VARS_POLICY_DENY_BACKEND_DSTATE() (0)
static inline void trace_uefi_vars_policy_deny(const char *reason) {
    (void)reason;
}
#define TRACE_UEFI_VARS_PROTO_CMD 0
#define TRACE_UEFI_VARS_PROTO_CMD_ENABLED 0
#define TRACE_UEFI_VARS_PROTO_CMD_BACKEND_DSTATE() (0)
static inline void trace_uefi_vars_proto_cmd(const char *cmd) {
    (void)cmd;
}
#define TRACE_UEFI_VARS_SECURITY_VIOLATION 0
#define TRACE_UEFI_VARS_SECURITY_VIOLATION_ENABLED 0
#define TRACE_UEFI_VARS_SECURITY_VIOLATION_BACKEND_DSTATE() (0)
static inline void trace_uefi_vars_security_violation(const char *reason) {
    (void)reason;
}

#endif