#ifndef XEMU_ANDROID_CONFIG_TARGET_H
#define XEMU_ANDROID_CONFIG_TARGET_H

#define CONFIG_SOFTMMU 1

#define TARGET_I386 1
#define TARGET_ABI_BITS 32
#define TARGET_LONG_BITS 32
#define TARGET_PAGE_BITS 12
#define TARGET_PHYS_ADDR_BITS 36
#define TARGET_VIRT_ADDR_BITS 32
#define TARGET_BIG_ENDIAN 0

#define TARGET_NAME "i386"
#define CONFIG_TARGET_I386 1
#define QEMU_ARCH QEMU_ARCH_I386

#endif  // XEMU_ANDROID_CONFIG_TARGET_H
